### ISSUE TITLE
更新hosts后，好像不起作用是为啥

### ISSUE THREAD

**Issue by wikiZhang** [googlehosts/hosts#100]
为啥更新完我电脑里的hosts，Google和Facebook还是上不了，是电脑出了什么bug吗？

**Comment by AlexsanderShaw** [comment]
我的也是，之前都是可以上的，最近不行了，不知道为什么

**Comment by kennylbj** [comment]
等会议过了再上把。(/▽╲)

**Comment by DDoSolitary** [comment]
Duplicate of #64

**Comment by vv-young** [comment]
很奇怪哇 我用go hosts的都可以 这个‘hosts’不大能用

**Comment by AlexsanderShaw** [comment]
go hosts的确定可以吗？能不能发一下资源

**Comment by zhimingluo** [comment]
http://www.uuhosts.com/
这个hosts可以上google的

**Comment by lrinQVQ** [comment]
嘛= =情愿GG也不用SNI

**Comment by buddychang** [comment]
@zhimingluo 这个直到一小时前还可以用，现在连不上了。

**Comment by kennylbj** [comment]
难道，我们中出了个叛徒🤣

**Comment by beyondgfw** [comment]
都说是duplicate了。。讨论去#64。。
