### ISSUE TITLE
services.gradle.org TCP Retransmission 严重怎么解决 下载100kb/s还不到

### ISSUE THREAD

**Issue by PantherJohn** [googlehosts/hosts#101]
你们除了改hosts用sni还有什么办法吗
这速度... 一个android studio project file 都没法gradle
这gfw我服

**Comment by JohnAndersonCA** [comment]
![image](https://user-images.githubusercontent.com/28533997/31611468-0c5151b6-b231-11e7-8ae3-ac214e4cb107.png)

**Comment by Hfenger** [comment]
[root@hfenger ~]# dig services.gradle.org @127.0.0.1

; <<>> DiG 9.9.4-RedHat-9.9.4-51.el7 <<>> services.gradle.org @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 15945
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;services.gradle.org.           IN      A

;; ANSWER SECTION:
services.gradle.org.    300     IN      A       104.16.173.166
services.gradle.org.    300     IN      A       104.16.172.166
services.gradle.org.    300     IN      A       104.16.171.166
services.gradle.org.    300     IN      A       104.16.175.166
services.gradle.org.    300     IN      A       104.16.174.166

这几个IP自己换着试试，都慢只有挂代理，开发还不常备代理我是服的。包子还有五年，现在各种新手段HOST快成历史了，机器学习识别代理流量都来了，以后流量全都要伪装，做到没特征才行

**Comment by beyondgfw** [comment]
GFW故意丢包，除了代理没啥好的解决方法。。

**Comment by JohnAndersonCA** [comment]
2333

**Comment by Makebignew** [comment]
cloudflare 的cdn电信联通都是这种垃圾速度，移动会走香港节点速度好很多，可以试着挂个国内移动的代理

**Comment by JohnAndersonCA** [comment]
@beyondgfw @Hfenger 唉... 那我如果用multi-thread 开几个thread 分别发包呢

**Comment by lrinQVQ** [comment]
2333其实可用的IP还有104.16.176.166 104.16.177.166 104.16.178.166 等等= =现在开完会不知道好不好一些

**Comment by Makebignew** [comment]
@lrinQVQ cloudflare所有ip都是anycast，只要是电信联通肯定被路由到美国😂gtt 辣鸡线路速度不可能快

**Comment by lrinQVQ** [comment]
23333对啊贼心疼
