### ISSUE TITLE
最近更新的 谷歌 推特 脸书都上不去了

### ISSUE THREAD

**Issue by wssyh2008** [googlehosts/hosts#102]
非常感谢你能参与本项目的维护，但是：
开新issue前请先阅读注意事项！
开新issue前请先阅读注意事项！
开新issue前请先阅读注意事项！
https://github.com/googlehosts/hosts/blob/master/.github/CONTRIBUTING.md
否则我们可能会不经警告地关闭你的issue，甚至禁言你的账号！
在阅读完后请删除此处的内容并填写你的issue的内容。

**Comment by boblao0714** [comment]
font{
        line-height: 1.7;
    }


    
Thank you不过我只是想把文件复制下来所以打开了编辑带来困扰很抱歉。谢谢您和各位的维护。隔雨听竹 敬上



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    




    在2017年10月16日 23:46，wssyh2008<notifications@github.com> 写道： 


非常感谢你能参与本项目的维护，但是：
开新issue前请先阅读注意事项！
开新issue前请先阅读注意事项！
开新issue前请先阅读注意事项！
https://github.com/googlehosts/hosts/blob/master/.github/CONTRIBUTING.md
否则我们可能会不经警告地关闭你的issue，甚至禁言你的账号！
在阅读完后请删除此处的内容并填写你的issue的内容。

**Comment by lrinQVQ** [comment]
@wssyh2008 2333github上打开编辑只是会fork到你的个人项目里而已 没关系的啦

**Comment by boblao0714** [comment]
font{
        line-height: 1.7;
    }


    
我一直不怎么会用GitHub233333333



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    




    在2017年10月17日 07:48，lrin<notifications@github.com> 写道： 


@wssyh2008 2333github上打开编辑只是会fork到你的个人项目里而已 没关系的啦

**Comment by lrinQVQ** [comment]
@boblao0714 2333没事都是慢慢摸索的啦 加油~

**Comment by beyondgfw** [comment]
Google: duplicate of #64 
Facebook: duplicate of #69 
Twitter: 目前没有办法了。。
