### ISSUE TITLE
种花西皮会终于开了，不知道下周墙姬是不是会打瞌睡呐~

### ISSUE THREAD

**Issue by wolfan** [googlehosts/hosts#103]
唱起歌儿，跳起舞，我们为祖国的十九大献歌献舞~
大会终于开了，调戏墙姬的日子就要来到了~
开森~

**Comment by beyondgfw** [comment]
嗯，我在关与不关这个issue之间纠结了一阵，最终决定不关。。

**Comment by boblao0714** [comment]
泽泽泽
你们不要在这种境外网站胡搞毛搞，江莱出了什么问题，你们要负泽任，民白不民白？

**Comment by guoyf** [comment]
求问嗜酒哒开到哪天结束啊？

**Comment by wolfan** [comment]
@guoyf 

> 中国共产党第十九次全国代表大会（简称党的十九大）于2017年10月18日至10月24日在北京召开。

**Comment by WeihuaGu** [comment]
其实都无所谓，问题是新闻联播每天加长到快8点，然后电视剧就拖后半小时，然后我就每天晚睡了半个小时……

**Comment by beyondgfw** [comment]
不知不觉issue好多了，就把这个关了吧。。
