### ISSUE TITLE
怎么玩

### ISSUE THREAD

**Issue by RichardKidd** [googlehosts/hosts#104]
关注这个项目好久了一直想知道Windows7直接替换C盘下的host是否可行?

**Comment by wizardforcel** [comment]
win7 还是那个目录。

**Comment by wolfan** [comment]
其实人只需要把 hosts 这一个文件替换掉系统里的hosts文件就行了，不管是win,linux,mac亦或Android,ios,Unix都是一样的道理。

**Comment by lychichem** [comment]
> 其实人只需要把 hosts 这一个文件替换掉系统里的hosts文件就行了，不管是win,linux,mac亦或Android,ios,Unix都是一样的道理。
但是要考虑Win和*nix的换行符不一样的问题

**Comment by DDoSolitary** [comment]
@lychichem 我记得没错的话windows用LF的也可以。。

**Comment by DDoSolitary** [comment]
@leoxxx 我知道，我是说Windows下使用LF的hosts文件也能正常工作。。

**Comment by leoxxx** [comment]
是否可用不清楚，没测试过。

**Comment by leoxxx** [comment]
@lychichem 改一下换行符也不费多少事啊。

**Comment by lychichem** [comment]
emm…实测用lf也行的

发送自我的iPhone

在 2017年10月22日，16:17，leoxxx <notifications@github.com<mailto:notifications@github.com>> 写道：


是否可用不清楚，没测试过。

**Comment by lychichem** [comment]
如果你有两个都有2w行+的hosts只是换行符不同，改完一个再改另一个而且还要传输到正确的设备上就不那么容易了

发送自我的iPhone

在 2017年10月22日，16:19，leoxxx <notifications@github.com<mailto:notifications@github.com>> 写道：


@lychichem<https://github.com/lychichem> 改一下换行符也不费多少事啊。

**Comment by leoxxx** [comment]
你编辑器没用对吧。点一直接切换换行符，保存就完事了。

**Comment by lychichem** [comment]
我知道可以这么用啊只是我编辑器开了自动保存，一切换行符俩文件就一模一样了

发送自我的iPhone

在 2017年10月22日，16:25，leoxxx <notifications@github.com<mailto:notifications@github.com>> 写道：


你编辑器没用对吧。点一直接切换换行符，保存就完事了。
