### ISSUE TITLE
能否加上https://www.apkmirror.com/，连下载个app都没办法了

### ISSUE THREAD

**Issue by jinyumarine** [googlehosts/hosts#106]
能否加上https://www.apkmirror.com/，连下载个app都没办法了，谢谢

**Comment by WeihuaGu** [comment]
@jinyumarine 我一般是apkmirror和apkpure换着用，apkmirror不行，试试apkpure.

**Comment by SerCom-KC** [comment]
大概可以 close 了？
@jinyumarine 解决了没有

**Comment by beyondgfw** [comment]
@SerCom-KC  commit里好像只加了一个主域名，我看看还有没有别的。。

**Comment by SerCom-KC** [comment]
@beyondgfw 喵这样啊）

**Comment by jinyumarine** [comment]
@SerCom-KC  @beyondgfw 谢谢，已经解决

**Comment by birdofprey** [comment]
开放只是个传说
