### ISSUE TITLE
ping 谷歌（172.217.60.241）超时

### ISSUE THREAD

**Issue by SunGuok** [googlehosts/hosts#107]

**Comment by HackerEliter** [comment]
从十月开始用过做作者好多个更新的HOSTS都没不能翻，不知道怎么回事，以前改了hosts刷新下DNS就行了，现在怎么也上不去，请问是什么问题？

**Comment by boblao0714** [comment]
现在主要是就是食酒哒

2017-10-19 11:01 GMT+08:00 HackerEliter <notifications@github.com>:

**Comment by ReySun** [comment]
同样，我是看见上个项目的issue过来的，同样替换hosts的方法用不鸟，已经很久没GG了，谢谢作者常常更新，可我找不到其他使用的方法了，求助....

**Comment by beyondgfw** [comment]
Duplicate of #64
