### ISSUE TITLE
为什么我好像用这里的host基本上不了google？但用别的地方的经常就行？

### ISSUE THREAD

**Issue by pengchin** [googlehosts/hosts#108]
我用的是移动宽带，北京。比如这次19号更新的。还是不能用。以前也是，好像基本没成功过，可是别的地方的就行，怎么回事？

**Comment by SerCom-KC** [comment]
因为本项目出于安全和隐私考虑只使用官方 IP，其他项目大多都使用自建的 sni 代理

**Comment by beyondgfw** [comment]
@SerCom-KC 你把我要说的话都说了那我该说啥 😆 

Duplicate of #64

**Comment by SerCom-KC** [comment]
@beyondgfw 当然是 marked this as a duplicate of #64 啊（手动滑稽
