### ISSUE TITLE
Google地图的app

### ISSUE THREAD

**Issue by 123ysys** [googlehosts/hosts#109]
Google地图的app与网页是不是使用着不同的端口啊？app无论如何也加载不出来。

**Comment by beyondgfw** [comment]
不清楚，你Google网页可以吗

**Comment by DaleXiao** [comment]
浏览器访问 https://ditu.google.cn

**Comment by 123ysys** [comment]
网页都是可以的，但是谷歌手机自带的地图app就难以加载。

**Comment by 123ysys** [comment]
似乎网页版的也时好时坏。

**Comment by lrinQVQ** [comment]
0.0 google android 的app 通常都是使用1e100域名的 233 比如我这里的地图 

lax02s23-in-f14.1e100.net:443

**Comment by 123ysys** [comment]
@lrinQVQ 啊啊啊，看不懂啊，没见过这种域名。不过看WIKI上说不是所有的谷歌服务都是web服务，不知这个对地图app有没有影响。

**Comment by lrinQVQ** [comment]
23333没有影响的啦 不过地图我想办法弄下好了

**Comment by 123ysys** [comment]
啊啊啊，不是的。我只是想了解一下这种情况是怎么回事，毕竟有在wiki上看到的说。我没有在手机上弄hosts的习惯。

**Comment by lrinQVQ** [comment]
soga23333嘛总之我也有测试环境我先弄下

**Comment by 123ysys** [comment]
请问这问题有解吗？

**Comment by 123ysys** [comment]
现在网页版的CSS加载不出来啊。
