### ISSUE TITLE
觉得前一段时间GFW开放Google 是有原因的... 

### ISSUE THREAD

**Issue by PantherJohn** [googlehosts/hosts#110]
为什么要开放呢? 之前Google肯定被研究过 开放只是一个实验 有人直接连接google就在帮助GFW完成实验...
然后就有RST TLS BLOCK...

**Comment by guoyf** [comment]
嗯，我觉得有这种可能。

**Comment by lrinQVQ** [comment]
嘛==其实这个不需要实验...2333明文的东西无难度

**Comment by PantherJohn** [comment]
最近VP*好像也被XX了 主机都ping通就是连接不上

**Comment by Codersadis** [comment]
这次之后host这条路就死掉了吧？

**Comment by lrinQVQ** [comment]
封端口= =日常

**Comment by boblao0714** [comment]
封端口是墙的日常啊
