### ISSUE TITLE
今天下的hosts文件失效

### ISSUE THREAD

**Issue by xiaoxintiaoda** [googlehosts/hosts#113]
地区:武汉
宽带:长城宽带
下载替换hosts文件了，在cmd中成功执行了ipconfig /flushdns，显示缓存已清除
然后仍然上不了 hosts中的网站，并使用ping 命令测试host中的ip,基本都ping不同，有一个
gist.github.com 的ip可以ping通，但是打开浏览器(更换hosts后已重启过浏览器)也是上不去

**Comment by SerCom-KC** [comment]
Google、Facebook、Twitter 等不能使用属正常现象。
`ping` 域名，检查一下 IP 是否与 hosts 中的一致，按理来说 GitHub 应该是不受影响的

**Comment by weinierfei** [comment]
会开完了;还是没有可用hosts么?还不能出去么?

**Comment by beyondgfw** [comment]
@SerCom-KC 正解

gist.github.com我记得没错的话就`192.30.253.118`和`192.30.253.119`，但是并没有被封啊，虽然延时较高有丢包。。你多刷几次网页试试，或者把hosts里118那个换成119，不行的话我们也没办法，就这俩ip。。
