### ISSUE TITLE
特殊时期结束了，新的Hosts什么时间更新呢？

### ISSUE THREAD

**Issue by SawaraNazo** [googlehosts/hosts#114]
特殊时期时期已过，没有Google的日子好不舒服。请问新鲜的Hosts什么时间会更新出来呢？

**Comment by beyondgfw** [comment]
我也不知道啊。。看什么时候封锁减轻吧。。

**Comment by SerCom-KC** [comment]
[预计下个月初](https://github.com/googlehosts/hosts/issues/115#issuecomment-340246707)。

**Comment by SawaraNazo** [comment]
@SerCom-KC   嗯，已经看到了，期待。多谢提醒~
