### ISSUE TITLE
网页版 Telegram 无法连接

### ISSUE THREAD

**Issue by notastudio** [googlehosts/hosts#115]
具体的表现是:可以打开 Telegram 网站,但始终显示为 Connecting... (已登录时)或 Generating keys... (未登录时).
在 web.telegram.org 网站和 Chrome 扩展上都遇到了相同的问题.
尝试开/关 Shadowsocks, 都无法成功连接.(在我的网络环境下,使用 hosts + Shadowsocks 可正常访问绝大多数墙外网站)
使用 Chrome 抓包发现,问题似乎在于发往 `flora.web.telegram.org` 的请求总是超时. `telegram.org` 的其他子域名并没有出现这种超时现象.并且在我的网络环境下 `flora.web.telegram.org` 是可以 ping 通的,解析到的是正确的 IP 地址 (149.154.164.225).

请问这是 hosts 文件的问题吗?是否有解决办法?谢谢.

**Comment by triplekiller** [comment]
请问Shadowsocks是收费的吗？免费的好像用户了了

**Comment by wolfan** [comment]
tg官服封了种花家，没办法，想上要么自建反代，要么其它方式上墙，比如肉翻。

@triplekiller SS好像没有什么免费的了吧……

**Comment by beyondgfw** [comment]
@notastudio 没办法的，`flora.web.telegram.org` 只有一个可用的IP，而且那个还被封了，本来这个服务器也只影响部分图片的加载，所以还能用，现在看来好像连登陆都影响了。。

@wolfan 这个不是tg封中国ip的问题，如果那样的话是 `web.telegram.org` 直接404的

**Comment by beyondgfw** [comment]
@triplekiller shadowsocks本身是开源软件，并不收费，但是要使用必须把软件安装到国外服务器，那些卖shadowsocks的实际上卖的是已经安装好shadowsocks的服务器的使用权。网上应该还能找到一些ss的免费服务吧，我前两天还找到过不少。。

**Comment by wolfan** [comment]
@beyondgfw 大会都完了，墙洞还打不通吗~?

**Comment by beyondgfw** [comment]
你问我，我问谁去啊 😆

**Comment by lrinQVQ** [comment]
@wolfan 快啦233 @beyondgfw 23333你可以问我啊

**Comment by SawaraNazo** [comment]
@lrinQVQ  这意思是马上就要更新了吗？(＃°Д°)   能用咕咯了？

**Comment by lrinQVQ** [comment]
咩预测下月初～

**Comment by SawaraNazo** [comment]
@lrinQVQ  233喔！期待ヾ(≧▽≦*)o

**Comment by triplekiller** [comment]
我以前自己用linode搭过ss，后来长城宽带不理想，就没用了
一直用的isx.yt最近也用不了
@wolfan @beyondgfw

**Comment by yhm2046** [comment]
现在还是不能登录，有啥解决办法？

**Comment by notastudio** [comment]
> 现在还是不能登录，有啥解决办法？

挂代理后可以正常使用.
或者也可以用反向代理.这里有一篇搭建反向代理的[教程](https://nota.moe/2017/telegram-reverse-proxy/),不过稍微有点过时了.
