### ISSUE TITLE
建议增加对https://my.pcloud.com/的支持。

### ISSUE THREAD

**Issue by WeihuaGu** [googlehosts/hosts#116]
pcloud是国外著名的网盘。提供一定大小的免费空间，难能可贵的是它支持离线下载，可以快速离线一些国内下载十分缓慢的文件。

**Comment by lrinQVQ** [comment]
get 2333

**Comment by lrinQVQ** [comment]
74.120.8.13 等我弄好KDE在Push

**Comment by WeihuaGu** [comment]
@lrinQVQ 感谢你的工作！问句多余的你用什么KDE,长期用dwm的人，觉得太单调了，我也想换个桌面……

**Comment by lrinQVQ** [comment]
小意思啦

**Comment by lifeidle** [comment]
@lrinQVQ 大神，google还会有希望么？

**Comment by lrinQVQ** [comment]
会233 @lifeidle

**Comment by siemenslee** [comment]
坐等Google~没得用很不爽。

**Comment by JokerShao** [comment]
@lrinQVQ 大神 你过几天还是会更新的是吧，，项目不会太监了吧 :-) 用这个好久了，可不要停止维护啊。

**Comment by lrinQVQ** [comment]
@JokerShao 2333今天要更新这个域名的啊
