### ISSUE TITLE
更新了11月1日的hosts文件依然还是访问不了Google

### ISSUE THREAD

**Issue by jiangjianshan** [googlehosts/hosts#118]
你好，

    我已经用11月1日的hosts文件覆盖到C:\Windows\System32\drivers\etc下的那个后，在命令行窗口运行ipconfig /flushdns命令后，无论在Chrome或者IE浏览器，依然是访问不了Google，我访问Google输入的网址是https://www.google.com.hk。使用"ping www.google.com.hk"，返回结果是“请求超时”。

**Comment by jinyumarine** [comment]
还没放大招，等吧

**Comment by lrinQVQ** [comment]
https://github.com/googlehosts/hosts/commit/058e3ef17df371003cac9b09bc2c7b46f031d4ee

> Google domain will be fix in openssl tls1.3-draft-21 and google network complete openssl-tls1.3-draft-21 support

**Comment by lrinQVQ** [comment]
Duplicate of #64
