### ISSUE TITLE
hosts google.com.hk 无法打开

### ISSUE THREAD

**Issue by cnkker** [googlehosts/hosts#120]
非常感谢你能参与本项目的维护，但是：
开新issue前请先阅读注意事项！
开新issue前请先阅读注意事项！
开新issue前请先阅读注意事项！
https://github.com/googlehosts/hosts/blob/master/.github/CONTRIBUTING.md
否则我们可能会不经警告地关闭你的issue，甚至禁言你的账号！
在阅读完后请删除此处的内容并填写你的issue的内容。

**Comment by cnkker** [comment]
hosts google.com.hk 无法打开
正在 Ping www.google.com.hk [172.217.60.148] 具有 32 字节的数据:
请求超时。
请求超时。

**Comment by SerCom-KC** [comment]
#64
