### ISSUE TITLE
建议在README中加个当前HOSTS是否有效的提示。

### ISSUE THREAD

**Issue by wolfan** [googlehosts/hosts#121]
如果加个小灯什么的图标，或者什么，对主要的网站如  google\fb\tw 这些进行提示。

**Comment by lrinQVQ** [comment]
好主意233

**Comment by braindevices** [comment]
agree

**Comment by Mogeko** [comment]
好主意

**Comment by SerCom-KC** [comment]
既然是好主意为啥不把 label 改成 enhancement（

**Comment by beyondgfw** [comment]
因为是对readme的修改不是对hosts的本身所以label就用meta了

**Comment by SerCom-KC** [comment]
唔，说实话，我觉得这种东西在特殊时期（长时间无法访问的情况）以“常见问题”的形式放在 Wiki 里就差不多了
平常偶尔失效一下就挂个灯也维护不过来是不

@wolfan 如果觉得这个方案没问题的话就关了 issue 吧（
Wiki 现在就有这么一个说明

**Comment by wolfan** [comment]
@lrinQVQ

**Comment by SerCom-KC** [comment]
@wolfan 有什么问题找 QVQ 咩

**Comment by lrinQVQ** [comment]
@wolfan @SerCom-KC 不用关2333等我忙完给你们用的SNIPROXY我准备加入的

**Comment by SerCom-KC** [comment]
@lrinQVQ 诶，真的要弄自动检测？

**Comment by maxiao227** [comment]
agree
