### ISSUE TITLE
这个项目应该启动了

### ISSUE THREAD

**Issue by RomanSmile** [googlehosts/hosts#122]
复活了大批官方ip不知道是暂时还是局部？
从昨天夜里两点到现在14：40为止，一直存活，
来这里如果稳定就是墙松口了，如果不稳定就是墙出现问题了，

这些段位全部复活
[googleip.txt](https://github.com/googlehosts/hosts/files/1440252/googleip.txt)

**Comment by lrinQVQ** [comment]
gfw放弃sni封锁了?!Σ(っ °Д °;)っ

**Comment by 123ysys** [comment]
@lrinQVQ 这是好是坏？

**Comment by lrinQVQ** [comment]
如果真的放弃了SNI封锁那就回归之前了啊= =不需要TLS1.3了

**Comment by SerCom-KC** [comment]
我很确定我这里还存在 sni 封锁……
提醒一下楼主，能扫到 IP 并不代表能用哦

**Comment by lrinQVQ** [comment]
+1～ 网线看来是插回去了但是针对SNI的封锁i还在XD

**Comment by braindevices** [comment]
does not work here either

**Comment by RomanSmile** [comment]
@lrinQVQ 
我想问一下，为什么关闭我的问题？
我上传了IP段。都是这些IP段，这不是官方是谁家的？
nslookup -q=TXT _netblocks.google.com 8.8.8.8
nslookup -q=TXT _netblocks2.google.com 8.8.8.8
nslookup -q=TXT _netblocks3.google.com 8.8.8.8
到了现在还在使用，我是来提醒一下，看看你们是不是该做些什么了，
本来打算观察一下稳定了再来，可是我太欣喜若狂了，马上就来说，
发现你们这个现在项目越来越差，趴窝好久了，还牛逼哄哄，
@lrinQVQ 你脱离原来组织也变了吗？

**Comment by 123ysys** [comment]
别生气呀。这不是情况尚未明了吗？慢慢来嘛。

**Comment by SerCom-KC** [comment]
很简单啊，IP 扫得出来不代表能用啊，因为还有 SNI 封锁。
你确定你代入到 hosts 文件里试过了吗？
原来的那个 repo 是属于 @racaljk 个人的，现在的这个 repo 才是 googlehosts 组织的，原来活跃的几个主要维护者现在也在这边，所以不存在脱离组织之类的说法

**Comment by RomanSmile** [comment]
我现在还在用，怎么不能用，你要直拨吗？

**Comment by RomanSmile** [comment]
64.18.0.0/20
64.233.160.0/19
66.102.0.0/20
66.249.80.0/20
72.14.192.0/18
74.125.0.0/16
108.177.8.0/21
173.194.0.0/16
207.126.144.0/20
209.85.128.0/17
216.58.192.0/19
216.239.32.0/19
172.217.0.0/19
108.177.96.0/19
告诉我这些是不是google官方ip段？？？

**Comment by SerCom-KC** [comment]
那我很明确地告诉你，我不能用，上面也有另外一个人反馈了不能用，就是这样
现在 @lrinQVQ 的重心在 TLS 1.3 协议的完善，只有这个才能真正解决问题，所以麻烦你耐心一点

**Comment by lrinQVQ** [comment]
@RomanSmile 啊XD你别误会 首先昂你可以看看https://github.com/googlehosts/hosts/issues/87
我在这里相信的分析了为什么所有IP都将不可用的原因
最主要的原因是现在GFW不单纯的依靠封锁IP来处理Google Facebook Twitter这类域名
而是依靠ClientHello包中的Server Name Indication明文域名进行无差别封锁
如果单纯的使用对IP的443进行测试是绝对通的,原因我在分析里面有说到
但是如果要带入我们日常使用的网站中gfw会检查数据包是否包含敏感域名,如果访问的地址包含对应敏感域名那么就会先链接重置然后封锁访问IP端口一段时间XD 所以哪怕有能用的也能通的依旧无法恢复
这也是https://github.com/googlehosts/chromium存在的原因

**Comment by RomanSmile** [comment]
@lrinQVQ 
我只是来这里反馈一下轻松动了，不幸的是我的ip也存活十几个小时全部死亡，谢谢你能回答，
@SerCom-KC 
你不要牛逼呼呼，没谁等着你的文件用，不要牛逼呼呼告诉我TSL1.3在phuslu的项目goproxy早已启用
也很少能有ip能用，更不要你所谓的官方IP，
我张贴出的ip段是google官方帮助给出的获取方法
https://support.google.com/a/answer/60764?hl=zh-Hans
你这种货还是就是装逼犯，这是你家地方以后不来就是！！！

**Comment by lrinQVQ** [comment]
@RomanSmile 首先我们说的TLS1.3是指的TLS1.3 draft 21 而不是目前的draft 18

**Comment by lrinQVQ** [comment]
顺便再次补充下
哪怕是在19大期间我的v4 google所有服务都没断过
现在也是
我没有断过
不要以为我只会走443查下IP通不通= =
![screenshot_20171104_062035](https://user-images.githubusercontent.com/12861134/32398137-4a1badce-c128-11e7-8976-2c92738aabf8.png)

**Comment by SerCom-KC** [comment]
@SerCom-KC
行，我牛逼，我不说话了；反正我也不是这个项目的人，那个文件也不是我的，我就一热心观众而已，想怎么黑我都行，你别污染这个项目就可以
技术细节上面已经说得很清楚了，我们讲的并不是同一个 TLS 1.3，Chrome 正式版现在同样有 TLS 1.3，然而管 Google 服务器的要求执行一个更新的草案，所以才一直在拖（来源请求？我牛逼，我不会告诉你请浏览我们在 Telegram 里的群聊记录）。
是的，你的获取 IP 的方案是官方的，但 Google 官方 IP 的范围远不止这些，有些 IP 可不是那么容易得到的，你有想过维护 hosts 的人有多辛苦吗？
还有，对于你这种 GAE 翻墙党，我还可以多骂一句：前段时间就因为你们中有人天天拿本项目的 IP往自己软件上套，搞得 Google 服务器被大炮打，才使得 Google 不得不在（至少是）TCP 协议上对中国做出限制。Google 已经被你们榨干得差不多了，连 phuslu 都删项目了，XX-Net 也改做 X-Tunnel 的生意了，我求你醒醒好嘛真的……
GAE 翻墙时代已经过去了。你要是还能用 QUIC，好的算你 UDP 环境牛逼；你要是能用 IPv6，如果是原生的，算你牛逼，如果是通过 Teredo 之类的弄出来的，不就是多重翻墙吗，不要自欺欺人了好不，唉……

**Comment by SawaraNazo** [comment]
@RomanSmile   @SerCom-KC   @lrinQVQ     大家都消消气，受益于此项目的观众看不下去了。

@RomanSmile   想让大家都用上谷鸽的心能理解，非常感谢你，不过还希望你不要着急。 @lrinQVQ   人家也是在努力的，只不过没让咱们都看到而已。而且你的态度有点激烈了， @SerCom-KC  人家 很耐心地在告诉你怎么回事，你却这么说人家。  真的不大好  ,,ԾㅂԾ,,
顺便，感谢 @lrinQVQ  的技术支持和 @SerCom-KC 的技术介绍，让咱稍稍了解到现在的问题。非常期待新浏览器。 []~(￣▽￣)~*

**Comment by beyondgfw** [comment]
这项目原本就是做公益，你又不是出了钱做项目，为什么这项目一定要每时每刻都要义务更新呢？大会是开完了没错，但是这就意味着我所有 IP 都能用了吗？我也知道你某些 IP 段已经可以用了，但是不代表别人能用啊，每个地区每个 ISP 的策略都是不一样的，并不一定是防火墙封锁，也有可能是 ISP 自己搞的鬼
>你这种货还是就是装逼犯，这是你家地方以后不来就是！！！

敢问这句话是什么意思？合着是围观群众的话就不应该被尊敬吗

最后，还是那句话 这是个非营利项目，服务不是每时每刻都可用是正常的，如果你需要稳定的google连接，请使用代理或者VPN，同时你也可以看看[提问的智慧](https://github.com/ruby-china/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)
