### ISSUE TITLE
Reuters 打不开

### ISSUE THREAD

**Issue by yalong1221** [googlehosts/hosts#123]
第一次个人制作hosts, 不知效果如何

# Reuters Start
13.32.179.46	reuters.com
13.33.28.73	      www.reuters.com
13.33.28.59	      static.reuters.com
13.33.28.30	      uk.reuters.com
13.33.28.21	      cn.reuters.com
52.5.76.226	      www.reuters.tv
13.33.28.114      www.reutersmedia.net
13.33.28.2        static.reutersmedia.net
13.33.28.32       s1.reutersmedia.net
13.33.28.16       s2.reutersmedia.net
13.33.28.32       s3.reutersmedia.net
13.33.28.17       s4.reutersmedia.net
2.22.154.165      www.thomsonreuters.com
164.57.192.16     www.thomsonreuters.net
13.32.141.115     queso-cdn.prod.reuters.tv
146.242.20.65     ns-emea-1.thomsonreuters.net
146.242.24.65     ns-apac-2.thomsonreuters.net
146.242.18.65     ns-amers-1.thomsonreuters.net
146.242.21.65     ns-emea-2.thomsonreuters.net
146.242.22.65     ns-apac-1.thomsonreuters.net
146.242.19.65     ns-amers-2.thomsonreuters.net
13.32.144.152     cdn.segment.com
13.33.151.251     cdn.distiltag.com
151.101.4.249     static.chartbeat.com
# Reuters End

**Comment by lrinQVQ** [comment]
thanks~我看看233

**Comment by lrinQVQ** [comment]
好像13.32.179.46是cloudfront.net的CDN ip但是这个网站似乎没有用任何CDN
禁ping 用的亚马逊服务器 目前在国内只是DNS污染
 ✘ lrin@lrinQVQ  ~  dig www.reuters.com                                               

; <<>> DiG 9.11.2 <<>> www.reuters.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63783
;; flags: qr rd ra; QUERY: 1, ANSWER: 9, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.reuters.com.               IN      A

;; ANSWER SECTION:
www.reuters.com.        240     IN      CNAME   www.reutersmedia.net.
www.reutersmedia.net.   59      IN      A       52.85.158.218
www.reutersmedia.net.   59      IN      A       52.85.158.163
www.reutersmedia.net.   59      IN      A       52.85.158.188
www.reutersmedia.net.   59      IN      A       52.85.158.165
www.reutersmedia.net.   59      IN      A       52.85.158.116
www.reutersmedia.net.   59      IN      A       52.85.158.202
www.reutersmedia.net.   59      IN      A       52.85.158.159
www.reutersmedia.net.   59      IN      A       52.85.158.178

;; Query time: 184 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: 日 11月 05 01:24:59 CST 2017
;; MSG SIZE  rcvd: 206

**Comment by lrinQVQ** [comment]
而且只污染了*.reuters.com

**Comment by lrinQVQ** [comment]
https://github.com/googlehosts/hosts/commit/76901da000b42368a40e72fcb0f428988712caff

**Comment by lrinQVQ** [comment]
头痛撑不住了XD 修复了记得关下issues谢谢啦~

**Comment by yalong1221** [comment]
本人昨晚又更改部分

**Comment by yalong1221** [comment]
# Reuters Start
13.32.179.46	reuters.com
13.33.28.121	www.reuters.com
13.33.28.59	      static.reuters.com
104.71.156.71     agency.reuters.com
34.203.177.148    liaison.reuters.com
104.71.156.71     plus.reuters.com
134.213.2.143     widerimage.reuters.com
206.135.6.134	us.reuters.com
13.33.28.30	      uk.reuters.com
13.33.28.40	      de.reuters.com
13.33.28.53       fr.reuters.com
13.33.28.91	      it.reuters.com
13.33.28.59       es.reuters.com
54.230.108.176    ru.reuters.com
54.230.108.8      jp.reuters.com
13.33.28.70	      cn.reuters.com
13.33.28.48	      lta.reuters.com
13.33.28.112	af.reuters.com
13.33.28.21	      ara.reuters.com
13.33.28.21	      ar.reuters.com
13.33.28.21	      br.reuters.com
13.33.28.21	      ca.reuters.com
13.33.28.21	      in.reuters.com
13.33.28.21	      mx.reuters.com
52.5.76.226	      www.reuters.tv
54.165.186.56     www.reutersbest.com
13.33.28.114      www.reutersmedia.net
13.33.28.2        static.reutersmedia.net
13.33.28.32       s1.reutersmedia.net
13.33.28.16       s2.reutersmedia.net
13.33.28.32       s3.reutersmedia.net
13.33.28.17       s4.reutersmedia.net
67.199.248.12     reut.rs
67.199.248.12     tmsnrt.rs
54.230.108.79     fingfx.thomsonreuters.com
2.22.154.165      www.thomsonreuters.com
104.71.156.71     www.thomsonreuters.cn
164.57.192.16     www.thomsonreuters.net
13.32.141.115     queso-cdn.prod.reuters.tv
146.242.20.65     ns-emea-1.thomsonreuters.net
146.242.24.65     ns-apac-2.thomsonreuters.net
146.242.18.65     ns-amers-1.thomsonreuters.net
146.242.21.65     ns-emea-2.thomsonreuters.net
146.242.22.65     ns-apac-1.thomsonreuters.net
146.242.19.65     ns-amers-2.thomsonreuters.net
23.219.39.80      18skyfiregce-vimeo.akamaized.net
23.219.39.105     111skyfiregce-vimeo.akamaized.net
23.219.39.82      130skyfiregce-vimeo.akamaized.net
23.219.39.75      133skyfiregce-vimeo.akamaized.net
23.219.39.88      157skyfiregce-vimeo.akamaized.net
13.32.144.152     cdn.segment.com
13.33.151.251     cdn.distiltag.com
151.101.4.249     static.chartbeat.com
# Reuters End

**Comment by lrinQVQ** [comment]
哇thanks 我继续处理下

**Comment by beyondgfw** [comment]
``````
```
对于代码 你可以这样框起来
这样会比较好看
```

**Comment by beyondgfw** [comment]
比如 
```
# Reuters Start
13.32.179.46	reuters.com
13.33.28.121	www.reuters.com
13.33.28.59	      static.reuters.com
104.71.156.71     agency.reuters.com
34.203.177.148    liaison.reuters.com
104.71.156.71     plus.reuters.com
134.213.2.143     widerimage.reuters.com
13.33.28.30	      uk.reuters.com
```

**Comment by yalong1221** [comment]
哦，好的
