### ISSUE TITLE
11.3日新版本hosts Android端无法使用

### ISSUE THREAD

**Issue by SawaraNazo** [googlehosts/hosts#124]
新版本的hosts在Windows端可以正常使用，但是在Android不可以。
我通过Notepad++看了下，发现是换行符出现的问题，结尾都是\r\n，修改为\n之后即可。
希望修改。（ 还要不要Pull一个Request呢？
（看了好久才发现的问题    இ௰இ

**Comment by SawaraNazo** [comment]
还有哦，就是继续 #4   出现的问题，即使手机端修改了hosts，官网可以正常使用，在进行注册时，第一步验证电话号可以正常通过，然而下一步上传头像和姓名就不行了，会提示连接错误。是因为这里要请求a.android,com吗？

**Comment by beyondgfw** [comment]
换行符的话...简单提交pr是没法解决问题的....(TBD)

**Comment by lrinQVQ** [comment]
对 因为请求a.android.com
这个域名你懂的

**Comment by beyondgfw** [comment]
换行符的话很奇怪啊，讲道理应该都是LF，没有CRLF啊。。

**Comment by beyondgfw** [comment]
```
$ curl https://raw.githubusercontent.com/googlehosts/hosts/master/hosts-files/hosts | file -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  719k  100  719k    0     0   719k      0  0:00:01 --:--:--  0:00:01  902k
/dev/stdin: ASCII text
```

**Comment by beyondgfw** [comment]
你有没有用别的文本编辑器编辑过你下载的hosts啊

**Comment by SawaraNazo** [comment]
欸，确实，还要修改yaml，那我就不随便PR了。

**Comment by SawaraNazo** [comment]
@lrinQVQ   இ௰இ  那就算了。

**Comment by SawaraNazo** [comment]
我是直接clone到本地的，打开就是这个样子。

![snipaste_20171104_154323](https://user-images.githubusercontent.com/31041465/32403528-5a9760a4-c177-11e7-80a8-7309691705fe.png)

**Comment by beyondgfw** [comment]
windows下git在checkout的时候会自动转换lf到crlf的。。

**Comment by lrinQVQ** [comment]
2333等会先去尽力处理下这个域名

**Comment by beyondgfw** [comment]
你试试先开命令行运行 `git config --global core.crlf=false`
然后文件夹删掉重新clone

**Comment by SawaraNazo** [comment]
@beyondgfw   这样啊，诶多，对不起，我不知道这个的。好像的确，我之前直接download就没有问题。谢谢了。请把这个问题close吧。打扰了。。

**Comment by beyondgfw** [comment]
没事。。

**Comment by beyondgfw** [comment]
自己是可以close掉自己开的issue的

**Comment by SawaraNazo** [comment]
是这样吗？我才用Github一小段时间，不太会用。
不过，我没在这个页面上找到Close的按钮诶。 ,,ԾㅂԾ,,

**Comment by lrinQVQ** [comment]
2333现在close掉啦肯定就在没了丫

**Comment by SawaraNazo** [comment]
@lrinQVQ   இ௰இ    这样啊。那下次有机会提个good issue 再试下吧。

**Comment by birdofprey** [comment]
linux下无法使用
