### ISSUE TITLE
昨天的已经挂了

### ISSUE THREAD

**Issue by hazakura** [googlehosts/hosts#125]
如题，Google，fa，Twitter等都上不了

**Comment by SawaraNazo** [comment]
昨天更新的Hosts更新了WhatsApp的相关功能，并没有修复G、F、T。
（ 具体更新日志可以查看commit里有关详情

**Comment by SawaraNazo** [comment]
Duplicate of #64

**Comment by lrinQVQ** [comment]
咩还未开始修复Google FB TW等重点对象Duplicate of #64
