### ISSUE TITLE
stunnel 现在还能用吗

### ISSUE THREAD

**Issue by PantherJohn** [googlehosts/hosts#126]
stunnel 现在还能用吗 是不是和socks5 一样都不能用了

**Comment by PantherJohn** [comment]
顺便在多说一句 *.googlevideo.com 大量ip被封怎么办呢昂

**Comment by monkeyklp** [comment]
好像是用不了额，看了半天issues，还是不懂plane b如何操作

**Comment by PantherJohn** [comment]
Fine...

**Comment by PantherJohn** [comment]
Fine...

**Comment by lrinQVQ** [comment]
顺便ps一下 *.googlevideo.com其实只需要能连上一次即可233没这么麻烦 stunnel难说了
