### ISSUE TITLE
在hosts更新后Google还是用不了啊

### ISSUE THREAD

**Issue by kervin521** [googlehosts/hosts#127]
非常感谢你能参与本项目的维护，但是：
开新issue前请先阅读注意事项！
开新issue前请先阅读注意事项！
开新issue前请先阅读注意事项！
https://github.com/googlehosts/hosts/blob/master/.github/CONTRIBUTING.md
否则我们可能会不经警告地关闭你的issue，甚至禁言你的账号！
在阅读完后请删除此处的内容并填写你的issue的内容。

**Comment by beyondgfw** [comment]
Duplicate of #64
