### ISSUE TITLE
在MAC下试了，好像没生效！

### ISSUE THREAD

**Issue by whh1009** [googlehosts/hosts#129]
下载了`hosts`文件，覆盖了本地，重启了`wifi`，也执行了`sudo killall -HUP [mDNSResponder`，但是还是不能访问[https://www.google.com](https://www.google.com)

**Comment by SawaraNazo** [comment]
Duplicate of #64

**Comment by beyondgfw** [comment]
@SawaraNazo 你说得对！

**Comment by SawaraNazo** [comment]
@beyondgfw   诶嘿嘿，看到了就顺手标记下。

不过建议下，既然已经有  #121  这个建议，不如有时间就加上，要不然天天问这些duplicate的问题，还挺麻烦的。

**Comment by beyondgfw** [comment]
大概会成有生之年系列，我下礼拜开始到寒假都没空了。。

**Comment by beyondgfw** [comment]
而且我的想法是利用 `ping`, `nmap`, `openssl s_client`这些工具进行一定程度上的自动化检测，然而这就需要有稳定的国内的服务器使用，这个比较困难。。

**Comment by beyondgfw** [comment]
所以理论上众筹一下就没问题了？(国内服务器是真的贵 同种规格是国外两倍以上 流量还另外算钱)

**Comment by SawaraNazo** [comment]
是这样考虑的啊，的确，利用自动化检测这样，确实能方便地实时判断可用情况。
我想的只是每次更新时，简单地标记一下当前一些大家都关心的网站（例如：Google、tw、fb、YouTube这类）的可用情况。确实是我考虑的简单了。

不过从其他的issue里了解到，你们现在的工作重心放在协议的协商和浏览器的制作的吧，如果这样能从根本上解决问题，不如就先照顾那一边。XD    （ 总之，努力的各位辛苦啦    []~(￣▽￣)~*

**Comment by SerCom-KC** [comment]
直接爬 `ping.chinaz.com` 的结果呢？不过代码量又爆炸了）
