### ISSUE TITLE
QAQ 为什么最近新的hosts都没用啊。。。

### ISSUE THREAD

**Issue by stefanielyq** [googlehosts/hosts#13]
是我打开的方式不对么。。。。

**Comment by lrinQVQ** [comment]
0.0 咩 你是https://www.google.com/ncr咩

**Comment by chavyleung** [comment]
我这也是无效，用的ncr，广东电信

**Comment by lrinQVQ** [comment]
0.0都是chrome咩,火狐或者其他的有些无解XD

**Comment by stefanielyq** [comment]
chrome呀。。。ncr也试过 不ncr也试过。。。

**Comment by lrinQVQ** [comment]
欸~看看情况换IP

**Comment by chavyleung** [comment]
@lrinQVQ 
chrome

现在ncr会跳到Google 环聊了：https://hangouts.google.com/

**Comment by chavyleung** [comment]
刚发现ncr会跳到Google 环聊，清浏览器缓存才正常
估计是早上因为新版本hosts无效，切换到老版本hosts引起的

**Comment by lrinQVQ** [comment]
新换的应该对全国友好0.0
