### ISSUE TITLE
没有hosts的日子里 菜鸟程序员该何去何从

### ISSUE THREAD

**Issue by liuxiaodongdefault** [googlehosts/hosts#130]
话说日子不是已经过去了吗 怎么还封锁ip啊

**Comment by fuchanghao** [comment]
https://github.com/lennylxx/ipv6-hosts

隔壁的v6还是能用的。

**Comment by liuxiaodongdefault** [comment]
@fuchanghao 试了一下 貌似也不行啊

**Comment by SerCom-KC** [comment]
你需要 IPv6 环境……没有当然不行

**Comment by masktao** [comment]
貌似现在失效了,刷进路由器。本来内网都可以用。现在大部分都不能用了

**Comment by wolfan** [comment]
duckduckgo.com 欢迎你~

**Comment by SawaraNazo** [comment]
@wolfan    之前也看其他人推荐过，尝试了一下，发现也打不开诶。    இ௰இ

**Comment by lifeidle** [comment]
盼月亮

**Comment by wolfan** [comment]
@lifeidle 外国的月儿圆，当肉翻之。

**Comment by kennylbj** [comment]
bing  duckduckgo 都还凑合

**Comment by dhqdqk** [comment]
firefox , setVPN

**Comment by lrinQVQ** [comment]
不出意外XD这个月我能releases新版chromium

**Comment by SerCom-KC** [comment]
@lrinQVQ 出不来怎么办🌚

**Comment by lrinQVQ** [comment]
@SerCom-KC 23333那就是意外了

**Comment by braindevices** [comment]
报告duckduckgo已经被墙了

**Comment by nxtreaming** [comment]
作为一个程序员连墙都出不去，有点丢人了。
为了自己工作方面，一个月几十块钱出不起吗？

**Comment by lrinQVQ** [comment]
duckduckgob也被SNI RST了嘛= =

**Comment by SawaraNazo** [comment]
期待新版chromium。
（duckduckgo.com可以使用，前面要使用https。简洁是简洁，不过个人感觉使用体验不如百度。。

**Comment by liuxiaodongdefault** [comment]
感谢各位大佬 让我知道了还有duckduckgo这个网站 好不好用就先试试看啦
另外期待IrinQVQ大佬的更新~

**Comment by JokerShao** [comment]
@lrinQVQ 你是自己写浏览器么。。。

**Comment by SerCom-KC** [comment]
@JokerShao 让Chromium适配TLS最新草案

**Comment by lrinQVQ** [comment]
@JokerShao 楼上正解XD 以及22草案也公布了==继续持续更近ing

**Comment by JokerShao** [comment]
期待中。

**Comment by HakureiMarisa** [comment]
@nxtreaming  买代理感觉也不方便，一开ss，charles就不能抓包了。。

**Comment by braindevices** [comment]
@nxtreaming 代理也被RST了，还不退钱，一个月20$呢，唉。

**Comment by beyondgfw** [comment]
变成讨论帖了吗XD

**Comment by lrinQVQ** [comment]
2333是的
