### ISSUE TITLE
能否添加sourceforge.net

### ISSUE THREAD

**Issue by jerry011235** [googlehosts/hosts#134]
能否添加 sourceforge.net 及其下载的hosts
感谢！

**Comment by SawaraNazo** [comment]
可以正常使用sourceforge.net

`正在 Ping sourceforge.net [216.34.181.60] 具有 32 字节的数据:
来自 216.34.181.60 的回复: 字节=32 时间=289ms TTL=234
来自 216.34.181.60 的回复: 字节=32 时间=314ms TTL=234
来自 216.34.181.60 的回复: 字节=32 时间=279ms TTL=234
来自 216.34.181.60 的回复: 字节=32 时间=269ms TTL=234

216.34.181.60 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 269ms，最长 = 314ms，平均 = 287ms`

**Comment by lrinQVQ** [comment]
下载也一切正常昂 也没有DNS污染
