### ISSUE TITLE
偶尔发现appshopper也被屏蔽了.可否加入下一版hosts?

### ISSUE THREAD

**Issue by 5cylinders** [googlehosts/hosts#135]
mac的app store没有收藏、关注之类的功能，appshopper.com 网站是不错的补充。但这一网站（里边没有任何涉及盗版的内容）居然也不可思议地被屏蔽了。为方便访问，可否将它的解析加入hosts？

**Comment by lrinQVQ** [comment]
Get

**Comment by 5cylinders** [comment]
收回请求。已发现https://appshopper.com可以访问。（但GOOGLE搜索 appshopper，会带到http协议下的网站，至少在我这里是访问不了的。）

**Comment by lrinQVQ** [comment]
soga 看来这个网站没有强制https造成的
