### ISSUE TITLE
建议整理一份排除google全家桶的hosts

### ISSUE THREAD

**Issue by jerry011235** [googlehosts/hosts#136]
建议整理一份**排除**google全家桶（包括google网页，邮箱，youtube等等）的hosts。
好像用findstr什么的。

**Comment by imba-tjd** [comment]
想法是可以，不过你以为本项目的hosts文件是怎么生成的？去改生成后的文件未免太原始了

**Comment by lrinQVQ** [comment]
昂可以是可以的就是有些麻烦

**Comment by 5cylinders** [comment]
如果有这需要，您自己动手删掉一部分内容不过是举手之劳。

**Comment by beyondgfw** [comment]
@jerry011235 可以是可以，但是有什么意义吗

**Comment by imba-tjd** [comment]
@beyondgfw 我想大概有一些人对“精简”有蜜汁追求，既然用不了就它去了。我就是这么做的，不过我刚才又想了想好像确实是意义不大…反正去掉和不去掉都上不了，用proxy又会直接无视hosts

**Comment by jerry011235** [comment]
@beyondgfw 您好，此举在于为翻墙**非刚需**的人而提供便利。
因为目前google全家桶的hosts基本失效，所以平时用hosts能正常上apkpure.com、disqus.com、duckduckgo.com等其他网站和国内网站。
等到用google全家桶时再连代理，因为有时代理会和google的hosts冲突。

**Comment by lrinQVQ** [comment]
@jerry011235 欸多主要是毕竟我们不用SNI 全为官方IP 所以代理也不会出现冲突 昂这个问题

**Comment by SerCom-KC** [comment]
同意楼上，@jerry011235 你可能需要详细讲一下所谓的冲突是什么，因为 Google 的官方服务器基本上都一个样，无论有没有 hosts 都应该不会出问题才对

**Comment by WeihuaGu** [comment]
一般，本地改动成本比较小，我是用
`cat /etc/hosts | grep -v -e google.com -e youtube.com`
能不能建立例如hostsnogoogle之类的新分支？

**Comment by tyfulcrum** [comment]
愿意定制的话可以自己duplicate维护一份定制版，定期同上游合并就好。

**Comment by lrinQVQ** [comment]
2333想要排除太简单了啊 你们看格式都是name:开头 而且我一般都严格按照首字母大写Google排除就好了2333 最后那些特殊域名我专门放在了一起不需要手动delete即可
因为考虑到都是官方IP 不会对代理造成影响所以我觉得没什么大的必要专门维护一份无Google的hosts

**Comment by beyondgfw** [comment]
总之想要就自己维护，这个项目的话因为没什么必要所以不单独维护了。
