### ISSUE TITLE
谷歌、脸书仍然打不开

### ISSUE THREAD

**Issue by wikiZhang** [googlehosts/hosts#137]
这份17-11-21的hosts可以登上Gmail，但是谷歌（香港）和脸书还是打不开。。。求救。。。

**Comment by lifeidle** [comment]
@wikiZhang 我这里和google相关的啥也上不去。。。

**Comment by suihansongmao** [comment]
我这里也是，上不去哦

**Comment by SerCom-KC** [comment]
Duplicate of #64 and #69
请前往以上两个 issue 继续讨论
