### ISSUE TITLE
谷歌翻译直接跳到ipv4.google.com

### ISSUE THREAD

**Issue by 123ysys** [googlehosts/hosts#138]
另外这个issue是否需要合并到#64？

**Comment by lrinQVQ** [comment]
0.0我看看欸

**Comment by SerCom-KC** [comment]
难道 `translate.google.cn` 还会出这种问题？

**Comment by 123ysys** [comment]
是的，现在已经好了，两天前曾出现过。

**Comment by SerCom-KC** [comment]
哇……这大概是谷翔的锅了……

**Comment by SerCom-KC** [comment]
说吧，你是哪个省的什么运营商233

**Comment by 123ysys** [comment]
浙江移动的，360早被卸载了，毕竟多一事不如少一事。这种情况在晚上比较常见

**Comment by SerCom-KC** [comment]
这样啊，我这边湖南移动倒霉这个问题
顺带回复你那边的提问，如果你自己的网络下没有别的装了 360 之类的机器（或者真的中了毒的机器）的话，那就有可能是你的运营商在借 IP 攻击谷歌了。
虽然我实在想不到攻击中国服务器有啥价值……等会儿我问问 @lrinQVQ 是不是存在误封吧

**Comment by 123ysys** [comment]
那就有劳您了@SerCom-KC

**Comment by 123ysys** [comment]
我想问问www.google.cn/map的服务器是不是存在问题？

**Comment by lrinQVQ** [comment]
@123ysys 2333好像是飞翔人方面ban掉了你们的NAT 出口IP

**Comment by lrinQVQ** [comment]
@123ysys www.google.cn/map确实有XD

**Comment by SerCom-KC** [comment]
现在还中枪吗w
（说实话这好像不是 hosts 能解决的问题呢）

**Comment by 123ysys** [comment]
暂时没有了，先关了。
