### ISSUE TITLE
上海移动网，更新完hosts，访问Google，抓包发现3秒超时

### ISSUE THREAD

**Issue by jingith** [googlehosts/hosts#140]
4	3.145492	192.168.152.151	151.101.40.133	TCP	56	62468→443 [FIN, ACK] Seq=1 Ack=1 Win=4103 Len=0 TSval=1505553655 TSecr=2827065830

**Comment by lrinQVQ** [comment]
TLS 1.3 21草案下版本 SNI 封锁233 请等待Chromium 
duplicate of #64

**Comment by beyondgfw** [comment]
Duplicate of #64
