### ISSUE TITLE
请求增加个niconico的hosts

### ISSUE THREAD

**Issue by 123ysys** [googlehosts/hosts#141]
niconico这网站目前很迷，首先官网是可以进的，亲测；但有些时候很多视频会RST，目前也找不到什么规律。不知用hosts可不可以解决这一问题。

**Comment by lrinQVQ** [comment]
啧 我去看看

**Comment by 123ysys** [comment]
谢谢大佬啦。

**Comment by 123ysys** [comment]
忽然发现这网站似乎和谷歌有关系诶？

**Comment by lrinQVQ** [comment]
好像好多域名被封了 我去解决下

**Comment by lrinQVQ** [comment]
昂我们可爱的niconico没有启用https 2333还在使用http
不被重置就有鬼啦XD
没办法解决了XD

**Comment by 123ysys** [comment]
GG

**Comment by 123ysys** [comment]
请问这RST是防火墙的鬼还是它网站自身的鬼？

**Comment by lrinQVQ** [comment]
2333防火墙RST 明文根本没难度

**Comment by 123ysys** [comment]
这样啊，不过我记得这网站在2013年的时候就应该已经不是防火墙的目标了。也是迷。

**Comment by lrinQVQ** [comment]
2333对啊 但是视频不让放

**Comment by 123ysys** [comment]
竟然变成time out了，GG。

**Comment by 123ysys** [comment]
niconico现在开始限制ip了么？如果不用日本的梯子连官网首页都进不去55555。

**Comment by lrinQVQ** [comment]
2333对啊限制代理

**Comment by 123ysys** [comment]
据说技术人员已经在考虑启用https协议了，不过估计也是悬吧。

**Comment by SerCom-KC** [comment]
好歹 niconico 还是有个中国官方的……肯定要想点办法

**Comment by 123ysys** [comment]
@SerCom-KC 我还真的不知道😭。

**Comment by SerCom-KC** [comment]
想 reopen 看戏🤔

**Comment by 123ysys** [comment]
233要是启用的话我再开一个吧。

**Comment by SerCom-KC** [comment]
不要开，开了我直接给你 duplicate 🌚
说一声就好

**Comment by 123ysys** [comment]
明白。

**Comment by 123ysys** [comment]
今天发现niconico的一些页面已经使用https了，也可以播放视频（例如动画板块），不过直播板块仍然没有启用https，还是HTTP RST的状态。各位大佬觉得这个issue有没有reopen的价值🤔？

**Comment by beyondgfw** [comment]
@123ysys 或许可以？

**Comment by 123ysys** [comment]
@beyondgfw 那就万分感谢了。我猜n站以后十有八九会被封吧2333。

**Comment by SerCom-KC** [comment]
pa1149f2c13.dmc.nico 似乎没有观测到 SNI RST，但好像也没 DNS 污染？
@123ysys 可以举一个有问题的域名嘛？

**Comment by 123ysys** [comment]
@SerCom-KC 不不不，大佬您误解我重新开这个issue的意思了。
目前niconico仅仅只有live域名还存在http rst现象，但我担心迟早别的有https的域名也会出问题，所以就想提前reopen。

**Comment by 123ysys** [comment]
@SerCom-KC 要不我先自己close等真有问题再reopen？

**Comment by SerCom-KC** [comment]
@123ysys 
😅脑子有点不好使了。
行吧，现在你应该能自行控制 issue 的开关，就先 close 了吧。

**Comment by 123ysys** [comment]
请求将#325issue与这个issue合并。

**Comment by GoogleHostsSupport** [comment]
@123ysys
由于这个 issue 时间已经过长，所以这边目前暂时决定将本 issue 反向合并到 #325 呢，不好意思～
不过还是感谢您对我们的支持～

**Comment by 123ysys** [comment]
> @123ysys
> 由于这个 issue 时间已经过长，所以这边目前暂时决定将本 issue 反向合并到 #325 呢，不好意思～
> 不过还是感谢您对我们的支持～

It is OK.
