### ISSUE TITLE
谷歌地图的CSS

### ISSUE THREAD

**Issue by 123ysys** [googlehosts/hosts#144]
现在网页版的CSS加载不出来啊

**Comment by SerCom-KC** [comment]
遇到这类问题我是建议打开开发者工具截个图
截图里至少应该包含域名和解析的 IP
![](https://user-images.githubusercontent.com/15853348/33941169-945cd348-e04c-11e7-88bc-fdbf4c6d2e3b.png)
话说你遇到的加载不出来是不是就是指一堆像这样的 404？
@lrinQVQ 可以叫谷翔同步一下资源了

**Comment by 123ysys** [comment]
并不是404，而是指页面一片空白。
@SerCom-KC 顺便求推荐个开发者工具。

**Comment by 123ysys** [comment]
55555，那我得发死了。有许多红条，我先截一条上来看看吧
![tim 20171214115638](https://user-images.githubusercontent.com/27964272/33974940-48b1ce38-e0c6-11e7-9cc7-48395ffd4d1c.png)

![tim 20171214115612](https://user-images.githubusercontent.com/27964272/33974947-59adca2a-e0c6-11e7-81f1-caf7d30cbd40.png)

**Comment by SerCom-KC** [comment]
@123ysys
👏👏👏
恭喜你，你被谷歌拉黑了。🌚
我建议你换个网络环境（比如手机流量开热点）再测试一下，如果恢复正常的话，我建议你关掉本 issue 和 #109，只留一个 #138 来帮你解决问题。

**Comment by 123ysys** [comment]
唔，换成热点可以了，不过谷歌干嘛要拉黑我？

**Comment by 123ysys** [comment]
如今似乎谷歌地图国内域名会直接回跳至谷歌中国的网址诶，不知道为什么。
