### ISSUE TITLE
建议加入并长期维护steam的hosts

### ISSUE THREAD

**Issue by zyf2008Neptune** [googlehosts/hosts#147]
嘛，steam又被墙了。先是社区steamcommunity被污染到facebook，然后又连接重置。
社区可以强制https加上hosts解决，但steam的hosts会经常变化，所以希望能把steam相关的hosts也放进来。

**Comment by SerCom-KC** [comment]
你的意思是干脆 Steam 全家桶？

**Comment by zyf2008Neptune** [comment]
@SerCom-KC 
steamcommunity.com和store.steampowered.com啊，它们共用1个hosts

**Comment by lrinQVQ** [comment]
2333也行 我全加吧 顺便优化下

**Comment by SerCom-KC** [comment]
@zyf2008Neptune 我在想客户端要不要一起了，客户端总不止这两个吧，当然下载服务器估计管不着

**Comment by lrinQVQ** [comment]
客户端我去抓包就好了233

**Comment by GeekCookie** [comment]
google hosts 能用么 好像不行啊

**Comment by lrinQVQ** [comment]
google暂时无法使用2333

**Comment by SerCom-KC** [comment]
@GeekCookie 
Google 目前处于重点封锁状态，需要等待浏览器完全支持 TLS 1.3 才能解决。
请前往 #64 讨论 Google 相关。

**Comment by lrinQVQ** [comment]
记得强制https

**Comment by lrinQVQ** [comment]
0.0看看还有没有遗漏的 有些域名是国内服务器我就没加 其他的都添加了

**Comment by SerCom-KC** [comment]
既然说到强制 https 那我打个公益广告吧
Steam 在 `store.steampowered.com` 下会强制 HTTP
所以……http://steamcommunity.com/discussions/forum/10/1458455461480324749/

**Comment by lrinQVQ** [comment]
2333可以

**Comment by zyf2008Neptune** [comment]
@lrinQVQ 应该都有了，之前用贴吧的工具找的hosts都没有证书。

**Comment by lrinQVQ** [comment]
可怜2333 有了就行 如果有不可用的欢迎随时在这里反馈2333我会去处理的
