### ISSUE TITLE
goods.pixiv.net IP需要更新

### ISSUE THREAD

**Issue by tyfulcrum** [googlehosts/hosts#148]
goods.pixiv.net的新IP为：
```
210.129.120.41
210.129.120.43
210.129.120.44
```
望更新，多谢。

**Comment by SerCom-KC** [comment]
@tyfulcrum 现在呢？~~某人又懒得出来接客了~~

**Comment by tyfulcrum** [comment]
@SerCom-KC 现在？IP还是那些呀。

**Comment by SerCom-KC** [comment]
@tyfulcrum 我的意思是
hosts 已经更新了，现在能用了吗？

**Comment by lrinQVQ** [comment]
2333哇我只是散心完了而已啦

**Comment by tyfulcrum** [comment]
@SerCom-KC 已经正常了，谢谢。

**Comment by lyflyflxf** [comment]
www.pixiv.net 现在也是

> 210.129.120.41
210.129.120.43
210.129.120.44

望更新，多谢。
