### ISSUE TITLE
请问如果有想添加的域名，可以直接提Pull request吗？

### ISSUE THREAD

**Issue by tyfulcrum** [googlehosts/hosts#149]
不清楚贵项目是喜欢提issue报域名IP然后你们自己加还是直接合并。

**Comment by lrinQVQ** [comment]
23333随便的啦 你想怎么样都没问题
但是请考虑好自身安全问题
我们很欢迎大家一起来提PR一起维护2333
但是请考虑好自身安全问题
但是请考虑好自身安全问题

**Comment by SerCom-KC** [comment]
大概是要以 @beyondgfw 的身份提交 commit 吧？🤔

**Comment by tyfulcrum** [comment]
@lrinQVQ @SerCom-KC 我估计也是ww

**Comment by lrinQVQ** [comment]
2333咩愿意的话随时欢迎 不过记得小心
