### ISSUE TITLE
喵？这个可以在这反馈吧？？？

### ISSUE THREAD

**Issue by wolfan** [googlehosts/hosts#15]
![捕获.JPG](https://i.loli.net/2017/08/25/59a0287af2126.jpg)

**Comment by DDoSolitary** [comment]
dang ran ke yi
fcitx hai mei zhuang hao...

**Comment by lrinQVQ** [comment]
咩0.0刷新下看看 不应该欸

**Comment by lrinQVQ** [comment]
记得更新下最新的233减轻下单个服务器的压力

**Comment by lrinQVQ** [comment]
没问题我就关掉啦0.0
