### ISSUE TITLE
建议增加对于https://androidfilehost.com的支持

### ISSUE THREAD

**Issue by WeihuaGu** [googlehosts/hosts#150]
因为xda论坛上发布的rom文件多指向这个网站，所以基本上老旧设备下rom就靠它了。另外对于好多手机的最新rom可以在这个网站上搜索到。

**Comment by SerCom-KC** [comment]
[没有发现DNS污染](http://www.17ce.com/site/dns/201712_24a23f2eed359eedf4e547435acc523c.html)+并没有第二个IP
大概是won't fix了

cc @beyondgfw

**Comment by WeihuaGu** [comment]
@SerCom-KC  那就没有办法了……

**Comment by SerCom-KC** [comment]
看 @lrinQVQ 的想法吧(；・∀・)
这次我先不下结论先233

**Comment by lrinQVQ** [comment]
151.139.240.14可用2333

**Comment by lrinQVQ** [comment]
https://github.com/googlehosts/hosts/commit/5510a8671ecaf5e2f0db42c5c866c08ad7c8d822

**Comment by WeihuaGu** [comment]
是不是这个站本身不稳定？早上根本打不开，中午能刷出来，就是慢，现在。反503 Service Unavailable

**Comment by lrinQVQ** [comment]
欸不应该吧0.0

**Comment by lrinQVQ** [comment]
试试hosts里面的IP

**Comment by WeihuaGu** [comment]
@lrinQVQ 打开还是空白,是不是它的jquery.js引用的是ajax.googleapis.com？

**Comment by WeihuaGu** [comment]
@lrinQVQ 等了很久，出了内容。然后再刷新又成了503。https://fonts.googleapis.com/css?family=Montserrat:400,700 这个字体加载了4400多毫秒。

**Comment by lrinQVQ** [comment]
233那果然了 看来我得先想办法解决下

**Comment by SerCom-KC** [comment]
> https://fonts.googleapis.com/css?family=Montserrat:400,700 这个字体加载了4400多毫秒。

服务器不是在国内吗……

and，看来下次得问清楚究竟是网站本身不行还是网页的某个部分不行了……

**Comment by lrinQVQ** [comment]
对啊2333
203.208.51.69 字体服务器在国内呀

**Comment by WeihuaGu** [comment]
不光是这个字体，今天这个字体倒是75ms就加载了，但是打开还是空白。然后等了很久加载出来了。
![打开还是空白](https://raw.githubusercontent.com/WeihuaGu/asserversource/master/androidfile.jpg)

**Comment by lrinQVQ** [comment]
2333欸

**Comment by lrinQVQ** [comment]
我看看哪里还有问题

**Comment by lrinQVQ** [comment]
有一个js需要use.typekit.net 但是没有污染

**Comment by WeihuaGu** [comment]
@lrinQVQ  use.typekit.net好像是正常的，我单独发了请求，挺快的。
https://use.typekit.net/af/d5fa11/00000000000000003b9ad1b1/27/l?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n7&v=3

**Comment by WeihuaGu** [comment]
@lrinQVQ 是不是因为https://platform.twitter.com/widgets.js这个js?

**Comment by WeihuaGu** [comment]
@lrinQVQ 503是网站加载出来后，再点刷新，就变成503了。
use.typekit.net 的aqx2gho.js这个js,我看了下，作用就是加载下面这几个https://use.typekit.net的字体，是正常的。
use.fontawesome.com
floodprincipal.com
contextual.media.net 
是正常的，打开在200ms左右，https://platform.twitter.com/widgets.js这个js打不开，不知道干什么的。

**Comment by lrinQVQ** [comment]
0.0这个应该是推特的登录功能相关的

**Comment by WeihuaGu** [comment]
恩，我也查了下，是推特关注之类的小插件。打开很慢，是不是因为这个？

**Comment by SerCom-KC** [comment]
这个 503 槽点有点大啊 为什么给的是 200 :joy:

**Comment by lrinQVQ** [comment]
2333有可能了

**Comment by WeihuaGu** [comment]
我盯着请求，https://fonts.googleapis.com/css?family=Montserrat:400,700这个是个分界岭，它加载完成后，就还是空白，然后等很久，突然一下子，界面就一下出来了。
然后firefox左下脚写的是连接ajax.google.com……

**Comment by lrinQVQ** [comment]
23333是啊

**Comment by lrinQVQ** [comment]
哇233333

**Comment by lrinQVQ** [comment]
ajax.google.com不存在啊啧

**Comment by WeihuaGu** [comment]
是https://ajax.googleapis.com,我打错了。

**Comment by lrinQVQ** [comment]
2333这个确实无法打开 估计也有一部分因为ajax.googleapis.com

**Comment by WeihuaGu** [comment]
反正是不明觉厉的卡在这个位置……
![卡](https://raw.githubusercontent.com/WeihuaGu/asserversource/master/androidfile2.jpg)

**Comment by SerCom-KC** [comment]
测试了一下，ajax.googleapis.com 的 jquery 的确会影响页面加载速度。
因为 #64 的原因，所以现在只能使用自动代理规则让这个域名走代理，或者[使用中科大的 CDN 替换之](https://addons.mozilla.org/zh-CN/firefox/addon/replace-google-cdn/)。

**Comment by WeihuaGu** [comment]
@SerCom-KC 感谢推荐附加组件，可以不用等太久就打开了: )

**Comment by lrinQVQ** [comment]
2333解决就好啦

**Comment by WeihuaGu** [comment]
感谢 @lrinQVQ 

使用中科大的镜像 CDN 替换ajax.googleapis.com  推荐可不可以写在wiki里。

**Comment by SerCom-KC** [comment]
写到不用写了吧，反正 #64 迟早要解决的。又不是说 hosts 永远无解
如果没有其他问题的话请 close issue

**Comment by lrinQVQ** [comment]
2333写到是没必要啦 毕竟Chrome已经合并了部分支持了 Google服务器也不久了

**Comment by WeihuaGu** [comment]
好。知道了: )
