### ISSUE TITLE
PIXIV需要更新

### ISSUE THREAD

**Issue by lyflyflxf** [googlehosts/hosts#151]
www.pixiv.net, factory.pixiv.net 现在也是
> 210.129.120.41
210.129.120.43
210.129.120.44

说不定pixiv还有别的IP也变化了。望更新，多谢。

**Comment by SerCom-KC** [comment]
@lrinQVQ `matsuri.pixiv.net` 貌似改用了 Cloudfront 的 CDN……

**Comment by lrinQVQ** [comment]
matsuri.pixiv.net看起来好像只有这个域名用了CDN 其他域名我为了避免使用重复IP使用了官方未公开的解析的IP负载均衡所以不受影响

**Comment by lrinQVQ** [comment]
@SerCom-KC 2333不过确实上了Cloudfront 的域名延迟之后会低一些 用更好的IP吧

**Comment by lrinQVQ** [comment]
https://github.com/googlehosts/hosts/commit/1f78ba43e8000d5c5acdf40b1f4dec2679e06189

**Comment by lyflyflxf** [comment]
@SerCom-KC sorry，210.129.120.53湖北联通PING不通

**Comment by lrinQVQ** [comment]
http://ping.chinaz.com/210.129.120.53
0.0平均延迟超低啊啧

**Comment by lyflyflxf** [comment]
我这边测的41更快一点。53对电信支持更好一些，41对联通支持更好一些
![](https://ws1.sinaimg.cn/large/56e44106gy1fmqmmujpgpj20qr07odg7.jpg)
![](https://ws1.sinaimg.cn/large/56e44106gy1fmqmmujew4j20qq06uwer.jpg)
![](https://ws1.sinaimg.cn/large/56e44106gy1fmqmmukxg5j20qp07pq3d.jpg)
![](https://ws1.sinaimg.cn/large/56e44106gy1fmqmmujjunj20qp07pjrp.jpg)

**Comment by lrinQVQ** [comment]
2333咩那就只能麻烦你手动调整下了XD 这个没办法分流啊

**Comment by lyflyflxf** [comment]
好的

**Comment by SerCom-KC** [comment]
总之可以 close 了吧😂

**Comment by lyflyflxf** [comment]
可以了。@SerCom-KC 幸亏你留了一个41的版本![smile](https://assets-cdn.github.com/images/icons/emoji/unicode/1f602.png)

**Comment by SerCom-KC** [comment]
hhhhh
你自己关就好了
还有友情提示一下
GitHub 是可以上传图片和发送 emoji 的
所以为了避免水表请尽量不要用新浪图床了（会暴露自己 ID 这事应该知道吧）

**Comment by lyflyflxf** [comment]
谢谢。是应该注意一下隐私问题:blush:
