### ISSUE TITLE
Google和fb是不是活不了了？

### ISSUE THREAD

**Issue by wolfan** [googlehosts/hosts#152]
这转眼就要过年了，Google有鸭子替换fb只能上墙梯了。

**Comment by lrinQVQ** [comment]
咩我就等一个证书了
我自己的SNI IP:45.124.64.82,可用的时候我会直接公开公布的
提供一年,直到Google公开

**Comment by wolfan** [comment]
✧٩(ˊωˋ*)و✧
给大佬送尻

**Comment by lrinQVQ** [comment]
咩~2333其实你在TG群的话很早就能知道的

**Comment by lrinQVQ** [comment]
暂时避免更多人看到我就先close了233

**Comment by wolfan** [comment]
( •̥́ ˍ •̀ू )嘤嘤嘤，梯子欠费了，没法用tg了。

**Comment by lrinQVQ** [comment]
2333你要是有办法用比较安全的方式联系到我 我免费给你服务器

**Comment by SerCom-KC** [comment]
Duplicate of #64 and #69

**Comment by lrinQVQ** [comment]
2333哇

**Comment by SerCom-KC** [comment]
Duplicate of #64

**Comment by SerCom-KC** [comment]
@wolfan 
> ( •̥́ ˍ •̀ू )嘤嘤嘤，梯子欠费了，没法用tg了。

https://github.com/googlehosts/hosts/wiki/Telegram-%E5%9F%BA%E6%9C%AC%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97
