### ISSUE TITLE
求增加http://www.crunchyroll.com的hosts

### ISSUE THREAD

**Issue by 123ysys** [googlehosts/hosts#153]
不知这个网站有没有https协议，求大佬帮我检查一下。目前测试是输入https会跳到http。

**Comment by SerCom-KC** [comment]
好像跟 Steam 一样也是有 HTTPS 但也会强制 HTTP 的类型…… :relieved:

**Comment by 123ysys** [comment]
主要是我用热点太费流量了（手机热点能用，但无线WiFi就打不开）。另外steam的强制http已经被人们吐过无数次的槽了。

**Comment by lrinQVQ** [comment]
哇

**Comment by lrinQVQ** [comment]
好像可以强制https

**Comment by 123ysys** [comment]
哇

**Comment by SerCom-KC** [comment]
大概加了没用系列
不过既然有 HTTP RESET 大概还是可以加一下（

**Comment by lrinQVQ** [comment]
emmm刚刚打开出现了强制https
我还以为ie终于上https了
结果XD http XD

**Comment by 123ysys** [comment]
似乎它们只有在登陆、付款这些需要加密的页面启用了https, 其他的都是http。我正在等待它们关于是否会全面启用https的回复。
ps: 不同的网络环境会得到不同的结果。例如我使用路由器就会SNI RST, 而我使用热点流量就会出现“EMPTY  RESPOND"的现象，多刷新几次就能加载出来。根据它们客服提供的参考，猜测可能是路由器解析出现了问题。 @lrinQVQ

**Comment by lrinQVQ** [comment]
@123ysys 2333 不不不其实是HTTP RST

**Comment by 123ysys** [comment]
@lrinQVQ 哦，是那个”SNI RST“吧？抱歉，还有很多不懂。

**Comment by SerCom-KC** [comment]
@123ysys
SNI RST 指的是 https 的情况
HTTP RST 指的是 http 的情况

**Comment by SerCom-KC** [comment]
不过话说回来
Crunchyroll 现在用的视频服务器其实是 VRV 的
而 VRV 支持全站 https
只不过 `vrv.co` 和 `api.vrv.co` 可能需要挂一下美国代理

**Comment by 123ysys** [comment]
哦，就是这两个网站需要代理是吧？那得怎么办呢？ 毕竟VRV有区域内容限制。

**Comment by SerCom-KC** [comment]
自己有美国代理的话，配合 SwitchyOmega 浏览器插件做一下自动规则切换就好了，反正就两个域名，实际视频不用走代理，所以你拿免费的代理应该都可以

**Comment by 123ysys** [comment]
@SerCom-KC 谢谢。

**Comment by SerCom-KC** [comment]
总之先暂时关了
Crunchyroll 目前并没有大面积 DNS 污染
而 hosts 并不能解决强制 http 的问题
这个只能等 Crunchyroll 自己改
等他们支持全站 https 了请再留言请求 reopen，会考虑加进 hosts 的

**Comment by 123ysys** [comment]
@SerCom-KC 请问SwitchyOmega是这样设置的吧？我改了似乎也没用。
![photo_2018-02-04_17-55-06](https://user-images.githubusercontent.com/27964272/35776341-65d36ffc-09d5-11e8-8ce9-9e2f86118e55.jpg)
