### ISSUE TITLE
173.194.198.82 gcr.io cant't work

### ISSUE THREAD

**Issue by fanhaozzu** [googlehosts/hosts#154]
173.194.198.82 gcr.io cant't work

**Comment by fanhaozzu** [comment]
173.194.198.82 gcr.io cant't work

**Comment by SerCom-KC** [comment]
Most Google services are not available via hosts at the moment.
Closing this issue as a duplicate of #64.

**Comment by SerCom-KC** [comment]
Most Google services are not available via hosts at the moment.
Closing this issue as a duplicate of #64.

**Comment by SerCom-KC** [comment]
Re-opening since this domain is not in the blacklist.
cc @lrinQVQ

**Comment by lrinQVQ** [comment]
Get I will try to fix it

**Comment by Runrioter** [comment]
Will this is fixed ?

**Comment by lrinQVQ** [comment]
This domain needs Google Code ip.
It takes a lot of time to find it

**Comment by limjoe** [comment]
什么时候修复？之前网上公开的 gcr.io 都不能用了

**Comment by SerCom-KC** [comment]
@limjoe 
正如 @lrinQVQ 所说，`gcr.io` 只能用 Google Code 的 IP，普通的 gws IP 是用不了的，所以很难找

**Comment by fanhaozzu** [comment]
https://github.com/fanhaozzu/googlehost，大家可以试试

**Comment by SerCom-KC** [comment]
姑且提醒一下各位，楼上使用的是非官方（腾讯）IP

**Comment by beyondgfw** [comment]
跟 #64 合并处理。
