### ISSUE TITLE
Happy new year !

### ISSUE THREAD

**Issue by lrinQVQ** [googlehosts/hosts#157]

**Comment by SawaraNazo** [comment]
各位参与人员辛苦了~多亏你们才能跨在墙头。    ♪(^∇^*)
新一年也希望继续下去，谢谢啦。  q(≧▽≦q)

**Comment by lrinQVQ** [comment]
咩也感谢你们的反馈啦~
2018年愿大家冲破枷锁,事事如愿以偿2333

**Comment by zyf2008Neptune** [comment]
![d3c63a9017a0cc542e7acb86b6b46c22](https://user-images.githubusercontent.com/16064492/34465319-1819eefc-eee2-11e7-9f55-0e2aa3c3327f.jpg)

**Comment by Orznge** [comment]
新年快乐~

还有你QQ好像被盗号了（虽然不用

**Comment by lrinQVQ** [comment]
@Orznge 2333来来了上TG一起说

**Comment by lrinQVQ** [comment]
@zyf2008Neptune @Orznge 新年快乐233

**Comment by tx67039328** [comment]
请问各位大神一下现在还有能用的翻墙工具么？我都断网了快半年了，都一直没找到有用的工具，现在迷茫的很。

**Comment by Orznge** [comment]
@lrinQvQ 我能上TG了，但是要联系人才能说话。id Kent Huang

**Comment by JokerShao** [comment]
新年快乐，一月了，不知道新版chrome如期释出了嘛@IrinQVQ

**Comment by lrinQVQ** [comment]
@JokerShao 新年快乐~ Chrome dev版本 chrome://flag 所以TLS 1.3 选择Enabled (Draft 22)

**Comment by JokerShao** [comment]
之后就可以了嘛。。？

**Comment by lrinQVQ** [comment]
Google服务器还未部署233 so 不行

**Comment by SerCom-KC** [comment]
@lrinQVQ 说好的“所有服务器早就有了”呢🌚

**Comment by lrinQVQ** [comment]
@SerCom-KC 2333你们用不上就等于没有啊

**Comment by JokerShao** [comment]
扎心了。。

**Comment by lrinQVQ** [comment]
2333等测试完公开我就会告诉你们的啦
现在解释可能会泄漏一些东西

**Comment by JokerShao** [comment]
好的，总的来说还是非常感谢的，辛苦啦！

**Comment by lrinQVQ** [comment]
2333小意思啦

**Comment by mygithome002** [comment]
新年快乐~

**Comment by lrinQVQ** [comment]
@mygithome002 新年快乐~

**Comment by fae88** [comment]
这些ip都ping超时啦，怎么破

**Comment by SerCom-KC** [comment]
@fae88 Google/Twitter/Facebook/OneDrive/Dropbox 目前一律不处理，详见 [Wiki](https://github.com/googlehosts/hosts/wiki#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%88%B0%E7%8E%B0%E5%9C%A8%E9%83%BD%E8%BF%98%E4%B8%8A%E4%B8%8D%E4%BA%86-googletwitterfacebookonedrivedropbox-%E7%AD%89%E6%9C%8D%E5%8A%A1)
