### ISSUE TITLE
建议加一波对 Google Drive 在线视频播放的支持

### ISSUE THREAD

**Issue by SerCom-KC** [googlehosts/hosts#16]
倒也不麻烦：把现在的 Google Video 部分复制一下，Ctrl + H `.googlevideo.com` → `.c.drive.google.com` 就好了![#(滑稽)](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)

**Comment by lrinQVQ** [comment]
吼啊

**Comment by lrinQVQ** [comment]
加了233,之后还要修复一些域名的说

**Comment by SerCom-KC** [comment]
诶还要修啥？

**Comment by SerCom-KC** [comment]
对了我在群里说了还有一个 `www.chromium.org` 来着233

**Comment by lrinQVQ** [comment]
是啊2333 基于这些域名修复一些失效IP啦

**Comment by SerCom-KC** [comment]
等等，你是不是把 `drive.google.com` 本体漏了！！！😂

**Comment by lrinQVQ** [comment]
欸2333确实忘了
