### ISSUE TITLE
关于Github打开不畅的问题

### ISSUE THREAD

**Issue by AlexDialga** [googlehosts/hosts#161]
个人在使用长城宽带的时候发现有些东西加载不出来，
所以就在myip.ms里随便找了一下github网站中，
需要加载域名的IP地址。
嘛，先让大家看看，再考虑要不要使用吧ww

151.101.184.133	raw.githubusercontent.com
151.101.184.133	assets-cdn.github.com
151.101.184.133	avatars0.githubusercontent.com
151.101.184.133	avatars1.githubusercontent.com
151.101.184.133	avatars2.githubusercontent.com
151.101.184.133	avatars3.githubusercontent.com

**Comment by lrinQVQ** [comment]
2333其实Fastly家的CDN全都是玄学
我这里151.101.0.133延迟才70
151.101.184.133 260 2333

**Comment by SerCom-KC** [comment]
目测是长宽自带的 DNS 污染？
非普遍性问题的话个人建议自行处理😂

**Comment by AlexDialga** [comment]
@lrinQVQ CDN还有这种操作2333

@SerCom-KC 嗯呐，当时 我只是感觉可能其他人看git的时候可能也会抽风，所以就随便搞一下啦ww

**Comment by lrinQVQ** [comment]
233333 @AlexDialga 是的233就是有这种操作

**Comment by SerCom-KC** [comment]
因为是个别情况所以暂时关了
有需要请再留言，谢谢~
