### ISSUE TITLE
关于维吾尔文维基百科

### ISSUE THREAD

**Issue by Chinese-User** [googlehosts/hosts#162]
维吾尔文维基百科目前也被屏蔽了，请求添加 ug.wikipedia.org 和 ug.m.wikipedia.org ，另外日文维基百科（ ja.wikipedia.org ）仅电脑版被墙，手机版（ ja.m.wikipedia.org ）不改 hosts 也能正常访问

**Comment by SerCom-KC** [comment]
确认 DNS 污染，感谢报告
`ja.m.wikipedia.org` 也留着吧，谁知道以后会不会翻车

**Comment by SerCom-KC** [comment]
@lrinQVQ review
