### ISSUE TITLE
developer.android.com

### ISSUE THREAD

**Issue by Adam0407** [googlehosts/hosts#166]
非常感谢你能参与本项目的维护，但是：
开新issue前请先阅读注意事项！
开新issue前请先阅读注意事项！
开新issue前请先阅读注意事项！
https://github.com/googlehosts/hosts/blob/master/.github/CONTRIBUTING.md
否则我们可能会不经警告地关闭你的issue，甚至禁言你的账号！
在阅读完后请删除此处的内容并填写你的issue的内容。

**Comment by Adam0407** [comment]
试了下两个android的网址，都ping不通

**Comment by SerCom-KC** [comment]
Duplicate of #64

论 https://developer.android.google.cn 存在的意义

不过你倒是指出了一个大问题，那个测试 IP 现在貌似已经被 Google 关了，所以 @lrinQVQ 过来接锅

**Comment by Adam0407** [comment]
可以，之前有用这个网址，但是因为通过google搜索关键字搜索出来的网页是android美国官网地址，又打不开所以才提到了这个问题。

**Comment by SerCom-KC** [comment]
这个是 Google 专门给中国另外开的官方镜像所以地址不同
类似的操作还有很多
总之请收藏好备用
两边内容应该是同步的
