### ISSUE TITLE
surge的conf建议

### ISSUE THREAD

**Issue by digicolor** [googlehosts/hosts#167]
第一个[Rule]中的FINAL,DIRECT是否可以删除，之前我记得好像没有这项，
一来，新版的surge3上已经可以选择是否是FINAL,DIRECT.
二来，像我这样用托管更新的，可操作性更大一点，因为我是一部分用的HOST，一部分用的是SS，在一个conf里，如果FINAL,DIRECT，等于SS那部分没用了，或者每次更新好后，要把那个[Rule]删掉，才可以，比较麻烦

希望采纳，

**Comment by beyondgfw** [comment]
>  一来，新版的surge3上已经可以选择是否是FINAL,DIRECT.

麻烦给出来源（文档或选项的截图一类），以便我确认，我没有ios设备。。

**Comment by beyondgfw** [comment]
Related: #99
