### ISSUE TITLE
这里的谷歌hosts根本ping不通的

### ISSUE THREAD

**Issue by effzmt** [googlehosts/hosts#168]
这里的谷歌hosts根本ping不通的，看了最近几次的提交，都是新增一些没用的地址。最基本的谷歌不能用，加那么多其他地址也是白搭。

**Comment by birdofprey** [comment]
本来就不是在墙内用的呀。哈哈

**Comment by SerCom-KC** [comment]
①关于 Google 的解释请看 [wiki](https://github.com/googlehosts/hosts/wiki#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%88%B0%E7%8E%B0%E5%9C%A8%E9%83%BD%E8%BF%98%E4%B8%8A%E4%B8%8D%E4%BA%86-googletwitterfacebookonedrivedropbox-%E7%AD%89%E6%9C%8D%E5%8A%A1)
②对你没用而已
③你觉得白搭而已

**Comment by SerCom-KC** [comment]
Duplicate of #64

**Comment by lrinQVQ** [comment]
fix now
https://github.com/googlehosts/hosts/commit/e56456b8027b3046770cf6d64cdf404cabe968ac
