### ISSUE TITLE
the GFW can block SSH connection based on data flow rate?

### ISSUE THREAD

**Issue by braindevices** [googlehosts/hosts#169]
I just found out the GFW will block IP for 1 hour, if download large file through ssh. This is crazy. So now I cannot obtain business data through ssh... Any data flow below 50KB/s is OK ...
Test inside China Telecomm, no such feature in China unicom.
Any one know any solution for this?

**Comment by SerCom-KC** [comment]
Kind of off-topic, but I prefer not closing this immediately.

And, IMO, no "actual" solution for this.
You'll probably have to make SSH traffic through VPN or something ~~or just leave "中国奠信" alone~~

**Comment by DDoSolitary** [comment]
Maybe a "question" label is better.

**Comment by beyondgfw** [comment]
It's been obersved for a long time. GFW does detect and block SSH connections. You can try using some encrypted proxying techniques in front of your SSH server (e.g. VPN as @SerCom-KC mentions). Or if you can control your SSH server, there is [a fork of OpenSSH server with an obfuscated protocol](https://github.com/brl/obfuscated-openssh), and putty has built-in clilent support for it. Though it is not guaranteed to work...

**Comment by SerCom-KC** [comment]
> Maybe a "question" label is better.
I thought that was for hosts-related questions only lol

**Comment by braindevices** [comment]
@SerCom-KC thanks a lot for keeping this topic open. @beyondgfw I am going to try the obfuscated protocol, let's see what will happen.

**Comment by SerCom-KC** [comment]
Close for now. Let me know if you have any reasons to keep this open
