### ISSUE TITLE
2018.2.11 怎么访问不了

### ISSUE THREAD

**Issue by px1005** [googlehosts/hosts#174]
2018.2.11 怎么访问不了

**Comment by SerCom-KC** [comment]
什么网站

**Comment by px1005** [comment]
google呀

**Comment by px1005** [comment]
我本地写host，还是访问不了

**Comment by SerCom-KC** [comment]
下次开 issue 前请一开始就写清楚
这个 hosts 又不止 Google 一个网站

Google 目前不修，原因见[此](https://github.com/googlehosts/hosts/wiki#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%88%B0%E7%8E%B0%E5%9C%A8%E9%83%BD%E8%BF%98%E4%B8%8A%E4%B8%8D%E4%BA%86-googletwitterfacebookonedrivedropbox-%E7%AD%89%E6%9C%8D%E5%8A%A1)，预计下个月更新
更新前请记得更新 Chrome 浏览器

**Comment by SerCom-KC** [comment]
Duplicate of #64
