### ISSUE TITLE
建议加入中文维基新闻的非手机版网址

### ISSUE THREAD

**Issue by Solid-Block** [googlehosts/hosts#176]
中文维基新闻是被封的。但是文件只有zh.m.wikinews.org没有zh.wikinews.org怎么回事？以致电脑版中文维基新闻无法访问。我在自己的hosts中加入198.35.26.96	zh.wikinews.org就修复了。

**Comment by SerCom-KC** [comment]
0788217e66e8b17ef4d7b2230c0ad0f20e6467d8
看来是由于玄学原因漏加了
