### ISSUE TITLE
建议添加https://www.proxysite.com/ https://www.kproxy.com/ https://www.proxfree.com/ https://www.filterbypass.me/

### ISSUE THREAD

**Issue by rockgregro** [googlehosts/hosts#177]
非常感谢你能参与本项目的维护，但是：
开新issue前请先阅读注意事项！
开新issue前请先阅读注意事项！
开新issue前请先阅读注意事项！
https://github.com/googlehosts/hosts/blob/master/.github/CONTRIBUTING.md
否则我们可能会不经警告地关闭你的issue，甚至禁言你的账号！
在阅读完后请删除此处的内容并填写你的issue的内容。

**Comment by SerCom-KC** [comment]
啥？

**Comment by rockgregro** [comment]
proxysite.com
很好的在线代理网站

**Comment by rockgregro** [comment]
这些都是

**Comment by SerCom-KC** [comment]
hmm 这种网站停留时间不会超过 5 分钟吧 挂梯子访问不好嘛（
姑且还是看一看

**Comment by rockgregro** [comment]
来一个没有封的https://chinaproxy.club/

**Comment by rockgregro** [comment]
proxysite.com可看youtube

**Comment by rockgregro** [comment]
这正是我们需要解决的问题

**Comment by SerCom-KC** [comment]
虽然是个好主意，但既然用 proxy 就没必要再用 hosts 了
这里不是 gfwlist，所以我个人觉得是没必要加
不过还是等其他人意见

**Comment by rockgregro** [comment]
谢谢 用hosts解封google youtube难度较大 但解封这种 比较容易 现在封锁严重 我想不妨添加 多一种方法

**Comment by SerCom-KC** [comment]
难度其实不大，细节的话 wiki 里有讲
而且，虽然这个项目隐性地安利了 socks5 和 shadowsocks（🌚），但这里终究不是交流翻墙方法的地方
同类的网站太多了，真要全加恐怕加不过来吧（

**Comment by beyondgfw** [comment]
Closed because of the resolution

**Comment by rockgregro** [comment]
您可能不太明白我滴意思 只需添加 proxysite.com         kproxy.com即可                        不用全加 @beyondgfw @SerCom-KC @lrinQVQ                            这是对抗封锁严重时的一种应急办法        如果觉得值得推广 说明情况 写进wiki                           如果认为不应推广              添加对个人帮助很大                                感激不尽

**Comment by SerCom-KC** [comment]
姑且说一下
close issue 不等于讨论截止
有很多人订阅了本项目的所有更新
所以就算是发在 closed issue 里面的东西他们也还是看得到

但是，本项目 **不是进行翻墙方式交流的地方**
不欢迎任何广告行为，包括疑似的（这个由管事的判断）
so 我不建议你在这里大量堆网站（

**Comment by rockgregro** [comment]
谢谢 见谅

**Comment by xxmmllqqqqccqq** [comment]
@rockgregro 有需要的可以直接拿走，但本人不对以下网址的安全性和可用性负责。
不喜欢的可以点反对。不清楚维护组是否有删回复的权限，如果有权限可以随意删，如果要求我自行删除的话请通知我（由于我先前block了某个账号，所以有可能收不到通知呵呵）。
<pre># ProxySite Start
34.203.154.97&ensp;&ensp;proxysite.com
34.203.154.97&ensp;&ensp;www.proxysite.com
213.32.5.165&ensp;&ensp;&ensp;eu0.proxysite.com
51.254.174.156&ensp;eu1.proxysite.com
137.74.58.219&ensp;&ensp;eu2.proxysite.com
178.33.33.138&ensp;&ensp;eu3.proxysite.com
164.132.119.16&ensp;eu4.proxysite.com
217.182.18.114&ensp;eu5.proxysite.com
188.165.65.182&ensp;eu6.proxysite.com
5.135.136.191&ensp;&ensp;eu7.proxysite.com
176.31.227.198&ensp;eu8.proxysite.com
68.235.48.43&ensp;&ensp;&ensp;us1.proxysite.com
68.235.52.51&ensp;&ensp;&ensp;us2.proxysite.com
68.235.52.123&ensp;&ensp;us3.proxysite.com
68.235.52.219&ensp;&ensp;us4.proxysite.com
68.235.61.83&ensp;&ensp;&ensp;us5.proxysite.com
68.235.61.99&ensp;&ensp;&ensp;us6.proxysite.com
192.99.65.210&ensp;&ensp;us7.proxysite.com
68.235.61.75&ensp;&ensp;&ensp;us8.proxysite.com
68.235.61.83&ensp;&ensp;&ensp;us9.proxysite.com
68.235.61.99&ensp;&ensp;&ensp;us10.proxysite.com
192.99.16.196&ensp;&ensp;us11.proxysite.com
167.114.210.76&ensp;us12.proxysite.com
68.235.60.179&ensp;&ensp;us13.proxysite.com
34.225.40.9&ensp;&ensp;&ensp;&ensp;us14.proxysite.com
34.225.40.9&ensp;&ensp;&ensp;&ensp;us15.proxysite.com
34.225.40.9&ensp;&ensp;&ensp;&ensp;us16.proxysite.com
# ProxySite End</pre>

**Comment by beyondgfw** [comment]
@rockgregro @xxmmllqqqqccqq 感谢对项目的关注和支持 其实很久以来一些类似的（需求较少的）网站都是这样放在issue里面，然后需要的人自取。
另外窝注意到 @rockgregro 好像把issue内容都写在了标题，建议以后在Github开issue的时候抽时间看一下项目的issue template（包括最后一行），谢谢合作。

**Comment by rockgregro** [comment]
表示楼上给的hosts完全没用

**Comment by PetTko** [comment]
贡献一个 pac
https://www.dun.im/free_dun.php

**Comment by SerCom-KC** [comment]
@PetTko 本项目谢绝对其他项目的代理的安利行为。
