### ISSUE TITLE
您可能不太明白我滴意思 只需添加 proxysite.com kproxy.com即可 不用全加 @beyondgfw @SerCom-KC @lrinQVQ 这是对抗封锁严重时的一种应急办法 如果觉得值得推广 说明情况 写进wiki 如果认为不应推广 添加对个人帮助很大 感激不尽 希望不要算我重开                或者当我请求添加proxysite.com              kproxy.com                感激不尽

### ISSUE THREAD

**Issue by rockgregro** [googlehosts/hosts#178]
非常感谢你能参与本项目的维护，但是：
开新issue前请先阅读注意事项！
开新issue前请先阅读注意事项！
开新issue前请先阅读注意事项！
https://github.com/googlehosts/hosts/blob/master/.github/CONTRIBUTING.md
否则我们可能会不经警告地关闭你的issue，甚至禁言你的账号！
在阅读完后请删除此处的内容并填写你的issue的内容。

**Comment by rockgregro** [comment]
希望大神不要禁言我

**Comment by rockgregro** [comment]
帮助大家    上一个分享被like了  证明有人喜欢这种方式        再来一个https://unblockit.co/

**Comment by SerCom-KC** [comment]
你多开issue就是等着被封禁的节奏啊（

**Comment by SerCom-KC** [comment]
Duplicate of #177

**Comment by rockgregro** [comment]
好吧        仅为建议
