### ISSUE TITLE
chrometophone.appspot.com 不可用

### ISSUE THREAD

**Issue by duicym** [googlehosts/hosts#179]
216.58.203.244	chrometophone.appspot.com
216.58.203.244	chrome-devtools-frontend.appspot.com
这两个不能用了

**Comment by lrinQVQ** [comment]
get

**Comment by lrinQVQ** [comment]
https://github.com/googlehosts/hosts/commit/c4e2526bf06832f66e89ec6a21ed51270888a598
fix now
