### ISSUE TITLE
建议添加 cdn.ampproject.org

### ISSUE THREAD

**Issue by SerCom-KC** [googlehosts/hosts#18]
虽说国内的话 `cdn.ampproject.org` 已经是解析到谷翔的 IP 上了，但似乎只是提供了 [AMP runtime 的加速](https://cdn.ampproject.org/v0.js)
搞网站开发的可能会懵逼，因为[官方教程](https://ampbyexample.com/introduction/how_to_publish_amps/#test-with-the-google-amp-cache)里的 `https://cdn.ampproject.org/c/AMP_URL_WITHOUT_SCHEME` 和 `https://cdn.ampproject.org/c/s/AMP_URL_WITHOUT_SCHEME` 之类的应该是没法用的😂（比如 https://cdn.ampproject.org/c/s/ampbyexample.com）
不知道有没有必要233

**Comment by lrinQVQ** [comment]
2333get

**Comment by lrinQVQ** [comment]
应该OK啦～能打开貌似

**Comment by SerCom-KC** [comment]
嗯OK了，不过我这边TCP干扰还是好严重啊（假移动Orz

**Comment by lrinQVQ** [comment]
2333准备换段

**Comment by SerCom-KC** [comment]
感觉这一条可以移掉了（速度考虑），因为官方对以上两种链接均设置了跳转到另一个域名
大概是有意为之吧233
