### ISSUE TITLE
tumblr 视频无法播放 

### ISSUE THREAD

**Issue by Mao-jiawei** [googlehosts/hosts#180]
tumblr 视频无法播放  求大神解决

**Comment by SerCom-KC** [comment]
电脑请 F12 → Network → 给一下红色的域名
请注意，类似 `博客ID.tumblr.com` 这样的域名请自行添加

**Comment by Mao-jiawei** [comment]
@SerCom-KC  不行额。 IP使用 66.6.32.21 不知道有没有问题

**Comment by Mao-jiawei** [comment]
@SerCom-KC   我用dnsmasq   泛解析   最近视频加载不行

**Comment by Mao-jiawei** [comment]
视频加载非常慢， vtt.tumblr.com ip选的也是低延迟的， 不知道问题出在哪里了。

**Comment by Mao-jiawei** [comment]
@lrinQVQ  大神

**Comment by lrinQVQ** [comment]
咦

**Comment by lrinQVQ** [comment]
@Mao-jiawei 216.115.100.126试试

**Comment by SerCom-KC** [comment]
> 视频加载非常慢

加载慢和完全无法访问是两个完全不同的级别23333 请务必要说清楚
一般来说 hosts 里的 IP 选择会倾向于全国可用性而不是速度，所以使用 hosts 翻墙是很难做到速度保证的（毕竟众口难调）

总之你试试 QVQ 给的 IP 吧

**Comment by Mao-jiawei** [comment]
@lrinQVQ  @SerCom-KC  感谢可以了 陷入误区了 ping低不代表get  用get 测得ip 才好用

**Comment by diyici18sui** [comment]
提交一个测试共大神参考 
目前电脑端和安卓端均采用此hosts
电脑端tumblr能正常登陆，显示图片，但视频无法打开。
手机端能正常登陆，显示图片，视频能正常播放，但是刷新比较慢。
将vtt.tumblr.com地址放入代理地址，则可以播放视频。。。估计是这个地址的解析有问题··
以上尝试请大神参考

**Comment by Mao-jiawei** [comment]
@diyici18sui 119.161.10.101 vtt.tumblr.com
 试试这个ip 非常ok

**Comment by diyici18sui** [comment]
@Mao-jiawei 感谢回复，试了下还是不行，北京联通。

**Comment by SerCom-KC** [comment]
> 电脑端视频无法打开
手机端视频能正常播放

@diyici18sui 这里的手机端指的应该是 app 内而不是网页吧
电脑端请 F12 → Network → 给一下红色的域名
我感觉应该是 `博客ID.tumblr.com` 无误

**Comment by diyici18sui** [comment]
@SerCom-KC  抱歉 电脑小白一名。手机端我说的app
另外您说的 “电脑端请 F12 → Network → 给一下红色的域名”红色的域名您只得是？

**Comment by Mao-jiawei** [comment]
@diyici18sui  可以叫我扣扣 478882070

**Comment by SerCom-KC** [comment]
@diyici18sui

打开有视频的 tumblr 页面，然后按下 F12，在弹出的窗口里找到 Network 选项卡，然后刷新 tumblr 页面
如果是 Chrome 的话，这时应该会出现一些红色的条目，请在这些条目上右键，选择 Copy link address，把从 https:// 直到后面第一个 / 的内容发上来

**Comment by diyici18sui** [comment]
@Mao-jiawei 非常感谢 只有一个qq用于工作 不方便加您，谢谢了

**Comment by diyici18sui** [comment]
@SerCom-KC assets.tumblr.com 谢谢指点，我刚才百度了下，也发现了

**Comment by SerCom-KC** [comment]
@diyici18sui

这个域名全国情况好像还好啊
直连访问 assets.tumblr.com 的那个 **完整** 链接有什么错误提示吗

**Comment by diyici18sui** [comment]
@SerCom-KC  谢谢您 
我刚把ublock关掉 红色的链接少了很多 在不开广告拦截 不开代理的情况下， 出现两个红色链接分别均为https://xxflouise.tumblr.com/开头，（xxflouise是博客的id，我似乎暴露了）
直接访问完整链接
显示响应时间过长

**Comment by SerCom-KC** [comment]
@diyici18sui

> 出现两个红色链接分别均为https://xxflouise.tumblr.com/开头

那就没错了，因为我们不可能把所有 tumblr 博主 ID 都加进 hosts 里，所以您只能自行添加到自己的 hosts 内，或给它们设置自动代理规则。

> https://97.media.tumblr.com/也是红色的

稍后我看一下

**Comment by diyici18sui** [comment]
@SerCom-KC 懂了 谢谢！

**Comment by SerCom-KC** [comment]
啊，貌似修掉了
各位感受一下看看？

**Comment by lrinQVQ** [comment]
嘛基本都是延迟80左右的

**Comment by userfromchina** [comment]
遇到了相似的问题，APP内视频预览图加载不出来，全都是黑色的，点击视频，等待一会儿后变成灰色的叉。偶尔打开APP后第一个视频能播放，后面的都是上述现象。
