### ISSUE TITLE
google.co.jp封锁没有google.com那么大

### ISSUE THREAD

**Issue by rockgregro** [googlehosts/hosts#183]

**Comment by rockgregro** [comment]
好像不是重点关照对象

**Comment by rockgregro** [comment]
希望 大神们帮我ping一下kproxy.com
重点还是google.co.jp

**Comment by rockgregro** [comment]
希望帮助更多的人

**Comment by lrinQVQ** [comment]
Thanks~!!好像确实欸

**Comment by lrinQVQ** [comment]
@rockgregro 192.95.4.124

**Comment by rockgregro** [comment]
@lrinQVQ  顺便问一下             如何自己ping出正确的ip地址               我ping出很多错误的
https://www.proxysite.com/                 https://hidester.com/proxy/           https://www.vpnbook.com/webproxy
都帮我ping一下呗

**Comment by rockgregro** [comment]
多包涵            信不信由你          我才14岁

**Comment by lrinQVQ** [comment]
@rockgregro 嘛~差不多同龄人嘛 我也就比你大几岁

**Comment by rockgregro** [comment]
帮忙ping一下呗

**Comment by lrinQVQ** [comment]
嘛这个网站禁止ping 只能检测443 目前出来的3个IP延迟在500左右
HPING 54.175.154.154 (eth0 54.175.154.154): S set, 40 headers + 0 data bytes
len=46 ip=54.175.154.154 ttl=227 DF id=0 sport=443 flags=SA seq=0 win=26883 rtt=529.4 ms
len=46 ip=54.175.154.154 ttl=227 DF id=0 sport=443 flags=SA seq=1 win=26883 rtt=549.2 ms
len=46 ip=54.175.154.154 ttl=227 DF id=0 sport=443 flags=SA seq=2 win=26883 rtt=529.2 ms
@rockgregro

**Comment by rockgregro** [comment]
好吧 万分感谢 @lrinQVQ

**Comment by lrinQVQ** [comment]
www.proxysite.com
54.175.154.154
52.22.213.196
34.203.154.97
嘛虽然都可以用,不过肯定很卡

**Comment by lrinQVQ** [comment]
hidester.com还行
158.69.216.125
允许ping(ICMP)延迟300左右

**Comment by lrinQVQ** [comment]
www.vpnbook.com也还行
46.28.53.124
允许ping(ICMP)延迟300左右

**Comment by lrinQVQ** [comment]
https://github.com/googlehosts/hosts/wiki/%E5%AE%9E%E9%AA%8C%E5%AE%A4-Laboratory
嘛你可以看下无污染DNS 普通DNS污染的域名用我的DNS一般即可解决

**Comment by SerCom-KC** [comment]
假移动表示无法复现JP可用的情况……（可怜如我）

**Comment by SerCom-KC** [comment]
还有，楼主你老毛病犯了，请把正事写在正文部分，标题简短一点就好😂

**Comment by rockgregro** [comment]
好吧 老师总说我记性不好

**Comment by rockgregro** [comment]
说实在的 个人觉得应该用hosts解决一下web proxy来访问google

**Comment by SerCom-KC** [comment]
@rockgregro 还有正文部分

> 非常感谢你能参与本项目的维护，但是：
开新issue前请先阅读注意事项！
开新issue前请先阅读注意事项！
开新issue前请先阅读注意事项！
https://github.com/googlehosts/hosts/blob/master/.github/CONTRIBUTING.md
否则我们可能会不经警告地关闭你的issue，甚至禁言你的账号！
在阅读完后请删除此处的内容并填写你的issue的内容。

这一段是我们的模板，把模板删掉然后在这里阐述你的问题

至于你说的
> 说实在的 个人觉得应该用hosts解决一下web proxy来访问google

我们的原则是不在公共 hosts 文件里添加这类网站。毕竟不是所有人都愿意选择 web proxy，所以有需要的自己拿走就好

**Comment by rockgregro** [comment]
@SerCom-KC                 ok

**Comment by rockgregro** [comment]
帮忙ping一下hola.org     Thanks

**Comment by lrinQVQ** [comment]
@rockgregro dig @140.143.226.193 hola.org

**Comment by lrinQVQ** [comment]
fix now
e56456b

**Comment by minimania** [comment]
有什么办法可以解析出网站的IP呢?
现在只知道用网页查询网站的解析记录,但是好像并不全
尝试PING解析记录里的这些IP,PING通的就加进HOSTS
虽然修复了一些网站,但多数还是没办法,看了你上面说换端口PING,好像又学到了一些
