### ISSUE TITLE
报告duckduckgo访问敲慢。

### ISSUE THREAD

**Issue by wolfan** [googlehosts/hosts#186]
github也一样。
湖南·联通

**Comment by SerCom-KC** [comment]
湖南联通4G无法复现🌚

**Comment by lrinQVQ** [comment]
https://github.com/googlehosts/hosts/commit/5cc17658f79616e986feaa39d484e4b6f402d3bb

**Comment by lrinQVQ** [comment]
https://github.com/googlehosts/hosts/commit/7758cf6f6f745b0d4b8c3a55c6558049e6ef03e6
