### ISSUE TITLE
现在更新HOSTS是不是上不了GOOGLE，FACEBOOK,TWITTER？

### ISSUE THREAD

**Issue by lyonye** [googlehosts/hosts#188]
现在更新HOSTS是不是上不了GOOGLE，FACEBOOK,TWITTER？这几天都更新了，好像都没反应。

**Comment by SerCom-KC** [comment]
Duplicate of #64

**Comment by lrinQVQ** [comment]
fix Google now
https://github.com/googlehosts/hosts/commit/e56456b8027b3046770cf6d64cdf404cabe968ac
