### ISSUE TITLE
新上线的outline，能否改善访问？

### ISSUE THREAD

**Issue by dalton-chiou** [googlehosts/hosts#189]
联通宽带环境，getoutline.org勉强能访问，但很难正常浏览。能否通过hosts改善访问？
（另外，arukas.io正常访问，但app.arukas.io就连不上了。）

**Comment by SerCom-KC** [comment]
观测到 `app.arukas.io` 有 DNS 污染现象，感谢报告，回头会加

**Comment by dalton-chiou** [comment]
谢谢。发现outline不用加，因为只是不稳定，另外，它在github上有。

**Comment by SerCom-KC** [comment]
@dalton-chiou 别急着关啊hhh 你这 issue 不是提了两个问题嘛
`app.arukas.io` 已经加上去了 看看能不能用？

**Comment by dalton-chiou** [comment]
能用。谢谢。
