### ISSUE TITLE
连接谷歌时出现隐私设置错误

### ISSUE THREAD

**Issue by Billyin1** [googlehosts/hosts#19]
您的连接不是私密连接

攻击者可能会试图从 www.google.com.hk 窃取您的信息（例如：密码、通讯内容或信用卡信息）。了解详情
NET::ERR_CERT_COMMON_NAME_INVALID
www.google.com.hk 通常会使用加密技术来保护您的信息。Google Chrome 此次尝试连接到 www.google.com.hk 时，此网站发回了异常的错误凭据。这可能是因为有攻击者在试图冒充 www.google.com.hk，或 Wi-Fi 登录屏幕中断了此次连接。请放心，您的信息仍然是安全的，因为 Google Chrome 尚未进行任何数据交换便停止了连接。

您目前无法访问 www.google.com.hk，因为此网站使用了 HSTS。网络错误和攻击通常是暂时的，因此，此网页稍后可能会恢复正常。

**Comment by lrinQVQ** [comment]
咦

**Comment by lrinQVQ** [comment]
日常换证书= =马上更新下
