### ISSUE TITLE
谷歌不能用

### ISSUE THREAD

**Issue by uchihaty** [googlehosts/hosts#192]
非常感谢你能参与本项目的维护，但是：
开新issue前请先阅读注意事项！
开新issue前请先阅读注意事项！
开新issue前请先阅读注意事项！
https://github.com/googlehosts/hosts/blob/master/.github/CONTRIBUTING.md
否则我们可能会不经警告地关闭你的issue，甚至禁言你的账号！
在阅读完后请删除此处的内容并填写你的issue的内容。

**Comment by SerCom-KC** [comment]
Duplicate of #64

**Comment by Tobenone** [comment]
用choose 7 debug 模式下，一直重复  hosts file Not update。9 strat service ：提示 tools 已经停止工作 ，关闭程序。hosts 文件已经替换，但是google 还是无法打开。请帮助
