### ISSUE TITLE
report bug voa

### ISSUE THREAD

**Issue by rockgregro** [googlehosts/hosts#196]
voachinese.com               error
Your connection is not private
Attackers might be trying to steal your information from www.voachinese.com (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_COMMON_NAME_INVALID 
like this on chrome
thanks

**Comment by rockgregro** [comment]
look like it opened cdn

**Comment by rockgregro** [comment]
104.110.131.21
184.26.204.54
23.205.192.81

**Comment by rockgregro** [comment]
my ping with vpn

**Comment by SerCom-KC** [comment]
`23.50.31.94` works
