### ISSUE TITLE
我的google一直不能用。怎么破呀

### ISSUE THREAD

**Issue by DoIphin** [googlehosts/hosts#197]
从来就没能用过，最想用的就是谷歌学术了，一直不能用。什么youtub，什么Facebook想都不敢想。赶紧救救我吧。山西太原联通

**Comment by lrinQVQ** [comment]
请看一下wiki https://github.com/googlehosts/hosts/wiki
以及https://github.com/googlehosts/hosts/wiki/实验室-Laboratory
Duplicate of #64 and #69

**Comment by lrinQVQ** [comment]
fix now
https://github.com/googlehosts/hosts/commit/e56456b8027b3046770cf6d64cdf404cabe968ac
