### ISSUE TITLE
soundcloud not work

### ISSUE THREAD

**Issue by rockgregro** [googlehosts/hosts#199]
soundcloud could not play audio

**Comment by lrinQVQ** [comment]
web or app?

**Comment by rockgregro** [comment]
web

**Comment by SerCom-KC** [comment]
Affected domain is probably `cf-hls-media.sndcdn.com` which is not present in the hosts file.
`52.84.48.209` seems working on my side.
However I'm experiencing a country block (`The Amazon CloudFront distribution is configured to block access from your country.`) when trying to access soundcloud.com - @lrinQVQ is there a way to fix this?

**Comment by lrinQVQ** [comment]
try to fix
