### ISSUE TITLE
改改文件结构呗……

### ISSUE THREAD

**Issue by wolfan** [googlehosts/hosts#2]

**Comment by lrinQVQ** [comment]
欸0.0 怎么改2333

**Comment by wolfan** [comment]
至少把文件丢上一层
`mv *.* ..`

**Comment by DDoSolitary** [comment]
@wolfan 因为是多文件生成，放到根目录会导致自动生成机制无法区别自动生成的文件和我们手动添加的文件（README，LICENSE等）。如果你觉得现在放在一个文件夹下有什么不好的地方，麻烦指出，我想办法来改

**Comment by wolfan** [comment]
@DDoSolitary 也不是不好，就是觉得怪怪的。

另外一个问题，
下载zip包里的hosts文件，和git下来居然不一样，试试了好几次还是一样的问题。
是不是我rp值掉的太多原故。。。。。

and 向fb之类的还是应该加上去吧。。。

**Comment by DDoSolitary** [comment]
> 下载zip包里的hosts文件，和git下来居然不一样，试试了好几次还是一样的问题。
是不是我rp值掉的太多原故。。。。。

你分别是怎么下的？

> and 向fb之类的还是应该加上去吧。。。

这个项目还在做，之后会一点一点加的。。

**Comment by wolfan** [comment]
之前git总错误（hosts目录重名）半天没弄明白过来，就直接下zip包了，可是解开来丢进etc发现没用就打了看看，结果居然是那个（yxml？配置文件？）反正不是正常的hosts文件，然后找找，发现没有hosts....
那就方了，之后又重新下了几次是这个，然后就去研究git的问题了。。。

**Comment by DDoSolitary** [comment]
git错误是因为你之前文件夹里有hosts文件，git想要新建hosts文件夹，就重名了，重新clone一下就会好了
你下的zip包是hosts-source分支的，里面都是些自动生成用的文件，当然没用了。。

**Comment by DDoSolitary** [comment]
没别的问题了吧。。先close了。。
