### ISSUE TITLE
Tumblr APP内视频和搜索推荐无法加载

### ISSUE THREAD

**Issue by userfromchina** [googlehosts/hosts#201]
近几天Tumblr APP内视频预览图加载不出来，全都是黑色的，点击视频的播放按钮，等待一会儿后变成灰色的叉。APP的搜索页面本应有推荐的博客，但现在只是一直在转圈。图片显示正常，APP内没有报错信息。
如果让*.tumblr.com走代理，则APP工作正常。而且播放过的视频，取消代理后依然可以播放，加载速度还很快。看起来是APP获取视频预览图和地址出问题了，一旦有了地址，下载还是很快的。
手机浏览器访问Tumblr，视频预览图显示正常。联通。

**Comment by lrinQVQ** [comment]
get

**Comment by SerCom-KC** [comment]
确定不是 `博客ID.tumblr.com` 之类的锅？此类域名必须自行添加。

**Comment by userfromchina** [comment]
@SerCom_KC
之前就是因为浏览器访问需要添加ID域名，嫌麻烦才改用APP的，APP用了很久都没问题，至少上周之前还是正常的。
不过也不排除APP端发生了变化，我没有测试，晚上试一下再回复。

**Comment by userfromchina** [comment]
初步测试，APP首页的视频预览图问题确实与ID域名有关，添加后可以加载，视频可以播放。
但APP搜索推荐不知道怎么解决，添加自己的ID域名无效。

**Comment by SerCom-KC** [comment]
看来要抓包了……（懒癌发作）

**Comment by userfromchina** [comment]
有什么好用的安卓抓包工具推荐吗？
开启Packet Capture之后，APP会提示网络错误，应该是SSL校验出问题了吧。

**Comment by SerCom-KC** [comment]
@userfromchina 当然，你要安装它的根证书

**Comment by userfromchina** [comment]
按提示安装了的，莫非我操作有误……

**Comment by userfromchina** [comment]
昨天又试了一下，APP的搜索推荐已经恢复正常了，看来不是hosts的问题，估计是Tumblr的一些调整造成的吧。就像是以前视频不需要添加ID域名，现在变成需要添加一样……
这个issue可以关闭了，感谢各位的回复(◍•ᴗ•◍)

**Comment by SerCom-KC** [comment]
可以自行关闭的，这样如果再有问题也可以再开～
