### ISSUE TITLE
Please add pao-pao.net into the hosts file

### ISSUE THREAD

**Issue by JohnSmithdesu** [googlehosts/hosts#202]
For now, _pao-pao.net_ has been blocked in the Mainland China through DNS spoofing. Please add _pao-pao.net_ into the hosts file, the IP address ought to be `151.101.0.230`.

**Comment by mraandtux** [comment]
不用加了，直接拿去：
> 23.235.33.230 pao-pao.net

**Comment by beyondgfw** [comment]
感谢分享，有需要的自取即可

**Comment by GoogleHostsSupport** [comment]
此 issue 合并至 #299 处理～
