### ISSUE TITLE
想请教一个问题，最近被弄得很头疼。

### ISSUE THREAD

**Issue by 123ysys** [googlehosts/hosts#203]
就是关于网页版的谷歌地图（.cn后缀）可以用而谷歌地图App不能直接使用的原因，谁能给我解释一下？
谢谢。

**Comment by beyondgfw** [comment]
@123ysys 0.0可以直接用啊 Google maps 9.76.0 (#97600240)使用www.google.cn作为服务器的啊

**Comment by 123ysys** [comment]
@beyondgfw 我的是9.74.1（#974101040），看来得升级了。

**Comment by beyondgfw** [comment]
@123ysys 0.0差不多是9.75/76就开始用cn直接使用了

**Comment by 123ysys** [comment]
@beyondgfw 感谢。

**Comment by beyondgfw** [comment]
@123ysys 2333小意思啦
可以用了记得Close一下

**Comment by 123ysys** [comment]
ok

**Comment by 123ysys** [comment]
唔，9.75.1还是无法使用。

**Comment by beyondgfw** [comment]
@123ysys 2333看来必须76

**Comment by 123ysys** [comment]
@beyondgfw 我看看有没有9.76的资源。

**Comment by lrinQVQ** [comment]
@123ysys 昂我给你好了稍等一下

**Comment by lrinQVQ** [comment]
@123ysys https://www.apkmirror.com/apk/google-inc/maps/maps-9-76-1-release/google-maps-navigation-transit-9-76-1-6-android-apk-download/ apkmirror就有啧

**Comment by 123ysys** [comment]
感谢QVQ。

**Comment by beyondgfw** [comment]
@123ysys 小意思啦～

**Comment by 123ysys** [comment]
@beyondgfw @IrinQVQ 抱歉，我在QVQ提供的Apkmirror上下载的9.76.1（#976101040）还是无法使用，譬如说我搜索一个地点，它会显示“无法搜索”。

**Comment by beyondgfw** [comment]
@123ysys emmm看来我还是得处理下

**Comment by 123ysys** [comment]
@beyondgfw 您能确定76版本的谷歌地图app使用的是cn的服务器么？

**Comment by beyondgfw** [comment]
@beyondgfw

**Comment by lrinQVQ** [comment]
![img_20180425_142758_856](https://user-images.githubusercontent.com/12861134/39229326-de5bbcc4-4894-11e8-852f-400796e2f329.jpg)
@123ysys

**Comment by 123ysys** [comment]
@beyondgfw 好迷
@lrinQVQ 大佬能否给我解释解释呢？

**Comment by beyondgfw** [comment]
@123ysys 这是我打开Google maps后的抓包。。。
地图的加载相关都用了cn域名 其他的用了1e100服务器

**Comment by 123ysys** [comment]
@beyondgfw 那就真的迷了，会不会是1e100服务器的原因？

**Comment by beyondgfw** [comment]
@123ysys emmm有这个可能

**Comment by beyondgfw** [comment]
@123ysys 能抓包看下嘛 0.0 这可是北京BGP

**Comment by 123ysys** [comment]
可以，不过我是小白，需要您教我怎么抓包。

**Comment by beyondgfw** [comment]
@123ysys 0.0你的爪机有root嘛
有的话装一个Proxymon抓包看看

**Comment by 123ysys** [comment]
@beyondgfw 我试一试，不过我是小白，可能要久一点。

**Comment by beyondgfw** [comment]
@123ysys 不着急2333

**Comment by beyondgfw** [comment]
@beyondgfw test

**Comment by 123ysys** [comment]
![screenshot_2018-04-25-18-43-32-829_com evbadroid](https://user-images.githubusercontent.com/27964272/39241258-d8ccca90-48b8-11e8-8480-789f152f4b77.png)
不知道是不是这样抓的。

**Comment by beyondgfw** [comment]
@123ysys 没毛病 然后你看下Store

**Comment by 123ysys** [comment]
@beyondgfw store一片空白。

**Comment by beyondgfw** [comment]
@123ysys 0.0你有打开Google maps嘛

**Comment by 123ysys** [comment]
打开的呀

**Comment by beyondgfw** [comment]
@123ysys 0.0那看看Logs里面有东西吗

**Comment by 123ysys** [comment]
有。
![screenshot_2018-04-25-18-50-16-758_com evbadroid](https://user-images.githubusercontent.com/27964272/39241454-894951c2-48b9-11e8-8644-4c912f8fd1c2.png)

**Comment by beyondgfw** [comment]
@123ysys XD好像失败了 你在Host里选择localhost 试试

**Comment by 123ysys** [comment]
@beyondgfw 什么失败了？抓包么？localhost 点击选择无反应。

**Comment by beyondgfw** [comment]
@123ysys 2333 对抓包失败了 点击之后你在打开Google maps

**Comment by 123ysys** [comment]
store有反应了。
![screenshot_2018-04-25-18-53-46-176_com evbadroid](https://user-images.githubusercontent.com/27964272/39241583-022a6c52-48ba-11e8-9579-b6c527a58153.png)

**Comment by 123ysys** [comment]
@beyondgfw 对了还有个问题，那就是我的测试的手机十分遗憾不能使用Google服务，因此地图一直提示说需更新Google服务，而可以用谷歌服务的亲儿子又没有root过，这让我很为难233。

**Comment by beyondgfw** [comment]
@123ysys 欸多2333这就很麻烦 我再去问问其他人好了

**Comment by 123ysys** [comment]
@beyondgfw OK，感谢。静候消息。

**Comment by lrinQVQ** [comment]
@123ysys 试了很多设备XD 都无法复现.jpeg都走了google.cn才对欸

**Comment by 123ysys** [comment]
@lrinQVQ 所以为何我的app就不行呢？甚至连加载都加载不出来。

**Comment by beyondgfw** [comment]
@123ysys 2333我也很迷茫 难道是dns问题

**Comment by SerCom-KC** [comment]
@123ysys 如果你没有谷歌服务包的话我倒是很想知道你的apk来源

**Comment by 123ysys** [comment]
@SerCom-KC 谷歌框架嘛是有的，只是有谷歌框架的手机没有经过root

**Comment by SerCom-KC** [comment]
@123ysys 没有root的那台手机可以用谷歌地图嘛

**Comment by 123ysys** [comment]
@SerCom-KC 可以打开，但无法加载地图，无法搜索地点，无法导航。必须使用魔法上网才能实现功能。

**Comment by SerCom-KC** [comment]
@123ysys 联通4G app 9.75.1 配合hosts表示加载地图没有问题
没有root=没有使用hosts对吧 试试用https://github.com/iTXTech/Daedalus

**Comment by 123ysys** [comment]
@SerCom-KC 可以裸连吗？
@beyondgfw 如果是dns的原因的话能给我一组么？

**Comment by SerCom-KC** [comment]
@123ysys 我怀疑是你那个root的手机没有完整谷歌服务包的原因，所以我还是想在你的亲儿子上再做一下测试

**Comment by lrinQVQ** [comment]
@123ysys https://github.com/googlehosts/hosts/wiki/%E5%AE%9E%E9%AA%8C%E5%AE%A4-Laboratory#%E9%98%B2%E6%B1%A1%E6%9F%93dns--anti-pollution-dns

**Comment by 123ysys** [comment]
@SerCom-KC 没错，我敢肯定就是没有谷歌包的原因。当然，我的亲儿子为什么无法加载与使用我也不知道。

**Comment by SerCom-KC** [comment]
@123ysys 但你亲儿子没有使用hosts吧 所以用一下试试

**Comment by 123ysys** [comment]
启用了Daedalus仍然不可行。

**Comment by SerCom-KC** [comment]
@123ysys 用的本项目hosts？

**Comment by 123ysys** [comment]
没错。步骤是规则 填写所有选项 点击钩 点击启用对吧？

**Comment by 123ysys** [comment]
@SerCom-KC 我尝试换一下dns吧。

**Comment by lrinQVQ** [comment]
XD好像真的我用MIUI都没法复现啧

**Comment by 123ysys** [comment]
我想问一下你们裸连可以使用诸如搜索或者导航的功能吗？

**Comment by hallochina** [comment]
不折腾了，术业有专攻，走付费v.pn吧，https://vpnchina.zdhweb.com

**Comment by 123ysys** [comment]
请问复现得怎么样了？

**Comment by lrinQVQ** [comment]
搜索和导航还真的要修一下

**Comment by lrinQVQ** [comment]
XD对对对 是因为android.clients.google.com 所以凉凉

**Comment by beyondgfw** [comment]
https://github.com/googlehosts/hosts/issues/203#issuecomment-403181671
跟 #64 合并处理。
