### ISSUE TITLE
about new hosts

### ISSUE THREAD

**Issue by zzaqvq** [googlehosts/hosts#205]
现在对gmail的修复是稳定的吗  google youtube有希望吗 @大佬

**Comment by beyondgfw** [comment]
@zzaqvq gmail目前稳定2天 google应该会在近期修复完毕 youtube待定

**Comment by zzaqvq** [comment]
facebook Twitter 是挂了 对吗

**Comment by beyondgfw** [comment]
@zzaqvq 不是 如果他们开始部署TLS1.3照样修复

**Comment by zzaqvq** [comment]
you mean Google已经部署TLS1.3了?

**Comment by SerCom-KC** [comment]
没有其它问题请记得 close
