### ISSUE TITLE
防污染DNS

### ISSUE THREAD

**Issue by zzaqvq** [googlehosts/hosts#207]
@lrinQVQ 你搭建的防污染DNS成本是多少钱，我考虑搭一个

**Comment by lrinQVQ** [comment]
XD准备好1w+再搭吧

**Comment by zzaqvq** [comment]
正在准备

**Comment by lrinQVQ** [comment]
2333加油
大概做好3Tbps攻击的心理准备 //经历过一次了

**Comment by zzaqvq** [comment]
如果没有被ddos大概多少钱？

**Comment by SerCom-KC** [comment]
我插个嘴，DNS 代理跟防污染 DNS 不是一个概念。
如果没有问题就当我没说。

**Comment by lrinQVQ** [comment]
@zzaqvq 1w+起步

**Comment by zzaqvq** [comment]
okay

**Comment by zzaqvq** [comment]
另外我觉得你建的shadowsocks就是浪费，想fq的自己就fq了

**Comment by lrinQVQ** [comment]
2333 @zzaqvq 其实每台服务器日流量1TB以上 我不觉得浪费

**Comment by beyondgfw** [comment]
@zzaqvq 所以说是实验室啊……研究的可不只是如何让你们能翻墙而已……

**Comment by zzaqvq** [comment]
我觉得你的服务器被滥用了   你又不是google xx net

**Comment by lrinQVQ** [comment]
@zzaqvq 嘛没事 mtr ip有署名 主要是我的服务器都是新特性的测试

**Comment by zzaqvq** [comment]
研究的可不只是如何让你们能翻墙而已……？？？    收集数据？？？

**Comment by lrinQVQ** [comment]
2333 新特性的测试 详细参考https://github.com/lrinQVQ/script @zzaqvq

**Comment by beyondgfw** [comment]
@zzaqvq 不收集个人数据，这点wiki上已经写明了。
但是会研究路由走向之类的东西。

**Comment by lrinQVQ** [comment]
@beyondgfw 嘛 本项目shadowsocks的目的之一
1.研究RTT和路由
2.部署最新的特性
3.测试我自己的脚本

**Comment by zzaqvq** [comment]
想fq的自己就fq了  my opinion  想fq的已经vpn 10dollars mo了

**Comment by lrinQVQ** [comment]
2333 年底你就能知道意义何在了

**Comment by zzaqvq** [comment]
年底？ 今年吗

**Comment by beyondgfw** [comment]
@zzaqvq 确实如此，机场那么多，如果我们开实验室只是为了提供机场的话，完全没必要。

**Comment by lrinQVQ** [comment]
yes 今年

**Comment by zzaqvq** [comment]
要干什么？

**Comment by lrinQVQ** [comment]
@zzaqvq 嘛我们可不是拿什么SSR做后端兼容SS
我可以直接公开说个人永久敌对SSR及其衍生

**Comment by lrinQVQ** [comment]
@zzaqvq https://github.com/lrinQVQ/script 去看看就知道了

**Comment by zzaqvq** [comment]
快速部署脚本？

**Comment by lrinQVQ** [comment]
就这么简单你就想多了= =

**Comment by beyondgfw** [comment]
@zzaqvq @lrinQVQ 已经[在上面说了](https://github.com/googlehosts/hosts/issues/207#issuecomment-385309436)。
我们开设实验室的目的很简单，就是研究GFW的运作。

**Comment by beyondgfw** [comment]
建議你在群內討論 而不是在這裡 spam flood 影響其他有關注這個項目的訂閱者

**Comment by lrinQVQ** [comment]
@zzaqvq https://github.com/lrinQVQ/script/blob/master/dependencies/ss_config 看完这个2333

**Comment by zzaqvq** [comment]
我才初二？？？看不太懂

**Comment by zzaqvq** [comment]
研究GFW的运作 有何意义  墙不还是存在吗？？？

**Comment by lrinQVQ** [comment]
emmm请问你都不知道GFW的运作你如何破解它

**Comment by beyondgfw** [comment]
我再說一次 這種比較長篇的討論請到群內討論 謝謝。 我們的 [telegram 群](https://t.me/googlehosts)就標識在主頁上

**Comment by lrinQVQ** [comment]
如果GFW屏蔽所有的SOCKS5协议 那么目前SS SSR V2 brook 代理软件都会死 就这么简单

**Comment by SerCom-KC** [comment]
https://github.com/googlehosts/hosts/issues/207#issuecomment-385309801
https://github.com/googlehosts/hosts/issues/207#issuecomment-385310056
