### ISSUE TITLE
关于魔改quic 和 YouTube

### ISSUE THREAD

**Issue by zzaqvq** [googlehosts/hosts#208]
什么是魔改quic 求大佬解释 既然Google YouTube一家亲 可否运用在YouTube上  Facebook twitter是否有类似解封计划？

**Comment by beyondgfw** [comment]
@zzaqvq YouTube是迟早会有的。
至于Facebook和Twitter得看他们心情，目前只知道Facebook确认上TLS 1.3。

**Comment by zzaqvq** [comment]
quic是一种协议吗？

**Comment by zzaqvq** [comment]
另外Google现在并不是所有项目可用

**Comment by beyondgfw** [comment]
@zzaqvq 没错，参见 https://zh.wikipedia.org/zh-cn/快速UDP网络连接 。
魔改指的是 QUIC over TCP，因为 QUIC 本身是基于 UDP 的协议。

**Comment by beyondgfw** [comment]
@zzaqvq Google 所有服务的修复需要时间。
还有，跟上次一样，请不要发过多提问，免得影响其他订阅者，谢谢。issue 区并不是论坛，我们不欢迎版聊。

**Comment by zzaqvq** [comment]
sorry so close
