### ISSUE TITLE
检举laod.cn

### ISSUE THREAD

**Issue by zzaqvq** [googlehosts/hosts#209]
Laod.cn对此项目并无贡献却使用本项目发布文章而且GitHub维护者还写错了建议与其调节解决

**Comment by beyondgfw** [comment]
@zzaqvq 协调失败 @laodcn 好自为之

**Comment by zzaqvq** [comment]
我个人觉得laodcn起码应该更改GitHub维护者也是对原作者的一种尊重没准他忘了希望其尽快处理@laodcn 勤快看到

**Comment by beyondgfw** [comment]
问题其实并不在于“更改GitHub维护者”
@zzaqvq 这件事已经充分讨论过了，稍微搜索一下可以获得更多细节
感谢您在这方面的思考

**Comment by laodcn** [comment]
已更改

**Comment by lrinQVQ** [comment]
@laodcn https://github.com/googlehosts/hosts/blob/master/LICENSE#L20 广告==

**Comment by SerCom-KC** [comment]
@laodcn 
这次是 https://laod.cn/black-technology/google-chrome-quic.html 和 https://mp.weixin.qq.com/s/6a3Tgt1o5Ov3E0jBZP34Iw 。
我就借这个机会声明一下我们的署名要求了：
1. 除非另有说明，否则请一律署名 `Google Hosts 组织`，不要写我、其他组织成员或者任何贡献者的名字，并且就算是墙内平台也要署名；
2. 如果墙内平台因为某些原因无法放置来源链接（比如微信的阅读原文请设置为我们的 wiki 链接，这个水表我们不怕），请预先取得我们的许可，否则视为非法转载。
