### ISSUE TITLE
ips.pepitastore.com

### ISSUE THREAD

**Issue by imba-tjd** [googlehosts/hosts#211]
ips.pepitastore.com为https://store.eu.square-enix.com/eu/ 的css网址
不过不同地区的商店用的好像不一样，英文主站的css就没事

**Comment by lrinQVQ** [comment]
XD现在确实全部污染了

**Comment by lrinQVQ** [comment]
但是emmm好像
https://ips.pepitastore.com/storefront/img/flags/ES.png 普通情况又能打开

**Comment by imba-tjd** [comment]
什么叫做普通情况…你给的图片链接我还是打不开的。不过这个商店是se送迷你忍者的时候看到的，访问的人应该会很少。可以考虑不加。

**Comment by lrinQVQ** [comment]
https://ips.pepitastore.com/storefront/themes/squareenix-store-v2/fonts/ProximaNova-Semibold.woff
又加载不了emmmm 我还是加上吧

**Comment by lrinQVQ** [comment]
@imba-tjd 嘛就是使用国内DNS作为DNS解析的时候

**Comment by lrinQVQ** [comment]
加了吧XD
