### ISSUE TITLE
img.buzzfeed.com；archive.org对应IP更新

### ISSUE THREAD

**Issue by techyanWP** [googlehosts/hosts#212]
img.buzzfeed.com 这个域名看起来被污染了，但是主站 www.buzzfeed.com 没有。

archive.org 系列的IP因为该网站自身的调整，需要变动。用现有的IP能够访问，但在有些域名下会报错（提示系统正在维护，实际上是找错IP了）。这一系列最好全部更新。

**Comment by beyondgfw** [comment]
@techyanWP 151.101.1.181

**Comment by techyanWP** [comment]
IP没封。用151.101.73.181这个。

**Comment by lrinQVQ** [comment]
但是一直没有找到办法验证img.buzzfeed.com的可用性 https://img.buzzfeed.com/buzzfeed-static/static/2017-03/3/13 也直接404了
