### ISSUE TITLE
pinterest 部分ip无效了

### ISSUE THREAD

**Issue by lixuzong** [googlehosts/hosts#213]
非常感谢你能参与本项目的维护，但是：
开新issue前请先阅读注意事项！
开新issue前请先阅读注意事项！
开新issue前请先阅读注意事项！
https://github.com/googlehosts/hosts/blob/master/.github/CONTRIBUTING.md
否则我们可能会不经警告地关闭你的issue，甚至禁言你的账号！
在阅读完后请删除此处的内容并填写你的issue的内容。

**Comment by CHVII-2** [comment]
请求修复 pinterest.com 图片无法加载的问题。谢谢。

###运营商
联通

###加载失败资源地址
https://www.pinterest.com/resource/StatsLogResource/create/

**Comment by SerCom-KC** [comment]
@CHVII-2 如果只是图片的话你给错资源地址了，应该是 https://i.pinimg.com 开头的。
总之临时修复了，测试一下吧。

**Comment by CHVII-2** [comment]
@SerCom-KC 访问可以加载图出片了。谢谢你。

**Comment by CHVII-2** [comment]
pinterest 又出现了图片无法加载的问题。请求再次修复，谢谢。

###图片加载失败资源地址
https://i.pinimg.com/236x/3e/55/51/3e5551deddbd399ca29e5353a0137296.jpg
https://i.pinimg.com/236x/66/f2/81/66f28147bd6b431eee57511607187484.jpg
