### ISSUE TITLE
请求更新google scholar，谢谢！

### ISSUE THREAD

**Issue by zhanglinbo** [googlehosts/hosts#214]
请求更新google scholar，谢谢！

**Comment by Feaskye** [comment]
need update google host !!

**Comment by beyondgfw** [comment]
@Feaskye Get

**Comment by DeemoTlz** [comment]
请求更新一下google

**Comment by beyondgfw** [comment]
@DeemoTlz 见 #64

**Comment by lrinQVQ** [comment]
//XD实在太忙抱歉只能托更了

**Comment by hgy371** [comment]
请问这波host失效是google的原因还是gfw的原因？

**Comment by lrinQVQ** [comment]
GFW @hgy371

**Comment by lrinQVQ** [comment]
如果急用
https://github.com/googlehosts/hosts/wiki/%E5%AE%9E%E9%AA%8C%E5%AE%A4-Laboratory

**Comment by gfw-breaker** [comment]
给大家推荐一个通用的Web代理   [https://node1.free-ss.win/](https://node1.free-ss.win/)

**Comment by PantherJohn** [comment]
Anyway, I hope scholar.google.cn will be available in the upcoming future since Google is heading for China. Congrats! Internet is again ours, though compromise is made at the same time.

**Comment by beyondgfw** [comment]
跟 #64 合并处理。
