### ISSUE TITLE
关于quic的发现

### ISSUE THREAD

**Issue by zzaqvq** [googlehosts/hosts#216]
中华人民共和国 天津    直连www.google.cn chrome https 默认quic hosts已经清空
vpn 连接 google.com youtube.com全部tls1.2  有何玄学？？？

**Comment by beyondgfw** [comment]
@zzaqvq 目前的基于SOCKS5的代理软件通常只代理TCP协议 QUIC不属于可代理的协议

**Comment by SerCom-KC** [comment]
🤔如果你对 VPN 的定义没有问题的话，同时也可以说明你用的 VPN 对 UDP 转发的支持不怎么好了。
请注意 shadowsocks 系严格来说属于代理而不是 VPN 哦。

**Comment by zzaqvq** [comment]
我用的不是shadowsocks 真的是vpn
