### ISSUE TITLE
更换国内镜像地址

### ISSUE THREAD

**Issue by SerCom-KC** [googlehosts/hosts#218]
https://coding.net/help/doc/project/public-project.html

**Comment by DDoSolitary** [comment]
有毒。。

**Comment by Ir1d** [comment]
![image](https://user-images.githubusercontent.com/10709657/41237160-757faee4-6dc5-11e8-9ddb-3fe35aabbf9b.png)
我觉得海星？

**Comment by DDoSolitary** [comment]
然而这相当于完全把开源丢掉了。。

**Comment by DDoSolitary** [comment]
外部协作者很难参与

**Comment by wolfan** [comment]
coding的公开库就要停止服务了，依我看就没有必要弄国内镜像了。

**Comment by SerCom-KC** [comment]
@DDoSolitary 不过就本项目而言本来就是个镜像而已，不太可能接受来自 coding 的 pull request 吧。

Close reason: https://github.com/googlehosts/hosts/issues/218#issuecomment-396260023
