### ISSUE TITLE
Google搜索无法使用

### ISSUE THREAD

**Issue by ddaodan** [googlehosts/hosts#219]
谷歌的其他服务应该都是没有问题的，搜索打不开，之前找到了个可以用的IP，可惜找不到了。另外，能否提供niconico的IP？

**Comment by 123ysys** [comment]
提供niconico的IP也没用，因为niconico还没有启用https。另，谷歌搜索不能用似乎和TLS1.3未推广有关。

**Comment by ddaodan** [comment]
自己用了一会，发现谷歌的绝大多数服务都是不能用的，包括YouTube

**Comment by ddaodan** [comment]
好吧，我是手机版的。没看到
