### ISSUE TITLE
google drive无法使用。

### ISSUE THREAD

**Issue by fuchanghao** [googlehosts/hosts#22]
无论是使用网页还是JDownloader等工具都有这个问题。

而且JDownloader中hosts对应的Google Service:Accounts下的hosts会导致google账户无法登陆。

**Comment by lrinQVQ** [comment]
扑哧0.0 登录那个目测纯属IP失效 把Google Service的IP移动下即可

**Comment by lrinQVQ** [comment]
google drive 0.0你下载服务器是什么

**Comment by fuchanghao** [comment]
就是那一堆doc-xx-xx-docs.googleusercontent.com
然而这个hosts并没有这些。

**Comment by lrinQVQ** [comment]
soga 晚点加
