### ISSUE TITLE
请更新并添加维基百科及相关网址的IP。

### ISSUE THREAD

**Issue by dzx-dzx** [googlehosts/hosts#221]
198.35.26.96今日已不可用。请更换IP。
另外部分原先可访问的相关网址（如英文维基百科/元维基）已不可用，请添加。

**Comment by SerCom-KC** [comment]
貌似英文维基之类的不能算 DNS 污染呢……
只是解析到了那个不可用的 IP 上……

**Comment by SerCom-KC** [comment]
似乎恢复了（https://zh.wikipedia.org/w/index.php?title=Help:如何访问维基百科&oldid=50061286），先 close。
还有维基相关访问困难的请直接评论。
