### ISSUE TITLE
US Full Name error

### ISSUE THREAD

**Issue by imba-tjd** [googlehosts/hosts#222]
![qq 20180621222818](https://user-images.githubusercontent.com/24759802/41725525-98e7ff96-75a2-11e8-8a47-9ad31dc6f96f.png)
![qq 20180621222929](https://user-images.githubusercontent.com/24759802/41725556-a768058e-75a2-11e8-9774-6b1f64c57b2c.png)

**Comment by SerCom-KC** [comment]
😂 手滑日常，感谢指正。
