### ISSUE TITLE
求大佬一份hosts保证hola vpn在中国大陆的正常使用，自己做过都不能用，用自己的无污染dns又访问不了Google YouTube等，求解

### ISSUE THREAD

**Issue by zzagreg** [googlehosts/hosts#226]
hola vpn详见hola.org

**Comment by Ir1d** [comment]
麻烦断一下句

**Comment by SerCom-KC** [comment]
- 虽然我不知道 hola 的情况，但这种 VPN 类的网站估计也就那么点 IP，很可能早就封光了。
- 解决 DNS 污染问题不代表干翻了 GFW，因为你还是会被解析到一个已经被墙的 IP。
- 本项目不收录 VPN / 代理系网站，所以恕我直接 close 了，当然有人要帮楼主的忙的话随意回复。

**Comment by SerCom-KC** [comment]
Possible duplicate of #187 & #194.
还有既然是 hosts 请不要在没有持续更新的前提下谈什么质量保证……
