### ISSUE TITLE
steam商店主页面无法访问

### ISSUE THREAD

**Issue by lokayimasi** [googlehosts/hosts#228]
23.50.18.229	store.steampowered.com这一条，加了这条就打不开steam商店，删了就能开

**Comment by lokayimasi** [comment]
坐标河北电信

**Comment by lrinQVQ** [comment]
0.0

**Comment by lrinQVQ** [comment]
大概昂 今晚修复

**Comment by beyondgfw** [comment]
@zyf2008Neptune 我们也很难过

**Comment by lrinQVQ** [comment]
23.37.147.226 一会会push的

**Comment by lrinQVQ** [comment]
https://github.com/googlehosts/hosts/commit/03a87308262e2ae29c619e36ded44ec840f7888e
