### ISSUE TITLE
报(ง ˙ω˙)ว 大佬，代理服务器全躺了。

### ISSUE THREAD

**Issue by wolfan** [googlehosts/hosts#229]
大佬，您看如何是好，都用上tg看小姐姐了，小的活不了了吖_(•̀ω•́ 」∠)_

**Comment by SerCom-KC** [comment]
中国移动表示仍然在愉快地~~下本~~用着……

**Comment by lrinQVQ** [comment]
0.0换了新域名的哦

**Comment by wolfan** [comment]
@lrinQVQ 不是tgsocks5-x.googlehosts.org 么我把所有的都加上去了，没一个成功的。

难道是我大扶兰国的联通和墙进行了Py交易？

**Comment by beyondgfw** [comment]
@wolfan 23333修改了啊 tg-x.googlehosts.org

**Comment by beyondgfw** [comment]
@wolfan 你看下wiki页面就知道了

**Comment by wolfan** [comment]
@beyondgfw wiki上怎么不改。。。嘤嘤嘤

**Comment by lrinQVQ** [comment]
@wolfan 2333抱歉忘了系列

**Comment by lrinQVQ** [comment]
修改了XD
