### ISSUE TITLE
英国皇家邮政真迷

### ISSUE THREAD

**Issue by 123ysys** [googlehosts/hosts#23]
求问，英国皇家邮政官网怎么会上不去？别的国家的邮政系统的官网都可以。
一个邮政网站，应该不会有屏蔽的理由啊？
ping的结果是“请求超时”。

**Comment by lrinQVQ** [comment]
确实被墙==

**Comment by 123ysys** [comment]
@lrinQVQ  厉害了。我以为只是屏蔽了中国的IP。

**Comment by lrinQVQ** [comment]
23333 我去弄下

**Comment by 123ysys** [comment]
3Q.

**Comment by lrinQVQ** [comment]
其实完全是CDN的锅==

**Comment by 123ysys** [comment]
这是什么意思？意思是和DNS污染或GFW无关？

**Comment by lychichem** [comment]
> 这是什么意思？意思是和DNS污染或GFW无关？
意思大概和当年大量Mozilla系网站被屏蔽一样，因为有人在CDN提供商的服务器上托管了不和谐内容，然而按照CDN本身的定义，是没法把内容定位到具体的专一的域名/IP的，于是索性整个含这个关键字的域名都禁掉，Mozilla当年就是因为edgecast CDN的原因躺枪，最后是中国分部（谋智）出面和总部一起把中国大陆地区的CDN重新部署过才恢复的

**Comment by lrinQVQ** [comment]
+1 CDN:akadns.net

**Comment by 123ysys** [comment]
@lychichem 哦哦，是这样。谢谢。
