### ISSUE TITLE
Discord在国内被Dns污染

### ISSUE THREAD

**Issue by yinfb** [googlehosts/hosts#230]
### 是什么网站 / app 出现了问题？
Discord

- [X] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [X] 完全无法使用：
Dns污染,
timeout。
- [ ] 部分无法使用：

### 您的运营商是？
山东/上海 电信 联通

### 加载失败的资源地址
discordapp.com
discord.gg
discord.media
media.discordapp.net
status.discordapp.com
images-ext-1.discordapp.net
images-ext-2.discordapp.net
cdn.discordapp.com

### 失效域名的 DNS 解析结果
208.101.60.87

### 封锁方式
- [X] DNS 污染
- [ ] IP 封锁
- [ ] TCP Reset
- [x] 涉及到第三方服务：
 Cloudflare

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方
104.16.58.5 discordapp.com
104.16.59.37 discord.gg
104.16.174.189 discord.media
104.16.251.144 media.discordapp.net
104.16.10.231 status.discordapp.com
104.16.250.144 images-ext-1.discordapp.net
104.16.251.144 images-ext-2.discordapp.net
104.16.10.231 cdn.discordapp.com
# 请将 hosts 内容粘贴在此行上方
```

**Comment by lrinQVQ** [comment]
thanks~

**Comment by lrinQVQ** [comment]
顺便你是第一个认真填完了这个模板的人!非常感谢!

**Comment by lrinQVQ** [comment]
0.0

**Comment by 123ysys** [comment]
也有可能只是单纯的墙抽风了。不过个人觉得是会话复用的几率更大。

**Comment by liuweihang-2019** [comment]
有一个问题，头像不能访问。
