### ISSUE TITLE
请问能添加cdn.steamcommunity.com的hosts吗

### ISSUE THREAD

**Issue by lokayimasi** [googlehosts/hosts#231]
最近在https://www.steamtradematcher.com     （一个steam卡牌背景表情交换网站）交换卡牌时发现卡牌图片不显示，f12看了一下控制台，是  cdn.steamcommunity.com  相关网址打不开，显示“无法访问此网站 
 cdn.steamcommunity.com   的响应时间过长，可以添加相关hosts吗，坐标江苏常州移动

**Comment by lrinQVQ** [comment]
get测试下 顺便那个图片的网址能给我下吗

**Comment by lokayimasi** [comment]
https://cdn.steamcommunity.com/economy/image/IzMF03bk9WpSBq-S-ekoE33L-iLqGFHVaU25ZzQNQcXdA3g5gMEPvUZZEaiHLrVJRsl8vGuCUY7Cjc9ehDNVzDMDfXStiyQrcex4NM6b6Qv9pOGZGXC8Wz_LOybMEhhhEOIJYGWM_Gb0tLiQRDCdRLt5FgoFK_AH-jEdPJuJOEM_1tEN-TbhwxR-RxcsPNVId0m5xWYXNK8awSwTIs5fnSChJMbd1ApmOU9jDOvjArTAatL3kCYtWBtgGakTbNmcviS5_8H0OOnGc68hIvw2UNWUD8A  @lrinQVQ

**Comment by lrinQVQ** [comment]
thanks

**Comment by lrinQVQ** [comment]
Steam换了CDN结果没改中国区的解析

**Comment by lrinQVQ** [comment]
ip: 61.213.183.138
DNS:a248.e.akamai.net
DNS:*.akamaihd-staging.net
DNS:*.akamaized.net
DNS:*.akamaihd.net
DNS:*.akamaized-staging.net

**Comment by lokayimasi** [comment]
嗯，访问的时候写的不安全

**Comment by lrinQVQ** [comment]
我去发个邮件提醒下他们

**Comment by lrinQVQ** [comment]
https://steamcommunity.com/discussions/forum/1/2572002906849112113/
直接发论坛了

**Comment by lokayimasi** [comment]
国区ip打不开社区讨论区XD，G胖把国区讨论锁了

**Comment by lrinQVQ** [comment]
XD忘了我开了代理的

**Comment by beyondgfw** [comment]
@lrinQVQ 我也开了

**Comment by tutukill** [comment]
新协议没有发布，你们更新host在玩什么？能否带我一个。

**Comment by SerCom-KC** [comment]
@tutukill 
当然是在玩不需要新协议就能解决的网站啊（

**Comment by lrinQVQ** [comment]
XD已经随Chrome发布了 不过可惜的是更关键的问题

**Comment by lrinQVQ** [comment]
Steam:不想管.jpeg
只能close先了XD
