### ISSUE TITLE
逼逼C貌似DNS污染

### ISSUE THREAD

**Issue by mraandtux** [googlehosts/hosts#233]
### 是什么网站 / app 出现了问题？
逼逼C

- [X] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [x] 完全无法使用：如题

- [ ] 部分无法使用：

### 您的运营商是？
广东有线U宽频（联通）

### 加载失败的资源地址
https://www.bbc.com/news
https://www.bbc.co.uk/radio/player/bbc_world_service_east_asia

### 失效域名的 DNS 解析结果
解出DNS污染专用IP (69.171.224.12)

### 封锁方式
- [X] DNS 污染
- [ ] IP 封锁
- [ ] TCP Reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```

# Beeb Start
151.101.8.81 www.bbc.com fig.bbc.co.uk
212.58.249.209 212.58.244.67 www.bbc.co.uk
23.9.188.16 static.bbci.co.uk static.bbc.co.uk nav.files.bbci.co.uk ichef.bbci.co.uk m.files.bbci.co.uk feeds.bbci.co.uk mybbc.files.bbci.co.uk polling.bbc.co.uk search.files.bbci.co.uk a.files.bbci.co.uk emp.bbc.co.uk gel.files.bbci.co.uk emp.bbc.com news.bbcimg.co.uk mybbc-analytics.files.bbci.co.uk 
212.58.246.213 212.58.244.114 ssl.bbc.co.uk
13.33.25.10 13.33.25.96 13.33.25.123 13.33.25.87 push.api.bbci.co.uk
52.210.200.185 34.251.9.18 54.72.23.188 search-suggest.api.bbci.co.uk
54.72.48.4 34.253.116.138 ess.api.bbci.co.uk
212.58.249.135 212.58.244.93 session.bbc.com
212.58.244.92 212.58.246.124 account.bbc.com
212.58.244.81 212.58.249.160 open.live.bbc.co.uk
# Beeb End

```

### 附加信息
附Greatfire的测试结果：
https://zh.greatfire.org/https/www.bbc.com/news
https://zh.greatfire.org/https/www.bbc.com/

以下地址无需加入列表，但可以自行加入自己的列表

```
# Counter-blocking CCTV for GFuckW blocking Beeb Start
127.0.0.1 cctv.com
127.0.0.1 news.cctv.com
127.0.0.1 www.cctv.com
127.0.0.1 tv.cctv.com
127.0.0.1 sports.cctv.com
127.0.0.1 www.cgtn.com
# Counter-blocking CCTV for GFuckW blocking Beeb End
```

**Comment by lrinQVQ** [comment]
thanks

**Comment by mraandtux** [comment]
还没完，再开回Issue：
``
23.9.188.16 rmp.files.bbci.co.uk weather.files.bbci.co.uk search.files.bbci.co.uk programmes.files.bbci.co.uk
52.208.100.59 54.76.152.33 52.51.23.77 mvt.api.bbc.com
212.58.249.186 212.58.244.158 search.bbc.co.uk

有可能会有更多的地址，因本人能力所限，暂时放这么多，希望其他人补完

**Comment by Ir1d** [comment]
@mraandtux 辛苦

**Comment by lrinQVQ** [comment]
昂 我去寻找吧
