### ISSUE TITLE
请求修复 pinterest.com 图片无法加载的问题。

### ISSUE THREAD

**Issue by CHVII-2** [googlehosts/hosts#235]
请求修复 pinterest.com 图片无法加载的问题。
之前一周 SerCom-KC 临时修复了下，但这几天 pinterest 又出现了图片无法加载的问题。请求再次修复。

另外可以麻烦加入 instagram.com 的hosts吗？
谢谢。

###运营商
联通

###图片加载失败资源地址
https://i.pinimg.com/236x/3e/55/51/3e5551deddbd399ca29e5353a0137296.jpg
https://i.pinimg.com/236x/66/f2/81/66f28147bd6b431eee57511607187484.jpg

**Comment by Sansui233** [comment]
i.pinimg.com三天两头地换ip...这咋整

**Comment by beyondgfw** [comment]
@Sansui233 绝望.jpeg
