### ISSUE TITLE
请问能否添加khanacademy.org的hosts?

### ISSUE THREAD

**Issue by lifeidle** [googlehosts/hosts#236]
www.khanacademy.org 网页
cdn.kastatic.org 视频
网页国内偶尔能直连，但是很不稳定，视频直连的话基本无法加载。
万分感谢！

**Comment by lrinQVQ** [comment]
真没救XD所有服务器都是fastly的CDN 救不了.jpeg

**Comment by lifeidle** [comment]
谢谢！

**Comment by beyondgfw** [comment]
@lifeidle 小意思啦
