### ISSUE TITLE
pixiv needs update

### ISSUE THREAD

**Issue by shawac** [googlehosts/hosts#237]
### 是什么网站 / app 出现了问题？
pixiv.net (IP changed several weeks ago)

- [X] 我确认这不是一个 NSFW 网站
↑ Well... if you turn off R-18 option.

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方
210.129.120.49	pixiv.net
# Someone at Tieba has published a long list (~50 lines) of relevant domains, but I do not have the permission to copy them here.
# 请将 hosts 内容粘贴在此行上方
```

**Comment by lrinQVQ** [comment]
The same with now hosts file
210.129.120.49	pixiv.net
and this ip is work.

**Comment by shawac** [comment]
Ah... I didn't know that it has already been updated. Sorry about that.

**Comment by SerCom-KC** [comment]
Duplicate of #151
