### ISSUE TITLE
Update requiring about pixiv PAY

### ISSUE THREAD

**Issue by SatoshiJek** [googlehosts/hosts#239]
### 是什么网站 / app 出现了问题？

- [X] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [X] 完全无法使用：

- [ ] 部分无法使用：

### 您的运营商是？
长城

Because of the wrong domain name of pixiv PAY in the original hosts file (it's `payment.pixiv.net` originally, but `pay.pixiv.net` correctly), I cannot visit the website. After modifying the domain name, it works.

### 可用的 hosts
```
210.129.120.52	pay.pixiv.net
# Modified the domain name only.
```

**Comment by lrinQVQ** [comment]
thanks
