### ISSUE TITLE
希望添加Backup and Sync From Google的支持

### ISSUE THREAD

**Issue by fimmy** [googlehosts/hosts#24]
Backup and Sync From Google是同步谷歌相册的桌面版程序，连接不上
希望能加上这个的支持

**Comment by SerCom-KC** [comment]
似乎是因为缺了 `www.googleapis.com`

**Comment by lrinQVQ** [comment]
0.0 soga

**Comment by lrinQVQ** [comment]
加了看看

**Comment by fimmy** [comment]
@lrinQVQ 我看了一下108.177.120.94这个ip我这边ping不通，我替换成别能ping通的谷歌服务器ip好像就可以了

**Comment by lrinQVQ** [comment]
ok 那就行 到时候更新ip

**Comment by fimmy** [comment]
好像又失效了，www.googleapis.com能ping通
![_20170904184416](https://user-images.githubusercontent.com/10045957/30023287-4eefa76c-91a1-11e7-8b51-18f36555749d.png)
![_20170904184452](https://user-images.githubusercontent.com/10045957/30023314-5fafd14e-91a1-11e7-9a13-29b4a59511ed.png)

**Comment by SerCom-KC** [comment]
你的网络运营商可以选择只封端口不封 ping
请用 tcping 或类似的工具检测一下 443 端口
（嘛虽说目前 hosts 里的 IP 确实死得差不多了……

**Comment by lrinQVQ** [comment]
0.0 呼今晚熬夜push一次吧

**Comment by fimmy** [comment]
@lrinQVQ @SerCom-KC 有什么方法可以找有效的ip，有时候ip失效了也可以自行更换

**Comment by lrinQVQ** [comment]
咩 扫IP段~

**Comment by mcxinyu** [comment]
支持

**Comment by SerCom-KC** [comment]
关于这个 issue 的话
现在我感觉就是 `accounts.google.com` 的 IP 不好使

**Comment by lrinQVQ** [comment]
accounts.google.com还在通用IP啦

**Comment by lrinQVQ** [comment]
貌似www.googleapis.com修复了吧0.0 关闭了先
