### ISSUE TITLE
quora

### ISSUE THREAD

**Issue by imba-tjd** [googlehosts/hosts#240]
### 是什么网站 / app 出现了问题？

- [x] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [x] 完全无法使用：

- [ ] 部分无法使用：

### 失效域名的 DNS 解析结果
![default](https://user-images.githubusercontent.com/24759802/43681705-38a0af34-988e-11e8-8b21-42371462b0e4.png)

### 封锁方式
- [x] DNS 污染
- [ ] IP 封锁
- [ ] TCP Reset
- [ ] 涉及到第三方服务：

**Comment by EthereumD** [comment]
Look #69

**Comment by imba-tjd** [comment]
@lrinQVQ emmm域名不够吧，最好还加上`quora.com`和`log.quora.com`。然后我在访问的时候它还会请求`tch221194.tch.quora.com`这样的地址……理论上hosts就修不好了吧:joy:

**Comment by lrinQVQ** [comment]
dig @114.114.114.114 log.quora.com

; <<>> DiG 9.13.0 <<>> @114.114.114.114 log.quora.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 22368
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 6ec9da88f6d9a932 (echoed)
;; QUESTION SECTION:
;log.quora.com.			IN	A

;; ANSWER SECTION:
log.quora.com.		79006	IN	CNAME	quora-prod-log-vpc-1111597382.us-east-1.elb.amazonaws.com.
quora-prod-log-vpc-1111597382.us-east-1.elb.amazonaws.com. 36 IN A 34.207.29.244
quora-prod-log-vpc-1111597382.us-east-1.elb.amazonaws.com. 36 IN A 52.71.168.65

log.quora.com没污染啊.jpeg

**Comment by lrinQVQ** [comment]
tch221194.tch.quora.com确实有xd

**Comment by imba-tjd** [comment]
我的测试结果：
```
$ dig @114.114.114.114 log.quora.com

; <<>> DiG 9.11.3-1ubuntu1.1-Ubuntu <<>> @114.114.114.114 log.quora.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 60393
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;log.quora.com.                 IN      A

;; ANSWER SECTION:
log.quora.com.          85      IN      A       88.191.253.157

;; Query time: 16 msec
;; SERVER: 114.114.114.114#53(114.114.114.114)
;; WHEN: Mon Aug 06 17:07:53 DST 2018
;; MSG SIZE  rcvd: 47
```
然后88.191.253.157是tcping不通的。

http://tool.chinaz.com/dns/?type=1&host=log.quora.com
有的可以有的不行

**Comment by SerCom-KC** [comment]
@EthereumD 
Quora 不算 Facebook 旗下所以不属于 duplicate。
