### ISSUE TITLE
不起作用 Hosts Not Work

### ISSUE THREAD

**Issue by yh371174229** [googlehosts/hosts#242]
### 是什么网站 / app 出现了问题？

- [ ] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [ ] 完全无法使用：

- [ ] 部分无法使用：

### 封锁方式
- [ ] DNS 污染
- [ ] IP 封锁
- [ ] TCP Reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方

# 请将 hosts 内容粘贴在此行上方
```

**Comment by SerCom-KC** [comment]
1. 你的问题不明。
2. 请再读一遍模板。
