### ISSUE TITLE
Telegram专用SOCKS5代理   在中国已经不能用了连接不上

### ISSUE THREAD

**Issue by xz00311** [googlehosts/hosts#243]
实验室  Telegram专用SOCKS5代理   在中国已经不能用了连接不上

**Comment by lrinQVQ** [comment]
因为P2P维权事件我们发布的那个频道收到了牵连被封了端口

**Comment by lrinQVQ** [comment]
SS一直存活 你们可以暂时使用下

**Comment by lrinQVQ** [comment]
@wolfan xd其实你仔细看wiki你会发现里面有ss的

**Comment by wolfan** [comment]
话说，能不能把 free-ss 的IP加到Hosts中，要不每次都要手动在加次。

**Comment by lrinQVQ** [comment]
@wolfan https://github.com/googlehosts/hosts/blob/master/hosts-files/hosts#L33
加过的呀

**Comment by wolfan** [comment]
@lrinQVQ 呃……我说的是free-ss.site

**Comment by wolfan** [comment]
`104.18.57.236 free-ss.site`

**Comment by SerCom-KC** [comment]
@wolfan 这个问题已经讨论过了，本项目不添加此类网站，详见 #177。

**Comment by lrinQVQ** [comment]
+1

**Comment by xz00311** [comment]
Telegram专用SOCKS5代理  啥时候能复活啊

**Comment by wolfan** [comment]
@xz00311 所说要等lts1.3 Ok后才会复活。

**Comment by beyondgfw** [comment]
@xz00311 我们会换到2334端口

**Comment by lrinQVQ** [comment]
详见wiki 已全部更换并增加mtprotoproxy

**Comment by lrinQVQ** [comment]
已全部更新请看wiki
