### ISSUE TITLE
Github上不了

### ISSUE THREAD

**Issue by 123ysys** [googlehosts/hosts#25]
与此一样的是Humble bundle也上不了，但是刷新了DNS缓存后Humble bundle是可以上的，但Github还是不行。
不知是自己网络的问题还是墙的问题。
两者都没有添加过hosts文件。

**Comment by lrinQVQ** [comment]
昂确实Github炸了

**Comment by 123ysys** [comment]
炸了好多。谷歌翻译也不行。这玩意儿明明已经被解禁了。

**Comment by lrinQVQ** [comment]
没办法XD 这几天要折腾的东西有点多233晚上来处理下

**Comment by 123ysys** [comment]
辛苦大佬了。

**Comment by ze00** [comment]
蛤蛤蛤蛤连Github都墙。。。。

**Comment by 123ysys** [comment]
@ze00 这网站本来就被弄过，DDoS攻击好像。现在还可以，但是Google翻译上不去了，郁闷啊！

**Comment by 123ysys** [comment]
我发现和Google相关的就封得特别快，脸书什么的就没事。

**Comment by ze00** [comment]
@123ysys 我这也是。。。只要是google相关的东西基本挺不过一天

**Comment by 123ysys** [comment]
不过说实话，我用手机流量，就可以上谷歌翻译、谷歌地图，甚至Google play，但用电脑WIFI，就全打不开，显示time out。

**Comment by ze00** [comment]
我全挂

**Comment by qw4096** [comment]
不会吧，我github从switchy里撤掉了，还觉得速度比以前好了呢，用的就是这里的hosts

**Comment by 123ysys** [comment]
@qw4096 看情况，现在又可以了，但谷歌相关的全挂了，Github在我开这个issue的时候的确上不了，不知是不是墙的关系。

**Comment by lrinQVQ** [comment]
移动更新了Github的CDN

**Comment by lrinQVQ** [comment]
14  GITHUB-INC.ear3.Seattle1.Level3.net (4.16.168.166)  230.054 ms  231.583 ms *
15  * GITHUB-INC.ear3.Seattle1.Level3.net (4.16.168.166)  224.726 ms  229.895 ms
16  * * *
17  * lb-192-30-255-112-sea.github.com (192.30.255.112)  269.104 ms *

现在貌似有两个节点了2333

**Comment by ze00** [comment]
刚才又挂一下。。。吓死

**Comment by lrinQVQ** [comment]
只是升级CDN 2333不要惊慌

**Comment by 123ysys** [comment]
心死，心累。
