### ISSUE TITLE
search.avira.com && blog.humblebundle.com && id.heroku.com

### ISSUE THREAD

**Issue by imba-tjd** [googlehosts/hosts#250]
### 是什么网站 / app 出现了问题？

- [x] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [x] 完全无法使用：

- [ ] 部分无法使用：

### 您的运营商是？

移动

### 加载失败的资源地址

* search.avira.com

### 失效域名的 DNS 解析结果

![default](https://user-images.githubusercontent.com/24759802/45278519-06973380-b500-11e8-91d1-65042e441d51.png)

### 封锁方式
- [x] DNS 污染
- [ ] IP 封锁
- [ ] TCP Reset
- [ ] 涉及到第三方服务：

### 可用的 hosts

![default](https://user-images.githubusercontent.com/24759802/45278595-70afd880-b500-11e8-9fc3-c95d7a7a42b6.png)

```
# 请将 hosts 内容粘贴在此行下方
18.212.47.0 search.avira.com
# 请将 hosts 内容粘贴在此行上方
```

---

`blog.humblebundle.com`也挂了，但是用Google dns查出来的ip会显示证书不匹配，是tumblr的证书。

---

`id.heroku.com`挂了，Google查出来的`34.199.75.61`现在可以用

**Comment by SerCom-KC** [comment]
下次还是分 issue 吧，网站不同的话不会记成 duplicate 的……
`search.avira.com` enhancement DNS污染确认
`blog.humblebundle.com` won't fix 基于Tumblr的自定义域名博客大概是不支持HTTPS的
`id.heroku.com` bug IP变动确认

**Comment by imba-tjd** [comment]
@SerCom-KC 话说我edit内容和标题你们会收到提醒吗？应该不会吧？

**Comment by SerCom-KC** [comment]
@imba-tjd 
确实不会，所以推荐还是分 issue，这样也方便我分类。这次就算了。

**Comment by imba-tjd** [comment]
你们七天一点反应都没有，我怎么知道什么情况嘛。
而且我在 https://github.com/googlehosts/hosts/commit/f4f9114fdcbfd3fe40c63e4272d51d421ca70fe5#diff-8cc7b2b0d78dd2501610391c086a8516R26 和 https://github.com/googlehosts/hosts/pull/198#issuecomment-419125167 评论了一下，你们也没反应……

**Comment by beyondgfw** [comment]
@imba-tjd 啧 貌似没收到推送

**Comment by SerCom-KC** [comment]
> 你们七天一点反应都没有，我怎么知道什么情况嘛。

主要维护者忙成狗了……😅 存在漏看的可能。

> 而且我在 f4f9114#diff-8cc7b2b0d78dd2501610391c086a8516R26 和 #198 (comment) 评论了一下，你们也没反应……

~~这种无伤大雅的问题会触发懒癌，~~ 你自己开 PR 其实更快（

**Comment by lrinQVQ** [comment]
好像还没修0.0 我确认下

**Comment by lrinQVQ** [comment]
fix all
blog.humblebundle.com是tumblr的直接gg
