### ISSUE TITLE
实验室中提供的outline账号手机可以用，电脑版连不上

### ISSUE THREAD

**Issue by ychao661** [googlehosts/hosts#251]
如题，下载了outline pc端，添加了key以后连不上，但是安卓端可以，同样的账号，是电脑端需要什么其他设置么？感觉win10的网络代理设置没改什么东西。

**Comment by SerCom-KC** [comment]
我们建议您更换至 Shadowsocks 开发组官方维护的客户端，恕我们无法处理与 Outline 的兼容性问题。

**Comment by ychao661** [comment]
> outline bug emmm

你好，我也试了shadowsocks，也用不了，难道是我插件的设置有问题么？我下了obfs-local的插件并把它放在ss的文件夹里了。
![ss](https://user-images.githubusercontent.com/40202658/45494856-88a78680-b7a4-11e8-9e22-42db99f28c04.jpg)

**Comment by beyondgfw** [comment]
@ychao661 看看日志里有没有什么东西

**Comment by SerCom-KC** [comment]
> 我下了obfs-local的插件并把它放在ss的文件夹里了。

与 Shadowsocks 主程序同文件夹即可，如果有问题的话 Shadowsocks 亦会弹出提醒。
如果您的电脑还是无法连接服务器，且您的手机与电脑处于同一网络环境下，请打开命令提示符并输入 `ping ss-1.googlehosts.org` 回车并截图。

**Comment by ychao661** [comment]
> > 我下了obfs-local的插件并把它放在ss的文件夹里了。
> 
> 与 Shadowsocks 主程序同文件夹即可，如果有问题的话 Shadowsocks 亦会弹出提醒。
> 如果您的电脑还是无法连接服务器，且您的手机与电脑处于同一网络环境下，请打开命令提示符并输入 `ping ss-1.googlehosts.org` 回车并截图。

ping服务器显示没问题，ping twitter.com超时。
![3](https://user-images.githubusercontent.com/40202658/45802412-52f52700-bce9-11e8-8d50-2b745037153f.jpg)

另外，浏览器打开twiter.com，详细日志如下：

![1](https://user-images.githubusercontent.com/40202658/45802635-f8a89600-bce9-11e8-936f-4a57d38c4c48.jpg)
![2](https://user-images.githubusercontent.com/40202658/45802636-f8a89600-bce9-11e8-8fc5-cd0c55081edc.jpg)

**Comment by beyondgfw** [comment]
@ychao661 DNS污染

**Comment by ychao661** [comment]
> @ychao661 DNS污染

那请问为什么手机连这个账号能登外网啊

**Comment by beyondgfw** [comment]
@ychao661 SS安卓版有UDP转发 远程DNS解析

**Comment by ychao661** [comment]
> @ychao661 SS安卓版有UDP转发 远程DNS解析

哦哦好的，谢谢啦
