### ISSUE TITLE
1.3的站都可以RST

### ISSUE THREAD

**Issue by mraandtux** [googlehosts/hosts#253]
地址：thestandnews点炕母，看来是第一次连接的时候用了TLSv1，导致之后的Client hello被RST，详情看附件
[result.zip](https://github.com/googlehosts/hosts/files/2381455/result.zip)

**Comment by lrinQVQ** [comment]
目前ESNI都没订好方案xd 当然可以RST啊 而且貌似这家网站没有防降级机制

**Comment by zyf2008Neptune** [comment]
E站瑟瑟发抖

**Comment by mraandtux** [comment]
https://blog.cloudflare.com/encrypted-sni/

**Comment by beyondgfw** [comment]
@mraandtux 友情提示 这不是一个有效的方案

**Comment by SerCom-KC** [comment]
视为 #87 相关，先 close。
