### ISSUE TITLE
香讨不能打开了

### ISSUE THREAD

**Issue by missmin1949** [googlehosts/hosts#254]
https://www.discuss.com.hk

前些天还能打开，现在不能了。谢谢

**Comment by SerCom-KC** [comment]
DNS 污染确认，暂时未能确定是否受到 SNI RST 影响。

**Comment by missmin1949** [comment]
请问有什么办法解决吗？新的hosts好象不行。一直用您的，印象中十天之前还行的。谢谢。

**Comment by SerCom-KC** [comment]
> 新的hosts好象不行。一直用您的，印象中十天之前还行的。

本项目的 hosts 并没有收录此网站，因此截止到目前为止您能否访问该网站与 hosts 无关。
似乎没有受到 SNI RST 影响，不过无法确认 IP 在电信和联通环境下的可用性，总之先添加上去吧。

**Comment by SerCom-KC** [comment]
@missmin1949 已尝试修复，请更新 hosts 测试。
b0c849f084034cdba743a95c390352c2d8e31ed8 cc @lrinQVQ for Cloudflare quality check
