### ISSUE TITLE
Twitch 无法进入。

### ISSUE THREAD

**Issue by 123ysys** [googlehosts/hosts#255]
### 是什么网站 / app 出现了问题？
twitch.tv

- [X] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [X] 完全无法使用：Error time out

- [ ] 部分无法使用：

### 您的运营商是？
中国移动

### 加载失败的资源地址
https://www.twitch.tv/

### 封锁方式
- [x] DNS 污染
- [ ] IP 封锁
- [ ] TCP Reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方

# 请将 hosts 内容粘贴在此行上方
```

**Comment by 123ysys** [comment]
谢谢。
ps:大佬不睡觉么？明天也可以啊。

**Comment by HashLiver** [comment]
先凑合着用：
```
151.101.66.167	twitch.tv
151.101.122.167	www.twitch.tv
104.88.57.25	api.twitch.tv
151.101.122.167	gql.twitch.tv
52.4.240.221	blog.twitch.tv
104.88.57.25	player.twitch.tv
23.34.217.143	cvp.twitch.tv
54.68.30.208	pubsub-edge.twitch.tv
151.101.2.167	static.twitchcdn.net
```
但貌似视频流`video-xxxxx.xxxx.hls.ttvnw.net`有很强的干扰

**Comment by 123ysys** [comment]
@HashLiver 感谢。

**Comment by lrinQVQ** [comment]
twitchcdn等似乎没有DNS污染 所以这类域名不会添加

**Comment by 123ysys** [comment]
hosts无效。

**Comment by lrinQVQ** [comment]
xd因为没有加完

**Comment by 123ysys** [comment]
了解了。

**Comment by beyondgfw** [comment]
@123ysys 差不多找完了其实 不过还需要确定人

**Comment by lrinQVQ** [comment]
基本添加完成

**Comment by 123ysys** [comment]
@beyondgfw 啊！法克。要不加个标签吧。

**Comment by beyondgfw** [comment]
@123ysys 好主意

**Comment by 123ysys** [comment]
app仍然尚可用。

**Comment by beyondgfw** [comment]
@123ysys 昂 我都修复了啊 肯定可用嘛

**Comment by 123ysys** [comment]
@beyoundgfw 嘶～，那网页版和app是分开的吗？

**Comment by beyondgfw** [comment]
@123ysys 其实是一起的 都没问题

**Comment by 123ysys** [comment]
@beyondgfw 那说明twitch本身就有1.3协议？还是说暂时没有SNI Rst？
看来我还要回去再试，刚才看网页是提示“拒绝访问”。

**Comment by beyondgfw** [comment]
@123ysys 昂只是目前还没有SNI RST 拒绝访问我还没遇到过欸

**Comment by 123ysys** [comment]
@beyondgfw 很多网站都会偶尔会有这个connect refused的情况，但大多会立即变成time out或RST。

**Comment by beyondgfw** [comment]
@123ysys 奇怪啧

**Comment by 123ysys** [comment]
网页版变成time out了。

**Comment by 123ysys** [comment]
是不是无法添加视频流的hosts？

**Comment by beyondgfw** [comment]
@123ysys 昂等我处理一些事情我加完

**Comment by rebiu** [comment]
#Twitch Start
54.254.167.84        app.twitch.tv
54.187.84.86        countess.twitch.tv
52.84.222.121        dev.twitch.tv
184.169.156.224        help.twitch.tv
52.89.26.201        passport.twitch.tv
35.161.182.231        spade.twitch.tv
34.212.220.91        trowel.twitch.tv
35.185.17.162        music.twitch.tv
54.230.159.250        clips-media-assets2.twitch.tv
54.230.159.146        vod-storyboards.twitch.tv
34.214.98.191        client-event-reporter.twitch.tv
50.112.132.198        irc-ws.chat.twitch.tv
52.89.48.200        video-edge-aed56b.sjc02.hls.ttvnw.net
35.163.203.219        video-edge-db8460.sjc02.hls.ttvnw.net
54.149.124.198        video-edge-5fbf1c.sjc02.hls.ttvnw.net
52.88.54.25        video-edge-87714e.sjc02.hls.ttvnw.net
151.101.66.167        twitch.tv
151.101.122.167        www.twitch.tv
104.88.57.25        api.twitch.tv
151.101.122.167        gql.twitch.tv
52.4.240.221        blog.twitch.tv
104.88.57.25        player.twitch.tv
23.34.217.143        cvp.twitch.tv
54.213.50.135        spade.sci.twitch.tv
54.68.30.208        pubsub-edge.twitch.tv
151.101.2.167        static.twitchcdn.net
# Twitch End

**Comment by beyondgfw** [comment]
@rebiu 0.0这一段怎么了嘛

**Comment by lrinQVQ** [comment]
准备穷举所有sjc02.hls.ttvnw.net域名x

**Comment by SerCom-KC** [comment]
@rebiu 日常提示，请用 ```` ``` ```` 把 hosts 内容圈起来。
已帮你修改了。

**Comment by 123ysys** [comment]
现在是能打开网页，加载页面内容也挺快的，但是看不了视频呢。用的是已经增补了的hosts。

**Comment by OctavusTao** [comment]
同上面一个问题，能打开网页，但是视频一直转圈圈，而且旁边的聊天也是完全加载不出来

**Comment by OctavusTao** [comment]
> 同上面一个问题，能打开网页，但是视频一直转圈圈，而且旁边的聊天也是完全加载不出来

补充一下，视频转圈过了一会儿后会跳出There was a network error. Please try again. (Error #2000)
