### ISSUE TITLE
store.steampowered.com和help.steampowered.com这2个hosts好像出问题了

### ISSUE THREAD

**Issue by lokayimasi** [googlehosts/hosts#256]
加了store.steampowered.com打不开steam商店，加了help.steampowered.com打开显示隐私错误

**Comment by lokayimasi** [comment]
河北电信

**Comment by lrinQVQ** [comment]
get

**Comment by lrinQVQ** [comment]
store.steampowered.com 可以打开
help.steampowered.com ip确实有问题

**Comment by lrinQVQ** [comment]
steam部分域名已经停止污染了 即将移除
