### ISSUE TITLE
Unicode的CLDR也被SNI照顾了么

### ISSUE THREAD

**Issue by liuxinyu970226** [googlehosts/hosts#257]
### 是什么网站 / app 出现了问题？
https://cldr.unicode.org/

- [X] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [X] 完全无法使用：
![1](https://user-images.githubusercontent.com/4254194/46055387-56bbfa00-c17e-11e8-9259-e63ca3add2a1.png)
哪有？
- [ ] 部分无法使用：

### 您的运营商是？
天津市滨海新区联通

### 失效域名的 DNS 解析结果
216.58.200.19

### 封锁方式
- [ ] DNS 污染
- [ ] IP 封锁
- [ ] TCP Reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方

# 请将 hosts 内容粘贴在此行上方
```

**Comment by SerCom-KC** [comment]
> 哪有？

虽然这话不中听但是现在 IE 确实没什么人权了，以 Chrome 为代表的现代浏览器（国产魔改除外）基本上都有错误代码。

**Comment by Ir1d** [comment]
@SerCom-KC http://cldr.unicode.org/

**Comment by SerCom-KC** [comment]
正如楼上所说，此网站并不支持 HTTPS 访问，请使用 HTTP。
如果您无法通过 HTTP 访问的话那我们也没什么办法了，毕竟 DNS 解析没有问题。

**Comment by liuxinyu970226** [comment]
@SerCom-KC 那为何ta们的主页却可以https打开？难道Unicode在开不开的问题上玩双标？

**Comment by SerCom-KC** [comment]
@liuxinyu970226 （纯个人观点注意）
搞不好他们只是单纯的技术力不足，因为主页托管在 Unicode 自己的服务器而 CLDR 的页面在谷歌服务器上，大概是不会配置谷歌服务器吧……

**Comment by Ir1d** [comment]
首页上的 Quick Links 底下是 http 的

**Comment by SerCom-KC** [comment]
我是用 SSL Labs 再确认了一下，毕竟不能排除写网页的偷懒没换的情况。
不过手动改成 HTTPS 确实是个好习惯就是了。
