### ISSUE TITLE
微软应用商店评论无法显示

### ISSUE THREAD

**Issue by lychichem** [googlehosts/hosts#258]
### 是什么网站 / app 出现了问题？
Microsoft Store或者https://www.microsoftstore.com.cn/c/apps

- [X] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [ ] 完全无法使用：

- [X] 部分无法使用：
评论区无法正常加载。可确认是web.vortex.data.microsoft.com加载错误

### 您的运营商是？
浙江教育网，电信出口

### 加载失败的资源地址
https://web.vortex.data.microsoft.com/collect/v1?$mscomCookies=true&ext-javascript-msfpc='GUID%3Dc302e4a12ce448ee9294ad9c91a9b780%26HASH%3Dc302%26LV%3D201809%26V%3D4%26LU%3D1537413642222'

### 失效域名的 DNS 解析结果
nslookup web.vortex.data.microsoft.com
服务器:  dns1.zju.edu.cn
Address:  10.10.0.21

非权威应答:
名称:    hk2.vortex.data.microsoft.com.akadns.net
Address:  111.221.29.254
Aliases:  web.vortex.data.microsoft.com
          web.vortex.data.microsoft.com.akadns.net
          geo.vortex.data.microsoft.com.akadns.net

### 封锁方式
- [ ] DNS 污染
- [ ] IP 封锁
- [ ] TCP Reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方

# 请将 hosts 内容粘贴在此行上方
```

**Comment by lychichem** [comment]
不能确定是哪种封锁方式，但是我换了个在lax的he dns，解析出的ip也不行……想不通封这玩意干嘛……

**Comment by SerCom-KC** [comment]
这个域名应该是微软用于跟踪/收集用户信息的域名，应该跟评论加载没有关系；此域名加载失败的原因应该是您的广告屏蔽插件自动拦截的结果，这种情况下，浏览器调试工具显示的错误信息应当含有“blocked”字样。
您可能需要寻找其他加载失败的域名。（本人 AFK，所以目前没法直接测试）

**Comment by lychichem** [comment]
@SerCom-KC 非windows系统也能测试的，只需要访问microsoft store网页版的链接，任意选择一个app查看评论即可。现在win10那个store完全就是对网页版的封装而已

**Comment by SerCom-KC** [comment]
@lychichem 我的意思是我在手机上……😅
晚些时候我也看一下吧。

**Comment by lychichem** [comment]
@SerCom-KC 又下了个火狐发现真的只有我提到的域名加载失败了……不知道什么情况……

**Comment by SerCom-KC** [comment]
@lychichem 
呃……为什么除了 https://www.microsoftstore.com.cn/accessories/forza-7-standard/p/miczy0003 以外几乎所有的 app 都完全看不到评论区（而不是显示“加载失败”之类的），你确定不是微软关闭了中国大陆地区的评论功能嘛……
请最好给个具体的示例页面。（还是说你的商店账户地区不是中国大陆？）

**Comment by lychichem** [comment]
@SerCom-KC 这点我还真没考虑到……我的账户确实是大陆地区的……我切个区看看……

**Comment by SerCom-KC** [comment]
@lychichem 
我再次测试了一下，测试链接是 https://www.microsoft.com/zh-cn/p/forza-motorsport-7-standard-edition/9n3nk5ww05ht?activetab=pivot%3Areviewstab#ratings-reviews 。
![image](https://user-images.githubusercontent.com/15853348/46566177-4a892700-c94c-11e8-9867-beeb35c43ffb.png)
点击上面的评分星星图标，可以注意到页面确实尝试切换至评论页，然而原本应该显示“评论”二字的位置（即截图中下面那个圈圈）并没有显示任何东西。
点击我上面的链接确实可以直接看到评论；然而，如果使用这个链接 https://www.microsoft.com/zh-cn/p/forza-motorsport-7-standard-edition/9n3nk5ww05ht 进入商店页面，然后点击评分星星切换到评论页的话，是无法加载出来的。
进一步观察测试链接的源代码（Google Chrome/Firefox 在地址栏粘贴 `view-source:https://www.microsoft.com/zh-cn/p/forza-motorsport-7-standard-edition/9n3nk5ww05ht?activetab=pivot%3Areviewstab#ratings-reviews`）：
![image](https://user-images.githubusercontent.com/15853348/46566235-59bca480-c94d-11e8-8e5d-997bcf18c584.png)
可以看到评论是直接打在页面上的，而不是通过其他域名加载，换句话就是评论区加载只与 `www.microsoft.com` 有关而与 `web.vortex.data.microsoft.com` 无关。


结论：
- `web.vortex.data.microsoft.com` 不背锅；
- 这显然是微软对国区的特别操作，所以 hosts 无法解决这个问题。

Labeled as invalid and closing this issue.

**Comment by lychichem** [comment]
总不能是因为使用中文的用户总不干正事就直接锁评论区吧……这也太😂
