### ISSUE TITLE
请求添加www.dynu.com的hosts，封锁方式未知。

### ISSUE THREAD

**Issue by 123ysys** [googlehosts/hosts#260]
### 是什么网站 / app 出现了问题？
www.dynu.com

- [X] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [X] 完全无法使用：

- [ ] 部分无法使用：

### 您的运营商是？
浙江移动

### 失效域名的 DNS 解析结果
正在 Ping www.dynu.com [69.171.235.101] 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

69.171.235.101 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，

### 封锁方式
- [X] DNS 污染
- [ ] IP 封锁
- [ ] TCP Reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方

# 请将 hosts 内容粘贴在此行上方
```

**Comment by lrinQVQ** [comment]
我看看0.0

**Comment by lrinQVQ** [comment]
似乎没有污染
HPING www.dyun.com (enp3s0 203.78.142.12): S set, 40 headers + 0 data bytes
len=48 ip=203.78.142.12 ttl=244 id=20098 sport=443 flags=SA seq=0 win=16384 rtt=43.9 ms
len=48 ip=203.78.142.12 ttl=244 id=30569 sport=443 flags=SA seq=1 win=16384 rtt=43.8 ms
len=48 ip=203.78.142.12 ttl=244 id=19391 sport=443 flags=SA seq=2 win=16384 rtt=47.8 ms
len=48 ip=203.78.142.12 ttl=245 id=50797 sport=443 flags=SA seq=3 win=16384 rtt=39.7 ms
len=48 ip=203.78.142.12 ttl=245 id=2807 sport=443 flags=SA seq=4 win=16384 rtt=39.6 ms
len=48 ip=203.78.142.12 ttl=244 id=18920 sport=443 flags=SA seq=5 win=16384 rtt=47.6 ms

**Comment by lrinQVQ** [comment]
0.0只是网站禁止了ICMP

**Comment by lrinQVQ** [comment]
而且这个域名正在被出售

**Comment by 123ysys** [comment]
不应该在出售啊。
呃，写错了，是www.dynu.com。抱歉。

**Comment by lrinQVQ** [comment]
0.0欸写错了还行

**Comment by lrinQVQ** [comment]
只是DNS污染而已昂

**Comment by 123ysys** [comment]
@IrinQVQ 经常有的事，233
那应该是有效的吧改hosts。

**Comment by lrinQVQ** [comment]
昂有 我晚点加下
