### ISSUE TITLE
https://lihkg.com 有时能上有时不行

### ISSUE THREAD

**Issue by missmin1949** [googlehosts/hosts#261]
首先要说谢谢，二次寻助最终都得到了完美解决。

这个网站，用一般的dns，无法浏览。换成了少污染的dns，有时候能打开，有时候不能，觉得应该可以通过hosts解决。

但自己是个小白，不知道如何弄，如果可以，希望可以加入hosts里面或者指点一下方法。

再次为二次得到的帮助说声谢谢。

**Comment by lrinQVQ** [comment]
嘛小意思啦 我先看看这个网站怎么了

**Comment by lrinQVQ** [comment]
fix now
https://github.com/googlehosts/hosts/commit/b2a6feb38a117f096866de755b2eabcdc43d73c9

**Comment by missmin1949** [comment]
谢谢

**Comment by imba-tjd** [comment]
此网站貌似含有NSFW内容

**Comment by lrinQVQ** [comment]
0.0嘛根据项目的定义 类似Pronhub那样的明显并且以成人色情为主的网站才算

**Comment by SerCom-KC** [comment]
@imba-tjd pixiv 也是有 NSFW 内容的，但是有严格的过滤政策，所以类似这样的网站都是可以进入项目的。
并不是说有 NSFW 就不能进项目了，那样的话怎么说都太极端了。
