### ISSUE TITLE
pbs.twimg.com

### ISSUE THREAD

**Issue by imba-tjd** [googlehosts/hosts#263]
此网站是推特的图床，不过并没有重置，只是dns污染。
直接访问不会返回结果，但是其实是有效的。如果要测试的话可以百度一下这个网址，能找到一些实际的链接。

**Comment by lrinQVQ** [comment]
get

**Comment by lrinQVQ** [comment]
确实没有RST

**Comment by lmfree** [comment]
100秒改变一次ip地址, 非常神奇的一个域名.
