### ISSUE TITLE
希望能够测试下apkpure app最近怎么了，一直卡在加载的log页面

### ISSUE THREAD

**Issue by 123ysys** [googlehosts/hosts#264]
### 是什么网站 / app 出现了问题？
Apkpure app 最新版
Android

- [X] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [X] 完全无法使用：

- [ ] 部分无法使用：

### 您的运营商是？
浙江移动

### 封锁方式
- [ ] DNS 污染
- [ ] IP 封锁
- [ ] TCP Reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方

# 请将 hosts 内容粘贴在此行上方
```

**Comment by 123ysys** [comment]
首先说明一下，我没有测试网站的可用性，开这个issue的本意是想弄清楚最近无法打开app的原因，请见谅。

**Comment by lrinQVQ** [comment]
稍后测试一下

**Comment by imba-tjd** [comment]
应该是它把我们屏蔽了

**Comment by 123ysys** [comment]
@imba-tjd 这样做的目的是什么？我还发了邮件询问，一直没反应。

**Comment by imba-tjd** [comment]
我当然不会知道他们的目的是什么:joy:

**Comment by lrinQVQ** [comment]
@imba-tjd @123ysys 近期身体情况极差x 之前还发烧了 so 处理效率很低
计划休息ing 2天后处理

**Comment by Titanlbr520** [comment]
同出现这问题，盼大神解答！

**Comment by SerCom-KC** [comment]
> 应该是它把我们屏蔽了

https://apkpure.com → HTTP 403
https://apkpure.com/cdn-cgi/trace → 正常显示 Cloudflare 信息

应该是屏蔽中国 IP 实锤了，`won't fix` 吧。🤔

**Comment by LittleGrocery** [comment]
找到办法了，详情见：https://github.com/ACL4SSR/ACL4SSR/issues/162

**Comment by lrinQVQ** [comment]
@LittleGrocery apkpure屏蔽中国IP 除非代理 无效啊

**Comment by LittleGrocery** [comment]
> @LittleGrocery apkpure屏蔽中国IP 除非代理 or 伪造IP 无效啊

所以代理不是更简单吗？

**Comment by lrinQVQ** [comment]
@LittleGrocery 所以和本issues无关 如果觉得代理简单用代理即可
