### ISSUE TITLE
Request to add Goodreads into the hosts list

### ISSUE THREAD

**Issue by Calliston3** [googlehosts/hosts#265]
### 是什么网站 / app 出现了问题？
Goodreads 网页版

- [X] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [X] 完全无法使用：
ERR CONNECTION TIMED OUT
- [ ] 部分无法使用：

### 您的运营商是？
山西太原联通

### 失效域名的 DNS 解析结果
31.13.72.54 

### 封锁方式
- [X] DNS 污染
- [ ] IP 封锁
- [ ] TCP Reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方
52.94.237.126    www.goodreads.com
52.94.237.126    ads.goodreads.com
# 请将 hosts 内容粘贴在此行上方
```

**Comment by Calliston3** [comment]
Additional Resources: [https://zh.greatfire.org/www.goodreads.com](https://zh.greatfire.org/www.goodreads.com)
自己拿GreatFire的工具测试了一下(10月19日那个是我测的)。。

**Comment by SerCom-KC** [comment]
#266 应该已经修复了。
