### ISSUE TITLE
这几天更新的host访问不了

### ISSUE THREAD

**Issue by chavyleung** [googlehosts/hosts#27]
用的chrome、ncr、广东电信
是区域和运营商的问题吗？

tg网页能上了

**Comment by lrinQVQ** [comment]
= =那你一定用的不是hosts 网页版ban 中国ip啊

**Comment by DDoSolitary** [comment]
难道我不是中国IP。。

**Comment by lrinQVQ** [comment]
咦难道 依赖的域名更新了

**Comment by lrinQVQ** [comment]
woc还真是

**Comment by lrinQVQ** [comment]
但是真的404欸

**Comment by chavyleung** [comment]
我这tg真能上，而且肯定是用的hosts上去的，ncr反而上不去，尴尬。
今天vps的ip都ping不通，4g网络也连不上vps，估计是ip被ban，在联系供应商换ip

**Comment by wolfan** [comment]
@lrinQVQ Tg的web服务还是蛮多的，自建都行。

https://telegramcn.github.io/#/login

**Comment by wolfan** [comment]
and，大佬，Chrome商店什么时候能用

**Comment by 123ysys** [comment]
@wolfan Chrome商店前段时间都可以直连的，现在又不行了。

**Comment by 123ysys** [comment]
为毛TG只在网页聊天上ban中国的IP，不在官网上ban中国的IP啊？

**Comment by wolfan** [comment]
@123ysys 应该是因为大兔兔的审查制度又惹到了白左的神精吧，比如Google以前一样。
其实你们有木有觉得这有点企鹅帝的作风，拿用户作怼气的工具。。

**Comment by lrinQVQ** [comment]
0.0 chrome的应用商店的ip 我计划用分流的ip还没丢出来

**Comment by lrinQVQ** [comment]
能给出一下你们hping3 -S -p 443 IP的状态咩

**Comment by lrinQVQ** [comment]
搜索主页的IP全数正常了咩0.0 应该没问题了吧
