### ISSUE TITLE
在使用代理服务器过程中发现的一些奇怪现象

### ISSUE THREAD

**Issue by SunlnuS** [googlehosts/hosts#273]
##在使用代理服务器过程中发现的一些奇怪现象：
1. 安卓手机、SS，使用数据流量（电信、联通）均可以使用三组配置，但是连接联通宽带WIFI时，仅第一组配置可用，但时好时坏。比如现在【2018.11.2 14:10】，手机端使用数据流量（电信、联通），三组配置均可使用，但是连接联通宽带WiFi后三组配置均不能使用，昨日连接WiFi时仅第一组配置可用。
2. 电脑Windows，SS，联通宽带，仅第一组配置可用，且时好时坏。比如现在【2018.11.2 14:10】，三组配置均不可使用，但是昨日仅第一组配置可以使用。

##做过如下尝试：
1. 尝试过重启路由器，更新IP，但无效。
2. 用手机数据流量开热点，电脑连接后，开启小飞机，三组配置均不可用。
3. 手机端开启小飞机，并开启热点，电脑连接后，无法打开Google。

**Comment by SunlnuS** [comment]
> @SunlnuS 咩 准备好了容备服务器后 正在重新部署node 请稍候

我其实重点想表达的是，为什么手机数据流量可用，但是连接WiFi就不可用了，好像也不是服务商的问题，因为联通数据流量也能使用。

**Comment by beyondgfw** [comment]
@SunlnuS 有一种东西叫玄学x

**Comment by SunlnuS** [comment]
> @SunlnuS 有一种东西叫玄学x

好一个玄学，在下竟无言以对，你赢了。

**Comment by AnyWAT** [comment]
😂不是GFW对手机数据、WiFi 的控制不一致？

**Comment by SunlnuS** [comment]
> @SunlnuS 昂除非你的wifi 2333不通 流量通

在能用的时候，第一组配置2333、2334都能使用。

**Comment by SunlnuS** [comment]
> 😂不是GFW对手机数据、WiFi 的控制不一致？

也许你是对的，看上去似乎是联通宽带的问题，应为连接宽带后，手机和电脑的情况相同。但是用联通数据流量手机是可以使用的

**Comment by justbaibai** [comment]
我的两台电脑一台能用，另一台不能用，提示秘钥不可用。很神奇啊

**Comment by lrinQVQ** [comment]
顺便 Duplicate of https://github.com/googlehosts/hosts/issues/267
