### ISSUE TITLE
shadowsocks代理如何使用?

### ISSUE THREAD

**Issue by jasonlee3652** [googlehosts/hosts#275]
新手，看了半天没看懂，我按教程安装了shadowsocks/simple-obfs。
但是未找到 'ss-server' 命令

$ ss-server -c config.json --plugin obfs-server --plugin-opts "obfs=http"
未找到 'ss-server' 命令，您要输入的是否是：
命令 'ssserver' 来自于包 'shadowsocks' (universe)
命令 'gss-server' 来自于包 'krb5-gss-samples' (universe)
ss-server：未找到命令

这个怎么搞，谢谢啦

**Comment by lrinQVQ** [comment]
0.0 使用是 ss-local 请说明您的系统

**Comment by lrinQVQ** [comment]
https://github.com/googlehosts/hosts/wiki/%E5%AE%9E%E9%AA%8C%E5%AE%A4#shadowsocks

**Comment by jasonlee3652** [comment]
> 0.0 使用是 ss-local 请说明您的系统

多谢大侠回复我，我的系统是ubuntu 16.04，我搞了好几天了，都没搞好，求大神指点！

**Comment by lrinQVQ** [comment]
@jasonlee3652 https://github.com/shadowsocks/shadowsocks-qt5

**Comment by SerCom-KC** [comment]
我们的 wiki 里没有涉及 shadowsocks 的具体使用教程， ~~按照《甩锅指南》您应该去找写教程的人或~~ 请您给出教程链接。
您参考的大概是服务器端的教程。

假定您是 Linux 系统，并有使用图形界面，请参考 https://github.com/shadowsocks/shadowsocks-qt5/wiki 。

**Comment by jasonlee3652** [comment]
shadowsocks-qt5 我已经安装了，各位的意思是我直接把类似下面的代码赋值到图形化界面的配置中吗

{
    "server":"ss-1.googlehosts.org",
    "server_port":2333,
    "password":"googlehosts",
    "method":"chacha20-ietf-poly1305",
    "plugin": "obfs-local",
    "plugin_opts": "obfs=tls;obfs-host=usa.baidu.com"
}

但是shadowsocks-qt5的客户端没有 "method":"chacha20-ietf-poly1305",另外 "plugin": "obfs-local",
    "plugin_opts": "obfs=tls;obfs-host=usa.baidu.com"是啥

**Comment by lrinQVQ** [comment]
@jasonlee3652 您可能需要这个版本
https://github.com/shadowsocks/shadowsocks-qt5/releases/download/v3.0.1/Shadowsocks-Qt5-3.0.1-x86_64.AppImage

**Comment by lrinQVQ** [comment]
apt安装的版本太老 没有chacha20-ietf-poly1305
以及插件是可选项 虽然推荐使用

**Comment by SerCom-KC** [comment]
请[使用二维码](https://github.com/shadowsocks/shadowsocks-qt5/wiki/使用手册#自二维码图像文件)。
