### ISSUE TITLE
请增加www.fcdm.cc的hosts

### ISSUE THREAD

**Issue by 123ysys** [googlehosts/hosts#277]
### 是什么网站 / app 出现了问题？
www.fcdm.cc(枫车动漫)

- [X]我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [X] 完全无法使用：

- [ ] 部分无法使用：

### 您的运营商是？
China Mobile

### 封锁方式
- [X] DNS 污染
- [ ] IP 封锁
- [ ] TCP Reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方

# 请将 hosts 内容粘贴在此行上方
```

**Comment by 123ysys** [comment]
我确定这个网站能用改hosts的方法来上。

**Comment by beyondgfw** [comment]
@123ysys get 稍后处理

**Comment by lrinQVQ** [comment]
fix now

**Comment by SerCom-KC** [comment]
> 我确定这个网站能用改hosts的方法来上。

我不觉得……
第一目前会跳转到 www.dm530.net，第二无论是哪个域名都没正常配置证书。（其实我很想挂 won't fix）

**Comment by lrinQVQ** [comment]
反正没有http rst 只是域名被污染而已 加个就完事了x

**Comment by SerCom-KC** [comment]
那就再加一个 `www.dm530.net` 吧……
其实这种玩域名游击战的网站我个人不是很想收……

**Comment by lrinQVQ** [comment]
确实昂 不过他的新域名暂时还没被污染x 思考下吧

**Comment by 123ysys** [comment]
@SerCom-KC 唔，看大佬们的心情啦233。

**Comment by SerCom-KC** [comment]
> 不过他的新域名暂时还没被污染x 

[反对。](https://www.17ce.com/site/dns/20181119_5617ee90ebbf11e8b68a91103989addb:1.html)

**Comment by beyondgfw** [comment]
@SerCom-KC 那就干脆全加了
