### ISSUE TITLE
google scholar上不去，其他可以

### ISSUE THREAD

**Issue by davidgooglehost** [googlehosts/hosts#28]
最近的hosts上不了google scholar，其他都可以，是什么问题呢？
用的是chrome、https://scholar.google.com、广东电信

**Comment by wang950312** [comment]
我怎么连chrome账户都登录不了。。。

**Comment by lrinQVQ** [comment]
XD因为计划每个域名对应一个IP 还未完善

**Comment by lrinQVQ** [comment]
0.0 现在搜索主页应该没毛病了先close
