### ISSUE TITLE
拜师学艺，还望不吝赐教

### ISSUE THREAD

**Issue by 123ysys** [googlehosts/hosts#280]
本人自从关注了项目组的前一个项目起，直到现在，一直承蒙项目组成员的关照。作为一名伸手党，心里有些惭愧，有些小伙伴即使提出更新请求，也会贴出有用的hosts，但本人目前还做不到。所以本人提出这个issue，希望能学习如何寻找有用的正确的ip。一来是为了能够自食其力，二来是想为项目组做点贡献，少做次伸手党；还望各位大佬能够不吝赐教，教教我这条咸鱼。
万分感谢！

**Comment by 123ysys** [comment]
@lrinQVQ 
@SerCom-KC 
@beyondgfw

**Comment by SerCom-KC** [comment]
就目前的情况来说还真没什么技巧——你要问 Google 的 IP 怎么找，因为我们是跟 Google 合作修复的，所以也只有我们知道什么 IP 能用。
其他网站的话简单一点基本上都是去爬各地的 DNS，高级一点的话就是去扫段了，后面这个如果只用自己的家用电脑怕是效率很低……

实在需要启蒙的话，https://github.com/racaljk/hosts/issues/1171#issuecomment-305783208 。
不过友情提示，这个方法 GFW 也会，所以只是启蒙而已。
