### ISSUE TITLE
代理服务器又挂了，无法访问google了！

### ISSUE THREAD

**Issue by xisohi** [googlehosts/hosts#282]
IOS系统，小火箭，北京联通，实验室中代理服务器全挂了！
可以访问github,但是不可以访问google.

**Comment by xisohi** [comment]
ip111.cn 全方位查询您的IP地址
从国内测试
221.216.***.*** China / Beijing

这是您访问国内网站所使用的IP

从国外测试

23.226.136.216
您访问没有被封的国外网站所使用的IP

从谷歌测试


这是您访问谷歌，Facebook，Twitter等网站所使用的IP
联系我们 info@ip111.cn

**Comment by xisohi** [comment]
C:\Users\administrator>ipconfig /flushdns

Windows IP 配置

已成功刷新 DNS 解析缓存。

C:\Users\administrator>

 我用IP111.CN测试无法访问google.

**Comment by SerCom-KC** [comment]
@xisohi 
ip111.cn“从谷歌测试”实际使用的地址是 `http://ip111cn.appspot.com`。
这是一个 Google App Engine 域名，一般 hosts 不会收录这类域名，所以如果您既没有做 DNS 防污染措施也没有使用全局代理的话，这个地址很大概率上不去。
我们不会处理这个问题；如果您一定要测试从谷歌访问的话，请以 https://www.google.com/search?q=ip&hl=en-US&gws_rd=cr 的结果为准。

**Comment by xisohi** [comment]
谢谢，全局代理是可以的！！
