### ISSUE TITLE
貌似所有shadowsocks账号失效了

### ISSUE THREAD

**Issue by jinyumarine** [googlehosts/hosts#286]
### 是什么网站 / app 出现了问题？

- [ ] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [ ] 完全无法使用：

- [ ] 部分无法使用：

### 封锁方式
- [ ] DNS 污染
- [ ] IP 封锁
- [ ] TCP Reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方

# 请将 hosts 内容粘贴在此行上方
```

**Comment by beyondgfw** [comment]
请在群上提问。

**Comment by lrinQVQ** [comment]
由于负载太高,目前ss-1/3 及其备用服务器暂时无法使用 仅ss-2 可用 我们的服务器已经到达 即将准备部署ss-4

**Comment by JimmyJLNU** [comment]
@lrinQVQ 希望你们能尽快修复，昨天晚上用你们的代理服务器的自周翻墙浏览器突然不能用了，那些节点都挂了。等你们修复完毕后，我才会把做好的翻墙浏览器发上去。

**Comment by lrinQVQ** [comment]
> @lrinQVQ 希望你们能尽快修复！昨天晚上用你们代理服务器的自用翻墙浏览器突然不能用了，所有节点都挂了，还好我有其他的备用翻墙浏览器，这才没有影响我去谷歌学术找国外的论文资料。（大四英语专业，着急写毕业论文）

所有的服务器都准备更换插件 原来的配置可能都会失效

**Comment by JimmyJLNU** [comment]
@lrinQVQ @googlehosts 应该重开这个问题了，因为尚未得到解决。

**Comment by lrinQVQ** [comment]
@JimmyJLNU  3和4是绝对正常工作的 我只测试了1 2在维护中

**Comment by SunlnuS** [comment]
我也发现，最近所有的节点好像都挂了，年前好像就全部挂了，然后我看插件变成了v2ray-plugin 和 kcptun ，但是配置里好像还是obfs-local

**Comment by GoogleHostsSupport** [comment]
@SunlnuS 请移步 #315 讨论哦～
