### ISSUE TITLE
求增加Tor浏览器的hosts

### ISSUE THREAD

**Issue by 123ysys** [googlehosts/hosts#29]
154.35.132.70	torproject.org
154.35.132.70	www.torproject.org
目前的hosts文件，不知可用否？

**Comment by lrinQVQ** [comment]
好像没毛病咩0.0 你要不要开PR

**Comment by DDoSolitary** [comment]
不是原项目有吗，放进来就好。。

**Comment by lrinQVQ** [comment]
soga 2333
