### ISSUE TITLE
用了hosts，还是连不上google

### ISSUE THREAD

**Issue by VinsonChiu** [googlehosts/hosts#292]
这是什么原因呢

**Comment by smallg0at** [comment]
因为你高估了host的作用

**Comment by lrinQVQ** [comment]
原因详见https://github.com/googlehosts/hosts/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E8%BF%99%E4%B8%AAhosts%E4%B8%80%E7%82%B9%E7%94%A8%E9%83%BD%E6%B2%A1%E6%9C%89%E5%8D%8A%E5%81%9C%E6%9B%B4%E6%98%AF%E4%BB%80%E4%B9%88%E6%84%8F%E6%80%9D
请见此处https://github.com/googlehosts/hosts/wiki/Google-Chrome-QUIC-%E7%99%BD%E5%90%8D%E5%8D%95%E6%B7%BB%E5%8A%A0%E6%96%B9%E6%B3%95

**Comment by lrinQVQ** [comment]
我们依旧处在内测阶段,如果您不会折腾,我们推荐您不要使用
