### ISSUE TITLE
用的最新的版本，可以访问谷歌，但是不能登录

### ISSUE THREAD

**Issue by buqiyong** [googlehosts/hosts#294]
### 是什么网站 / app 出现了问题？

- [ ] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [ ] 完全无法使用：

- [ ] 部分无法使用：

### 封锁方式
- [x] DNS 污染
- [x] IP 封锁
- [x] TCP Reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方

# 请将 hosts 内容粘贴在此行上方
```

**Comment by Sansui233** [comment]
同，好像是只能用google.com.hk，account.google.com也连不上的

**Comment by liuchunyang** [comment]
急需帐号登录啊

**Comment by sunwen900815** [comment]
同样的问题，有没有解决办法

**Comment by GoogleHostsSupport** [comment]
本 issue 将合并至 #274 处理～
