### ISSUE TITLE
Twitch被墙网址增补

### ISSUE THREAD

**Issue by P-256** [googlehosts/hosts#297]
### 是什么网站 / app 出现了问题？
client-event-reporter.twitch.tv
extension-files.twitch.tv
video-edge-6c210a.sjc02.hls.ttvnw.net
video-edge-7e96a0.sea01.abs.hls.ttvnw.net
video-edge-7e9938.sea01.abs.hls.ttvnw.net
video-edge-af973f.sjc02.hls.ttvnw.net

- [X] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [] 完全无法使用：

- [X] 部分无法使用：ERR_CONNECTION_TIMED_OUT（部分视频和部分功能无法加载）

### 您的运营商是？
长沙电信

### 失效域名的 DNS 解析结果
日常解析到FB、G歌、TW系列

### 封锁方式
- [X] DNS 污染
- [ ] IP 封锁
- [ ] TCP Reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方
35.160.43.140            client-event-reporter.twitch.tv
13.35.8.39                 extension-files.twitch.tv
35.167.233.226          video-edge-6c210a.sjc02.hls.ttvnw.net
35.161.182.231          video-edge-af973f.sjc02.hls.ttvnw.net
52.223.227.246          video-edge-7e96a0.sea01.abs.hls.ttvnw.net
52.223.228.119          video-edge-7e9938.sea01.abs.hls.ttvnw.net
# 请将 hosts 内容粘贴在此行上方
```

**Comment by beyondgfw** [comment]
@P-256 吼get 3q

**Comment by P-256** [comment]
> @P-256 吼get 3q

别说了，最近找到了一堆DNS污染的网站，到时候再选择一下送上来

**Comment by beyondgfw** [comment]
@P-256 2333稳 万分感谢

**Comment by P-256** [comment]
> @P-256 2333稳 万分感谢

还挖到几个
首先是还要加一个www.twitch.tv
151.101.230.167	www.twitch.tv
还有
52.34.42.243	countess.twitch.tv   这个要换
35.163.32.174            video-edge-867df2.sjc02.hls.ttvnw.net

**Comment by P-256** [comment]
> @P-256 2333稳 万分感谢

麻烦还来一个
35.167.37.81             video-edge-91c358.sjc02.hls.ttvnw.net

**Comment by lrinQVQ** [comment]
吼 统一处理下到时候

**Comment by P-256** [comment]
> 吼 统一处理下到时候

还有几个去哪了（大雾）

**Comment by beyondgfw** [comment]
@P-256 那几个IP没法用 我还在处理ing

**Comment by P-256** [comment]
> @P-256 那几个IP没法用 我还在处理ing

我再找一下吧

**Comment by P-256** [comment]
> @P-256 那几个IP没法用 我还在处理ing

怕不是又换IP了

**Comment by beyondgfw** [comment]
@P-256 你不用找全球DNS解析一个地址

**Comment by beyondgfw** [comment]
@P-256 TCP 443不通 我还在扫段

**Comment by P-256** [comment]
> @P-256 TCP 443不通 我还在扫段

35.165.41.164            video-edge-a4da6d.sjc02.hls.ttvnw.net
大雾？？？

**Comment by beyondgfw** [comment]
@P-256 这个添加过了啊我指的video-edge-7e96a0.sea01.abs.hls.ttvnw.net

**Comment by P-256** [comment]
> @P-256 这个添加过了啊我指的video-edge-7e96a0.sea01.abs.hls.ttvnw.net

有添加过吗？？（雾）

**Comment by beyondgfw** [comment]
@P-256 0.0反正在我现在在编辑的版本里面有欸

**Comment by beyondgfw** [comment]
@P-256 x哦我没push

**Comment by P-256** [comment]
> @P-256 0.0反正在我现在在编辑的版本里面有欸

Twitch真心费力，我先把我整理完的一些网站开个新的

**Comment by beyondgfw** [comment]
@P-256 昂没事 我差不多已经get完被污染的域名了

**Comment by P-256** [comment]
> @P-256 昂没事 我差不多已经get完被污染的域名了

video-edge-116e5a.sjc02.hls.ttvnw.net 又来一个？

**Comment by 123ysys** [comment]
无法播放视频是需要更新吗？

**Comment by ychao661** [comment]
网站能正常登录，但是无法播放视频，请问上面所说的一些ip已经添加到最新的hosts里面了吗

**Comment by 123ysys** [comment]
@ychao661 已经全部更新过，而且在两台网络不同的电脑上更新了三次。

**Comment by 123ysys** [comment]
抱歉，理解错了。@ychao661

**Comment by ychao661** [comment]
@123ysys 哈哈，没事，所以你也是不能放视频是吧

**Comment by 123ysys** [comment]
@ychao661 是的。

**Comment by 123ysys** [comment]
目前似乎还是需要更新。使用该ip后，会造成无法登录的情况，不管有没有挂代理。

**Comment by GoogleHostsSupport** [comment]
@P-256 
不好意思让您久等了，您在本 issue 中提交的 hosts 条目已全部更新完毕～
因 review 时间较长，如有部分条目在此期间失效的情况，还请尽早提出～
如果没有异议的话，本 issue 将在 24 小时后作关闭处理～
