### ISSUE TITLE
cn.bing.com被污染

### ISSUE THREAD

**Issue by TinQlo** [googlehosts/hosts#298]
### 是什么网站 / app 出现了问题？
cn.bing.com

- [x] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [x] 完全无法使用：

- [ ] 部分无法使用：

### 您的运营商是？
中国移动

### 失效域名的 DNS 解析结果
127.0.0.1

### 封锁方式
- [x] DNS 污染
- [ ] IP 封锁
- [ ] TCP Reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方

# 请将 hosts 内容粘贴在此行上方
```

**Comment by beyondgfw** [comment]
@TinQlo 已知,待完全确认中

**Comment by lautis0503** [comment]
这里使用正常

**Comment by TinQlo** [comment]
> @TinQlo 这是站长工具的解析结果，部分地区的DNS解析结果不正常，过一段时间之后应该就能恢复正常。
> 这不是DNS污染，应该是DNS劫持，因为DNS污染的黑名单中并没有localhost（127.0.0.1），这可能是由于操作失误导致。（参照去年11月28日百度打不开的情况）
> 如果要急需使用必应，请将站长工具的正确结果粘贴到hosts文件上。
> http://ping.chinaz.com/?host=cn.bing.com
> 或者也可以直接使用现成的：
> 202.89.233.101 cn.bing.com
> 202.89.233.100 cn.bing.com

thanks~~~

**Comment by mraandtux** [comment]
> 202.89.233.101 cn.bing.com
> 202.89.233.100 cn.bing.com
广东有线U宽频所使用的DNS服务器解析结果为上述IP，联通广东是127.0.0.1。

**Comment by lrinQVQ** [comment]
关于cn.bing.com
目前来看:
1.部分地区的默认DNS还能正常解析到微软北京的节点(也有人反馈解析的IP TCP 443不通,同时路由被切断)
2.部分地区的默认DNS已经被指向了127.0.0.1(本地回环)无法访问
3.114.114.114.114 已将cn.bing.com指向127.0.0.1 23日23:45开始正常了
4.似乎电信/移动大量切断了路由,联通大多没问题
持续观察中

**Comment by rampageX** [comment]
![c4q5-b6grk6t3cslk-3x](https://user-images.githubusercontent.com/994081/51667402-fc7f5880-1ffa-11e9-89cd-a3270dda93fb.png)

**Comment by lrinQVQ** [comment]
@rampageX  工信部网站黑名单中并无bing.com or cn.bing.com 且大多公共DNS/非运营商DNS能正常解析

**Comment by nxtreaming** [comment]
就是被Block了，不需要继续观察。

**Comment by beyondgfw** [comment]
@nxtreaming 我们不能这么不负责 大多数联通都能正常路由解析访问

**Comment by lautis0503** [comment]
这里测试解析为127.0.0.1，十多分钟后解析正常，访问正常（并不是被墙

**Comment by JimmyJLNU** [comment]
@rampageX 你的那张图片从哪里来的？

**Comment by JimmyJLNU** [comment]
@lrinQVQ 目前必应搜索在全国范围内已经恢复正常，可以关闭issue了。
http://s.weibo.com/weibo?q=bing&wvr=6&b=1&Refer=SWeibo_box
http://s.weibo.com/weibo?q=%E5%BF%85%E5%BA%94&wvr=6&b=1&Refer=SWeibo_box

**Comment by JimmyJLNU** [comment]
@lrinQVQ @nxtreaming 吉林联通，今天Bing一切正常，路由并没有被切断。

**Comment by lrinQVQ** [comment]
> @lrinQVQ @nxtreaming 吉林联通，今天Bing一切正常，路由并没有被切断。

x我说的是电信/移动 而且这条其实是23号的消息了
