### ISSUE TITLE
一堆网站

### ISSUE THREAD

**Issue by P-256** [googlehosts/hosts#299]
### 是什么网站 / app 出现了问题？

- [X] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [x] 完全无法使用：TIME OUT 系列

- [x] 部分无法使用：比如quora的CDN、油猴官网主体部分

### 您的运营商是？
长沙电信

### 失效域名的 DNS 解析结果
不讲了，一堆

### 封锁方式
- [X] DNS 污染
- [ ] IP 封锁
- [X] TCP Reset （这个是www.thetvdb.com和*.dictionary.search.yahoo.com、*.quora.com）
- [X] 涉及到第三方服务：有个网站使用Rawit的

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方
# Arte Start
212.95.74.37   www.arte.tv
23.14.7.241    static-cdn.arte.tv
# Arte End

# Behance Start
# Use Google CDN (ytimg.com）
216.146.46.10   behance.com
54.192.182.143  a5.behance.net    
151.101.193.197 www.behance.net
54.192.75.182   mir-cdn-cf.behance.net
52.85.231.84     mir-s3-cdn-cf.behance.net
# Behance End

# Clyp Start
13.33.231.37  clyp.it
13.33.231.37  static.clyp.it
13.33.231.37 api.clyp.it
13.33.231.37 soundwave.clyp.it
13.33.231.37 audio.clyp.it
# Clyp End

# CNA Start
# Already SNI RST
211.72.255.204   www.cna.com.tw
72.21.81.200    img4.cna.com.tw
210.242.210.65  img5.cna.com.tw
# CNA End

# CD Universe Start
110.232.178.118   www.cduniverse.com
72.248.115.70       cduniverse.ws
110.232.178.118   c6.cduniverse.ws
110.232.178.118   c7.cduniverse.ws
110.232.178.118   c8.cduniverse.ws
110.232.178.118   c9.cduniverse.ws
# CD Universe End

# Dailyview Start
# Use Facebook and Google CDN （fbcdn.net）
52.230.12.205   dailyview.tw
# Dailyview End

# SWI Start
72.21.91.239    www.swissinfo.ch
# SWI End

# Fastly Start
151.101.230.79    tampermonkey.freetls.fastly.net
151.101.230.79 freetls.fastly.net
# Fastly End

# Thetvdb Start
# Already SNI RST
104.16.230.14  www.thetvdb.com
# Thetvdb End

# Quora Start
# Already SNI RST
151.101.73.2             blog.quora.com
151.101.73.2             bn.quora.com
151.101.73.2             da.quora.com
151.101.73.2             de.quora.com
151.101.73.2             en-us.quora.com
151.101.73.2             es.quora.com
151.101.73.2             fi.quora.com
151.101.73.2             fr.quora.com
151.101.73.2             id.quora.com
151.101.73.2             it.quora.com
104.16.52.111           help.quora.com
151.101.73.2             hi.quora.com
151.101.73.2             jp.quora.com
151.101.73.2             mn.quora.com
151.101.73.2             nl.quora.com
151.101.73.2             no.quora.com
151.101.73.2             pt.quora.com
151.101.73.2             sv.quora.com
151.101.73.2             ta.quora.com
151.101.73.2             qsf.fs.quoracdn.net
# Quora End

# Pincong Start
104.18.54.73    pincong.rocks
# Pincong End

# Biggo Start
61.222.241.168	biggo.com.tw
61.222.241.167	img.biggo.com.tw
# Biggo End

# 请将 hosts 内容粘贴在此行上方
```

**Comment by lrinQVQ** [comment]
3q 稍后处理

**Comment by P-256** [comment]
> 3q 稍后处理

Line一堆需要大修
203.104.129.202        admin-official.line.me
203.104.129.195        at.line.me
203.104.131.82          at-talk.line.me
203.104.130.201         buy.line.me
203.104.131.76         creator.line.me
203.104.130.159       destiny-child-blog.line.me
125.209.230.71         ec.line.me
203.104.131.93         manga.line.me
23.35.196.59             media.line.me
203.104.153.58         mobile.line.me
203.104.131.77          news.line.me
203.104.129.163        lbc.line.me
203.104.142.96          live.line.me
203.104.130.159        official-blog.line.me
125.209.210.27          partners.line.me
203.104.137.133        web-pay.line.me
119.235.235.38          store.line.me
119.235.235.114        store-bill.line.me
23.57.92.220             social-plugins.line.me
116.92.246.220          terms.line.me
23.211.96.22              today.line.me
111.91.133.89            tv.line.me
23.35.196.242           d.line-scdn.net
目前统计到了这些

**Comment by beyondgfw** [comment]
@P-256 吼3q

**Comment by P-256** [comment]
> @P-256 吼3q
203.104.138.130        page.line.me
23.211.96.22             timeline.line.me
203.104.129.221       entry-at.line.me
23.211.96.22            event-web.line.me
125.209.230.71         ezstore.line.me
203.104.130.159       creator-mag.line.me
203.104.130.159       manual-at.line.me
203.104.142.42         music.line.me
23.51.208.61              ticket.line.me
119.235.235.63          callback.line.me
203.104.129.212        qr-official.line.me
203.104.153.115        travel.line.me
203.104.131.44         contact.line.me
203.104.153.152       contact-cc.line.me
125.209.210.184       jumputi.game.line.me
203.104.131.120       developers.line.me
这些

**Comment by P-256** [comment]
AWS找到换的IP了
52.219.0.190	s3-ap-northeast-1.amazonaws.com
52.95.131.21	s3-ap-southeast-2.amazonaws.com

**Comment by beyondgfw** [comment]
@P-256 0.0现在的IP没问题啊

**Comment by P-256** [comment]
> @P-256 0.0现在的IP没问题啊

我这里换IP前没法用，电信确认过没墙中墙

**Comment by P-256** [comment]
> @P-256 0.0现在的IP没问题啊

对了上面的网站......

**Comment by beyondgfw** [comment]
@P-256 昂似乎只是部分地区丢包

**Comment by beyondgfw** [comment]
@P-256 HPING 52.219.0.4 (wlp3s0 52.219.0.4): S set, 40 headers + 0 data bytes
len=44 ip=52.219.0.4 ttl=35 id=61088 sport=443 flags=SA seq=4 win=512 rtt=458.6 ms
len=44 ip=52.219.0.4 ttl=35 id=13078 sport=443 flags=SA seq=10 win=512 rtt=378.9 ms
len=44 ip=52.219.0.4 ttl=36 id=58340 sport=443 flags=SA seq=12 win=512 rtt=421.6 ms
len=44 ip=52.219.0.4 ttl=36 id=63838 sport=443 flags=SA seq=20 win=512 rtt=796.4 ms
^C
--- 52.219.0.4 hping statistic ---
23 packets transmitted, 4 packets received, 83% packet loss

**Comment by beyondgfw** [comment]
@beyondgfw HPING 54.231.249.17 (wlp3s0 54.231.249.17): S set, 40 headers + 0 data bytes
len=44 ip=54.231.249.17 ttl=46 id=3064 sport=443 flags=SA seq=0 win=512 rtt=423.9 ms
len=44 ip=54.231.249.17 ttl=47 id=53768 sport=443 flags=SA seq=1 win=512 rtt=447.9 ms
len=44 ip=54.231.249.17 ttl=46 id=60387 sport=443 flags=SA seq=2 win=512 rtt=331.7 ms
len=44 ip=54.231.249.17 ttl=46 id=6285 sport=443 flags=SA seq=3 win=512 rtt=489.1 ms
len=44 ip=54.231.249.17 ttl=47 id=9158 sport=443 flags=SA seq=4 win=512 rtt=338.4 ms
^C
--- 54.231.249.17 hping statistic ---
5 packets transmitted, 5 packets received, 0% packet loss
第二个似乎比较正常

**Comment by P-256** [comment]
> @P-256 HPING 52.219.0.4 (wlp3s0 52.219.0.4): S set, 40 headers + 0 data bytes
> len=44 ip=52.219.0.4 ttl=35 id=61088 sport=443 flags=SA seq=4 win=512 rtt=458.6 ms
> len=44 ip=52.219.0.4 ttl=35 id=13078 sport=443 flags=SA seq=10 win=512 rtt=378.9 ms
> len=44 ip=52.219.0.4 ttl=36 id=58340 sport=443 flags=SA seq=12 win=512 rtt=421.6 ms
> len=44 ip=52.219.0.4 ttl=36 id=63838 sport=443 flags=SA seq=20 win=512 rtt=796.4 ms
> ^C
> --- 52.219.0.4 hping statistic ---
> 23 packets transmitted, 4 packets received, 83% packet loss

反正湖南这边貌似普遍丢，昨天去岳阳也丢包

**Comment by beyondgfw** [comment]
@P-256 昂考虑考虑换一下也行

**Comment by P-256** [comment]
> @P-256 昂考虑考虑换一下也行

我上面堆出的一堆网站.....................................................

**Comment by beyondgfw** [comment]
@P-256 x暂时没空ing 你方便的话开个PR如何咩

**Comment by beyondgfw** [comment]
@P-256 我可能要后天才能一个一个验证添加x

**Comment by P-256** [comment]
> @P-256 我可能要后天才能一个一个验证添加x

嗯

**Comment by GoogleHostsSupport** [comment]
@P-256 由于此 issue 域名较多，为方便处理，可以麻烦您将 hosts 按服务提供方进行分类吗？例如：
```
# Disqus Start
151.101.0.134	disqus.com
151.101.24.134	www.disqus.com
# Disqus End

# Discord Start
104.16.58.5	discordapp.com
104.16.59.37	discord.gg
# Discord End
```

**Comment by GoogleHostsSupport** [comment]
@P-256 
请问您还需要添加本 issue 中涉及的条目吗？
这边注意到其中有部分条目已经在 hosts 中了，如果您还是想提交此 issue 中的条目的话，这边建议您进行一下分类并移除重复条目呢～

**Comment by P-256** [comment]
@GoogleHostsSupport 加一下吧，我来移除。顺便twitch得fix ip了

**Comment by GoogleHostsSupport** [comment]
@P-256 非常感谢～
这边先帮您做了一下格式修正，因为涉及的服务较多且情况各有不同，所以这边会在晚些时候分多个 pull request 进行处理，请知悉～

**Comment by GoogleHostsSupport** [comment]
这边追踪一下进度～

- [X] ARTE #358
- [X] Behance #351
- [X] Clyp #351
- [ ] CNA (SNI RST)
- [X] CD Universe #358
- [X] DailyView #358
- [X] SWI #358
- [X] Fastly #358
- [ ] TheTVDB (SNI RST)
- [X] Quora (SNI RST) #352
- [X] Pincong #358
- [X] BigGo #358
- [ ] Line
- [X] Doubi #378
- [X] Pubu #378
- [X] Matters.news #358
- [ ] Economist (SNI RST)
- [X] The Nation #358
- [ ] SCMP (SNI RST)
- [X] Foreign Policy #358
- [X] GreatFire #358
- [ ] Euro News (SNI RST)
- [X] Feedly #358
- [ ] Up Media (SNI RST)
- [X] rixCloud #358
- [ ] Bussiness Insider (SNI RST)
- [X] Uncyclopedia #378
- [ ] Japan Times (SNI RST)
- [X] SupChina #358
- [X] AbeBooks #358
- [ ] RawGit

**Comment by GoogleHostsSupport** [comment]
@P-256
不好意思让您久等了，您在本 issue 中提交的 hosts 条目已全部更新完毕～
因 review 时间较长，如有部分条目在此期间失效的情况，还请尽早提出～
如果没有异议的话，本 issue 将在 24 小时后作关闭处理～
