### ISSUE TITLE
host使用问题

### ISSUE THREAD

**Issue by KeithChou** [googlehosts/hosts#30]
现在的host可以用嘛 感觉copy paste之后用不到也:(

**Comment by lrinQVQ** [comment]
0.0可以丫 哪里不能用了咩

**Comment by KeithChou** [comment]
是我使用错误嘛 为什么在mac上paste host文件到电脑上 不能用呐

2017-09-02 17:12 GMT+08:00 lrin <notifications@github.com>:

**Comment by lrinQVQ** [comment]
咦是Chrome咩0.0

**Comment by chavyleung** [comment]
#27 我感觉跟我提的是同一个问题，可能还是区域或运营商问题

**Comment by ananas-xxj** [comment]
不管 pc 还是 手机 都没用。还有就是 tg 群怎么没有了。

**Comment by lrinQVQ** [comment]
TG群有呀 0.0是ncr咩

**Comment by lrinQVQ** [comment]
搜索主页的IP全数正常了咩0.0 你继续看看
