### ISSUE TITLE
能不能hosts文件不要用制表符 

### ISSUE THREAD

**Issue by ziyuedi** [googlehosts/hosts#300]
如题，制表符引起了批量修改时的很多问题，而且也不符合规范

**Comment by beyondgfw** [comment]
@ziyuedi 请说明具体有什么问题，否则只能认为是你的批量修改方式有问题。

> Each field is separated by white space – tabs are often preferred for historical reasons, but spaces are also used.

From https://en.wikipedia.org/wiki/Hosts_(file)

> Fields of the entry are separated by any number of blanks and/or tab characters.

From http://man7.org/linux/man-pages/man5/hosts.5.html

因此不存在不合规范的问题

**Comment by beyondgfw** [comment]
@beyondgfw test
