### ISSUE TITLE
微软账户管理页面

### ISSUE THREAD

**Issue by lychichem** [googlehosts/hosts#305]
### 是什么网站 / app 出现了问题？
accounts.microsoft.com

- [X] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [ ] 完全无法使用：

- [X] 部分无法使用：
页面由于一个脚本无法加载无法正常排版或提供正确功能，显示“抱歉，出现了一些问题”

### 您的运营商是？
陕西电信，chinaz测试结果：中/西部地区情况较差，东部情况较好

### 加载失败的资源地址
mwf-service.akamaized.net

### 封锁方式
- [ ] DNS 污染
- [ ] IP 封锁
- [ ] TCP Reset
- [X] 涉及到第三方服务：
使用了Akamai CDN

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方
104.100.93.8 mwf-service.akamaized.net #a1963.g2.akamai.net
# 请将 hosts 内容粘贴在此行上方
```

**Comment by 123ysys** [comment]
login.live.com 显示连接重置。

**Comment by lychichem** [comment]
@123ysys 你运营商是哪个？我这边感觉浙江移动网络情况很差

**Comment by 123ysys** [comment]
> @123ysys 你运营商是哪个？我这边感觉浙江移动网络情况很差

同是浙江移动，家里的网络根本打不开。但是刚刚用了公司的电信，似乎又是可以的。

**Comment by lychichem** [comment]
是的了，浙江移动的网络质量非常恶心，这边我不仅微软相关的站打不开，就连学术站点前两天也打不开。然而黄站还一如既往坚挺甚至更快了……

发自我的 iPhone

在 2019年4月23日，15:09，123ysys <notifications@github.com<mailto:notifications@github.com>> 写道：


@123ysys<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2F123ysys&data=02%7C01%7C%7C441e831a7c3e4a45a8df08d6c7ba94ba%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636916001496380410&sdata=ON%2BPIYOSplG6XJiWclvzofmvkLBSymAfivbSQavJX60%3D&reserved=0> 你运营商是哪个？我这边感觉浙江移动网络情况很差

同是浙江移动，家里的网络根本打不开。但是刚刚用了公司的电信，似乎又是可以的。

**Comment by 123ysys** [comment]
> 是的了，浙江移动的网络质量非常恶心，这边我不仅微软相关的站打不开，就连学术站点前两天也打不开。然而黄站还一如既往坚挺甚至更快了……
> 
> 发自我的 iPhone
> 
> 在 2019年4月23日，15:09，123ysys <notifications@github.com<mailto:notifications@github.com>> 写道：
> 
> 
> @123ysys<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2F123ysys&data=02%7C01%7C%7C441e831a7c3e4a45a8df08d6c7ba94ba%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636916001496380410&sdata=ON%2BPIYOSplG6XJiWclvzofmvkLBSymAfivbSQavJX60%3D&reserved=0> 你运营商是哪个？我这边感觉浙江移动网络情况很差
> 
> 同是浙江移动，家里的网络根本打不开。但是刚刚用了公司的电信，似乎又是可以的。
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgooglehosts%2Fhosts%2Fissues%2F305%23issuecomment-485671052&data=02%7C01%7C%7C441e831a7c3e4a45a8df08d6c7ba94ba%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636916001496390415&sdata=RW5TpDri7ibVRR9b1wBgfO60jd8kJajenDX3z2Sw6zw%3D&reserved=0>, or mute the thread<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACHCR3TP5R4O2YN6P3FSONLPR2YZJANCNFSM4GT5HQKA&data=02%7C01%7C%7C441e831a7c3e4a45a8df08d6c7ba94ba%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636916001496400414&sdata=FY9HEk%2F3m7Bur5u7Su2ZPmx8TNCocpsIDxWWcVC53ZY%3D&reserved=0>.

所以浙江移动这是什么骚操作😳？
