### ISSUE TITLE
rootexplorer 挂梯子无法连接gdrive

### ISSUE THREAD

**Issue by WhiCCX0** [googlehosts/hosts#306]
### 是什么网站 / app 出现了问题？

- [x] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [x] 完全无法使用：

- [ ] 部分无法使用：

### 封锁方式
- [ ] DNS 污染
- [x] IP 封锁
- [ ] TCP Reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方

# 请将 hosts 内容粘贴在此行上方
```

**Comment by WhiCCX0** [comment]
rootexplorer 挂梯子无法连接gdrive

**Comment by sxyoxygen** [comment]
你都挂梯子了，那和这个项目有什么联系:-\

**Comment by WhiCCX0** [comment]
那不是啊，我也不是全天挂梯子啊😯。。。

sxyoxygen <notifications@github.com> 于 2019年2月6日周三 21:35写道：

**Comment by beyondgfw** [comment]
@WhiCCX0 同问 难道是我阅读有问题(

**Comment by GoogleHostsSupport** [comment]
由于此 issue 时间过长，且无法复现，这边暂时做 close 处理哦。
如果还是有问题的话，欢迎继续评论～
