### ISSUE TITLE
补充下go.googlesource.com

### ISSUE THREAD

**Issue by zhangpy** [googlehosts/hosts#307]
### 是什么网站 / app 出现了问题？

- [ ] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [ ] 完全无法使用：

- [ ] 部分无法使用：

### 封锁方式
- [ ] DNS 污染
- [ ] IP 封锁
- [ ] TCP Reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方
108.177.127.82	go.googlesource.com
# 请将 hosts 内容粘贴在此行上方
```

**Comment by zhangpy** [comment]
换成shadowsocks解决这些问题

**Comment by GoogleHostsSupport** [comment]
由于这个域名目前确实不在 hosts 中，所以这边还是要 reopen 的哦～

**Comment by GoogleHostsSupport** [comment]
不好意思让您久等了，您在本 issue 中提交的 hosts 条目已更新完毕～
