### ISSUE TITLE
继续补域名~

### ISSUE THREAD

**Issue by SerCom-KC** [googlehosts/hosts#31]
~虽然群里面说过了233~
`www.googleapis.com` 重了（[第 551 行](https://github.com/googlehosts/hosts/blob/hosts-source/data/hosts.yml#L551) 和 [第 1115 行](https://github.com/googlehosts/hosts/blob/hosts-source/data/hosts.yml#L1115)）
建议增加 `chrome.google.com` （插件商店）
建议增加 `android.clients.google.com` （Android Google Play 相关）

**Comment by DDoSolitary** [comment]
我下次在ci里检测下重复域名吧。。

**Comment by lrinQVQ** [comment]
啊XD今天忙了一天

**Comment by zoujialing125** [comment]
从日志和网上搜索接过来看，play上不去的原因是这个打开play会被解析到这个地址services.googleapis.cn，所以上不去，麻烦下次这个也加进去

Reference: https://github.com/shadowsocks/shadowsocks-android/issues/1057

**Comment by lrinQVQ** [comment]
get

**Comment by lautis0503** [comment]
skia.googlesource.com

**Comment by SerCom-KC** [comment]
@zoujialing125 看了一下这个域名是解析到谷翔的0.0 难道说谷翔还没准备好？

**Comment by zoujialing125** [comment]
@SerCom-KC IP ping的通，但是确实手机上不去。。。我找了一个美国的发现一直连接超时。。

**Comment by SerCom-KC** [comment]
@zouzoujialing125 你所在地的那个域名解析的IP是多少？203.208开头就是谷翔，不是就是被污染了

**Comment by zoujialing125** [comment]
@SerCom-KC 是谷翔的，但是如果是默认不设置ip的话就提示“从服务器检索信息时出错[DF-DFERH-01]”

我刚刚找了个美国的ip 172.217.5.99，终于上去了。。不过速度比较慢

**Comment by SerCom-KC** [comment]
这样啊。这墙就有点猛了，境内干扰，又回到当年了233
我的机子现在连的仍然是 android.clients.google.com，不知道跟系统语言有没有关系，回头我再试试

**Comment by zoujialing125** [comment]
@SerCom-KC 好像是升级7.0的有些机器出这问题，搜到的帖子是华为的，但是我机器是三星的。

**Comment by SerCom-KC** [comment]
调了一下系统语言，新开了个国区账号，还是没能复现出新域名。也没发现 Play Service 有更新的样子……
@lrinQVQ 两个都加上去？

**Comment by lrinQVQ** [comment]
0.0估计得加 呼调整完服务器不行了XD

**Comment by lrinQVQ** [comment]
services.googleapis.cn 这个域名的要求有点高233 我晚上回来加
chrome.google.com 也有某些特殊要求233 可能拖一下

**Comment by zoujialing125** [comment]
https://github.com/Lerist/Go-Hosts
Go hosts的项目里到是包含的挺全的，不过貌似不够更新啊。。

**Comment by lrinQVQ** [comment]
XD 啊... 能不能别再这里提到别的项目啊XD 而且并不全真的...

**Comment by zoujialing125** [comment]
sorry...每太注意到这个。。哈哈，编辑掉了

**Comment by lrinQVQ** [comment]
31061001.googleapis.com 2333它并没有这个

**Comment by lrinQVQ** [comment]
没事XD 只是每次看到别人老提这个那个的 而且那个项目还是全用SNI的就很XD

**Comment by zoujialing125** [comment]
我就加了一个 172.217.5.99 services.googleapis.cn 后就能了，IP是我自己找的，就是比较慢

**Comment by SerCom-KC** [comment]
@lrinQVQ woc那啥域名233

**Comment by lrinQVQ** [comment]
services.googleapis.cn 我也做修复了的
那个域名以后要用到～～

**Comment by SerCom-KC** [comment]
再来一个 `drive-thirdparty.googleusercontent.com`

**Comment by lrinQVQ** [comment]
0.0 get
