### ISSUE TITLE
cloud.google.com  无法访问

### ISSUE THREAD

**Issue by QiTk** [googlehosts/hosts#312]
cloud.google.com  无法访问

- [x] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [x] 完全无法使用：

- [ ] 部分无法使用：

### 封锁方式
- [ ] DNS 污染
- [ ] IP 封锁
- [ ] TCP Reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方

# 请将 hosts 内容粘贴在此行上方
```

**Comment by sxyoxygen** [comment]
Google 相关已经遭到防火墙 SNI RST 级别待遇，如果急用请使用
https://github.com/googlehosts/hosts/wiki/实验室/
我们可能在将来的提交中修复

**Comment by jinyumarine** [comment]
@sxyoxygen 然而实验室已经挂了N久了

**Comment by beyondgfw** [comment]
@jinyumarine 近期将恢复ss-*解析 127.0.0.1是我们手动修改 此域名待修复

**Comment by GoogleHostsSupport** [comment]
@sxyoxygen 并非所有 Google 域名都有 SNI RST 哦～

我们目前暂时没有可用于修复该域名的 IP，还请耐心等待～

**Comment by lrinQVQ** [comment]
Get 开始慢慢修复issues
