### ISSUE TITLE
与ssr代理冲突？

### ISSUE THREAD

**Issue by Newchensheng** [googlehosts/hosts#314]
使用ssr代理正常 ，在代理环境下使用你们的hosts文件不正常打开Google 但可以打开推特

**Comment by lrinQVQ** [comment]
无法复现 目前hosts中的IP都指向了正确的地址
个人永久敌对ssr及其衍生,恕无法提供更多支持

**Comment by Newchensheng** [comment]
知道了 谢谢 😄
