### ISSUE TITLE
shadowsocks-qt5 连接错误

### ISSUE THREAD

**Issue by jasonlee3652** [googlehosts/hosts#315]
延迟显示错误。
我之前配置成功过，也能使用，现在不能使用了。访问谷歌，不会去加载，而是直接弹出‘无法访问此网站’。
我现在的配置：
1.ubuntu 16.4，已在设置 - 网络 - 手动将端口改为 127.0.0.1
2.启动shadowsocks-qt5 (Shadowsocks-Qt5-3.0.1-x86_64.AppImage)，扫描二维码，扫描完后将客户端中的本地端口也改成 127.0.0.1，其他信息都是扫描二维码自动填充的，我没改动。
3.链接。在连接的 '延迟'这一栏会显示错误。

**Comment by lrinQVQ** [comment]
我们正在对所有的公益服务器进行调整，Shadowsocks服务器将于2019年3月5日之前完成所有插件的调整和支持，届时将准时恢复。通过内部人员一致决定，我们希望正常情况下所有的公益服务器持续工作至2020年4月1日。

**Comment by Dealtz** [comment]
@lrinQVQ Wiki页面的服务器配置信息仍使用的是obfs-local混淆插件,请问何时更新v2ray-plugin 和 kcptun插件的配置?

**Comment by xcc23** [comment]
然鹅现在还没恢复？

**Comment by beyondgfw** [comment]
> 因为一些事情,我们的Shadowsocks服务器将延期一段时间

**Comment by jinyumarine** [comment]
@beyondgfw 维护好久了，头尾两年了，哈哈哈

**Comment by jinyumarine** [comment]
@lrinQVQ @beyondgfw 
看起来殷切盼望公益SS雄起
