### ISSUE TITLE
steam商店 RESET 

### ISSUE THREAD

**Issue by TinQlo** [googlehosts/hosts#317]
### 是什么网站 / app 出现了问题？
store.steampowered.com

- [X] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [X] 完全无法使用：
喜闻乐见的连接已重置
- [ ] 部分无法使用：

### 您的运营商是？
中国移动宽带

### 失效域名的 DNS 解析结果
23.50.18.229

### 封锁方式
- [ ] DNS 污染
- [ ] IP 封锁
- [X] TCP Reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方
store.steampowered.com 23.213.99.129
# 请将 hosts 内容粘贴在此行上方
```

**Comment by 123ysys** [comment]
我这里暂时可用，但是陕西地区似乎超时。

**Comment by TinQlo** [comment]
什么情况。。。怎么突然好了。 GFW玩我呢

**Comment by 123ysys** [comment]
> 什么情况。。。怎么突然好了。 GFW玩我呢

也许是抽风了，也许只是提前试验一下。

**Comment by 123ysys** [comment]
现在全国范围大规模RST。

**Comment by imba-tjd** [comment]
> 
> 
> 现在全国范围大规模RST。

Steam吧一片和平

**Comment by sxyoxygen** [comment]
23.50.18.229 的确不可用
我这边解析 104.99.107.130 是 OK 的

**Comment by ICHx** [comment]
教育網，兩個都ping得通

**Comment by P-256** [comment]
> 现在全国范围大规模RST。
23.50.18.229被Reset，steam倒没事。毕竟还愿自己已经改素材了没必要杀一儆百
