### ISSUE TITLE
最新的hosts还是无法打开google的一些网址，

### ISSUE THREAD

**Issue by anzigcom** [googlehosts/hosts#32]
您好，

最新的hosts还是无法打开google的一些网址，IP地址还是很多有问题啊！

**Comment by lrinQVQ** [comment]
0.0比如 举个列子咩

**Comment by Dcfm** [comment]
@lrinQVQ 哥，有使用教程不？不会用啊~

**Comment by lrinQVQ** [comment]
咩0.0什么平台

**Comment by Dcfm** [comment]
@lrinQVQ `linux` 额，运行哪个脚本啊~

**Comment by zoujialing125** [comment]
谷歌网站，谷歌PLAY商店还是上不去。安卓手机，电脑没测

**Comment by lrinQVQ** [comment]
play还没处理 https://www.google.com/ncr可以用嘛

**Comment by lrinQVQ** [comment]
@Dcfm LInux啊咩 sudo cp -r hosts /etc/hosts

**Comment by zoujialing125** [comment]
@lrinQVQ 我换了个DNS服务器可以用浏览器上google搜索了。但是Play还是不行，Play需要什么特殊设置么

**Comment by lrinQVQ** [comment]
咦估计有些域名还没添加XD 到时候加上

**Comment by zoujialing125** [comment]
@lrinQVQ 这就奇怪了，我用的Daedalus这个软件不设置DNS服务器就登不上。。

**Comment by zoujialing125** [comment]
108.177.120.94 貌似是因为这个IP 挂了，ping不通了

**Comment by lrinQVQ** [comment]
soga 预计今晚会更新一波ip

**Comment by lrinQVQ** [comment]
这两天事情不少XD有点忙

**Comment by digicolor** [comment]
ncr可以 但是.hk不行，gmail也不行

**Comment by lrinQVQ** [comment]
gmail已经全国大半正常所以删除 目前只是完美适配ncr .hk之类一会继续XD
