### ISSUE TITLE
google.com.hk无法访问，可ping通

### ISSUE THREAD

**Issue by shiyue2002** [googlehosts/hosts#322]
### 是什么网站 / app 出现了问题？
www.google.com.hk

- [X] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [X] 完全无法使用：
ERR_QUIC_PROTOCOL_ERROR
- [ ] 部分无法使用：

### 您的运营商是？
上海电信

### 失效域名的 DNS 解析结果
172.217.160.0

### 封锁方式
- [ ] DNS 污染
- [ ] IP 封锁
- [ ] TCP Reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方

# 请将 hosts 内容粘贴在此行上方
```

**Comment by eyelivermore** [comment]
完全无法使用：
ERR_QUIC_PROTOCOL_ERROR

中国联通运营商

**Comment by warlord1989** [comment]
我这里也不行了，前几天还可以的，怎么回事呢？

**Comment by P-256** [comment]
同。
长沙电信
浏览器版本chrome 72.0.3626.109
换IP前后都不能用

**Comment by jinyumarine** [comment]
+1
杭州电信
无法访问此网站 网址为 https://www.google.com.hk/ 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。

**Comment by miaomiaosoft** [comment]
QUIC已经能被GFW屏蔽了

**Comment by GoogleHostsSupport** [comment]
> QUIC已经能被GFW屏蔽了

确实可以这么认为呢～虽然不像 TLS 1.2，GFW 仍然无法对 QUIC 进行针对性阻拦～
更准确地说，是 GFW 最近针对基于 UDP 协议进行了升级，目前所有利用 UDP 翻墙的手段都可能会受到干扰，特别是在针对 QUIC 方面会阻断 UDP 443 端口的连接～

**Comment by 123ysys** [comment]
> > QUIC已经能被GFW屏蔽了
> 
> 确实可以这么认为呢～虽然不像 TLS 1.2，GFW 仍然无法对 QUIC 进行针对性阻拦～
> 更准确地说，是 GFW 最近针对基于 UDP 协议进行了升级，目前所有利用 UDP 翻墙的手段都可能会受到干扰，特别是在针对 QUIC 方面会阻断 UDP 443 端口的连接～

如果是这样的话，我们如何确认是否可以继续通过修改hosts的手段来达到翻墙的目的呢？首先GFW不能有效拦截QUIC协议，但是却可以干扰QUIC的基础UDP。
应该说，QUIC是我们接下来的最主要的法宝了，在尚不明确各网站何时完成适配的情况下被GFW抢先了一步，不知会不会对我们有什么影响？

**Comment by JimmyJLNU** [comment]
我这里不是这个样子，172.217.160.0不可PING通，更换成google官方的其它IP地址（如：172.217.16*.***）在HTTPS条件下可PING通，但仍然打不开网页，提示连接被重置而非超时。吉林省电信和联通均如此（SNI）

**Comment by GoogleHostsSupport** [comment]
@JimmyJLNU 
> 无论用HTTP还是HTTPS，提示连接被重置，而非超时。

这是因为您没有强制使用 QUIC 进行连接呢～
请注意本项目已经放弃基于 TLS 1.2/1.3 的修复方案了哦～

**Comment by eyelivermore** [comment]
更新了3月9日的hosts文件 还是显示 

无法访问此网站 网址为 https://www.google.com.hk/ 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_QUIC_PROTOCOL_ERROR

请问有什么解决办法吗?

**Comment by JimmyJLNU** [comment]
@GoogleHostsSupport 最新测试结果：吉林联通，使用QQ浏览器极速内核，在chrome://flags 中强制开启QUIC功能，仍然然并卵，提示连接重置。

**Comment by GoogleHostsSupport** [comment]
@eyelivermore 我们还在讨论对策哦，还请您继续耐心等待～

@JimmyJLNU 我们不支持除 Google Chrome 官方最新正式版以外的浏览器哦（即便是使用 Chromium 内核的浏览器，我们也不作可用性保证），此外您还需要使用命令行参数启动才会有强制效果呢，烦请您仔细阅读我们的 [wiki 说明](https://github.com/googlehosts/hosts/wiki/Google-Chrome-QUIC-%E7%99%BD%E5%90%8D%E5%8D%95%E6%B7%BB%E5%8A%A0%E6%96%B9%E6%B3%95)～

**Comment by railjty** [comment]
3.24江西移动，ERR_QUIC_PROTOCOL_ERROR

**Comment by railjty** [comment]
主要还是V2Ray，SS这些工具加入的QUIC混淆，导致Firewall升级干扰UDP

**Comment by liuxinyu970226** [comment]
issue 368告诉我这事现在有可能出现奇迹了，某些特定的Android是可以用的

**Comment by a76854** [comment]
陕西电信google.com.hk也挂了

**Comment by GoogleHostsSupport** [comment]
@a76854 本 issue 现已合并至 #274 处理了哦，还请在那里反馈～
