### ISSUE TITLE
公益代理服务器全挂了！

### ISSUE THREAD

**Issue by JimmyJLNU** [googlehosts/hosts#323]
@lrinQVQ  @GoogleHostsSupport
**紧急情况！公益代理服务器全挂了！**
**吉林省四平市 联通 TCPING 结果！**
> C:\Users\Lenovo>tcping64 ss-1.googlehosts.org 2337
> 
> Probing 23.226.136.24:2337/tcp - No response - time=2002.394ms
> Probing 23.226.136.24:2337/tcp - No response - time=2002.541ms
> Probing 23.226.136.24:2337/tcp - No response - time=2001.953ms
> Probing 23.226.136.24:2337/tcp - No response - time=2000.921ms
> 
> Ping statistics for 23.226.136.24:2337
>      4 probes sent.
>      0 successful, 4 failed.
> Was unable to connect, cannot provide trip statistics.
> 
> C:\Users\Lenovo>tcping64 ss-1.googlehosts.org 2333
> 
> Probing 23.226.136.24:2333/tcp - No response - time=2002.932ms
> Probing 23.226.136.24:2333/tcp - No response - time=2001.062ms
> Probing 23.226.136.24:2333/tcp - No response - time=2001.544ms
> Probing 23.226.136.24:2333/tcp - No response - time=2002.102ms
> 
> Ping statistics for 23.226.136.24:2333
>      4 probes sent.
>      0 successful, 4 failed.
> Was unable to connect, cannot provide trip statistics.
> 
> C:\Users\Lenovo>tcping64 ss-2.googlehosts.org 2334
> 
> Probing 23.226.136.132:2334/tcp - No response - time=2002.639ms
> Probing 23.226.136.132:2334/tcp - No response - time=2004.985ms
> Probing 23.226.136.132:2334/tcp - No response - time=2001.974ms
> Probing 23.226.136.132:2334/tcp - No response - time=2001.498ms
> 
> Ping statistics for 23.226.136.132:2334
>      4 probes sent.
>      0 successful, 4 failed.
> Was unable to connect, cannot provide trip statistics.
> 
> C:\Users\Lenovo>tcping64 ss-3.googlehosts.org 2334
> 
> Probing 185.22.152.42:2334/tcp - No response - time=2003.012ms
> Probing 185.22.152.42:2334/tcp - No response - time=2000.746ms
> Probing 185.22.152.42:2334/tcp - No response - time=2000.999ms
> Probing 185.22.152.42:2334/tcp - No response - time=2001.478ms
> 
> Ping statistics for 185.22.152.42:2334
>      4 probes sent.
>      0 successful, 4 failed.
> Was unable to connect, cannot provide trip statistics.
> 
> C:\Users\Lenovo>tcping64 ss-4.googlehosts.org 2333
> 
> Probing 167.88.163.163:2333/tcp - No response - time=2002.580ms
> Probing 167.88.163.163:2333/tcp - No response - time=2001.699ms
> Probing 167.88.163.163:2333/tcp - No response - time=2001.027ms
> Probing 167.88.163.163:2333/tcp - No response - time=2002.016ms
> 
> Ping statistics for 167.88.163.163:2333
>      4 probes sent.
>      0 successful, 4 failed.
> Was unable to connect, cannot provide trip statistics.
> 
> C:\Users\Lenovo>tcping64 ss-4.googlehosts.org 2337
> 
> Probing 167.88.163.163:2337/tcp - No response - time=2003.748ms
> Probing 167.88.163.163:2337/tcp - No response - time=2000.714ms
> Probing 167.88.163.163:2337/tcp - No response - time=2001.195ms
> Probing 167.88.163.163:2337/tcp - No response - time=2001.860ms
> 
> Ping statistics for 167.88.163.163:2337
>      4 probes sent.
>      0 successful, 4 failed.
> Was unable to connect, cannot provide trip statistics.
> 
> C:\Users\Lenovo>tcping64 ss-4.googlehosts.org 2336
> 
> Probing 167.88.163.163:2336/tcp - No response - time=2002.394ms
> Probing 167.88.163.163:2336/tcp - No response - time=2000.832ms
> Probing 167.88.163.163:2336/tcp - No response - time=2000.510ms
> Probing 167.88.163.163:2336/tcp - No response - time=2001.955ms
> 
> Ping statistics for 167.88.163.163:2336
>      4 probes sent.
>      0 successful, 4 failed.
> Was unable to connect, cannot provide trip statistics.

**Comment by P-256** [comment]
我这里湖南电信四个都可以ping成功同时直接访问也没问题

**Comment by ychao661** [comment]
江苏南京也挂了

**Comment by xcc23** [comment]
坐标湖南
全挂了

**Comment by GoogleHostsSupport** [comment]
因为 Shadowsocks 的依赖之一 libsodium 的代码出现了一些变动，导致 Shadowsocks 无法正常工作，所以目前确实有一些服务器是不可用的哦，非常抱歉呢～

**Comment by P-256** [comment]
> 我这里湖南电信四个都可以ping成功同时直接访问也没问题

现在也挂了

**Comment by wolfan** [comment]
大会都开完了，还无法恢复……
只能说明是墙又高了，哭。

**Comment by GoogleHostsSupport** [comment]
@wolfan 这次是我们这边的问题哦，并不是服务器被封锁了～
由于我们的运维近期比较忙，所以可能需要较长时间才能恢复呢，敬请谅解～

**Comment by wolfan** [comment]
@GoogleHostsSupport 可是为什么我的SS还是用不上呐。。。感觉墙确实又高了……

**Comment by P-256** [comment]
> @GoogleHostsSupport 可是为什么我的SS还是用不上呐。。。感觉墙确实又高了……

最近没啥大动作，只有QUIC被干扰和imgur被加入SNI阻断名单，但最近墙CDN网站比较多

**Comment by GoogleHostsSupport** [comment]
本项目的公益 Shadowsocks 代理服务器目前已经开始恢复了哦，请大家再测试一下，没有大问题的话这边会在稍晚时间关闭此 issue～

**Comment by wolfan** [comment]
Android版telegram 怎么使用MTProto呐？

**Comment by GoogleHostsSupport** [comment]
@wolfan
请移步[实验室页面](https://github.com/googlehosts/hosts/wiki/%E5%AE%9E%E9%AA%8C%E5%AE%A4#telegram-mtproto)哦，有详细说明的呢～
另外需要特别指出的是，中国大陆区域由于 GFW 的针对性封锁，目前仅 7 号服务器可用，**此服务器为中国大陆境内的中转服务器**，还请留意～

本 issue 主要针对 Shadowsocks 服务器，由于目前暂时没有出现较大的异常状况，这边先关闭 issue 了～
