### ISSUE TITLE
一个轻量级的防止 TCP RST 的实现

### ISSUE THREAD

**Issue by LGA1150** [googlehosts/hosts#329]
[netfilter-spooftcp](https://github.com/LGA1150/netfilter-spooftcp)
这是我去年开始写的一个 Linux 内核模块，原本是想替换 SNI，之后发现会导致 TLS 握手失败，于是想到了更底层的方法
原理来自 [INTANG](https://github.com/seclab-ucr/INTANG)
纯内核态，占用小，4M ROM+32M RAM 路由器都可以轻松运行起来
支持 IPv4 和 IPv6
```
root@OpenWrt:~# lsmod |grep ^xt_SPOOFTCP
xt_SPOOFTCP             3664  3
```
规则配置好后，除非网络环境改变（包括墙升级、更换 ISP 等），可以说是一劳永逸

在 NAT 网关运行要给内核打[补丁](https://github.com/LGA1150/iptables-raw-POSTROUTING)以加入 raw 表 POSTROUTING 链，重新编译内核；在客户端或在非 NAT 的路由器上则不用

**Comment by GoogleHostsSupport** [comment]
这边建议您前往 #87 或 #131 进行讨论呢。
由于您的 issue 内容与本项目并非直接相关，因此这边暂时先 close 处理，敬请谅解～

**Comment by beyondgfw** [comment]
@LGA1150 0.0想法挺好的欸给你点赞～

**Comment by beyondgfw** [comment]
@GoogleHostsSupport 有关的啦x哪里无关啦

**Comment by beyondgfw** [comment]
@LGA1150 不过曾经我也想过类似的方法 那个时候我自己的测试在一些地区没有成功(均为非NAT网关环境),待我多测试一下

**Comment by kotori2** [comment]
@LGA1150 貌似这个对于教育网v6用处不是很大吧，毕竟封IP直接黑洞

**Comment by beyondgfw** [comment]
@kotori2 嘛 部分v6 ip的路由并非显式路由 无法被单纯的黑洞路由

**Comment by beyondgfw** [comment]
@beyondgfw 曾经也有人提到过类似的拼包的方案,我都做过一定测试,并非所有情况都不对后续的数据包进行检测,所以 这也差不多是一个治根不治本的方案,但是想法值得赞同,并且暂时也应该在部分区域可用
