### ISSUE TITLE
gmail smtp/imap 可用的IP

### ISSUE THREAD

**Issue by kouheikouhei** [googlehosts/hosts#330]
最新的HOST中已经移除了gmail的smtp/imap/pop的对应ip地址。
目前是否有这些对应可用的IP地址？

**Comment by beyondgfw** [comment]
@kouheikouhei 大多数SMTP/IAMP/POP的地址都没有被污染/屏蔽 所以我们于很早就已经移除这类地址

**Comment by kouheikouhei** [comment]
@beyondgfw 最近重装了电脑并忘记备份之前HOSTS，OUTLOOK无法正常收发gmail。之后尝试了下用历史中早期的HOSTS中的SMTP/IMAP/POP地址也无法正常收发。

**Comment by beyondgfw** [comment]
@kouheikouhei 0.0尝试复现

**Comment by kouheikouhei** [comment]
@beyondgfw 那两种情况都再尝试下，感觉您的答复！谢谢！
