### ISSUE TITLE
DeviantArt被DNS污染

### ISSUE THREAD

**Issue by HashLiver** [googlehosts/hosts#331]
### 是什么网站 / app 出现了问题？

- [X] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [X] 完全无法使用：

- [ ] 部分无法使用：

### 您的运营商是？
湖南电信

### 加载失败的资源地址
*.deviantart.com
*.deviantart.net

### 失效域名的 DNS 解析结果
Windows上使用nslookup命令发现被解析至Facebook IP

### 封锁方式
- [X] DNS 污染
- [ ] IP 封锁
- [ ] TCP Reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方
52.85.220.219	deviantart.com
52.85.220.244	www.deviantart.com
54.70.219.228	deviantart.net
99.84.104.122	st.deviantart.net
99.84.104.23	a.deviantart.net
99.84.104.59	e.deviantart.net
99.84.104.59	i.deviantart.net
# 请将 hosts 内容粘贴在此行上方
```

**Comment by HashLiver** [comment]
追加：
```
52.84.150.14	pre00.deviantart.net
99.84.254.116	orig00.deviantart.net
99.84.254.32	t00.deviantart.net
```

**Comment by liuweihang-2019** [comment]
PLEASE HELP DEVIANTART IN CHINA?QAQ

**Comment by lrinQVQ** [comment]
Get

**Comment by liuweihang-2019** [comment]
DA站到3月20日那天下午就不能访问了

**Comment by liuweihang-2019** [comment]
要等到什么时候才恢复访问啊...TAT

**Comment by 123ysys** [comment]
可能需要有csc资源。

**Comment by beyondgfw** [comment]
0.0 感谢

**Comment by 123ysys** [comment]
@liuweihang-2019 怎么把自己的隐私暴露出来了呢？
@lrinQVQ 毕竟GFW不会自废武功lol。

**Comment by lrinQVQ** [comment]
> @liuweihang-2019 怎么把自己的隐私暴露出来了呢？
> @lrinQVQ 毕竟GFW不会自废武功lol。

2333对啊

**Comment by 123ysys** [comment]
> @liuweihang-2019 怎么把自己的隐私暴露出来了呢？
> @lrinQVQ 毕竟GFW不会自废武功lol。
> 
> 2333对啊
> 我帮他直接删掉了

其实像这种黑名单的话，日亚应该也是误伤的吧？毕竟我是真的想不出一个购物网站有什么被封的必要。
像niconico那样的主动解封，毕竟是少数。

**Comment by beyondgfw** [comment]
@123ysys 对啊x很惨

**Comment by 123ysys** [comment]
@liuweihang-2019 所以说不太会是误伤了啊lol

**Comment by P-256** [comment]
> 0.0 感谢

今天又换IP了，麻烦fix一下
```
52.85.154.83	deviantart.com
52.85.154.131	www.deviantart.com
```

**Comment by liuweihang-2019** [comment]
我不会FIX...

**Comment by 960PRO** [comment]
别忘记在hosts里添加deviantart图片服务器的IP地址！
13.35.8.105     images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com
