### ISSUE TITLE
最近一个月为什么不能访问www.google.com.hk

### ISSUE THREAD

**Issue by VinsonChiu** [googlehosts/hosts#332]
用最新的hosts也显示

无法访问此网站 
网址为 https://www.google.com.hk/ 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_QUIC_PROTOCOL_ERROR

**Comment by beyondgfw** [comment]
@VinsonChiu 因为UDP 443端口被大量屏蔽

**Comment by liuxinyu970226** [comment]
话说谁给标记一下duplicate？

**Comment by sxyoxygen** [comment]
#322
