### ISSUE TITLE
无法访问www.google.com

### ISSUE THREAD

**Issue by qazgqr** [googlehosts/hosts#334]
### 是什么网站 / app 出现了问题？

- [x] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [x] 完全无法使用：

- [ ] 部分无法使用：

### 封锁方式
- [ ] DNS 污染
- [ ] IP 封锁
- [ ] TCP Reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方

# 请将 hosts 内容粘贴在此行上方
```

**Comment by GoogleHostsSupport** [comment]
关于 Google 的情况，请注意阅读[常见问题第一条](https://github.com/googlehosts/hosts/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E8%BF%99%E4%B8%AAhosts%E4%B8%80%E7%82%B9%E7%94%A8%E9%83%BD%E6%B2%A1%E6%9C%89%E5%8D%8A%E5%81%9C%E6%9B%B4%E6%98%AF%E4%BB%80%E4%B9%88%E6%84%8F%E6%80%9D)哦～
由于这个问题已经有其他 issue 在跟踪了，所以为避免重复，这边要关闭此 issue 了呢，还请理解～

**Comment by GoogleHostsSupport** [comment]
Duplicate of #274.
