### ISSUE TITLE
9gag 求host

### ISSUE THREAD

**Issue by willshion** [googlehosts/hosts#336]
### 是什么网站 / app 出现了问题？

- [ ] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [ ] 完全无法使用：

- [ ] 部分无法使用：

### 封锁方式
- [ ] DNS 污染
- [ ] IP 封锁
- [ ] TCP Reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方

# 请将 hosts 内容粘贴在此行上方
```

**Comment by 123ysys** [comment]
似乎已经RST。

**Comment by GoogleHostsSupport** [comment]
@123ysys 这边的测试结果是目前只有 DNS 污染呢～不过还是感谢您协助测试～

**Comment by beyondgfw** [comment]
7f0b5e3c164bfad2abce719a311aefe65c26151a
