### ISSUE TITLE
关于 Gmail IMAP

### ISSUE THREAD

**Issue by ElfSundae** [googlehosts/hosts#34]
上海，长城宽带。

我这边的情况是，用了这个 hosts 之后，Mac 自带的邮件程序就无法连接 Gmail 了，不用 hosts 的话 IMAP 能连接， SMTP 时好时坏。现在我每次更新完 hosts 后要把 Gmail IMAP 全注释掉：
```
googlemail-imap.l.google.com
imap.googlemail.com
gmail-imap.l.google.com
imap.gmail.com
```
想问下是不是 IMAP 没被河蟹？ 不知道别人是什么情况，我的想法是如果大部分地区都能正常连接 IMAP 的话这个 hosts 就没必要加 IMAP 了，因为加了反而会让正常的连接不上...

**Comment by ElfSundae** [comment]
我没试过 POP ，不了解情况

**Comment by lrinQVQ** [comment]
soga 0.0我确定下

**Comment by lrinQVQ** [comment]
可以移除了2333 没问题的

**Comment by ElfSundae** [comment]
👍

**Comment by lrinQVQ** [comment]
貌似GMAIL全部都正常欸

**Comment by ElfSundae** [comment]
我这边是 IMAP 一直正常，SMTP 时好时坏，不过大多时间是正常的。

**Comment by lrinQVQ** [comment]
soga~我看下如果影响不大就全删了

**Comment by ElfSundae** [comment]
嗯

**Comment by lrinQVQ** [comment]
直接移除了
