### ISSUE TITLE
寻求帮助，先行谢谢。

### ISSUE THREAD

**Issue by missmin1949** [googlehosts/hosts#340]
比较喜欢研究足彩，但这个网站无法打开，不知道hosts能不能解决这个问题。研究了挺久，都不知道如何得到真实的ip....，麻烦了，谢谢。

http://football.on.cc/cnt/recommend/tipa/20190418/fbtipa0101x0.html

**Comment by sxyoxygen** [comment]
该网站没有被 DNS 污染，https 连接会自动跳转 http，而 http 下被 RST 了...@beyondgfw

**Comment by missmin1949** [comment]
那应该是没有办法了对吧，谢谢。

**Comment by 123ysys** [comment]
@sxyoxygen 试过强制https了吗？

**Comment by missmin1949** [comment]
试过了，但是没有用，恢复成http://谢谢



------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>; 
发送时间: 2019年4月20日(星期六) 下午2:02
收件人: "hosts"<hosts@noreply.github.com>; 
抄送: "卍虚空藏卍"<712118188@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [googlehosts/hosts] 寻求帮助，先行谢谢。 (#340)




@sxyoxygen 试过强制https了吗？
