### ISSUE TITLE
部分语言wikipedia疑似被dns投毒

### ISSUE THREAD

**Issue by jimmyshjj** [googlehosts/hosts#342]
### 是什么网站 / app 出现了问题？
en.wikipedia.org
en.m.wikipedia.org 等

- [X] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [X] 完全无法使用：

- [ ] 部分无法使用：

### 您的运营商是？
上海电信

### 失效域名的 DNS 解析结果
60.220.149.32

### 封锁方式
- [X] DNS 污染
- [ ] IP 封锁
- [ ] TCP Reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方
198.35.26.96
# 请将 hosts 内容粘贴在此行上方
```

**Comment by 123ysys** [comment]
包括官网首页 www.wikipedia.org

**Comment by P-256** [comment]
湖南电信，测试已被投毒。目前没有SNI RST但估计和之前欧洲新闻台等一样会先DNS污染然后过个几周开始SNI RST

**Comment by 123ysys** [comment]
> 湖南电信，测试已被投毒。目前没有SNI RST但估计和之前欧洲新闻台等一样会先DNS污染然后过个几周开始SNI RST。另：文言文、藏文、客家、闽南、闽东、赣语版也被投毒
> PS：疑似是打算封锁通过证书缓存来访问中文日文版

证书缓存早就行不通了呀？

**Comment by P-256** [comment]
chrome还是可以用的。

**Comment by 123ysys** [comment]
> chrome还是可以用的。

仅仅是官网首页可行。

**Comment by liuxinyu970226** [comment]
直接说除首页外所有语言版本都被干了，不信可以https://ace.wikipedia.org/ （亚齐语版）试验下

**Comment by jimmyshjj** [comment]
> 直接说除首页外所有语言版本都被干了，不信可以https://ace.wikipedia.org/ （亚齐语版）试验下

不是吗 aa.wikipedia.org也是（一个很早以前被关站的维基百科语言站点）

**Comment by P-256** [comment]
> 直接说除首页外所有语言版本都被干了，不信可以https://ace.wikipedia.org/ （亚齐语版）试验下

首页也被干了。

**Comment by P-256** [comment]
> > chrome还是可以用的。
> 
> 仅仅是官网首页可行。
我这里英文跳转还ok

**Comment by mraandtux** [comment]
我之前在#248 有发过pcap包，晚点发新的
附GreatFire测试结果
https://zh.greatfire.org/https/en.wikipedia.org
https://zh.greatfire.org/https/en.m.wikipedia.org
(Death to GFuckW!)

**Comment by beyondgfw** [comment]
@mraandtux 非常感谢啦 我大概知道什么情况 但可能需要晚一点处理

**Comment by Calliston3** [comment]
注:似乎所有语言的Wikipedia都已经被SNI Reset 了。。

**Comment by mraandtux** [comment]
Jimbo：封我网站者，虽远必诛！
[wiki424.zip](https://github.com/googlehosts/hosts/files/3112059/wiki424.zip)

**Comment by liuxinyu970226** [comment]
[issue 248](https://github.com/googlehosts/hosts/issues/248)哪个合并到那个呢，看来问题一样了

**Comment by liuxinyu970226** [comment]
功夫网好大的胆子，刚更新完[Help:如何访问维基媒体旗下项目](https://meta.wikimedia.org/wiki/Help:%E5%A6%82%E4%BD%95%E8%AE%BF%E9%97%AE%E7%BB%B4%E5%9F%BA%E5%AA%92%E4%BD%93%E6%97%97%E4%B8%8B%E9%A1%B9%E7%9B%AE)，马上给我SNI掉元维基，难不成天津是SNI封网的先锋基地？

**Comment by jimmyshjj** [comment]
> [issue 248](https://github.com/googlehosts/hosts/issues/248)哪个合并到那个呢，看来问题一样了

合并过去吧 既然现在都是SNI RST 了

**Comment by P-256** [comment]
@liuxinyu970226 元维基我这没事。另：SNI RST要部署基本上是一起部署。长城的主要节点是北京上海广州，另外有几个走狗:哈工大专属实验室 360 腾讯（不负责技术但收集ssr信息和聊天记录）

**Comment by P-256** [comment]
@GoogleHostsSupport 请加http3标签

**Comment by liuxinyu970226** [comment]
所以到底哪个issue合并到哪个啊？

**Comment by mraandtux** [comment]
> 长城的主要节点是北京、上海、广州，另外有几个走狗：哈工大专属实验室、360、腾讯······

深圳也有节点，见我的pcap文件

**Comment by GoogleHostsSupport** [comment]
@liuxinyu970226 此 issue 将合并至 #248 跟踪处理哦～
再次感谢大家协助测试～

**Comment by billchenchina** [comment]
https://commons.wikimedia.org 还能上
