### ISSUE TITLE
动漫花园

### ISSUE THREAD

**Issue by P-256** [googlehosts/hosts#350]
### 是什么网站 / app 出现了问题？
动漫花园

- [X] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [X] 完全无法使用：

- [ ] 部分无法使用：

### 您的运营商是？
湖南电信

### 加载失败的资源地址
dmhy.org

### 封锁方式
- [X] DNS 污染
- [ ] IP 封锁
- [ ] IP reset
- [ ] SNI reset
- [X] 涉及到第三方服务：Cloudflare

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方
# DMHY Start
104.25.27.31	dmhy.org
104.25.27.31	www.dmhy.org
104.25.27.31	share.dmhy.org
104.25.27.31	bbs.dmhy.org
104.25.27.31	dl.dmhy.org
104.25.27.31	u2.dmhy.org
# DMHY End
# 请将 hosts 内容粘贴在此行上方
```

**Comment by GoogleHostsSupport** [comment]
@P-256
不好意思让您久等了，您在本 issue 中提交的 hosts 条目已全部更新完毕～
因 review 时间较长，如有部分条目在此期间失效的情况，还请 reopen 后提出～

**Comment by ConnorSu** [comment]
友情提醒，如果是U2站，tracker无法工作，采用本方法，还应加上
104.25.27.31  tracker.dmhy.org
