### ISSUE TITLE
如何使用

### ISSUE THREAD

**Issue by lvchakele** [googlehosts/hosts#353]
谁能告诉我这个hosts-file 怎么使用？

**Comment by Ir1d** [comment]
https://github.com/googlehosts/hosts/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by beyondgfw** [comment]
请不要做伸手党

**Comment by GoogleHostsSupport** [comment]
@lvchakele
**hosts 是一个系统文件**，如果您不了解如何替换这个文件以及**可能存在的风险**，您可能不适合使用 hosts 呢～
而且，就[目前的情况](https://github.com/googlehosts/hosts/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E8%BF%99%E4%B8%AAhosts%E4%B8%80%E7%82%B9%E7%94%A8%E9%83%BD%E6%B2%A1%E6%9C%89%E5%8D%8A%E5%81%9C%E6%9B%B4%E6%98%AF%E4%BB%80%E4%B9%88%E6%84%8F%E6%80%9D)而言，**使用 hosts 很可能无法满足您的需求**哦～
如果您确实需要使用 hosts，还请您移步[常见问题页面](https://github.com/googlehosts/hosts/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#hosts-files%E6%96%87%E4%BB%B6%E5%A4%B9%E9%87%8C%E6%9C%89%E5%A5%BD%E5%A4%9A%E6%96%87%E4%BB%B6%E6%88%91%E5%BA%94%E8%AF%A5%E7%94%A8%E5%93%AA%E4%B8%80%E4%B8%AA)了解本项目各种 hosts 文件的说明～
