### ISSUE TITLE
墙是分省份的了？

### ISSUE THREAD

**Issue by ApolloRoad** [googlehosts/hosts#36]
最新的我这里杭州不可以用，Google大部分都不行，墙是分省份的了？
去年的却可以用。我整理了我这里Google全部可以用的，YouTube可以播放视频

**Comment by lrinQVQ** [comment]
差不多是这样昂 不过我现在在用新方案 目前确保了搜索主页 和 www.youtube.com的可用性

**Comment by onplus** [comment]
是各地运营商自己加规则。
总不能全在那几个出口做处理

**Comment by HelloBerserker** [comment]
同一个host，现在我的电脑电信宽带能用，联通宽带不能用。

**Comment by lrinQVQ** [comment]
2333神奇的运营商区别了

**Comment by digicolor** [comment]
同杭州 不能用youtube、gmail、google hk..杭州电信

**Comment by lrinQVQ** [comment]
0.0 Youtube应该不会啊
gmail待分流
google gk待分流
google ncr应该无压力

**Comment by digicolor** [comment]
可能是 www.youtube.com 这个ip的问题，如果用m.youtube.com，手机端是可以访问的，而且ping的通，但是用www.youtube.com，手机端不能访问，surge看 应该ip没ping通，但是电脑端2个ip都能ping通，但是不论是m，还是www，都不能上

**Comment by lrinQVQ** [comment]
看来443不通昂 换ip吧到时候

**Comment by zhuweijia** [comment]
最新的，杭州移动，YouTube可以啊，还可以看视频卧槽，谷歌也是正常的

**Comment by lrinQVQ** [comment]
Youtube视频肯定正常啦 有不正常的报下域名
Google ncr5天未翻车了

**Comment by zhuweijia** [comment]
我记得以前改hosts不是不能看YouTube视频的吗，难道跟IP地址有关。。。话说老哥，twitter是不是没戏了

**Comment by lrinQVQ** [comment]
咩其实Youtube的视频地址1.被DNS污染 2.有些地址的资源是通用的 所以有时候一个地址可用另外一个地址也可以使用同样的IP3.Youtube在播放视频时会不断通过redirector.googlevideo.com的解析获取新的地址,这种尝试是不间断的尝试,而且还会更新到包含同样资源的相同地址,如果用hping3 -S -p 443 TCP查询443端口这些地址大多能在第N次连接后连上一次这样就行了咩 or 尝试QUIC连接 or 尝试连接到新协议服务器

**Comment by lrinQVQ** [comment]
推特的话2333 只是封锁了ARIN美国段的推特 欧洲那边的还在考虑是否放出来

**Comment by lrinQVQ** [comment]
https://github.com/googlehosts/hosts/issues/48
