### ISSUE TITLE
kadokawa系列加进去可好？

### ISSUE THREAD

**Issue by liuxinyu970226** [googlehosts/hosts#360]
### 是什么网站 / app 出现了问题？
www.kadokawa.co.jp 等

- [X] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [X] 完全无法使用：
ERR_BLOCKED_BY_CLIENT（还需要别的理由么）
- [ ] 部分无法使用：

### 您的运营商是？
联通

### 封锁方式
- [X] DNS 污染
- [ ] IP 封锁
- [ ] IP reset
- [ ] SNI reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方
# Kadokawa Start
183.177.40.130 kadokawa.co.jp
183.177.40.130 www.kadokawa.co.jp
183.177.40.228 asciimw.kadokawa.co.jp
183.177.42.87 ir.kadokawa.co.jp
183.177.40.130 kadokawa-mg.kadokawa.co.jp
183.177.40.130 kadokawagakugei.kadokawa.co.jp
183.177.40.130 kadokawashoten.kadokawa.co.jp
183.177.40.106 kmh.kadokawa.co.jp
183.177.44.38 license.kadokawa.co.jp
183.177.40.130 mediafactory.kadokawa.co.jp
54.230.193.207 mediaguide.kadokawa.co.jp
99.84.181.106 store.kadokawa.co.jp
202.213.45.132 www.chara-ani.com
# Kadokawa End
# 请将 hosts 内容粘贴在此行上方
```

**Comment by 123ysys** [comment]
什么鬼？这是角川啊？！

**Comment by imba-tjd** [comment]
理论上`ERR_BLOCKED_BY_CLIENT`是被去广告的扩展禁的，至少在我这里访问是`ERR_CONNECTION_REFUSED`

**Comment by P-256** [comment]
污染了是不错，but我这里也是refused。refused还不如不加（反正也要挂代理）

**Comment by liuxinyu970226** [comment]
@P-256 可是不加hosts去tcping也是能看到DNS污染相关的IP地址啊，例如69.63.181.11

**Comment by GoogleHostsSupport** [comment]
> refused还不如不加（反正也要挂代理）

@P-256 凡是存在 DNS 污染且符合准入条件的域名都是可以加入我们的 hosts 的哦～
