### ISSUE TITLE
status.googlehosts.org网站处于超时状态

### ISSUE THREAD

**Issue by 123ysys** [googlehosts/hosts#362]
公益代理服务器状态查询网站status.googlehosts.org无法正常被打开。我尝试按照wiki上的说明启用TLS 1.3的支持，但是居然在最新版的chrome里无法找到这个选项了？
不过我在vivaldi浏览器里试了试，虽然启用了TLS 1.3，但是仍然无法打开。

**Comment by lrinQVQ** [comment]
0.0是的将在不久后修复

**Comment by GoogleHostsSupport** [comment]
因 #397，现决定不再恢复上线。
