### ISSUE TITLE
PotPlayer突然打不开了！求助！呜呜！

### ISSUE THREAD

**Issue by liuweihang-2019** [googlehosts/hosts#365]
### 是什么网站 / app 出现了问题？

- [x] 我确认这不是一个 NSFW 网站
韩国播放器影音网站

### 是完全无法使用，还是部分无法使用？
- [x] 完全无法使用：

- [ ] 部分无法使用：

### 您的运营商是？
中国移动

### 加载失败的资源地址
potplayer.daum.net
t1.daumcdn.net

### 失效域名的 DNS 解析结果
Windows上使用nslookup命令发现被解析至Facebook IP

### 封锁方式
- [x] DNS 污染
- [ ] IP 封锁
- [ ] IP reset
- [ ] SNI reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方

# 请将 hosts 内容粘贴在此行上方
```

**Comment by P-256** [comment]
同 https://github.com/googlehosts/hosts/issues/303#issuecomment-487010482

**Comment by GoogleHostsSupport** [comment]
由于此 issue 涉及到的两个域名均已被合并进项目内，这边先作 duplicate 关闭处理哦～
