### ISSUE TITLE
能否提供ipv6地址版本

### ISSUE THREAD

**Issue by merry200603** [googlehosts/hosts#366]
在ipv6已经大范围普及的现状下，使用ipv6访问有更好的优势，希望能提供下ipv6版本，谢谢！

**Comment by 123ysys** [comment]
ipv6版本的在这里：https://github.com/googlehosts/hosts-ipv6
ps：ipv6普及还有一大段路要走吧？

**Comment by merry200603** [comment]
> ipv6版本的在这里：https://github.com/googlehosts/hosts-ipv6
> ps：ipv6普及还有一大段路要走吧？

三大巨头很多地方都提供ipv6了，现在移动手机就可以直连ipv6地址了；你所提的ipv6 host已经很久没更新了，lennylxx的ipv6hosts上次更新也在上一年底

**Comment by 123ysys** [comment]
> > ipv6版本的在这里：https://github.com/googlehosts/hosts-ipv6
> > ps：ipv6普及还有一大段路要走吧？
> 
> 三大巨头很多地方都提供ipv6了，现在移动手机就可以直连ipv6地址了；你所提的ipv6 host已经很久没更新了，lennylxx的ipv6hosts上次更新也在上一年底

至少我的浙江移动的手机的数据蜂窝是提供了，但是我每次询问浙江移动的客服人员是否可以给我们安装ipv6宽带的时候，没有一个人是明白ipv6是什么的。
另外，lennylxx的ipv6资源也是folk组织的，至于为什么这么久也不更新，那纯粹是因为大佬们太忙了，这个资源也是有一个月没更了呀。

**Comment by merry200603** [comment]
> > > ipv6版本的在这里：https://github.com/googlehosts/hosts-ipv6
> > > ps：ipv6普及还有一大段路要走吧？
> > 
> > 
> > 三大巨头很多地方都提供ipv6了，现在移动手机就可以直连ipv6地址了；你所提的ipv6 host已经很久没更新了，lennylxx的ipv6hosts上次更新也在上一年底
> 
> 至少我的浙江移动的手机的数据蜂窝是提供了，但是我每次询问浙江移动的客服人员是否可以给我们安装ipv6宽带的时候，没有一个人是明白ipv6是什么的。
> 另外，lennylxx的ipv6资源也是folk组织的，至于为什么这么久也不更新，那纯粹是因为大佬们太忙了，这个资源也是有一个月没更了呀。

尝试了wiki里面的方法，自己搞了好久，还是搞不定，毕竟外行

**Comment by 123ysys** [comment]
wiki里的方法暂时不可用，wiki里应该有说明过。

**Comment by merry200603** [comment]
> wiki里的方法暂时不可用，wiki里应该有说明过。

这倒是没注意到，也是前一段折腾的，折腾了几天，然后放弃了

**Comment by 123ysys** [comment]
> > wiki里的方法暂时不可用，wiki里应该有说明过。
> 
> 这倒是没注意到，也是前一段折腾的，折腾了几天，然后放弃了

UDP 443端口被封得太厉害了，管理组还在想办法，可能大方向不会变，就是小细节技术修改一下。

**Comment by beyondgfw** [comment]
@123ysys //实际上换个端口就好emmm 但是不知道这么做到底会不会继续被追着封

**Comment by 123ysys** [comment]
> @123ysys //实际上换个端口就好emmm 但是不知道这么做到底会不会继续被追着封

这就陷入死路了，如果没有百分百的防范机制，那就只能试，而一试就可能被封。

**Comment by beyondgfw** [comment]
@123ysys 是的emmm 所以 我还是继续思考解决方案吧

**Comment by GoogleHostsSupport** [comment]
IPv6 hosts 相关问题还请移步我们的对应仓库进行提问哦，我们一样会收到通知推送的：https://github.com/googlehosts/hosts-ipv6/issues
另外这边要指出的是，目前不少地区的 IPv6 环境也是有 GFW 的（级别甚至可以跟 IPv4 相当，SNI 重置也是可以有的，如果您没有那就只能说恭喜啦），所以 IPv6 的优势其实并没有那么明显，加上我们在维护时需要考虑全国范围的整体情况，所以短期内我们仍会优先维护 IPv4 hosts，这点还请各位 IPv6 用户见谅呢～
