### ISSUE TITLE
你们更换后都有用吗？

### ISSUE THREAD

**Issue by victorwangk** [googlehosts/hosts#367]
我在中国大陆，替换hosts后，Google的各个网站没一个能打开

**Comment by jinyumarine** [comment]
不能用了，google被特别照顾了

**Comment by liuweihang-2019** [comment]
google现在已经被墙了，用HOSTS修改访问没有用了...

**Comment by liuweihang-2019** [comment]
G的IP被封锁，修改HOSTS彻底没有用了

**Comment by lekj** [comment]
敏感时刻~

**Comment by beyondgfw** [comment]
@victorwangk 嘛暂时当作不可用就好

**Comment by wangfeng35** [comment]
sigh

**Comment by carlwangcan** [comment]
同为大陆，不止谷歌，我这pinterest这类设计网站都打不开，ping 和 tcping、telnet 还有端口80/443我都测试过，都可以通过，是否我这里设置有问题，除了替换host我还需要什么操作，目前是win10系统

**Comment by 123ysys** [comment]
> 同为大陆，不止谷歌，我这pinterest这类设计网站都打不开，ping 和 tcping、telnet 还有端口80/443我都测试过，都可以通过，是否我这里设置有问题，除了替换host我还需要什么操作，目前是win10系统

pinterest也是被重点照顾的呀。

**Comment by zyx0609** [comment]
google.com.hk还可以呀～

**Comment by P-256** [comment]
> google.com.hk还可以呀～

鬼来了，UDP不是早GG了吗

**Comment by cnrting** [comment]
> 同为大陆，不止谷歌，我这pinterest这类设计网站都打不开，ping 和 tcping、telnet 还有端口80/443我都测试过，都可以通过，是否我这里设置有问题，除了替换host我还需要什么操作，目前是win10系统

你难道不知道gfw还有sni reset这一招吗

**Comment by GoogleHostsSupport** [comment]
请移步 #274 继续讨论哦～
