### ISSUE TITLE
有没有用实验室手机能用，win10下不能用的

### ISSUE THREAD

**Issue by jinyumarine** [googlehosts/hosts#368]
### 是什么网站 / app 出现了问题？

- [ ] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [ ] 完全无法使用：

- [ ] 部分无法使用：

### 封锁方式
- [ ] DNS 污染
- [ ] IP 封锁
- [ ] IP reset
- [ ] SNI reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方

# 请将 hosts 内容粘贴在此行上方
```

**Comment by jinyumarine** [comment]
在同网络下（WIFI），手机用SS正常，win10下连不上，切换到win7下又正常，用手机做热点，win10下连接后还是无法连接外网，win7下又正常，我重装了win10，问题依旧，有哪位大大能解决下，谢谢

**Comment by liuxinyu970226** [comment]
我X提交者手机竟然可以用实验室方法上G氏？奇迹呀，不是说功夫墙把UDP 443封杀的体无完肤了么

**Comment by jinyumarine** [comment]
@liuxinyu970226  手机和win7下都正常，就是在win10下抽风

**Comment by 123ysys** [comment]
> 我X提交者手机竟然可以用实验室方法上G氏？奇迹呀，不是说功夫墙把UDP 443封杀的体无完肤了么

提交者手机是啥子手机🤔？

**Comment by jinyumarine** [comment]
@123ysys  小米，2个小米都正常使用。不管是wifi还是数据，就是在win10下无法使用

**Comment by 123ysys** [comment]
> @123ysys 小米，2个小米都正常使用。不管是wifi还是数据，就是在win10下无法使用

不带这样的，我的米5根本一点用都没有，已经root了，而且我以前用着nexus 5，刷着刷着就成砖了。

**Comment by jinyumarine** [comment]
@123ysys 我的米5主要做制作主题用了，现在用的米8和N7P，在wifi下，手机和win7都正常使用，唯独在win10下不能使用，我说的是公益SS，不是hosts，不要搞错了哟

**Comment by 123ysys** [comment]
> @123ysys 我的米5主要做制作主题用了，现在用的米8和N7P，在wifi下，手机和win7都正常使用，唯独在win10下不能使用，我说的是公益SS，不是hosts，不要搞错了哟

Oppps,搞错了。公益代理我没怎么试过呢，我在等TG里的通知。

**Comment by jinyumarine** [comment]
@123ysys wiki里的实验室只有公益代理和TG，代理手机能用，不管是wifi还是数据下，win7在wifi下也正常使用，就是win10下不能用，我就奈闷了，害我重装win10，还是抽风，更绝的是win10下用手机热点还是抽风，win7没此问题

**Comment by 123ysys** [comment]
> @123ysys wiki里的实验室只有公益代理和TG，代理手机能用，不管是wifi还是数据下，win7在wifi下也正常使用，就是win10下不能用，我就奈闷了，害我重装win10，还是抽风，更绝的是win10下用手机热点还是抽风，win7没此问题

实验室，我晓得了😂。咱们先暂停吧，让QVQ大佬们弄去。

**Comment by lrinQVQ** [comment]
我决定变身恶魔

**Comment by gaoquanbing-ausxin** [comment]
跟进了QUIC draft 2 ? @lrinQVQ 能具体点不

**Comment by lrinQVQ** [comment]
> 跟进了QUIC draft 2 ? @lrinQVQ 能具体点不

使用方法不变只是跟进了草案到20版本

**Comment by lrinQVQ** [comment]
昂忘记更新后端 稍等下

**Comment by GoogleHostsSupport** [comment]
我们决定终止维护所有公益 Shadowsocks 代理服务器。
公益 Telegram 代理服务器不受此次变动的影响。
