### ISSUE TITLE
公益 Shadowsocks 代理配置问题

### ISSUE THREAD

**Issue by xisohi** [googlehosts/hosts#370]
shadowrocked已更新支持v2ray-plugin和kcptun插件，但是无法使用，配置如下：
quic设置：
![image](https://user-images.githubusercontent.com/29686769/59267392-bad70d80-8c7c-11e9-8742-04341be7145a.png)

![image](https://user-images.githubusercontent.com/29686769/59266943-83b42c80-8c7b-11e9-96cc-25da4f320ea5.png)

kuptun设置：
![image](https://user-images.githubusercontent.com/29686769/59267170-12c14480-8c7c-11e9-8a1b-d7b72bbe942e.png)
![image](https://user-images.githubusercontent.com/29686769/59267175-19e85280-8c7c-11e9-80eb-de7278126660.png)

请大神看一下问题出在什么地方？非常感谢！！！

**Comment by szescxz** [comment]
您的配置的确有一处错误哦～
[Shadowrocket 目前仅支持 websocket 和 tls + websocket 两种模式](https://github.com/Shadowrocket/manual/issues/7)，分别对应我们 [wiki 页面](https://github.com/googlehosts/hosts/wiki/%E5%AE%9E%E9%AA%8C%E5%AE%A4)上的 V2RAY-HTTP 和 V2RAY-HTTPS，因此目前您无法通过 Shadowrocket 使用 2335 端口，请留意～

**Comment by GoogleHostsSupport** [comment]
您的配置的确有一处错误哦～
根据 Shadowrocket/manual#7，Shadowrocket 目前仅支持 websocket 和 tls + websocket 两种模式，分别对应我们 [wiki 页面](https://github.com/googlehosts/hosts/wiki/%E5%AE%9E%E9%AA%8C%E5%AE%A4)上的 V2RAY-HTTP 和 V2RAY-HTTPS，因此目前您无法通过 Shadowrocket 使用 2335 端口，请留意～
