### ISSUE TITLE
实验室里的ss用不了

### ISSUE THREAD

**Issue by veteran233** [googlehosts/hosts#371]
是只有我一个人用不了吗？

**Comment by Brs-39** [comment]
同，无插件和kcptun都不行，试了很多方法了，是服务器关了吗？

**Comment by GoogleHostsSupport** [comment]
因机房离线维护，目前我们只有一台服务器可用，非常抱歉呢～
您可以将已有配置的服务器地址改为 `185.22.152.42`，也可以使用下方的 `ss://` 链接：

<details>
<summary>点击展开</summary>

V2RAY-HTTP: `ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpnb29nbGVob3N0cw@185.22.152.42:2333/?plugin=v2ray-plugin%3Bhost%3Dss-3.googlehosts.org#ss-3.googlehosts.org-v2ray-http`
V2RAY-HTTPS: `ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpnb29nbGVob3N0cw@185.22.152.42:2334/?plugin=v2ray-plugin%3Btls%3Bhost%3Dss-3.googlehosts.org#ss-3.googlehosts.org-v2ray-https`
V2RAY-QUIC: `ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpnb29nbGVob3N0cw@185.22.152.42:2335/?plugin=v2ray-plugin%3Bmode%3Dquic%3Bhost%3Dss-3.googlehosts.org#ss-3.googlehosts.org-v2ray-quic`
KCPTUN: `ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpnb29nbGVob3N0cw@185.22.152.42:2336/?plugin=kcptun%3Bcrypt%3Dsalsa20%3Bmode%3Dnormal%3Bmtu%3D1200%3Bparityshard%3D0%3Bdscp%3D46%3Bnocomp#ss-3.googlehosts.org-kcptun`
PLAIN: `ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpnb29nbGVob3N0cw@185.22.152.42:2337#ss-3.googlehosts.org-plain`

</details>

**Comment by veteran233** [comment]
> 因机房离线维护，目前我们只有一台服务器可用，非常抱歉呢～
> 您可以将已有配置的服务器地址改为 `185.22.152.42`，也可以使用下方的 `ss://` 链接：
> 
> 点击展开
> V2RAY-HTTP: `ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpnb29nbGVob3N0cw@185.22.152.42:2333/?plugin=v2ray-plugin%3Bhost%3Dss-3.googlehosts.org#ss-3.googlehosts.org-v2ray-http`
> V2RAY-HTTPS: `ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpnb29nbGVob3N0cw@185.22.152.42:2334/?plugin=v2ray-plugin%3Btls%3Bhost%3Dss-3.googlehosts.org#ss-3.googlehosts.org-v2ray-https`
> V2RAY-QUIC: `ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpnb29nbGVob3N0cw@185.22.152.42:2335/?plugin=v2ray-plugin%3Bmode%3Dquic%3Bhost%3Dss-3.googlehosts.org#ss-3.googlehosts.org-v2ray-quic`
> KCPTUN: `ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpnb29nbGVob3N0cw@185.22.152.42:2336/?plugin=kcptun%3Bcrypt%3Dsalsa20%3Bmode%3Dnormal%3Bmtu%3D1200%3Bparityshard%3D0%3Bdscp%3D46%3Bnocomp#ss-3.googlehosts.org-kcptun`
> PLAIN: `ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpnb29nbGVob3N0cw@185.22.152.42:2337#ss-3.googlehosts.org-plain`

没事的，谢谢了

**Comment by Brs-39** [comment]
感谢

**Comment by gaoquanbing-ausxin** [comment]
@veteran233  谢谢， 妥妥的可用了

**Comment by 01c0006f5d010cc6cd87e56965f2ecd0** [comment]
> 因机房离线维护，目前我们只有一台服务器可用，非常抱歉呢～
> 您可以将已有配置的服务器地址改为 `185.22.152.42`，也可以使用下方的 `ss://` 链接：
> 
> 点击展开
按照您的提示，在 Shadowrocket 2.1.27(742) 上仍然不能使用 ss-3.googlehosts.org KCPTUN 线路。请问以下图示设置有什么问题吗？检查N遍，不得其解。请将正确的参数设置值 图示出来吧，谢谢。
![IMG_1509](https://user-images.githubusercontent.com/52157841/60009784-0a6bff00-96a9-11e9-805f-f6eb03ae980c.PNG)
![IMG_1510](https://user-images.githubusercontent.com/52157841/60009788-0d66ef80-96a9-11e9-968f-c5d2b42044b3.PNG)
![IMG_1511](https://user-images.githubusercontent.com/52157841/60009801-148dfd80-96a9-11e9-9fd8-75efa0c6f3cd.PNG)

**Comment by GoogleHostsSupport** [comment]
@01c0006f5d010cc6cd87e56965f2ecd0

_提示：因为这边缺乏 Shadowrocket 的测试数据，所以以下配置仅供参考，不保证可用哦～_

根据您提供的截图，这边建议您作如下修改：

#### 服务器配置（Edit Server）
Host `185.22.152.42`
_其余不变_

#### 插件配置（Plugin）
Address （留空）
Port （留空）
Key （留空）
_其余不变_

**Comment by 01c0006f5d010cc6cd87e56965f2ecd0** [comment]
试了您说的这个配置，不起作用。建议您在 Shadowrocket 上测试有关参数的值并成功连通后，再做公布。
ps Shadowsocksx-NG 1.8.2 上没有问题。插件选项是[crypt=salsa20;mode=normal;mtu=1200;parityshard=0;dscp=46;nocomp;]
![屏幕快照 2019-06-24 19 23 24](https://user-images.githubusercontent.com/52157841/60015233-8cfabb80-96b5-11e9-986b-251a15dd96ff.png)

**Comment by GoogleHostsSupport** [comment]
@01c0006f5d010cc6cd87e56965f2ecd0 
> 建议您在 Shadowrocket 上测试有关参数的值并成功连通后, 再做公布。

非常抱歉，这边从客服本人到服务器运维的所有人都没有 iOS 设备，所以目前只能依靠社群用户提供反馈～😂

> Shadowsocksx-NG 1.8.2 上没有问题

[ShadowsocksX-NG](https://github.com/shadowsocks/ShadowsocksX-NG) 是[官方 Shadowsocks 组织](https://github.com/shadowsocks)旗下的项目，因而我们可以保证兼容。但 Shadowrocket 并非如此～

> 试了您说的这个配置, 不起作用。

不过还是要感谢您的反馈～
这边再调查了一下，根据[官方说明](https://github.com/Shadowrocket/manual/issues/8#issuecomment-502416699)，如果您是从 App Store 下载的 Shadowrocket，插件配置（Plugin）中的 Address 和 Port 也是需要填写的，即：
> Address `185.22.152.42`
> Port `2336`

**Comment by 01c0006f5d010cc6cd87e56965f2ecd0** [comment]
> @01c0006f5d010cc6cd87e56965f2ecd0
> 
> > 建议您在 Shadowrocket 上测试有关参数的值并成功连通后, 再做公布。
> 
> 非常抱歉，这边从客服本人到服务器运维的所有人都没有 iOS 设备，所以目前只能依靠社群用户提供反馈～😂
> 
> > Shadowsocksx-NG 1.8.2 上没有问题
> 
> [ShadowsocksX-NG](https://github.com/shadowsocks/ShadowsocksX-NG) 是[官方 Shadowsocks 组织](https://github.com/shadowsocks)旗下的项目，因而我们可以保证兼容。但 Shadowrocket 并非如此～
> 
> > 试了您说的这个配置, 不起作用。
> 
> 不过还是要感谢您的反馈～
> 这边再调查了一下，根据[官方说明](https://github.com/Shadowrocket/manual/issues/8#issuecomment-502416699)，如果您是从 App Store 下载的 Shadowrocket，插件配置（Plugin）中的 Address 和 Port 也是需要填写的，即：
> 
> > Address `185.22.152.42`
> > Port `2336`

权威答复说: Shadowrocket KCPTUN 线路 KCPTUN-key 不能为空。所以如果想让 IOS 用户使用 KCPTUN 线路，请站方设置 KCPTUN-key 为 非空的值, 并公布之。
谢谢。

**Comment by GoogleHostsSupport** [comment]
@01c0006f5d010cc6cd87e56965f2ecd0 
> 权威答复说: Shadowrocket KCPTUN 线路 KCPTUN-key 不能为空。所以如果想让 IOS 用户使用 KCPTUN 线路，请站方设置 KCPTUN-key 为 非空的值, 并公布之。

是这边疏忽了，再次抱歉～😂
正如您所提到的，我们的 kcptun 配置按照 SIP003 的格式写出来是 `crypt=salsa20;mode=normal;mtu=1200;parityshard=0;dscp=46;nocomp`，也就是说我们并没有对 `key` 参数进行配置。
但 kcptun 的这一参数有一默认值 `it's a secrect`，所以您的插件配置（Plugin）一栏中 Key 填写默认的 `it's a secrect` 即可。
给您带来了困扰，非常抱歉呢～

**Comment by 01c0006f5d010cc6cd87e56965f2ecd0** [comment]
> it's a secrect

不过，一切都回到了起点，我反应问题的时候，除了 host 是 name 不是 raw IP 以外，有什么进展么？
您的线路我放弃提问和尝试了，谢谢您的一番答复。

**Comment by GoogleHostsSupport** [comment]
@01c0006f5d010cc6cd87e56965f2ecd0 
> 您的线路我放弃提问和尝试了，谢谢您的一番答复。

非常抱歉给您带来了困扰，也感谢您的反馈～

> 有什么进展么？

如果您是指其他服务器的情况的话，非常抱歉这边目前无法给出具体的恢复时间，也就是说我们可能会在相当长的一段时间内只有一台 Shadowsocks 代理服务器可用呢～
有进一步的消息的话，这边也会尽快在此 issue 中公开；不过如果您有条件的话，也可以选择关注我们的 Telegram 频道推送：https://t.me/s/googlehostsnews

**Comment by 01c0006f5d010cc6cd87e56965f2ecd0** [comment]
> @01c0006f5d010cc6cd87e56965f2ecd0
> 
> > 您的线路我放弃提问和尝试了，谢谢您的一番答复。
> 
> 非常抱歉给您带来了困扰，也感谢您的反馈～
> 
> > 有什么进展么？
> 
> 如果您是指其他服务器的情况的话，非常抱歉这边目前无法给出具体的恢复时间，也就是说我们可能会在相当长的一段时间内只有一台 Shadowsocks 代理服务器可用呢～
> 有进一步的消息的话，这边也会尽快在此 issue 中公开；不过如果您有条件的话，也可以选择关注我们的 Telegram 频道推送：https://t.me/s/googlehostsnews

我愿意重复粘贴我的帖子
“““
不过，一切都回到了起点，我反应问题的时候，除了 host 是 name 不是 raw IP 以外，有什么进展么？
您的线路我放弃提问和尝试了，谢谢您的一番答复。
”””
我没有就你所有路线做评价，一直指向的也仅是 ss-3.googlehosts.org 之 KCPTUN 如何配置才能在  Shadowrocket 上工作。不愿意听您（们）无实质进展拿腔拿调的言辞了，就此打住。

**Comment by GoogleHostsSupport** [comment]
@01c0006f5d010cc6cd87e56965f2ecd0 
> 一直指向的也仅是 ss-3.googlehosts.org 之 KCPTUN 如何配置才能在 Shadowrocket 上工作

ss-3.googlehosts.org 目前可用的 IP 只有 `185.22.152.42` 一个哦，您可以自行检查 DNS 解析结果进行确认：https://dns.google.com/query?name=ss-3.googlehosts.org
因为这边无法确认您所使用的 ISP 是否对该域名进行污染，以及您是否使用了我们的 hosts 等情况，保险起见所以才建议您使用 IP～
此外这边之前也提到过，**Shadowrocket 并非由 Shadowsocks 官方组织维护，因而我们无法保证我们的 Shadowsocks 服务器对于 Shadowrocket 可用，所以也无法提供相应支持**；但 ShadowsocksX-NG 是由 Shadowsocks 官方组织维护的，因此我们可以保证兼容～
还有就是，根据下载来源的不同，Shadowrocket 的配置方式亦有可能存在差异：从 App Store 下载的正式版可能与从 TestFlight 下载的测试版有所不同，而且就此例而言，App Store 正式版的 kcptun 插件的确存在 bug～
就您的情况，这边建议您通过其他渠道寻求帮助；我们的服务器插件配置即为 `crypt=salsa20;mode=normal;mtu=1200;parityshard=0;dscp=46;nocomp`，没有提及的参数即为默认值。
另外，如果您在 iOS 设备上确实无法通过 kcptun 插件访问我们的服务器的话，这边建议您使用其他配置：Shadowrocket 理论上支持我们实验室页面列出的 V2RAY-HTTP、V2RAY-HTTPS 和 PLAIN（即无插件）配置，其中前两个插件的配置建议您参考 https://github.com/googlehosts/hosts/issues/370#issuecomment-502928792
以上～

**Comment by 01c0006f5d010cc6cd87e56965f2ecd0** [comment]
> @01c0006f5d010cc6cd87e56965f2ecd0
> 
> > 一直指向的也仅是 ss-3.googlehosts.org 之 KCPTUN 如何配置才能在 Shadowrocket 上工作
> 
> ss-3.googlehosts.org 目前可用的 IP 只有 `185.22.152.42` 一个哦，您可以自行检查 DNS 解析结果进行确认：https://dns.google.com/query?name=ss-3.googlehosts.org
> 因为这边无法确认您所使用的 ISP 是否对该域名进行污染，以及您是否使用了我们的 hosts 等情况，保险起见所以才建议您使用 IP～
> 此外这边之前也提到过，**Shadowrocket 并非由 Shadowsocks 官方组织维护，因而我们无法保证我们的 Shadowsocks 服务器对于 Shadowrocket 可用，所以也无法提供相应支持**；但 ShadowsocksX-NG 是由 Shadowsocks 官方组织维护的，因此我们可以保证兼容～
> 还有就是，根据下载来源的不同，Shadowrocket 的配置方式亦有可能存在差异：从 App Store 下载的正式版可能与从 TestFlight 下载的测试版有所不同，而且就此例而言，App Store 正式版的 kcptun 插件的确存在 bug～
> 就您的情况，这边建议您通过其他渠道寻求帮助；我们的服务器插件配置即为 `crypt=salsa20;mode=normal;mtu=1200;parityshard=0;dscp=46;nocomp`，没有提及的参数即为默认值。
> 另外，如果您确实无法通过 Shadowrocket 的 kcptun 插件访问我们的服务器的话，这边建议您使用其他配置：Shadowrocket 理论上支持我们[实验室页面](https://github.com/googlehosts/hosts/wiki/%E5%AE%9E%E9%AA%8C%E5%AE%A4)列出的 V2RAY-HTTP、V2RAY-HTTPS 和 PLAIN（即无插件）配置，其中前两个插件的配置建议您参考 [#370 (comment)](https://github.com/googlehosts/hosts/issues/370#issuecomment-502928792)
> 以上～

感谢您详尽绵长耐心的回复。回溯以上可知，线路 ss-3.googlehosts.org 配置 ss + KCPTUN ，Shadowrocket 可以使用以下这条 ( ss://... ) ：
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpnb29nbGVob3N0c0AxODUuMjIuMTUyLjQyOjIzMzY?kcptun=eyJjcnlwdCI6InNhbHNhMjAiLCJkYXRhc2hhcmQiOiIxMCIsImtlZXBhbGl2ZSI6IjEwIiwicmN2d25kIjoiMTAyNCIsImRzY3AiOiI0NiIsInBhcml0eXNoYXJkIjoiMCIsImF1dG9leHBpcmUiOiIwIiwia2V5IjoiaXQncyBhIHNlY3JlY3QiLCJtb2RlIjoibm9ybWFsIiwiYWRkcmVzcyI6IjE4NS4yMi4xNTIuNDIiLCJub2NvbXAiOnRydWUsInNuZHduZCI6IjEwMjQiLCJtdHUiOiIxMjAwIiwicG9ydCI6IjIzMzYifQ#ss-3.googlehosts.org-kcptun

**Comment by GoogleHostsSupport** [comment]
@01c0006f5d010cc6cd87e56965f2ecd0 
> 回溯以上可知，线路 ss-3.googlehosts.org 配置 ss + KCPTUN ，Shadowrocket 可以使用以下这条 ( ss://... ) ：
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpnb29nbGVob3N0c0AxODUuMjIuMTUyLjQyOjIzMzY?kcptun=eyJjcnlwdCI6InNhbHNhMjAiLCJkYXRhc2hhcmQiOiIxMCIsImtlZXBhbGl2ZSI6IjEwIiwicmN2d25kIjoiMTAyNCIsImRzY3AiOiI0NiIsInBhcml0eXNoYXJkIjoiMCIsImF1dG9leHBpcmUiOiIwIiwia2V5IjoiaXQncyBhIHNlY3JlY3QiLCJtb2RlIjoibm9ybWFsIiwiYWRkcmVzcyI6IjE4NS4yMi4xNTIuNDIiLCJub2NvbXAiOnRydWUsInNuZHduZCI6IjEwMjQiLCJtdHUiOiIxMjAwIiwicG9ydCI6IjIzMzYifQ#ss-3.googlehosts.org-kcptun

感谢您的反馈！
如果您确定您的这一配置可用的话，这边想请您做进一步测试，因为这边注意到您的配置中某些参数的值并非默认值。当然如果您不愿意的话也没问题～

[Receive Window 的默认值应为 `512`](https://github.com/shadowsocks/kcptun/blob/3522da116625395cfba0495219e89a2ec20b755e/client/main.go#L163)，您目前设置的值为 `1024`；
[Auto Expire 的默认值应为 `10`](https://github.com/shadowsocks/kcptun/blob/3522da116625395cfba0495219e89a2ec20b755e/client/main.go#L143)，您目前设置的值为 `0`；
[Send Window 的默认值应为 `128`](https://github.com/shadowsocks/kcptun/blob/3522da116625395cfba0495219e89a2ec20b755e/client/main.go#L158)，您目前设置的值为 `1024`；

此外需要提醒您的是，您的这一 `ss://` 链接并非标准格式（标准的写法是 `ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpnb29nbGVob3N0cw@185.22.152.42:2336/?plugin=kcptun%3Bcrypt%3Dsalsa20%3Bmode%3Dnormal%3Bmtu%3D1200%3Bparityshard%3D0%3Bdscp%3D46%3Bnocomp#ss-3.googlehosts.org-kcptun
`），因此可能仅限 Shadowrocket 使用哦～

**Comment by 01c0006f5d010cc6cd87e56965f2ecd0** [comment]
> @01c0006f5d010cc6cd87e56965f2ecd0
> 
> > 回溯以上可知，线路 ss-3.googlehosts.org 配置 ss + KCPTUN ，Shadowrocket 可以使用以下这条 ( ss://... ) ：
> > ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpnb29nbGVob3N0c0AxODUuMjIuMTUyLjQyOjIzMzY?kcptun=eyJjcnlwdCI6InNhbHNhMjAiLCJkYXRhc2hhcmQiOiIxMCIsImtlZXBhbGl2ZSI6IjEwIiwicmN2d25kIjoiMTAyNCIsImRzY3AiOiI0NiIsInBhcml0eXNoYXJkIjoiMCIsImF1dG9leHBpcmUiOiIwIiwia2V5IjoiaXQncyBhIHNlY3JlY3QiLCJtb2RlIjoibm9ybWFsIiwiYWRkcmVzcyI6IjE4NS4yMi4xNTIuNDIiLCJub2NvbXAiOnRydWUsInNuZHduZCI6IjEwMjQiLCJtdHUiOiIxMjAwIiwicG9ydCI6IjIzMzYifQ#ss-3.googlehosts.org-kcptun
> 
> 感谢您的反馈！
> 如果您确定您的这一配置可用的话，这边想请您做进一步测试，因为这边注意到您的配置中某些参数的值并非默认值。当然如果您不愿意的话也没问题～
> 
> [Receive Window 的默认值应为 `512`](https://github.com/shadowsocks/kcptun/blob/3522da116625395cfba0495219e89a2ec20b755e/client/main.go#L163)，您目前设置的值为 `1024`；
> [Auto Expire 的默认值应为 `10`](https://github.com/shadowsocks/kcptun/blob/3522da116625395cfba0495219e89a2ec20b755e/client/main.go#L143)，您目前设置的值为 `0`；
> [Send Window 的默认值应为 `128`](https://github.com/shadowsocks/kcptun/blob/3522da116625395cfba0495219e89a2ec20b755e/client/main.go#L158)，您目前设置的值为 `1024`；
> 
> 此外需要提醒您的是，您的这一 `ss://` 链接并非标准格式（标准的写法是 `ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpnb29nbGVob3N0cw@185.22.152.42:2336/?plugin=kcptun%3Bcrypt%3Dsalsa20%3Bmode%3Dnormal%3Bmtu%3D1200%3Bparityshard%3D0%3Bdscp%3D46%3Bnocomp#ss-3.googlehosts.org-kcptun `），因此可能仅限 Shadowrocket 使用哦～

贴出那条 ss 是为了展示讨论的阶段性结论，建立一个讨论的基点。改参数之前之后，Shadowrocket 均不能使用此 ss-3 KCPTUN。

**Comment by GoogleHostsSupport** [comment]
@01c0006f5d010cc6cd87e56965f2ecd0 
> 改参数之前之后，Shadowrocket 均不能使用此 ss-3 KCPTUN。

好的，还是谢谢您的反馈！
鉴于您的情况，以及 Shadowrocket 目前的开发进度，这边仍然建议您向 Shadowrocket 的开发者进行反馈，或通过其他渠道寻求帮助。您也可以选择参照 Shadowrocket/manual#4 贴出相关的日志信息（请记得对您的隐私信息进行处理），**但请注意我们不保证能解决问题，亦不会针对 Shadowrocket 等非 Shadowsocks 官方组织所维护的客户端进行服务端的兼容性调整**。

**Comment by 01c0006f5d010cc6cd87e56965f2ecd0** [comment]
> @01c0006f5d010cc6cd87e56965f2ecd0
> 
> > 改参数之前之后，Shadowrocket 均不能使用此 ss-3 KCPTUN。
> 
> 好的，还是谢谢您的反馈！
> 鉴于您的情况，以及 Shadowrocket 目前的开发进度，这边仍然建议您向 Shadowrocket 的开发者进行反馈，或通过其他渠道寻求帮助。您也可以选择参照 [Shadowrocket/manual#4](https://github.com/Shadowrocket/manual/issues/4) 贴出相关的日志信息（请记得对您的隐私信息进行处理），**但请注意我们不保证能解决问题，亦不会针对 Shadowrocket 等非 Shadowsocks 官方组织所维护的客户端进行服务端的兼容性调整**。

是否考虑众包方式，新开一 issue , 请大家分享 ss-3 +KCPTUN 可工作、分平台、分应用的配置参数值 ？

**Comment by GoogleHostsSupport** [comment]
@01c0006f5d010cc6cd87e56965f2ecd0

由于 issue 主要还是以反馈问题为主，且过多无意义的讨论会影响到订阅本项目邮件推送的用户，所以除非有必要，否则我们一般不会开设专门用于讨论的 issue 呢～但是这并不影响大家在合适的 issue 下进行反馈哦～
此外，一般来说，我们会建议大家加入我们的 [Telegram 群组](https://t.me/googlehosts)进行讨论～
以及，这边需要再次提醒您，**我们只能保证与官方 Shadowsocks 组织所维护的客户端兼容**，而官方组织所维护的客户端目前已经涵盖了 Windows、Linux、Mac OS、Android 和 OpenWRT 这些比较常用的平台，且配置方法都是统一的，所以目前只有 iOS 是例外哦～
同样的道理，如果您在上述受支持的平台使用非官方组织维护的 Shadowsocks 客户端（例如 Google Jigsaw 出品的 Outline），我们也一样无法提供支持，仅会建议您更换为官方客户端～

**Comment by GoogleHostsSupport** [comment]
我们决定终止维护所有公益 Shadowsocks 代理服务器。
公益 Telegram 代理服务器不受此次变动的影响。
