### ISSUE TITLE
有点儿小麻烦

### ISSUE THREAD

**Issue by yichangshengwu** [googlehosts/hosts#374]
以前一直是用 lhosts 脚本来更新hosts的，
最近，
每次都是失败，只能手动复制粘贴，
然后发现，

在**需要更新**hosts的时候，
https://raw.githubusercontent.com/googlehosts/hosts/master/hosts-files/hosts-no-sni-rst
这个地址打不开！！！

可是，
https://github.com/googlehosts/hosts/blob/master/hosts-files/hosts-no-sni-rst
这个页面却是正常的。。。

然而，
在手动更新了最新的host文件**之后**，
https://raw.githubusercontent.com/googlehosts/hosts/master/hosts-files/hosts-no-sni-rst
这个地址却又是可以正常打开的了。。。

这就郁闷了，
难道就没办法一键搞定了？

**Comment by GoogleHostsSupport** [comment]
> 然而，
> 在手动更新了最新的host文件之后，
> https://raw.githubusercontent.com/googlehosts/hosts/master/hosts-files/hosts-no-sni-rst
> 这个地址却又是可以正常打开的了。。。

目前的 hosts 中并没有 `raw.githubusercontent.com` 这一条目，所以跟 hosts 是无关的，这边认为很有可能是因为您与 GitHub 连接不够稳定，从而使首次连接时间过长而导致的呢～

> 难道就没办法一键搞定了？

如果您与 GitHub 的连接确实不够稳定的话，您也可以选择从国内镜像更新哦～
[在 lhosts 中对应有一个 -m / --mirror 参数～](https://github.com/googlehosts/hosts-tools/blob/dd3636770be8ef50304ae181b10f4b70b3694a17/lhosts#L36)

**Comment by yichangshengwu** [comment]
看来也只好先用国内镜像对付着了，

怀疑gfw在搞啥，
打开一个https页面（以前没打开过的站点）的时候经常是头一次先打不开，刷新一下才可以，

**Comment by GoogleHostsSupport** [comment]
没有其他问题的话这边先关闭 issue 了喔～
