### ISSUE TITLE
github.com

### ISSUE THREAD

**Issue by zuiyixifeng2006** [googlehosts/hosts#376]
### 是什么网站 / app 出现了问题？

- [X] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [ ] 完全无法使用：

- [X] 部分无法使用：

### 您的运营商是？
chinatelecom

### 加载失败的资源地址
https://github.com/googlehosts/hosts/zip/master

### 封锁方式
- [ ] DNS 污染
- [ ] IP 封锁
- [ ] IP reset
- [ ] SNI reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方

# 请将 hosts 内容粘贴在此行上方
```
![捕获](https://user-images.githubusercontent.com/16421078/60064471-1bf9e900-9733-11e9-8cfe-a0aacdae9026.PNG)

dnscrypt-proxy-cloaking-no-sni-rst.txt
禁用 Github 域名
重新启动dnscrypt-proxy
能够下载

为什么？

**Comment by GoogleHostsSupport** [comment]
首先，正确的 ZIP 压缩包下载地址是 https://github.com/googlehosts/hosts/archive/master.zip
其次，如果您只需要单个文件，这边建议您使用右上角的 Raw 按钮进行下载呢，例如 https://github.com/googlehosts/hosts/raw/master/hosts-files/dnscrypt-proxy-cloaking-no-sni-rst.txt
此外，根据您的截图，GitHub 的证书是完全正常的，这种情况下的 404 错误提示不能视为加载失败哦～
