### ISSUE TITLE
Tor Project 部分 IP 失效

### ISSUE THREAD

**Issue by 123ysys** [googlehosts/hosts#377]
### 是什么网站 / app 出现了问题？

- [X] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [ ] 完全无法使用：

- [X] 部分无法使用：
部分子网页，例如www.torproject.org/dist.torproject.org等的ip已经失效了。

### 您的运营商是？
浙江移动

### 加载失败的资源地址
www.torproject.org
dist.torproject.org

### 封锁方式
- [ ] DNS 污染
- [ ] IP 封锁
- [ ] IP reset
- [ ] SNI reset
- [X] 涉及到第三方服务：
如果继续使用旧的ip，会提示隐私错误，就当作是涉及第三方服务了QAQ。

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方
138.201.14.197	www.torproject.org
82.195.75.101	dist.torproject.org
# 请将 hosts 内容粘贴在此行上方
```

**Comment by GoogleHostsSupport** [comment]
> 或者需不需要pull request？

如果您想提交 pull request 的话，需要编辑 [hosts-source 分支下的 hosts.yml 文件](https://github.com/123ysys/hosts/blob/hosts-source/data/hosts.yml)才可以哦～

> 需不需要进行额外的操作？

您也可以选择通过这个 issue 提交，不过这边还是建议您先还原原先的 issue 模板再做操作呢～

**Comment by 123ysys** [comment]
> > 或者需不需要pull request？
> 
> 如果您想提交 pull request 的话，需要编辑 [hosts-source 分支下的 hosts.yml 文件](https://github.com/123ysys/hosts/blob/hosts-source/data/hosts.yml)才可以哦～
> 
> > 需不需要进行额外的操作？
> 
> 您也可以选择通过这个 issue 提交，不过这边还是建议您先还原原先的 issue 模板再做操作呢～

THX.那我就先试着提交pull request吧，如果真的不行我再把这个issue改回去。

**Comment by GoogleHostsSupport** [comment]
@123ysys 
不好意思让您久等了，您在本 issue 中提交的 hosts 条目已全部更新完毕～
因 review 时间较长，如有部分条目在此期间失效的情况，还请尽早提出～
如果没有异议的话，本 issue 将在 24 小时后作关闭处理～
