### ISSUE TITLE
Typo in host file

### ISSUE THREAD

**Issue by vrysmart** [googlehosts/hosts#383]
https://github.com/googlehosts/hosts/commit/1dd65b1a7793732912a72940a387d1de85f2d6d4#r34201842

It looks like 
scontent-mad1-1.cdninstagram.comc	31.13.83.52

might have a typographical error? "comc"

Can you verify?

### 是什么网站 / app 出现了问题？

- [ ] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [ ] 完全无法使用：

- [ ] 部分无法使用：

### 封锁方式
- [ ] DNS 污染
- [ ] IP 封锁
- [ ] IP reset
- [ ] SNI reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方

# 请将 hosts 内容粘贴在此行上方
```

**Comment by GoogleHostsSupport** [comment]
Thanks for pointing out!
This issue will be resolved once #392 gets merged.
