### ISSUE TITLE
公益SS无法使用

### ISSUE THREAD

**Issue by xisohi** [googlehosts/hosts#385]
移动4G可用，联通WIFI无法使用公益SS
![4G](https://user-images.githubusercontent.com/29686769/61840375-884b4200-aec3-11e9-952d-92a50af2d05f.jpg)
![无线](https://user-images.githubusercontent.com/29686769/61840385-913c1380-aec3-11e9-8312-65901b19bba0.jpg)

**Comment by xisohi** [comment]
座标010

**Comment by wolfan** [comment]
telegram代理也挂了。

**Comment by 123ysys** [comment]
tg代理挂了好几天了。

**Comment by eyelivermore** [comment]
联通 用不了 坐标 0371

**Comment by eyelivermore** [comment]
我的现在可以用了!原来是我的chrome上装了一个代理,关闭了那个代理就好了

**Comment by GoogleHostsSupport** [comment]
我们决定终止维护所有公益 Shadowsocks 代理服务器。
公益 Telegram 代理服务器不受此次变动的影响。
