### ISSUE TITLE
https://news.ycombinator.com/   hacknews  不行啊 

### ISSUE THREAD

**Issue by willshion** [googlehosts/hosts#388]
### 是什么网站 / app 出现了问题？

- [x] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [x] 完全无法使用：

- [ ] 部分无法使用：

### 封锁方式
- [ ] DNS 污染
- [ ] IP 封锁
- [ ] IP reset
- [ ] SNI reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方

# 请将 hosts 内容粘贴在此行上方
```

**Comment by willshion** [comment]
能给个 host 吗

**Comment by Stzx** [comment]
`[209.216.230.240]`

**Comment by liuxinyu970226** [comment]
> `[209.216.230.240]`

rbl至少我这边已挂，难不成常见问题一了解一下？

**Comment by willshion** [comment]
> `[209.216.230.240]`

又炸了

**Comment by liuxinyu970226** [comment]
@lrinQVQ 挂黄标签吧，curl试了好几百次都是tcp挂

**Comment by GoogleHostsSupport** [comment]
@liuxinyu970226 这边没有观测到 SNI RST 哦～

现已在 c62fb644f23e164ad62c59542fe591a45ffda146 增加～
