### ISSUE TITLE
为什么我加了hosts之后还是无法访问google啊

### ISSUE THREAD

**Issue by zeasin** [googlehosts/hosts#396]
为什么我加了hosts之后还是无法访问google啊

**Comment by lrinQVQ** [comment]
请阅读[常见问题](https://github.com/googlehosts/hosts/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E8%BF%99%E4%B8%AAhosts%E4%B8%80%E7%82%B9%E7%94%A8%E9%83%BD%E6%B2%A1%E6%9C%89%E5%8D%8A%E5%81%9C%E6%9B%B4%E6%98%AF%E4%BB%80%E4%B9%88%E6%84%8F%E6%80%9D)
