### ISSUE TITLE
[2020.1.11] 实验室相关通知

### ISSUE THREAD

**Issue by lrinQVQ** [googlehosts/hosts#397]
[2020.2.23] 
防污染DNS延期下线,时间未知。

[2020.1.11] 
Shadowsocks服务器 TG代理 将延期下线，时间未知。

[2019.9.12]一些变动
~~公益Shadowsocks服务将于2020年4月1日与防污染DNS和Telegram Mtproto服务同时下线~~

很遗憾地通知大家：
我们已无力负担继续运营下去的成本。
因此，经过内部商议，我们决定:
~~公益Shadowsocks服务将于2019年9月底全部下线；
防污染DNS和Telegram Mtproto服务将于2020年4月1日全部下线。~~
谢谢大家的参与和反馈。

“聚散终有期，世事总无常。”

**Comment by 123ysys** [comment]
祝好QAQ。
那hosts项目本身会继续下去吗？

**Comment by lrinQVQ** [comment]
> 祝好QAQ。
> 那hosts项目本身会继续下去吗？

会的啦 不过可能频率会更低一些

**Comment by 123ysys** [comment]
> > 祝好QAQ。
> > 那hosts项目本身会继续下去吗？
> 
> 会的啦 

那就没事啦，本来实验室的内容就是附加的。

> 不过可能频率会更低一些

会继续关注的。

**Comment by wolfan** [comment]
啊咧……

**Comment by gaoquanbing-ausxin** [comment]
建议收费,继续运行下去， 按照15062的star, 每人每月1-5RMB 应该够运营下去吧， 这样用的人也没有经济上的负担！ 大家觉得呢？

**Comment by jeff6562** [comment]
顶一下~
------------------------------------------------------------------
发件人：高全兵 <notifications@github.com>
发送时间：2019年9月9日(星期一) 10:08
收件人：googlehosts/hosts <hosts@noreply.github.com>
抄　送：Subscribed <subscribed@noreply.github.com>
主　题：Re: [googlehosts/hosts] [2019.09.06] 实验室相关通知 (#397)

建议收费,继续运行下去， 按照15062的star, 每人每月1-5RMB 应该够运营下去吧， 这样用的人也没有经济上的负担！ 大家觉得呢？

**Comment by wolfan** [comment]
@gaoquanbing-ausxin 更多是政治成本无法负担了

**Comment by gaoquanbing-ausxin** [comment]
@wolfan 理解，祝好！

**Comment by GoogleHostsSupport** [comment]
@gaoquanbing-ausxin 感谢您的提议，但**实验室项目仅作实验性用途**，目标即为让尽可能多的人参与测试，因此我们不会考虑任何商业化的选项，目前也没有接受捐赠的计划。

@jeff6562 再次提醒各位，请避免发表不必要的评论。如果您只是想“顶楼上”，请使用 GitHub 的 reaction 功能（即消息框右上角的笑脸符号，移动版页面则是在消息框下方）。

**Comment by beyondgfw** [comment]
@wolfan 安心 无关政治

**Comment by liuxinyu970226** [comment]
@beyondgfw 所以QUIC也不打算修复了么

**Comment by beyondgfw** [comment]
@liuxinyu970226 有空会修的

**Comment by RockJun** [comment]
很遗憾但也很感谢实验室带来的免费free世界，祝好。

**Comment by lrinQVQ** [comment]
更新一下
公益Shadowsocks服务将于2020年4月1日与防污染DNS和Telegram Mtproto服务同时下线
所以ss-3将保持可用直至2020年4月1日

**Comment by wolfan** [comment]
⊙_⊙tgm 也下架。。。

**Comment by lrinQVQ** [comment]
> ⊙_⊙tgm 也下架。。。

"已无力负担继续运营下去的成本"
自然是所有服务啦

**Comment by eyelivermore** [comment]
那以后怎么办哦

**Comment by beyondgfw** [comment]
@eyelivermore 你可以自己搭一个
https://github.com/lrinQVQ/script

**Comment by Licheng-Xu** [comment]
“聚散终有期，世事总无常。”
感谢你们一直以来的付出

**Comment by lrinQVQ** [comment]
[2020.1.11]
Shadowsocks服务器 TG代理 将延期下线，时间未知。

**Comment by Brs-39** [comment]
服务器还正常吗？现在持续连不上。

**Comment by beyondgfw** [comment]
@Brs-39 暂时只恢复了2337端口的服务

**Comment by Brs-39** [comment]
@beyondgfw 感谢

**Comment by lrinQVQ** [comment]
恢复2333/2334/2335/2337端口正常使用
并支持Shadowsocks-android >= 5.0.0中提供的订阅功能
订阅地址:https://googlehosts.org

**Comment by jinyumarine** [comment]
好像公益SS经常抽风，不能使用

**Comment by beyondgfw** [comment]
@jinyumarine https://t.me/googlehostsnews/521

**Comment by jinyumarine** [comment]
> @jinyumarine https://t.me/googlehostsnews/521

没梯子，访问不了了，也没安装T

**Comment by beyondgfw** [comment]
@jinyumarine 稍等 即将开始修复

**Comment by jinyumarine** [comment]
> @jinyumarine 稍等 即将开始修复

谢谢

**Comment by jinyumarine** [comment]
> @jinyumarine 稍等 即将开始修复

貌似还没修复是吗

**Comment by lrinQVQ** [comment]
[2020.2.23]
防污染DNS延期下线,时间未知。

**Comment by lrinQVQ** [comment]
由于所有服务都将继续运行,所以关闭此issues

**Comment by jinyumarine** [comment]
@lrinQVQ 
貌似实验室SS公益账号又挂了，所有都不能用了
第四个KC插件的，直接显示后台启动失败
本来第一个昨天还能用，现在连第一个都挂了
忘修复，想想

**Comment by jinyumarine** [comment]
@lrinQVQ @beyondgfw 
貌似实验室SS公益账号又挂了，所有都不能用了
第四个KC插件的，直接显示后台启动失败
本来第一个昨天还能用，现在连第一个都挂了
忘修复，想想

**Comment by Roelauph** [comment]
感谢
