### ISSUE TITLE
Wiki 信息错误：v2ray

### ISSUE THREAD

**Issue by Suxuanhua** [googlehosts/hosts#398]
![图片](https://user-images.githubusercontent.com/30725732/64946799-48428300-d8a6-11e9-96c7-762845e6fa42.png)

“将可执行文件名改为v2ray-plugin（Windows平台请注意保留.exe后缀）”，
这句话错误：
在windows10，
如果将插件名称  v2ray-plugin-windows-amd64-v1.1.0.exe
改成 v2ray-plugin.exe，会出现异常：
![图片](https://user-images.githubusercontent.com/30725732/64947102-df0f3f80-d8a6-11e9-8e47-916a957b46d5.png)

将 v2ray-plugin.exe 改成 v2ray.exe 正常运行。

**Comment by Stzx** [comment]
> [2019.9.12]一些变动
> 公益Shadowsocks服务将于2020年4月1日与防污染DNS和Telegram Mtproto服务同时下线
> 
> 很遗憾地通知大家：
> 我们已无力负担继续运营下去的成本。
> 因此，经过内部商议，我们决定:
> 公益Shadowsocks服务将于2019年9月底全部下线；
> 防污染DNS和Telegram Mtproto服务将于2020年4月1日全部下线。
> 谢谢大家的参与和反馈。
> 
> “聚散终有期，世事总无常。”

https://github.com/googlehosts/hosts/issues/397#issue-490181611

公益Shadowsocks服务将下线，届时Wiki内容应该会移除，所以我目前已经没有必须重新修改内容了。

**Comment by imba-tjd** [comment]
无法复现。

![图片](https://user-images.githubusercontent.com/24759802/64950431-eab23480-d8ad-11e9-8be6-de0dfc375f1b.png)
