### ISSUE TITLE
求增加个whatsapp的hosts（ps.whatsapp的封锁方式疑似发生了变化）

### ISSUE THREAD

**Issue by 123ysys** [googlehosts/hosts#4]
昨天眼睁睁地看着whatsapp从下午到晚上从好用到不好用，官网从昨天的特定的浏览器可以打开到今天的一片空白，没有链接重置或任何代码报错，就是显示成一片空白（我的浏览器的背景是绿色的，所以是一片绿）。想来这个软件在中国内地是活不久了。不求在这里有能上软件的方法，但求有上官网的方法。谢谢啦么么哒。（ps. 官网从以前的RST变成了TIME-OUT，希望有条件的大佬能够检测一下这是怎么回事，谢谢。）

**Comment by lrinQVQ** [comment]
好像欸多 今天好多了0.0

**Comment by 123ysys** [comment]
是啊，今天好像又好了。迷……

**Comment by lrinQVQ** [comment]
+1 2333

**Comment by lrinQVQ** [comment]
现在全国DNS污染了好像XD

**Comment by 123ysys** [comment]
我的似乎还可以上。

**Comment by lrinQVQ** [comment]
2333很奇怪突然就恢复了又

**Comment by SawaraNazo** [comment]
诶多，我这里能上，但是是这个样子的，这是问题吗？    （ 还是说CSS没加载出来？இ௰இ

![snipaste_20171103_195208](https://user-images.githubusercontent.com/31041465/32372674-d5ca8636-c0d0-11e7-86db-c27e73f854d8.png)

**Comment by beyondgfw** [comment]
应该是css没加载出来，我看看。。

**Comment by lrinQVQ** [comment]
CSS炸了咩哇我看看

**Comment by beyondgfw** [comment]
那你看吧，我懒。。

**Comment by lrinQVQ** [comment]
23333好

**Comment by lrinQVQ** [comment]
www-cdn.whatsapp.net GG了

**Comment by SawaraNazo** [comment]
诶，所以是被墙了，不是我加载的问题吗？

**Comment by lrinQVQ** [comment]
对XD

**Comment by lrinQVQ** [comment]
@SawaraNazo HPING www-cdn.whatsapp.net (enp3s0 157.240.13.54): S set, 40 headers + 0 data bytes
^C
--- www-cdn.whatsapp.net hping statistic ---
4 packets tramitted, 0 packets received, 100% packet loss
round-trip min/avg/max = 0.0/0.0/0.0 ms

**Comment by SawaraNazo** [comment]
那咱就放心了 （X      இ௰இ       谢谢解答，辛苦啦。

**Comment by lrinQVQ** [comment]
2333小意思啦 顺便马上修复

**Comment by SawaraNazo** [comment]
好厉害，已经可以正常用啦~    ♪(´▽｀)

![snipaste_20171103_203837](https://user-images.githubusercontent.com/31041465/32374088-3b81855a-c0d7-11e7-8470-f696aaa984ec.png)

**Comment by SerCom-KC** [comment]
我就说 .net 炸了233
这上面有 css 的

**Comment by 123ysys** [comment]
我的CSS还是加载不出来，gg。

**Comment by SawaraNazo** [comment]
咱又发现哦，PC端能正常用了，但是在Android端上咱想注册一下都提示无法连接，这又怎么情况   இ௰இ

**Comment by 123ysys** [comment]
PC端是要连手机的哥你是怎么上去的55555

**Comment by SawaraNazo** [comment]
@123ysys   我说错了，我意思是官网可以打开了 233       。咱还没用过这个软件的

**Comment by 123ysys** [comment]
@SawaraNazo 官网一直可以上呀？至少我这里这样。只是加载得像第一张图一样。

**Comment by SawaraNazo** [comment]
@123ysys   诶诶，是啦，一样的，用了修改后Hosts的就正常了。

**Comment by 123ysys** [comment]
我还不行啊2333

**Comment by SawaraNazo** [comment]
再换一遍，重新flushdns一下看看呢。

**Comment by 123ysys** [comment]
好了，是一个低级的错误操作。惭愧。

**Comment by SawaraNazo** [comment]
@123ysys   2333   还需要多学习一个啊。

**Comment by 123ysys** [comment]
是是。

**Comment by lrinQVQ** [comment]
已经找到手机appah无法使用的原因了咩 
73.b6.2da9.ip4.static.sl-reverse.com 169.45.182.115
56.88.adb8.ip4.static.sl-reverse.com 184.173.136.86 not work
a.50.2ca9.ip4.static.sl-reverse.com 169.44.80.10
55.f3.25ae.ip4.static.sl-reverse.com 174.37.243.85 not work

**Comment by SawaraNazo** [comment]
@lrinQVQ     咱网络学的很菜，问个问题。   为什么有的网站通过修改hosts的方法就可以继续上，就像pixiv、WhatsApp这样的，但是有的就不可以，例如google、twitter这类，这是gfw处理的力度不一样？还是什么的？
麻烦有时间解答一下。   ヽ(*。>Д<)o゜

**Comment by SerCom-KC** [comment]
@lrinQVQ 没错，力度不一样。

**Comment by lrinQVQ** [comment]
@SawaraNazo 对呀力度不同而已 顺便App已经fix登录 备份请手动跳过因为请求a.android.com

**Comment by SawaraNazo** [comment]
@SerCom-KC    @lrinQVQ     这样啊，谢谢咯。拿去试试。

所以你们另一个chromium开源项目，就是要重写一个更新协议之后的浏览器？以后借助浏览器就可以直接跨过gfw，而不用频繁地更换hosts了吗？

**Comment by lrinQVQ** [comment]
@SawaraNazo 咩确实如此 不过目前这个项目我会先做完TLS1.3 draft-21的z完整支持

**Comment by 123ysys** [comment]
请问APP怎么修改呀？将hosts覆写系统进去？

**Comment by SerCom-KC** [comment]
@123ysys
hosts 一般对于所有程序都有效，所以直接修改系统 hosts 即可

**Comment by SawaraNazo** [comment]
@lrinQVQ   耶233，猜对。不过看不懂你说的TLS和draft。。有趣的协议？期待期待。  q(≧▽≦q)

**Comment by SawaraNazo** [comment]
不过我在Android上使用这个hosts还是有问题，使用电话号码注册已经可以顺利进行，但是下一步要填入个人信息，这里就死活进不去。这一步该不会是要请求a.android.com 吧。。

**Comment by 123ysys** [comment]
这几天我的whatsapp断断续续地部分恢复正常了，不过别人的都不行，不知是什么原因。

**Comment by 123ysys** [comment]
似乎最近又不行了555555

**Comment by lrinQVQ** [comment]
咦ip 被ban 了嘛

**Comment by 123ysys** [comment]
不清楚诶，前几天我的app可以断断续续地发送消息，但别人地app都不行。昨天开始我的app也不行了，想来是墙又修复了吧？

**Comment by 123ysys** [comment]
@SerCom-KC 我将hosts覆写进了手机里，可是仍然无法连接。

**Comment by lrinQVQ** [comment]
2333应该只能登录注册

**Comment by lrinQVQ** [comment]
连接依赖a.android.com

**Comment by 123ysys** [comment]
其实就是登陆不了，收不到短信认证码，不过我不确定是否添加了a.android.com的域名，待我检查一下。

**Comment by lrinQVQ** [comment]
验证码啧

**Comment by SerCom-KC** [comment]
@123ysys 主要是 `a.android.com` 这个域名属于重点打击对象（Google），所以如果 WhatsApp 用到了这个域名的话 hosts 是暂时无解的

**Comment by 123ysys** [comment]
SO U DA.谢谢。

**Comment by SerCom-KC** [comment]
@123ysys 如果确定只剩 `a.android.com` 上不了的话我建议先 close？反正得等 Google 修复

**Comment by 123ysys** [comment]
@SerCom-KC 嗯，先close吧。

**Comment by SerCom-KC** [comment]
@123ysys 你是 issue 主你 close……你 close 的话有问题可以自己再 reopen，让管理 close 就没法自己 reopen 了

**Comment by 123ysys** [comment]
明白。

**Comment by 123ysys** [comment]
嗯，打不开官网了，提示RST。

**Comment by 123ysys** [comment]
打不开web.whatsapp.com的相关网页。

**Comment by SerCom-KC** [comment]
这边确认 `www-cdn.whatsapp.net` 和 `web.whatsapp.com` 均存在 SNI RST
虽然 `www.whatsapp.com` 倒是没事……
应该可以判定死刑了（笑）

**Comment by 123ysys** [comment]
看来和谷歌一样的待遇了啊，真看得起。

**Comment by SerCom-KC** [comment]
@123ysys 本来就是 Facebook 旗下的，不奇怪

**Comment by 123ysys** [comment]
话虽这样，但ins也是FB旗下的吧（笑）。

**Comment by lrinQVQ** [comment]
@SerCom-KC 2333我确定下

**Comment by 123ysys** [comment]
似乎官网首页也受到了SNI RST。因为不添加hosts就无法打开。

**Comment by SerCom-KC** [comment]
@123ysys
SNI RST 会出现的情况跟加不加 hosts 无关（

**Comment by 123ysys** [comment]
@SerCom-KC 那难道是HTTP RAT？可是明明是HTTPS协议啊？

**Comment by SerCom-KC** [comment]
@123ysys 欸这就有意思了
加之前 DNS 给你解析到哪个 IP 上？

**Comment by lrinQVQ** [comment]
2333欸一切正常啊

**Comment by 123ysys** [comment]
@SerCom-KC 现在ping是184.173.147.38

**Comment by lrinQVQ** [comment]
184.173.147.38 欸好像DNS污染了 @123ysys

**Comment by 123ysys** [comment]
诶？DNS污染吗？可是提示是RST。

**Comment by lrinQVQ** [comment]
sudo hping3 -S -p 443 157.240.11.53
现在的IP应该是这个欸我这里测试延迟不高

**Comment by SerCom-KC** [comment]
@lrinQVQ 我这边 ISP 解析的也是 SoftLayer 的 IP
不过服务器证书貌似是真的？

**Comment by lrinQVQ** [comment]
啧 惊了

**Comment by 123ysys** [comment]
这是怎么了？

**Comment by lrinQVQ** [comment]
(py2) [lrin@lrinQVQ 15.1]$ sudo hping3 -S -p 443 web.whatsapp.com
[sudo] lrin 的密码：
HPING web.whatsapp.com (enp3s0 157.240.11.53): S set, 40 headers + 0 data bytes
len=46 ip=157.240.11.53 ttl=135 DF id=23135 sport=443 flags=RA seq=0 win=3306 rtt=36.5 ms
len=46 ip=157.240.11.53 ttl=141 DF id=24815 sport=443 flags=RA seq=1 win=3312 rtt=36.5 ms

**Comment by 123ysys** [comment]
啊，我说的是www.whatsapp.com

**Comment by lrinQVQ** [comment]
啧

**Comment by 123ysys** [comment]
@lrinQVQ web的那个我是请求超时啦

**Comment by lrinQVQ** [comment]
23333 soga @123ysys

**Comment by 123ysys** [comment]
@lrinQVQ 所以这是怎么了？

**Comment by lrinQVQ** [comment]
www-cdn.whatsapp.net 未知原因爆炸

**Comment by lrinQVQ** [comment]
2333我看看怎么弄

**Comment by 123ysys** [comment]
@lrinQVQ 谢谢啦。

**Comment by 123ysys** [comment]
已出现SNI RST

**Comment by lrinQVQ** [comment]
欸多 不应该吧啧

**Comment by SerCom-KC** [comment]
@lrinQVQ 
观测到了 https://157.240.1.53 出现 RST

**Comment by SerCom-KC** [comment]
确认 `www-cdn.whatsapp.net` 存在 SNI RST，放弃修复XD

**Comment by 123ysys** [comment]
@SerCom-KC 那只能等新的协议适配才可以了是吧？

**Comment by SerCom-KC** [comment]
@123ysys
也有可能是某人的 360 安全路由器的锅😂……换了一个环境没有 SNI RST 了
查看一下 GitHub 通知，我在另一个地方 @ 你了

**Comment by 123ysys** [comment]
@SerCom-KC 看到了，不过这几天总是会有所谓的“拒绝访问”或“意外中断连接”，个人表示一脸懵b，是不是它们主动屏ip啊？

**Comment by SerCom-KC** [comment]
@123ysys
有那么一部分原因，WhatsApp貌似给中国另外设置了解析
CSS还是加载不出来啊……也就是说 `www-cdn.whatsapp.net` 还是有问题了

**Comment by 123ysys** [comment]
已成功。

**Comment by lrinQVQ** [comment]
好像终于强制https了

**Comment by SerCom-KC** [comment]
@123ysys 嗯？用另一份 hosts 成功了？

**Comment by 123ysys** [comment]
@SerCom-KC 是的，cdn的那条也可以用了。

**Comment by 123ysys** [comment]
很奇怪，我这里似乎只存在SNI RST， 用http不存在RST的情况(+_+)?

**Comment by SerCom-KC** [comment]
HTTP 如果老扎做了 PY 交易的话是有可能免 RST 的……

**Comment by SerCom-KC** [comment]
https://github.com/googlehosts/hosts/commit/50a8087626af960d7db9598ecd3865d09e9bc22b
看来  dalao们已经把 WhatsApp 合并过来了

**Comment by 123ysys** [comment]
whatsapp官网从RST变成了TIME-OUT，不知是不是封锁的方式发生了变化。

**Comment by beyondgfw** [comment]
@123ysys TLS1.3

**Comment by 123ysys** [comment]
@beyondgfw 意思是需要最新的谷歌浏览器是吗？

**Comment by beyondgfw** [comment]
@123ysys 不必 好好按部就班更新浏览器的话你的版本应该是足够了的 应该只是单纯的IP失效

**Comment by 123ysys** [comment]
@beyondgfw 应该不是IP失效的原因，毕竟我现在没在用Whatsapp的hosts啊。

**Comment by 123ysys** [comment]
官网地址栏显示“连接不安全”。

**Comment by beyondgfw** [comment]
@123ysys http请加s，https请贴证书信息

**Comment by 123ysys** [comment]
网站显示页面与证书信息
![tim 20180516112811](https://user-images.githubusercontent.com/27964272/40095077-c1d8aec2-58fc-11e8-8c56-e567425a376c.png)
![tim 20180516113028](https://user-images.githubusercontent.com/27964272/40095079-c5a50d3e-58fc-11e8-9663-a8c54588dccb.png)

**Comment by beyondgfw** [comment]
@123ysys 噗 还以为你说的哪个不安全😂
没连上服务器做验证当然不安全啊

**Comment by 123ysys** [comment]
@beyondgfw lol。所以为什么会连不上服务器呢？是哪一步被阻挡了吗？

**Comment by PantherJohn** [comment]
Ummmm... Handshaking + Packet Loss ...

**Comment by lrinQVQ** [comment]
158.85.5.203
好不容易有一个XD然后发现没有TLS1.3 还有SNI RST

**Comment by 123ysys** [comment]
现在软件本体（非官网）也是受到了SNI RST了吗？
