### ISSUE TITLE
Google YT已死

### ISSUE THREAD

**Issue by CrackFileso** [googlehosts/hosts#40]
广东已经上不去了
209.x的ip

连接超时

Gmail可以用

**Comment by CrackFileso** [comment]
Emm 现在又诈尸了

**Comment by lrinQVQ** [comment]
get 打完排位更新

**Comment by Bianfuchen** [comment]
hk和jp上不去，ncr倒是可以，但很慢。这是啥原因？？

**Comment by SerCom-KC** [comment]
@Bianfuchen 因为目前并没有对地区网站做支持吧
所以才强调 ncr 啊）

**Comment by viscropst** [comment]
浙江宁波的，android.googlesource.com，*.google.com连接超时

**Comment by lrinQVQ** [comment]
0.0欸我repo sync还行的说 *google.com都不是一个IP 而且只能ncr

**Comment by viscropst** [comment]
昨天android.googlesource.com还能访问网页和sync。今天就访问超时，无论web还是repo sync。
![image](https://user-images.githubusercontent.com/16207250/30246749-71d1e31a-9635-11e7-8052-9946da13c5b6.png)

**Comment by lrinQVQ** [comment]
我这还能打开和下载0.0 你试试173.194.76.82

**Comment by lrinQVQ** [comment]
我这速度0.0 11.95 MiB/s

**Comment by lrinQVQ** [comment]
修复了0.0

**Comment by viscropst** [comment]
Thanks!
