### ISSUE TITLE
可否增加国际版apple app store?

### ISSUE THREAD

**Issue by smart-z** [googlehosts/hosts#400]
比如 某些 https://apps.apple.com/us/xxxxxx   这些us区的就是404，请考虑，谢谢

**Comment by imba-tjd** [comment]
https://github.com/gfwlist/gfwlist/issues/900

**Comment by GoogleHostsSupport** [comment]
这边现已确认 iTunes 的情况属于 Apple 对来自中国大陆 IP 的主动屏蔽，因此 hosts 无法解决此问题哦～
