### ISSUE TITLE
现有HOSTS里有油管IP，建议更新，移动网络近日上不去油管

### ISSUE THREAD

**Issue by jzmswe** [googlehosts/hosts#401]
油管IP如果更新后，再加一些组合工具，还是能上去的。推特等一些网站就是例子。

**Comment by liuxinyu970226** [comment]
Duplicate of #274

**Comment by GoogleHostsSupport** [comment]
目前我们还在针对 YouTube 的修复做内部测试，由于涉及到一些 hosts 中尚未增加的域名，且工作量相对较大，因此不会作优先处理哦～
现将此 issue 与 #274 合并～
