### ISSUE TITLE
hosts-compact在Windows上有bug

### ISSUE THREAD

**Issue by imba-tjd** [googlehosts/hosts#414]
![image](https://user-images.githubusercontent.com/24759802/69843915-8eec2a80-12a4-11ea-9b78-9517537e14e6.png)

一行只能有九个域名。win7和win10 1909都有此现象。

其实是Windows的bug，但Windows没办法改，只能算做hosts-compact的bug了。

要不加一个hosts-compact-win。

**Comment by GoogleHostsSupport** [comment]
设计上而言，[`hosts-compact` 仅供 iOS 使用](https://github.com/googlehosts/hosts/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#hosts-files%E6%96%87%E4%BB%B6%E5%A4%B9%E9%87%8C%E6%9C%89%E5%A5%BD%E5%A4%9A%E6%96%87%E4%BB%B6%E6%88%91%E5%BA%94%E8%AF%A5%E7%94%A8%E5%93%AA%E4%B8%80%E4%B8%AA)，理论上 Windows 是可以正常使用标准版 `hosts` 的，因此这个问题我们不视为 bug 哦～
不过，如果您有一定要使用 `hosts-compact-win` 的场景的话，还请在此 issue 下提出，我们会重新进行评估的～
