### ISSUE TITLE
yande.re

### ISSUE THREAD

**Issue by imba-tjd** [googlehosts/hosts#422]
http://ping.chinaz.com/yande.re

```
188.165.205.120 yande.re assets.yande.re
51.77.247.63 files.yande.re
```

不过此网站含有R18内容，如果不想加可以close

**Comment by daiaji** [comment]
u1s1，P站不也是R18拉满吗？

**Comment by beyondgfw** [comment]
@daiaji 所以本项目没有加过p站

**Comment by GoogleHostsSupport** [comment]
@daiaji
如果您说的 P 站指的是 Pixiv 的话，因为该站有明确的 NSFW 警告（Steam 也有这种提示哦），所以可以收录进本项目～
完全以 NSFW 内容为主的网站才是不能被收录的对象哦～
