### ISSUE TITLE
chrome浏览器自带翻译功能的目标链接

### ISSUE THREAD

**Issue by tanjiarui15** [googlehosts/hosts#427]
### 是什么网站 / app 出现了问题？

- [X] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [X] 完全无法使用：

- [ ] 部分无法使用：

### 您的运营商是？
电信，西部地区

### 加载失败的资源地址
https://translate.googleapis.com/translate_static/js/element/main_zh-CN.js

### 失效域名的 DNS 解析结果
203.208.50.64

### 封锁方式
- [X] DNS 污染
- [ ] IP 封锁
- [ ] IP reset
- [ ] SNI reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方
203.208.39.224 translate.googleapis.com
# 请将 hosts 内容粘贴在此行上方
```

**Comment by imba-tjd** [comment]
建议换个DNS
