### ISSUE TITLE
近期windows ss使用公益ss3失效的问题的解决

### ISSUE THREAD

**Issue by macarthor** [googlehosts/hosts#430]
看看你是不是升级到了4.1.9版本，如果是，参考：
https://github.com/shadowsocks/shadowsocks-windows/issues/2766

**Comment by macarthor** [comment]
放在顶层为了让更多人看到，我自己关。。。

**Comment by beyondgfw** [comment]
@macarthor 3q 实际上更多内幕请见TG频道

**Comment by macarthor** [comment]
@beyondgfw 3q
