### ISSUE TITLE
github.com 已经无法访问

### ISSUE THREAD

**Issue by Jetereting** [googlehosts/hosts#432]

**Comment by liuxinyu970226** [comment]
我反正没开SS，照样进来的

**Comment by Jetereting** [comment]
连着同样的无线网，我的mac本可以访问，linux访问不了，阿里云服务器也拉不下代码

**Comment by GoogleHostsSupport** [comment]
这边没有发现 `github.com` 存在大规模 DNS 污染或 hosts 中的对应 IP 失效的情况哦～
由于您同一网络环境下有可以正常访问的设备，因此恕这边视为无效 issue 先关闭了呢～
另外请注意，本项目的 hosts 无法保证您使用 git 拉取代码的速度，因此如有需要的话请自行注释掉相关条目哦～
