### ISSUE TITLE
pixiv解析有问题

### ISSUE THREAD

**Issue by daiaji** [googlehosts/hosts#439]
https://sketch.pixiv.net/@ta_nakamori/lives/6798327323934635831?from=pixiv
比如这个网址
我直接用套了代理的DNS查的话
是可以上这个网址的
但用googlehosts会
> 421 Misdirected Request
> nginx

比较不爽的是dnsmasq指定域名用某个DNS查询的话
优先级比hosts低……
于是就只能自己改hosts了
不过加了wget自动更新的话……
“我们所做的一切全部都木大”

**Comment by beyondgfw** [comment]
bcc645d5388319b31a098f8776573f7a3f21e508
