### ISSUE TITLE
关于dnsmasq

### ISSUE THREAD

**Issue by GHOriginal** [googlehosts/hosts#44]
有什么方法可以让路由器自动更新dnsmasq.conf这个文件吗？

**Comment by lrinQVQ** [comment]
计划任务
0 0 * * * wget -q https://raw.githubusercontent.com/googlehosts/hosts/master/hosts-files/dnsmasq.conf -O /var/dnsmasq.d/googlehosts.conf --no-check-certificate ; /etc/init.d/dnsmasq restart

**Comment by lrinQVQ** [comment]
每天凌晨更新

**Comment by GHOriginal** [comment]
@lrinQVQ  openwrt 可用吗？   我昨天自己在网上搜到了一些 用了 结果我重刷了路由器系统。。。。。。。。

**Comment by lrinQVQ** [comment]
可以丫
