### ISSUE TITLE
修复GitHub图片加载问题

### ISSUE THREAD

**Issue by VoidxHoshi** [googlehosts/hosts#440]
### 是什么网站 / app 出现了问题？

- [X] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [ ] 完全无法使用：

- [X] 部分无法使用：
GitHub图片有时未加载完全

### 您的运营商是？
电信

### 加载失败的资源地址
*.githubusercontent.com

### 封锁方式
- [X] DNS 污染
- [ ] IP 封锁
- [ ] IP reset
- [ ] SNI reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方
199.232.28.133	raw.githubusercontent.com
199.232.28.133	gist.githubusercontent.com
199.232.28.133	cloud.githubusercontent.com
199.232.28.133	camo.githubusercontent.com
199.232.28.133	avatars0.githubusercontent.com
199.232.28.133	avatars1.githubusercontent.com
199.232.28.133	avatars2.githubusercontent.com
199.232.28.133	avatars3.githubusercontent.com
199.232.28.133	avatars4.githubusercontent.com
199.232.28.133	avatars5.githubusercontent.com
199.232.28.133	avatars6.githubusercontent.com
199.232.28.133	avatars7.githubusercontent.com
199.232.28.133	avatars8.githubusercontent.com
199.232.28.133	user-images.githubusercontent.com
199.232.28.133	repository-images.githubusercontent.com
199.232.28.133	marketplace-screenshots.githubusercontent.com
# 请将 hosts 内容粘贴在此行上方
```

**Comment by beyondgfw** [comment]
bc0f00da3087f8841a6a8d6d2ee63a6f41adb65c

**Comment by VoidxHoshi** [comment]
主要是fastly cdn时不时就挂了，时好时坏。

**Comment by VoidxHoshi** [comment]
要是CDN稳定，肯定不直连

**Comment by VoidxHoshi** [comment]
观察了下，发现设置的IP地址的CDN挺稳定的，没挂，比直连快的多，把我的IP弃了算了。

**Comment by fuchanghao** [comment]
我这边武汉电信用这个才能进去。

151.101.0.133	avatars0.githubusercontent.com
151.101.0.133	avatars1.githubusercontent.com
151.101.0.133	avatars2.githubusercontent.com
151.101.0.133	avatars3.githubusercontent.com
151.101.0.133	avatars4.githubusercontent.com
151.101.0.133	avatars5.githubusercontent.com
151.101.0.133	avatars6.githubusercontent.com
151.101.0.133	avatars7.githubusercontent.com
151.101.0.133	avatars8.githubusercontent.com
151.101.0.133	camo.githubusercontent.com
151.101.0.133	cloud.githubusercontent.com
151.101.0.133	gist.githubusercontent.com
151.101.0.133	marketplace-screenshots.githubusercontent.com
151.101.0.133	raw.githubusercontent.com
151.101.0.133	repository-images.githubusercontent.com
151.101.0.133	user-images.githubusercontent.com

**Comment by VoidxHoshi** [comment]
> 我这边武汉电信用这个才能进去。
> 
> 151.101.0.133 avatars0.githubusercontent.com
> 151.101.0.133 avatars1.githubusercontent.com
> 151.101.0.133 avatars2.githubusercontent.com
> 151.101.0.133 avatars3.githubusercontent.com
> 151.101.0.133 avatars4.githubusercontent.com
> 151.101.0.133 avatars5.githubusercontent.com
> 151.101.0.133 avatars6.githubusercontent.com
> 151.101.0.133 avatars7.githubusercontent.com
> 151.101.0.133 avatars8.githubusercontent.com
> 151.101.0.133 camo.githubusercontent.com
> 151.101.0.133 cloud.githubusercontent.com
> 151.101.0.133 gist.githubusercontent.com
> 151.101.0.133 marketplace-screenshots.githubusercontent.com
> 151.101.0.133 raw.githubusercontent.com
> 151.101.0.133 repository-images.githubusercontent.com
> 151.101.0.133 user-images.githubusercontent.com

因为Fastly CDN也被污染了，只有几个落网之鱼。

**Comment by VoidxHoshi** [comment]
> [bc0f00d](https://github.com/googlehosts/hosts/commit/bc0f00da3087f8841a6a8d6d2ee63a6f41adb65c)
> 0.0 IP我再观察一下

GitHub限速貌似接触了？今天Git下载满速了。

**Comment by mraandtux** [comment]
> 主要是fastly cdn时不时就挂了，时好时坏。

移动或使用移动出口的ISP有可能影响比其他ISP大，见 gfwlist/gfwlist#1905 ，1楼提供的IP我用广电网络都连接不了

**Comment by GoogleHostsSupport** [comment]
因 GitHub 近况较为复杂，本 issue 将合并至 #444 ～
