### ISSUE TITLE
daumcdn.net 部分IP失效，请更新IP或使用Google DNS

### ISSUE THREAD

**Issue by BlancRay** [googlehosts/hosts#442]
### 是什么网站 / app 出现了问题？

- [X] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [ ] 完全无法使用：

- [X] 部分无法使用：
IP失效，导致potplayer无法下载

### 您的运营商是？
电信

### 加载失败的资源地址
t1.daumcdn.net

### 失效域名的 DNS 解析结果
115.127.250.75	img1.daumcdn.net
115.127.250.75	img2.daumcdn.net
115.127.250.75	m1.daumcdn.net
115.127.250.75	search1.daumcdn.net
115.127.250.75	search2.daumcdn.net
115.127.250.75	shop1.daumcdn.net
115.127.250.75	t1.daumcdn.net
115.127.250.75	t2.daumcdn.net

### 封锁方式
- [X] DNS 污染
- [ ] IP 封锁
- [ ] IP reset
- [ ] SNI reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方
14.0.44.247	img1.daumcdn.net
14.0.44.247	img2.daumcdn.net
14.0.44.247	m1.daumcdn.net
14.0.44.247	search1.daumcdn.net
14.0.44.247	search2.daumcdn.net
14.0.44.247	shop1.daumcdn.net
14.0.44.247	t1.daumcdn.net
14.0.44.247	t2.daumcdn.net
# 请将 hosts 内容粘贴在此行上方
```

**Comment by beyondgfw** [comment]
a5ffecfdad5382d82fd52cb36eb752466df5e654
