### ISSUE TITLE
evernote.com

### ISSUE THREAD

**Issue by xxmmllqqqqccqq** [googlehosts/hosts#449]
### 是什么网站 / app 出现了问题？
evernote.com

- [X] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [X] 完全无法使用：

- [ ] 部分无法使用：

### 您的运营商是？
中国电信

### 加载失败的资源地址
www.evernote.com

### 失效域名的 DNS 解析结果
$ nslookup www.evernote.com 119.29.29.29
Server:		119.29.29.29
Address:	119.29.29.29#53

Non-authoritative answer:
Name:	www.evernote.com
Address: 34.98.114.63

### 封锁方式
- [ ] DNS 污染
- [ ] IP 封锁
- [ ] IP reset
- [ ] SNI reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方
35.190.29.187	evernote.com
35.190.29.187	www.evernote.com
# 请将 hosts 内容粘贴在此行上方
```
上面这个IP经测试只是网页能打开，并且打开后会强制跳转到国内版主页，客户端是否可用没有测试。

**Comment by imba-tjd** [comment]
不可用，你点那个注册就能发现了。

**Comment by imba-tjd** [comment]
好了，恢复了
