### ISSUE TITLE
Google Code  已失效，望更新

### ISSUE THREAD

**Issue by sbwml** [googlehosts/hosts#451]
### 是什么网站 / app 出现了问题？

- [X] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [X] 完全无法使用：

- [ ] 部分无法使用：

### 封锁方式
- [ ] DNS 污染
- [ ] IP 封锁
- [ ] IP reset
- [ ] SNI reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方

# 请将 hosts 内容粘贴在此行上方
```

**Comment by lrinQVQ** [comment]
是的 正常情况 如有急用请暂时使用公益ss 目前正在忙新版本ESNI

**Comment by GoogleHostsSupport** [comment]
本 issue 将合并至 #274 处理～
