### ISSUE TITLE
谷歌学术进不去。。。

### ISSUE THREAD

**Issue by fuzuiqingyun** [googlehosts/hosts#454]
### 是什么网站 / app 出现了问题？

- [ ] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [x] 完全无法使用：

- [ ] 部分无法使用：

### 封锁方式
- [ ] DNS 污染
- [ ] IP 封锁
- [ ] IP reset
- [ ] SNI reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方

# 请将 hosts 内容粘贴在此行上方
```

**Comment by fuzuiqingyun** [comment]
谷歌学术连不上，，，前几天还可以的

**Comment by lrinQVQ** [comment]
是的 正常情况 如有急用请暂时使用公益ss 目前正在忙新版本ESNI

**Comment by GoogleHostsSupport** [comment]
本 issue 将合并至 #274 处理～
