### ISSUE TITLE
DNS_PROBE_FINISHED_NXDOMAIN

### ISSUE THREAD

**Issue by justin-qingshan** [googlehosts/hosts#46]
用chrome使用最新的hosts后会出现错误DNS_PROBE_FINISHED_NXDOMAIN
（已刷新dns，ipconfig /flushdns）
广州电信

**Comment by lrinQVQ** [comment]
啧0.0 hosts为什么影响dns

**Comment by justin-qingshan** [comment]
呃，其实我也不太明白为什么.....用laod提供的以前的hosts是正常的，然后换成这个就出现这个错误

**Comment by lrinQVQ** [comment]
你是什么系统捏== IOS?还是OS X0.0

**Comment by lrinQVQ** [comment]
win和linux 系应该不存在这个问题吧

**Comment by justin-qingshan** [comment]
windows啊.....windows 7

**Comment by justin-qingshan** [comment]
sorry，我大约知道是为什么了
两个hosts是通过不同方式生成和copy进去的，而用的这个可能是因为权限问题导致无法读取.......
Sorry...

**Comment by lrinQVQ** [comment]
23333 soga 心疼你
