### ISSUE TITLE
胡萝卜周博客无法访问

### ISSUE THREAD

**Issue by woshoxxx** [googlehosts/hosts#465]
### 是什么网站 / app 出现了问题？
(carrotchou.blog)

- [x] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [X] 完全无法使用：

- [ ] 部分无法使用：

### 您的运营商是？
黑龙江省哈尔滨市龙江网络

### 失效域名的 DNS 解析结果
104.148.5.227

### 封锁方式
- [ ] DNS 污染
- [X] IP 封锁
- [ ] IP reset
- [ ] SNI reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方

# 请将 hosts 内容粘贴在此行上方
```

**Comment by 123ysys** [comment]
IP ca又是什么呀🤔？

**Comment by HashLiver** [comment]
电信网络可以正常访问，可能你是移动的特色“墙中墙”宽带。

**Comment by LGCaerwyn** [comment]
这个issue可以close了。胡萝卜周被思杰马克丁搞得  没办法 关站了。。。
