### ISSUE TITLE
使用起来不太好了！

### ISSUE THREAD

**Issue by anzigcom** [googlehosts/hosts#47]
您好！

之前一直使用：https://github.com/racaljk/hosts  的hosts文件，使用起来很顺畅，
现在使用了最新的：https://github.com/googlehosts/hosts  ，但发现很多网站依然打不开，google的很多服务也打不开，请问是什么原因呢？你们方法有改变吗？现在体验效果不太好了啊。

谢谢！

**Comment by lrinQVQ** [comment]
0.0比如哪些网站捏 现在使用新的策略后 IP死亡几率变小但是维护难度变得更大而且更麻烦2333

**Comment by lrinQVQ** [comment]
目前完成了分流的IP只有搜索主页和Youtube 一旦让一个IP通用的话 死亡率超高 谷歌搜索主页5天未出问题`

**Comment by c02y** [comment]
gmail网页和app（第三方接入gmail的安卓app）都打不开

**Comment by lrinQVQ** [comment]
0.0 网页版也不行咩～哪个地区

**Comment by chavyleung** [comment]
gmail网页版我这不行，广东电信

**Comment by c02y** [comment]
gmail:
广东电信，电脑和手机都不行
广东联通，手机web端可以，app（第三方接入gmail的安卓app）不行

**Comment by c02y** [comment]
还有Twitter也打不开，以前很好用的，比刷微博还快，现在的hosts连不上Twitter，而且vpn也连不上Twitter，我得把hosts清零再vpn才能连得上Twitter

**Comment by lrinQVQ** [comment]
Twitter亚洲IP死亡 只能观察下了－ －
gmail的ip貌似不稳定 回家换
方案B过渡期任何一个IP都可以套用所有域名

**Comment by lrinQVQ** [comment]
0.0你们可以自行测试www.google.com的ip www.google.com.hk的ip以及任何谷歌相关域名

**Comment by lrinQVQ** [comment]
0.0你们可以自行测试www.google.com的ip www.google.com.hk的ip以及任何谷歌相关域名

**Comment by c02y** [comment]
我发现广东联通不需要hosts，不需要vpn，app（第三方接入gmail的安卓app）都能使用gmail，google和gmail网页打不开，应该是我配置的原因

**Comment by lrinQVQ** [comment]
0.0 gmail的收发服务器在国内可用一段时间了的说

**Comment by lrinQVQ** [comment]
https://github.com/googlehosts/hosts/issues/48
