### ISSUE TITLE
如何上Pixiv？这里有一个好方法

### ISSUE THREAD

**Issue by Moisas-yu** [googlehosts/hosts#478]
### 是什么网站 / app 出现了问题？

- [X] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [X] 完全无法使用：

- [ ] 部分无法使用：

### 您的运营商是？
中国电信

### 加载失败的资源地址
pixiv.net

### 封锁方式
- [ ] DNS 污染
- [ ] IP 封锁
- [ ] IP reset
- [X] SNI reset
- [ ] 涉及到第三方服务：

### 可用的 网站（注意：必须有PIXIV账号，如果没有则需要FQ到PIXIV.NET进行注册，否则显示一片空白）
```
pixiv.moe
```

**Comment by GoogleHostsSupport** [comment]
本项目不提倡也不会使用任何非官方的反向代理或类似方案哦，因此恕这边关闭本 issue～
