### ISSUE TITLE
维护方案

### ISSUE THREAD

**Issue by lrinQVQ** [googlehosts/hosts#48]
Plan A:保持原来项目的计划状态,一个IP对应所有的相关域名
结果:一天炸一次/两天炸一次
不过维护轻松2333死了换死了换就行了

Plan B:对所有域名进行分类,然后一个IP对应一个域名
结果:谷歌搜索主页Ncr(无国别转向),自从实行Plan B 后没有出过问题
但是一个域名对应一个IP维护起来复杂,不过不需要频繁更换

所以为了用户最方便的解决方案考虑还是决定用Plan B,也恳请别copy and paste 分流IP丢到统一的域名 XD不然也是用一天死一个IP,~~特别是某些XD我就不说了~~  请看README,呼全域名的完成大概在20号之前完成吧～希望别出什么意外吧

**Comment by OumaSyuu** [comment]
辛苦了。
gayhub上面开发党应该比较多吧，可不可以把开发相关的网站优先级提高一点呢？最近android的ip（108.177.120.94）ping不通。。。

**Comment by lrinQVQ** [comment]
0.0 呼回家先修源码同步和安卓吧

**Comment by guoyf** [comment]
不太懂，请教，Plan B的话，难道不会一天炸一批IP吗？也就是暴露的IP越多，被封的越多？

**Comment by DDoSolitary** [comment]
因为gfw的人太傻，没有直接到项目里来看hosts文件，而是检测流量大的ip封调

**Comment by guoyf** [comment]
额，不会吧。。毕竟能捣鼓出来gfw的人，我觉得与其说他们傻，更可能的是他们睁一只眼闭一只眼。。。流量大说明影响范围广，剩下个别的不成气候就放过，毕竟我国科研工作者和高科技从业者是必须要用Google的。。。

**Comment by lrinQVQ** [comment]
= =不得不说是他们没这个能力 一旦出现QUIC 和 G SSL的情况下 他们就无法处理了

**Comment by guoyf** [comment]
好吧，更深入的就不了解了，我也不多问了。

**Comment by lrinQVQ** [comment]
23333好好好

**Comment by Leridy** [comment]
@guoyf 那些科研工作者和高科技从业者，估计他们的单位或者公司 都给他们牵了 自带翻墙的 宽带

**Comment by beyondgfw** [comment]
讨论请转TG群，有问题请另开issue
