### ISSUE TITLE
Google Maps

### ISSUE THREAD

**Issue by JesusCortezMatias** [googlehosts/hosts#481]
https://www.google.com

**Comment by liuxinyu970226** [comment]
Google相关网站请洽询[issue 274](https://github.com/googlehosts/hosts/issues/274)

**Comment by GoogleHostsSupport** [comment]
I've removed the unnecessary URI part for you.
And, as the previous poster mentioned, I'm marking this issue as a duplicate of #274.

**Comment by 123ysys** [comment]
@GoogleHostsSupport GitHub可以不可以直接block某个用户啊？很烦诶。

**Comment by beyondgfw** [comment]
@123ysys 我们已经对该用户进行了org级别的block
您也可以自行进入该用户的profile对其进行block或report操作

**Comment by 123ysys** [comment]
> @123ysys 我们已经对该用户进行了org级别的block
> 您也可以自行进入该用户的profile对其进行block或report操作

Thx.
