### ISSUE TITLE
<!-- Error al cargar Gmail - Issue 982341 in chromium_ No obvious way to undo _Always open these types of links_ decision for External Protocols(1).pdf -->https://github.com/googlehosts/hosts/issues/483

### ISSUE THREAD

**Issue by JesusCortezMatias** [googlehosts/hosts#484]
_Publicado originalmente por @JesusCortezMatias en https://github.com/googlehosts/hosts/issues/483#issuecomment-729395803_

**Comment by GoogleHostsSupport** [comment]
Continuing spamming will result in an organization-level ban.
Please use your own repository if you want to test GitHub features (or whatever you are testing with).
