### ISSUE TITLE
为啥移除 hosts-compact 

### ISSUE THREAD

**Issue by ElfSundae** [googlehosts/hosts#49]
https://github.com/googlehosts/hosts/commit/b4a86b1849f9031c6827f0a80b8c0c00d3f9838c

这个提交说合并了也是超过 5000 行，所以创建这个文件没有意义了。我拿最新的 2017-09-11 合并了下才 1117 行啊。

**Comment by DDoSolitary** [comment]
实际上还不止5000+。。
你看这个revert前的最后一个commit下的hosts-comact：https://github.com/googlehosts/hosts/blob/e82780a2d1443a37670df892c0510a549c860765/hosts-files/hosts-compact
已经6000+行了。。

**Comment by DDoSolitary** [comment]
或者说你有什么奇怪的高级合并姿势？

**Comment by ElfSundae** [comment]
应该是合并姿势不对。 我刚试了下这个文件，除去空白行一共 1055 行，例如最后一个 IP 出现了9次

```
74.125.106.140  r6---sn-oguesnze.c.2mdn.net
74.125.106.140  r6---sn-oguesnze.c.bigcache.googleapis.com
74.125.106.140  r6---sn-oguesnze.c.chat.google.com
74.125.106.140  r6---sn-oguesnze.c.docs.google.com
74.125.106.140  r6---sn-oguesnze.c.doc-0-0-sj.sj.googleusercontent.com
74.125.106.140  r6---sn-oguesnze.c.drive.google.com
74.125.106.140  r6---sn-oguesnze.gvt1.com
74.125.106.140  r6---sn-oguesnze.googlevideo.com
74.125.106.140  r6---sn-oguesnze.a1.googlevideo.com
```

一共有 913 个 IPv4 ：

```sh
$ cat hosts-compact.txt | grep -oE "^\d+\.\d+\.\d+\.\d+" | sort -u | cat -n
````

每个 IP 的重复次数：

```sh
$ cat hosts-compact.txt | grep -oE "^\d+\.\d+\.\d+\.\d+" | sort | uniq -c | sort
```

我也没啥高级姿势，就是把相同 IP 合并成一行，一个 IP 只占一行。

**Comment by ElfSundae** [comment]
我是用这个拙劣的 PHP 脚本合并的：https://github.com/ElfSundae/tools/blob/master/bin/optimize-hosts

**Comment by DDoSolitary** [comment]
我懂了。。看来是我合并姿势不对，等下再给加上。。

**Comment by DDoSolitary** [comment]
搞定了，只有972行。。db77942d006568781cfff5f72279b48076cb9d87

**Comment by ElfSundae** [comment]
👍
