### ISSUE TITLE
QVQNetwork Git Server可能部分地区不能用，如果需要则添加

### ISSUE THREAD

**Issue by Moisas-yu** [googlehosts/hosts#490]
### 是什么网站 / app 出现了问题？
git.qvq.network

- [X] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [X] 完全无法使用：
DNS_PROBE_FINISHED_NXDOMAIN (检查 git.qvq.network 中是否有拼写错误。)
- [ ] 部分无法使用：

### 您的运营商是？
中国电信

### 加载失败的资源地址
git.qvq.network

### 失效域名的 DNS 解析结果
请求找不到主机 git.qvq.network

### 封锁方式
- [X] DNS 污染
- [ ] IP 封锁
- [ ] IP reset
- [ ] SNI reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方
# QVQNetwork Git Server Start
162.250.189.147	git.qvq.network
# QVQNetwork Git Server End
# 请将 hosts 内容粘贴在此行上方
```

**Comment by lrinQVQ** [comment]
(其实是我懒 没去处理CDN

**Comment by GoogleHostsSupport** [comment]
由于网站运营方已确认是配置问题，因此本项目这边暂不作处理哦～
另外本项目同时还提供了 Coding 镜像，建议国内访问困难的用户使用此镜像～
