### ISSUE TITLE
github头像

### ISSUE THREAD

**Issue by dtlalala** [googlehosts/hosts#494]
### 是什么网站 / app 出现了问题？
avatars.githubusercontent.com

- [X] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [ ] 完全无法使用：

- [X] 部分无法使用：

### 您的运营商是？
中国电信

### 加载失败的资源地址
avatars.githubusercontent.com

### 封锁方式
- [ ] DNS 污染
- [ ] IP 封锁
- [ ] IP reset
- [ ] SNI reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方
151.101.56.133	avatars.githubusercontent.com
# 请将 hosts 内容粘贴在此行上方
```

**Comment by GoogleHostsSupport** [comment]
Merging to #491.
