### ISSUE TITLE
hosts没解决tg的问题

### ISSUE THREAD

**Issue by p0mp0k0** [googlehosts/hosts#5]
不用vpn，只用hosts，tg就连不上

**Comment by uchen1225** [comment]
可以来看看这里哦 希望对你有帮助 https://github.com/sy618/hosts/blob/master/md/telegram.md

**Comment by lrinQVQ** [comment]
XD 最早周一2333 继续添加中 and 本项目禁止随意指向其他项目= =

**Comment by uchen1225** [comment]
抱歉，还小不懂事

**Comment by wolfan** [comment]
那个你们访问 https://web.telegram.org/  是404不？

**Comment by p0mp0k0** [comment]
何止web呢，正经客户端也不行，一直是重连。北京电信和北京联通都不行

2017-08-27 15:38 GMT+08:00 wolfan <notifications@github.com>:

**Comment by lrinQVQ** [comment]
客户端无解2333 web版迷

**Comment by wolfan** [comment]
我觉得是官方的web版服务器有问题了。

**Comment by lrinQVQ** [comment]
+1

**Comment by TooYoungTooSimp** [comment]
Web版服务器是好的，我挂个代理就能上了，不挂就是404

**Comment by lrinQVQ** [comment]
怀疑屏蔽中国大陆IP XD

**Comment by wolfan** [comment]
这是区别对待么？
走，我们一起寄刀片去，还要上街游行

**Comment by TooYoungTooSimp** [comment]
在hosts里写入用8.8.8.8查询出的ip，一样是404，同样怀疑屏蔽了中国ip对网页版的访问（但是挂上代理之后用中国手机号注册/登录并不受影响）

**Comment by SerCom-KC** [comment]
看来 Web 版是无解了
加上客户端本来就是 hosts 不可解
干脆 close issue 算了 :joy:

**Comment by lrinQVQ** [comment]
2333我在确定下

**Comment by wolfan** [comment]
tg，想用Hosts正常使用基本感觉不可行。
中科之前那个tg服务也是用反代实现的。

**Comment by lrinQVQ** [comment]
web.telegram.org 屏蔽中国IP XD 无解了
