### ISSUE TITLE
作者放弃维护了吗？几个月没更新了

### ISSUE THREAD

**Issue by liyujiang-gzu** [googlehosts/hosts#503]
新发现了个正在活跃维护的：https://github.com/StevenBlack/hosts

**Comment by beyondgfw** [comment]
@liyujiang-gzu 临时休整中

**Comment by liyujiang-gzu** [comment]
> @liyujiang-gzu 临时休整中

我们这边的网络访问GitHub有点恼火，GitHub的IP经常在这几个之间变动，访问不了之后每次都得重新查询IP手动更换太麻烦了，还是能通过“SwitchHosts”之类的工具自动维护比较爽。
```bash
140.82.112.3 github.com
#140.82.112.4 github.com
#140.82.113.3 github.com
#140.82.113.4 github.com
#140.82.114.3 github.com
#140.82.114.4 github.com
```

**Comment by liyujiang-gzu** [comment]
StevenBlack/hosts活跃维护，dan但遗憾的是里面并没有GitHub的IP。
![微信截图_20210522000429](https://user-images.githubusercontent.com/16816717/119166535-512f2300-ba91-11eb-9dde-7529aa5a0764.png)

**Comment by Leon406** [comment]
自用github hosts 
https://raw.githubusercontent.com/Leon406/pyutil/master/github/hosts

**Comment by liyujiang-gzu** [comment]
> > @liyujiang-gzu 临时休整中
> 
> 我们这边的网络访问GitHub有点恼火，GitHub的IP经常在这几个之间变动，访问不了之后每次都得重新查询IP手动更换太麻烦了，还是能通过“SwitchHosts”之类的工具自动维护比较爽。
> 
> ```shell
> 140.82.112.3 github.com
> #140.82.112.4 github.com
> #140.82.113.3 github.com
> #140.82.113.4 github.com
> #140.82.114.3 github.com
> #140.82.114.4 github.com
> ```

> 自用github hosts
> https://raw.githubusercontent.com/Leon406/pyutil/master/github/hosts

老铁，你这个`https://raw.githubusercontent.com/Leon406/pyutil/master/github/hosts`是适时更新的吗？我之前是弄了个GitHub的hosts查询接口，配合“SwitchHosts”：http://qqtheme.cn/github_hosts.php 。
![image](https://user-images.githubusercontent.com/16816717/121769721-d0e37580-cb97-11eb-9eb3-da86c6b56eec.png)

**Comment by Leon406** [comment]
有人催就更新, 不行就自己fork分支, 跑下python自动生成

**Comment by JohyC** [comment]
> > > @liyujiang-gzu 临时休整中
> > 
> > 
> > 我们这边的网络访问GitHub有点恼火，GitHub的IP经常在这几个之间变动，访问不了之后每次都得重新查询IP手动更换太麻烦了，还是能通过“SwitchHosts”之类的工具自动维护比较爽。
> > ```shell
> > 140.82.112.3 github.com
> > #140.82.112.4 github.com
> > #140.82.113.3 github.com
> > #140.82.113.4 github.com
> > #140.82.114.3 github.com
> > #140.82.114.4 github.com
> > ```
> 
> > 自用github hosts
> > https://raw.githubusercontent.com/Leon406/pyutil/master/github/hosts
> 
> 老铁，你这个`https://raw.githubusercontent.com/Leon406/pyutil/master/github/hosts`是适时更新的吗？我之前是弄了个GitHub的hosts查询接口，配合“SwitchHosts”：http://qqtheme.cn/github_hosts.php 。
> ![image](https://user-images.githubusercontent.com/16816717/121769721-d0e37580-cb97-11eb-9eb3-da86c6b56eec.png)

GitHub hosts两小时同步一次。国内可以使用私人服务器地址同步。

**Comment by AIYANintofire** [comment]
DNS pollution, GitHub can't get on




---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月6日(周二) 中午12:34
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [googlehosts/hosts] 作者放弃维护了吗？几个月没更新了 (#503)




    
@liyujiang-gzu 临时休整中
  
我们这边的网络访问GitHub有点恼火，GitHub的IP经常在这几个之间变动，访问不了之后每次都得重新查询IP手动更换太麻烦了，还是能通过“SwitchHosts”之类的工具自动维护比较爽。
 140.82.112.3 github.com #140.82.112.4 github.com #140.82.113.3 github.com #140.82.113.4 github.com #140.82.114.3 github.com #140.82.114.4 github.com
   
自用github hosts
 https://raw.githubusercontent.com/Leon406/pyutil/master/github/hosts
  
老铁，你这个https://raw.githubusercontent.com/Leon406/pyutil/master/github/hosts是适时更新的吗？我之前是弄了个GitHub的hosts查询接口，配合“SwitchHosts”：http://qqtheme.cn/github_hosts.php 。
 
  
https://github.com/JohyC/Hosts
 GitHub hosts两小时同步一次。国内可以使用私人服务器地址同步。

**Comment by aoout** [comment]
> 新发现了个正在活跃维护的：https://github.com/StevenBlack/hosts

求助。StevenBlack这个项目我添加了之后怎么就完全没有网络了啊，我是把"Raw hosts"直接填入了switchhosts的远程类型里，是食用方法有错误吗？

**Comment by wherewhere** [comment]
> > 新发现了个正在活跃维护的：https://github.com/StevenBlack/hosts
> 
> 求助。StevenBlack这个项目我添加了之后怎么就完全没有网络了啊，我是把"Raw hosts"直接填入了switchhosts的远程类型里，是食用方法有错误吗？

这个好像是屏蔽网站，而不是上网的。。。
(生成的host全部是0.0.0.0

**Comment by liyujiang-gzu** [comment]
还是使用 VPN 科学上网最靠谱。

**Comment by lrinQVQ** [comment]
各有各的好处
