### ISSUE TITLE
大佬能不能拉我进中文群？作为一个程序员，实在受够了百度的搜索结果，只是想用google搜索。

### ISSUE THREAD

**Issue by diegobona** [googlehosts/hosts#505]
### 是什么网站 / app 出现了问题？

- [ ] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [ ] 完全无法使用：

- [ ] 部分无法使用：

### 封锁方式
- [ ] DNS 污染
- [ ] IP 封锁
- [ ] IP reset
- [ ] SNI reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方

# 请将 hosts 内容粘贴在此行上方
```

**Comment by diegobona** [comment]
电报用户名：will chow

**Comment by GoogleHostsSupport** [comment]
中文群组的话请自行按照相关说明入群哦～

**Comment by diegobona** [comment]
我回答过问题了，但错了两次就不给机会了，不是说有三次机会吗？ 还有：除中国大陆以外，GoogleHosts项目还针对哪一个国家的用户进行了优化？这个问题我写的答案是：没有。不对吗？

**Comment by GoogleHostsSupport** [comment]
与入群相关的问题请按相关提示在 Telegram 上通过工单系统进行反馈哦。由于 GitHub issue 属于公开内容，原则上不处理个别的此类问题～
