### ISSUE TITLE
OneDrive   not on the list

### ISSUE THREAD

**Issue by John0King** [googlehosts/hosts#52]

**Comment by DDoSolitary** [comment]
But it is not blocked.

**Comment by John0King** [comment]
被 DNS 污染了啊

**Comment by DDoSolitary** [comment]
目测并未。。哪些域名被污染了？

**Comment by John0King** [comment]
onedrive 客户端可以访问，可能直接使用的IP访问的接口，  但是 Web版被 DNS污染了， 事实上从 2014年好像就被污染了。
域名我知道的不多：

1. onedrive.live.com     ~134.170.108.26~
2. skyapi.onedrive.live.com  ~134.170.108.152~

这是我很久以前收集的， 但是好像不管用了

**Comment by zhangyz1997** [comment]
刚刚实测至少主域名onedrive.live.com就被污染了，广东教育网

**Comment by beyondgfw** [comment]
这个污染很迷啊，返回的并不是常见的黑洞ip，而是dropbox/facebook这些已经被封的服务的ip。。

**Comment by beyondgfw** [comment]
目测只有*.onedrive.live.com被污染，其他相关域名没事。。
