### ISSUE TITLE
Mac 更换了没有效果，刚开始几分钟还行，后面就不能访问了

### ISSUE THREAD

**Issue by jiexishede** [googlehosts/hosts#54]
Mac 更换了没有效果，刚开始几分钟还行，后面就不能访问了

**Comment by lrinQVQ** [comment]
恭喜你2333刚好失效不久晚点更新

**Comment by icybergking** [comment]
請問mac要如何更新？

**Comment by jiexishede** [comment]
@icybergking  https://www.zhihu.com/question/19608612

**Comment by icybergking** [comment]
@jiexishede 我的表達有問題，我是想問你是用branch裡面的方法自動生成hosts文件的麼？我的mac終端裡面有一些錯誤，但是我不會排查。

**Comment by beyondgfw** [comment]
Duplicate of #55

**Comment by birdofprey** [comment]
已知，谢谢

**Comment by beyondgfw** [comment]
欸，什么已知，一脸蒙蔽。。
