### ISSUE TITLE
Google打不开，hosts没有效果

### ISSUE THREAD

**Issue by wlos** [googlehosts/hosts#55]
如题。更改hosts后没有效果。
https:打开的

**Comment by StillForever** [comment]
同上

**Comment by lrinQVQ** [comment]
一堆拿着分流ip当全局IP的今晚处理==

**Comment by StillForever** [comment]
win10 平台 0.0.。。

**Comment by pj0y1** [comment]
是因为用分流ip当全局ip 所以这个ip才无效了吗

**Comment by beyondgfw** [comment]
@pj0y1 没毛病详见维护方案

**Comment by birdofprey** [comment]
在黑天鹅起舞的所有的裂痕中，那是光照进来的地方。愿这样的裂痕越来越多，照亮整个世界

**Comment by birdofprey** [comment]
好像用不了，不知何因

**Comment by icybergking** [comment]
現在說的這麼曖昧，完全不會用了已經。

**Comment by pj0y1** [comment]
现在gmail和google又能使用了

**Comment by JackieMium** [comment]
什么是分流....README啥也没说，所以这个不是替换`/etc/hosts`这样用？

**Comment by beyondgfw** [comment]
@JackieMium #48

**Comment by JackieMium** [comment]
@beyondgfw我看了这个了，也知道你们有PalnA/B两个计划，这也没有解释这个hists分流是个啥以及怎么用啊😳
或者，你的意思是现在不能用，得等到20号以后？🙉

**Comment by beyondgfw** [comment]
已经恢复了www.google.com Android development YouTube 但是我要对那些喜欢把更新的ip分配给所有谷歌相关域名的人说如果继续把我本来计划分流的IP和域名混在一起 就坐等全部失效吧XD

**Comment by pmw1014** [comment]
www.google.com 确实已经可以用了。确实就是怕乱搞的人。感谢大大们

**Comment by JackieMium** [comment]
好，既然反反复复也没见说到底分流是干嘛的那我就拿来当全局等失效吧:(

**Comment by beyondgfw** [comment]
没脑子不要怪别人。。

> Plan B:对所有域名进行分类,然后一个IP对应一个域名

**Comment by beyondgfw** [comment]
Closing as fixed.

**Comment by JackieMium** [comment]
@beyondgfw 我觉得不是有没有脑子的事情，在另一个Issue也有人提到说法暧昧，我觉得就是没说清。既然都直接开喷没脑子也就没有再“交流”下去的必要了吧。

**Comment by beyondgfw** [comment]
> 好，既然反反复复也没见说到底分流是干嘛的那我就拿来当全局等失效吧:(

只是你这么说让我感到火大而已。。

**Comment by JackieMium** [comment]
你觉得你可以对小白冷嘲热讽，同时也不正面回答问题，然后我不知道怎么办了选择什么也不干了算了，你又要反过来说我不对…
我知道你们维护不容易，做GitHub公开项目也不容易，那这个项目现在既然放出来了，有人问怎么用(不止我一个人吧？)，你们没有给正面回答，只给一个PLAN B 的链接，里面也没有说怎么用的问题。
和用户交流算不算维护的一部分呢？

**Comment by beyondgfw** [comment]
首先，对于询问分流是怎么回事的问题，我除了放plan b的链接还能怎样，我认为那里已经说清楚了分流是怎么搞的，最多也就是没说清楚为什么分流而已

然后，你说有人问怎么用，就我目前看到的，也就是因为自动生成系统产生了疑惑（我也进行了说明 #56），以及一般的不会使用hosts的问题

再然后，你说因为分流导致你不会用，然而 #48 的标题已经写明了是“维护方案”，也就是说完全是我们维护上的事情，只是做一个告知（就我看来除了因为有人乱用分流的ip以外连告知都没必要做），用户根本没必要采取任何措施除了像以往一样更新hosts，我们也没有说要用户采取任何措施。

最后，你说你不知道怎么办了选择什么也不干，但这个结果就是分流IP用作全局IP？我并不能看到这之间的逻辑是什么。你把手动把已经在hosts文件里分流好的IP用作全局IP，才是“干了什么”吧

**Comment by JackieMium** [comment]
好的，我的 hosts 现在只有`127.0.0.1`那两行了。

**Comment by JackieMium** [comment]
好的，我的 hosts 现在只有`127.0.0.1`那两行了。

**Comment by beyondgfw** [comment]
弄得好像我求你用一样的。。

**Comment by JackieMium** [comment]
谁也没有求谁，你也不要觉得我用了你的项目就是在求你，所以你可以摆出一副高高在上的样子。平等交流才好。再见。

**Comment by JackieMium** [comment]
谁也没有求谁，你也不要觉得我用了你的项目就是在求你，所以你可以摆出一副高高在上的样子。平等交流才好。再见。

**Comment by beyondgfw** [comment]
我并没有摆出所谓高高在上的样子，只是在摆事实讲道理，你觉得我摆的事实或讲的道理不对，你指出我改。反倒是你，完全不考虑维护者和其他hosts使用者，随意说什么“等着失效”，说得难听一点，这是有违道德的。

**Comment by beyondgfw** [comment]
再者
（摘自[LICENSE](https://github.com/googlehosts/hosts/blob/master/LICENSE)）

```
Section 5 -- Disclaimer of Warranties and Limitation of Liability.

  a. UNLESS OTHERWISE SEPARATELY UNDERTAKEN BY THE LICENSOR, TO THE
     EXTENT POSSIBLE, THE LICENSOR OFFERS THE LICENSED MATERIAL AS-IS
     AND AS-AVAILABLE, AND MAKES NO REPRESENTATIONS OR WARRANTIES OF
     ANY KIND CONCERNING THE LICENSED MATERIAL, WHETHER EXPRESS,
     IMPLIED, STATUTORY, OR OTHER. THIS INCLUDES, WITHOUT LIMITATION,
     WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR
     PURPOSE, NON-INFRINGEMENT, ABSENCE OF LATENT OR OTHER DEFECTS,
     ACCURACY, OR THE PRESENCE OR ABSENCE OF ERRORS, WHETHER OR NOT
     KNOWN OR DISCOVERABLE. WHERE DISCLAIMERS OF WARRANTIES ARE NOT
     ALLOWED IN FULL OR IN PART, THIS DISCLAIMER MAY NOT APPLY TO YOU.

  b. TO THE EXTENT POSSIBLE, IN NO EVENT WILL THE LICENSOR BE LIABLE
     TO YOU ON ANY LEGAL THEORY (INCLUDING, WITHOUT LIMITATION,
     NEGLIGENCE) OR OTHERWISE FOR ANY DIRECT, SPECIAL, INDIRECT,
     INCIDENTAL, CONSEQUENTIAL, PUNITIVE, EXEMPLARY, OR OTHER LOSSES,
     COSTS, EXPENSES, OR DAMAGES ARISING OUT OF THIS PUBLIC LICENSE OR
     USE OF THE LICENSED MATERIAL, EVEN IF THE LICENSOR HAS BEEN
     ADVISED OF THE POSSIBILITY OF SUCH LOSSES, COSTS, EXPENSES, OR
     DAMAGES. WHERE A LIMITATION OF LIABILITY IS NOT ALLOWED IN FULL OR
     IN PART, THIS LIMITATION MAY NOT APPLY TO YOU.

  c. The disclaimer of warranties and limitation of liability provided
     above shall be interpreted in a manner that, to the extent
     possible, most closely approximates an absolute disclaimer and
     waiver of all liability.
```

**Comment by littlebigdream** [comment]
@beyondgfw 
大佬,不要生气!!
其实是这样的, 对于小白用户来说, 我们之前用 hosts, 都是把hosts文件下载下来, 然后放到系统的 etc文件夹下..  但是现在我们把此项目下的hosts文件下载放到etc文件夹下, 好像并没有效果, 还是上不了Google.

所以, 就想, 是不是我们的使用方法 不对!!! 然后 来这里找找相关说明.. 然后, 大佬们让我们看 readme和 维护公告.

可是, readme和维护公告里都没有具体的使用方法..什么 如何贡献,使用条款,分流IP,全局IP 啊.....等等. 这些都是给 大佬 开发者 看的嘛.. 小白用户根本不关心或者看不懂.. ((有个梗: Windows眼里 所有人都是傻子,Linux眼里 所有人都是 开发者))
就好像任何一个产品,, 用户想要的就是 简单的 使用说明书, 不是工业制造流程规范..

**Comment by zhangxiangxiao** [comment]
开发人员这种态度对开源项目影响不好，任何开源项目不好好维护用户都不会成功。开源协议是底线性的规定，自我要求要更高一点，不要图样。

**Comment by beyondgfw** [comment]
早上起来就一肚子火。。

**Comment by beyondgfw** [comment]
@littlebigdream 确实目前项目的各种说明之类还很不完善，之后会逐步加上的。。

**Comment by beyondgfw** [comment]
算了，lock也没有意思。。就unlock吧。。

**Comment by birdofprey** [comment]
在黑天鹅起舞的所有的裂痕中，那是光照进来的地方。愿这样的裂痕越来越多，照亮整个世界

**Comment by wlos** [comment]
@beyondgfw 这个问题是我开的，本意是想反馈该项目中的问题，希望更加完善从而方便更多使用者。非常感谢作者的贡献。已经有好几个hosts的更新关闭了，更继续更新着实不易。而且这不是本职工作，还能做到这样真的非常感谢。我是从一开始就关注这个项目，看着一点点完善，非常高兴！
