### ISSUE TITLE
請教一下現在這個項目如何使用？

### ISSUE THREAD

**Issue by icybergking** [googlehosts/hosts#56]
看了看似乎直接複製粘貼已經不行了。
我裝了node之後折騰很久到了 运行./generate-local.sh 這一步就報錯了。
還有那個Travis CI的自動生成怎麼用？
yml文件看上去就是個打亂了的hosts版本，靠其他的工具來進行整理然後生成新的hosts？有沒有不那麼“專業”的玩法⋯⋯實在不懂。
請求給予解答。謝謝。

**Comment by beyondgfw** [comment]
自动生成仅用于方便我们制作hosts，master分支下的hosts文件和hosts.yml是同步的

**Comment by birdofprey** [comment]
请教下分流的事！！！

**Comment by beyondgfw** [comment]
@birdofprey #48
