### ISSUE TITLE
Chrome上无法上Facebook

### ISSUE THREAD

**Issue by 123ysys** [googlehosts/hosts#57]
奇怪的是QQ浏览器这种国产浏览器还可以，虽然慢，而且排版混乱。

**Comment by 123ysys** [comment]
不不不，QQ浏览器也不行了。

**Comment by beyondgfw** [comment]
然而我这里可用啊。。

**Comment by John0King** [comment]
@123ysys  是不是没有https

**Comment by 123ysys** [comment]
@John0King 不，手动加了https。

**Comment by SerCom-KC** [comment]
我表示目前也无压力啊
Facebook 最近真的很稳定的说
检查一下你 hosts 是不是最新版本吧，或者把 `ping www.facebook.com` 贴上来？（只是确认一下 hosts 使用姿势对不对）

**Comment by 123ysys** [comment]
可以肯定的是Facebook的hosts文件我用了很久了，但Chrome的自动https协议总是跳不出来。
