### ISSUE TITLE
Gmail无法使用

### ISSUE THREAD

**Issue by lyonye** [googlehosts/hosts#58]
好像记得最早第一个HOSTS曾经可以使用，后来一直都不行。不知道怎么回事？

**Comment by Leridy** [comment]
好像 现在 国内已经支持 邮件app gmail 了。。。

**Comment by lyonye** [comment]
@Leridy 我把所有GMAIL HOSTS文件删除掉试试。

**Comment by beyondgfw** [comment]
对呀2333 gmail收发服务器国内可用一段时间了

**Comment by lyonye** [comment]
@Leridy @beyondgfw 我刚删除了GMAIL IMAP的相关HOSTS，再重新打开邮件APP也是一样上不去。尝试添加新的GOOGLE邮件也是跳出窗口，一直加载链接谷歌服务器。

**Comment by Leridy** [comment]
@lyonye 这我就不是很清楚了。。。

**Comment by beyondgfw** [comment]
@lyonye 啧 什么域名

**Comment by lyonye** [comment]
<img width="529" alt="screen shot 2017-09-13 at 17 42 05" src="https://user-images.githubusercontent.com/17535518/30370679-e4ad7e7c-98aa-11e7-85dc-c6a092c6b38b.png">

点击添加账户，选择GOOGLE，就一直是上面这个状态。

和域名有关系吗？是用自己的网站域名。

**Comment by beyondgfw** [comment]
@lyonye 这个是因为登陆google邮箱必须要走一遍google自己的web登陆流程，不止依赖于gmail的服务器，如果hosts里相关域名不可用的话就会这样。。

**Comment by lyonye** [comment]
@beyondgfw 那还是一样要依赖可用的HOSTS了。可刚你们说国内可以收发GMAIL，是怎么回事呢？

**Comment by beyondgfw** [comment]
完成首次登陆的认证后，就只依赖于gmail的pop3/imap/smtp服务器了，这些服务器国内可访问

**Comment by lyonye** [comment]
那就先用VPN完成首次登陆，然后断开VPN也可以继续使用，对吗？
如果这样，以后肯定还会更新HOSTS文件，是否会对邮件客户端IMAP/SMTP产生影响？还是说HOSTS文件相应的IMAP/SMTP每次都要删除掉？

**Comment by beyondgfw** [comment]
> 那就先用VPN完成首次登陆，然后断开VPN也可以继续使用，对吗？

对

> 如果这样，以后肯定还会更新HOSTS文件，是否会对邮件客户端IMAP/SMTP产生影响？还是说HOSTS文件相应的IMAP/SMTP每次都要删除掉？

现在最新的hosts里这些服务器已经删除了，如果之后访问又有问题，我们会在加上的，所以一般来说保持与最新hosts同步即可，不用手动操作

**Comment by beyondgfw** [comment]
不过我看了下现在gmail服务器好像又连不上了。。

**Comment by lyonye** [comment]
那只能等你们的HOSTS更新了。只是奇怪，更新这么久，即使最新的HOSTS，邮件APP也连不上，然而用更早些的HOSTS，有时反而可以连上。

**Comment by beyondgfw** [comment]
最近因为gmail服务器国内暂时可用，移除了相关条目，没有注意到又被封了，更早些的hosts里应该有gmail相关，所以可用

**Comment by lyonye** [comment]
建议还是经常保持GMAIL服务器项目，不要移除它。毕竟国内就算有时可访问也会偶尔。即使国内可访问，也不会影响增加一个服务器备用。

**Comment by beyondgfw** [comment]
但是如果国内真的可用的话，显然是移除比较好，毕竟hosts时常失效。。

**Comment by p0mp0k0** [comment]
gmail又失效了

**Comment by kevinbest0702** [comment]
gmail 又不行了。。

**Comment by Bianfuchen** [comment]
gmail一直不能用。ping不通

**Comment by FSSU** [comment]
gmail不能用很久很久很久了。湖南电信

**Comment by zjhxmjl** [comment]
关于gmail的问题烦请修复，thx

**Comment by lrinQVQ** [comment]
web版的话XD和google.com一个待遇 很难马上恢复 目前好像大多客户端是可用的

**Comment by SerCom-KC** [comment]
Possibly duplicate of #64
国内服务器应该不会提供 Gmail 了吧

**Comment by Gdreamlend** [comment]
gmail又没办法用了
