### ISSUE TITLE
wikipedia不能少啊。

### ISSUE THREAD

**Issue by wolfan** [googlehosts/hosts#6]
google、fb、tw、wiki……这些还是不能少的嘛~

**Comment by DDoSolitary** [comment]
又没说不给你。。现在还在做，怎么可能一次性全都加上去。。

**Comment by wolfan** [comment]
(,,•́ . •̀,,)  我是想说，能不能给相应的制度一个维护等级。
比如google\fb\wiki之类的常用性定为Aclass
其它一些不常用的但也不能少的Bclass
至于其它可有可无，或是特殊的Cclass

这样在维护的时候就有个优先次序，或者是分组维护都是方便的嘛~

**Comment by DDoSolitary** [comment]
真正维护的时候也没有忙不过来到要分优先级的地步。。
现在只是还在加，也就是说是半成品，你还指望什么。。

**Comment by lrinQVQ** [comment]
23333吼吼 我马上加一波
