### ISSUE TITLE
gvs 域名查漏补缺报告用 issue

### ISSUE THREAD

**Issue by SerCom-KC** [googlehosts/hosts#61]
~原谅我擅自定的标题 233~
可以的话这个 issue 由我来控制 open/close 吧（collaborator close 的话我就没法 re-open 了）

- [ ] `r*---sn-oguesney.c.youtube.com`
- [ ] `r*---sn-oguesnel.googlevideo.com`
- [ ] `r*---sn-oguesnly.googlevideo.com`
- [ ] `r*---sn-oguesnll.googlevideo.com`
- [ ] `r*---sn-oguesnes.googlevideo.com`
- [ ] `r*---sn-nx57yn7r.googlevideo.com`
- [ ] `r*---sn-i5h7ln76.googlevideo.com`
- [ ] `r*---sn-25glene6.googlevideo.com`
- [ ] `r*---sn-q4flrnel.googlevideo.com`
- [ ] `r*---sn-nx57ynee.googlevideo.com`

**Comment by beyondgfw** [comment]
欸，我记得是开issue的账号可以随意reopen的呀

**Comment by SerCom-KC** [comment]
> 欸，我记得是开issue的账号可以随意reopen的呀
@beyondgfw 并不能，如果是 collaborator 关的话开 issue 的人是无法 re-open 的

**Comment by SerCom-KC** [comment]
看到了 `https://r20---sn-nx57ynee.googlevideo.com/videogoodput` 这一类的请求，不知道会不会影响视频播放
这一类域名要不要也放上来？

**Comment by lrinQVQ** [comment]
2333会的而且不止这些

**Comment by dhqdqk** [comment]
感觉这一批IP没效果啊，google, twitter都没发连上。

**Comment by SerCom-KC** [comment]
@dhqdqk
Twitter 本来就因为某事件被针对了，现在就算是把域名指向自己服务器的 IP 照样会炸；
Google 则是因为 GFW 开始拔网线了（封回程）。
这两个网站现在都是“头等待遇”，需求较大的话现在还是建议使用其他方案吧……

**Comment by birdofprey** [comment]
最短的自由诗 在黑天鹅起舞的所有的裂痕中，那是光照进来的地方。愿这样的裂痕越来越多，照亮整个世界

**Comment by SerCom-KC** [comment]
@lrinQVQ 我在这个 issue 里说算了……
可以加几个 `*.withyoutube.com` 的条目

**Comment by lrinQVQ** [comment]
好啊2333

**Comment by SerCom-KC** [comment]
等待 #64 解决，暂时关闭
