### ISSUE TITLE
修改了/etc/hosts还是上不了

### ISSUE THREAD

**Issue by hjs0512** [googlehosts/hosts#63]
在Mac上的Safari和Chrome都上不了，为什么呢？

**Comment by wensanlang0817** [comment]
me too

**Comment by beyondgfw** [comment]
是说Google吧？

Duplicate of #64

**Comment by nzsghdx** [comment]
是我不会玩吗,win下替换掉hosts文件我的也用不了

**Comment by SawaraNazo** [comment]
@nzsghdx  最近的话，原来的hosts是无法上谷歌的，其他有些网站是可以上的。你可以尝试下www.pixiv.net这个网站，如果可以上，说明hosts文件是可用的。
如果不能用，记得替换文件后打开cmd，使用ipconfig /flushdns命令清除一下DNS缓存。再尝试下，一般就可以了。

**Comment by yudigithub** [comment]
更换完了之后，还是不可以上。我找到后台的hosts文件，然后把一些主要的IP，ping了一下，发现都ping不通了。hosts文件是最近更新的，是不是因为移动宽带什么的也加了一些过滤的机制，导致连IP都ping不通吖。例如 Twitter、Facebook 以及 Youtube，都上不了。

**Comment by SerCom-KC** [comment]
@yudigithub 事实上这三家的 IP 确实很久没更新了，并不是因为没有可用的 IP，而是因为就算更换了也上不了，详见 [wiki](https://github.com/googlehosts/hosts/wiki#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%88%B0%E7%8E%B0%E5%9C%A8%E9%83%BD%E8%BF%98%E4%B8%8A%E4%B8%8D%E4%BA%86-googletwitterfacebookonedrivedropbox-%E7%AD%89%E6%9C%8D%E5%8A%A1)
