### ISSUE TITLE
北京市联通 google搜索不可用

### ISSUE THREAD

**Issue by JokerShao** [googlehosts/hosts#65]
半个月前在石家庄的时候google和youtube是都可以用的，现在在北京，改了hosts和没改一个样，啥服务也用不了。。。好在github不用翻墙。

**Comment by lrinQVQ** [comment]
0.0

**Comment by JokerShao** [comment]
google主页也打不开，搜索也不可用，小伙伴们，是我打开方式不正确吗。。？？

**Comment by lrinQVQ** [comment]
2333有可能

**Comment by JokerShao** [comment]
..那应该如何使用- -。我是用脚本直接https://github.com/googlehosts/hosts/blob/master/hosts-files/hosts把这里的文件覆盖了我的hosts

**Comment by JokerShao** [comment]
舞草，原来是我打开方式不正确？？？那youtube的视频也看不了阿。。

**Comment by JokerShao** [comment]
最新的commit主页可开，但是chrome搜索栏不可用，youtube能上但是不能看视频。

**Comment by lrinQVQ** [comment]
视频的解析域名我还没修2333搜索栏应该默认.hk https://www.google.com.hk试试

**Comment by JokerShao** [comment]
https://www.google.com.hk可上，但是我这里默认的搜索栏是jp。。。而且不瞒你说，我不会改。。

**Comment by lrinQVQ** [comment]
XD .jp就…你搜索下怎么改吧2333

**Comment by beyondgfw** [comment]
那就想办法改啊。。
http://www.thesempost.com/force-google-chrome-to-use-google-com-not-country-version/

**Comment by JokerShao** [comment]
^_^ 搞定啦，谢谢两位！
