### ISSUE TITLE
专门注册个号来问

### ISSUE THREAD

**Issue by pencebx** [googlehosts/hosts#66]
最近几天谷歌系的网站都打不开了，NCR，youtube。
facebook倒是一直能打开，这种状况在反复更换新旧各种版本的hosts文件以后都一样，难道是我hosts文件修改的方式不对咩？

ps.我试了下关闭DNS client服务和清楚DNS缓存，都不行。。。

**Comment by beyondgfw** [comment]
fb能上的话修改方式应该是没问题的。大概是因为Google的IP又失效了，见 #64

**Comment by beyondgfw** [comment]
Duplicate of #64
