### ISSUE TITLE
建议添加P站的支持

### ISSUE THREAD

**Issue by fatloong** [googlehosts/hosts#67]
[Pixiv被屏蔽](http://www.solidot.org/story?sid=53878)，P站的域名被DNS投毒污染了。
![1](https://user-images.githubusercontent.com/11400000/30578925-e44a67f4-9d48-11e7-9c5b-dcb1ef1c6682.PNG)

**Comment by beyondgfw** [comment]
不少地区已经直接墙IP了，暂时先不加，观望下吧。。
