### ISSUE TITLE
打搅下，今天是不是大面积封锁了？

### ISSUE THREAD

**Issue by JohnWu17** [googlehosts/hosts#68]
我这里深圳电信， 所有HOST失效，第一次出现这种情况，请问有没有知道情况的同学来说下，谢谢

**Comment by lrinQVQ** [comment]
还不至于大面积啦

**Comment by whyrookie** [comment]
我记得前几天改的hosts就不行了,但是我搜了其他的hosts又成功了。ip被墙了？
https://www.zhihu.com/question/19782572

**Comment by beyondgfw** [comment]
Duplicate of #64
