### ISSUE TITLE
建议把lhosts这个脚本迁移过来

### ISSUE THREAD

**Issue by WeihuaGu** [googlehosts/hosts#70]
这样方便获取一点。

**Comment by WeihuaGu** [comment]
这个issue没人，还是关了吧……

**Comment by lrinQVQ** [comment]
2333欸忘了这个XD

**Comment by beyondgfw** [comment]
每人也别关啊，只是都太懒了，而且我觉得直接把脚本放到这个repo里不太好，在想着另开repo。。

**Comment by WeihuaGu** [comment]
@beyondgfw 恩。符合软件设计中分离的思想：）其它引用原hosts项目的工具项目基本都改到了新项目，那个脚本的问题是，它属于“半个工具”，就像社会主义改造中的小民族资产阶级。用的人会把脚本源改一下继续用，或者用linux的人可以自己写脚本。

**Comment by SerCom-KC** [comment]
总之先开个 repo？🤔 之后的事情都可以 PR

**Comment by beyondgfw** [comment]
你说得很有道理，已开：

**Comment by SerCom-KC** [comment]
@beyondgfw 呃，先初始化一下吧，我现在没法 fork 诶

**Comment by beyondgfw** [comment]
好像弄好了？那我先close了
