### ISSUE TITLE
添加soundcloud

### ISSUE THREAD

**Issue by AlexDialga** [googlehosts/hosts#71]
我在广东使用着移动和长城两种宽带。
使用myip.ms来对域名搜索IP，所以自己似乎也会小做了一点文件，例如vimeo：
151.101.0.217	vimeo.com
151.101.0.217	api.vimeo.com
151.101.0.217	player.vimeo.com
151.101.0.217	www.vimeo.com
（毕竟之前的hosts没更新vimeo啦）

但是对Soundcloud使用同一招数来反查ip并使用的时候却发现，
我前往的ip会直接被Amazon的AWS把我403了（应该不是不是GFW的问题）。
可能是对面的DNS看到我的ip是国内的，所以把我ban掉了，sad = =
然而我使用之前的hosts的时候却仍然可以用，
或许可以证明这个域名是有多个ip地址，来规划地区分流的。
所以我想问一下，有没有能查找一个域名含有多个ip地址的方法？
或者直接更新一下Soundcloud好了【捂脸逃

**Comment by beyondgfw** [comment]
欸，讲道理是不会的，你查出来soundcloud的域名是什么？

**Comment by AlexDialga** [comment]
52.84.12.10    soundcloud.com
来源于https://myip.ms/info/whois/52.84.12.10/k/1229077393/website/soundcloud.com

**Comment by beyondgfw** [comment]
myip.ms提供的信息是没问题的，但是52.84.12.10这个服务器似乎封锁了中国IP的访问

**Comment by AlexDialga** [comment]
@beyondgfw 我想的确是的。
估计下面两张截图的右下角都可以说明了...
![1](https://user-images.githubusercontent.com/14726859/30648587-f98ae95a-9e50-11e7-83a9-c0e2948c1906.JPG)
![2](https://user-images.githubusercontent.com/14726859/30648589-fac3ec7c-9e50-11e7-9ded-fc838c56191b.JPG)

**Comment by beyondgfw** [comment]
我看看有没有可用的IP吧。。

**Comment by z306334796** [comment]
北方电信 谷歌已经挂了

**Comment by z306334796** [comment]
河北电信

**Comment by beyondgfw** [comment]
@z306334796 Google相关讨论请转 #64 ，不要讨论与这个issue无关的话题

**Comment by lrinQVQ** [comment]
soundcloud.com 只是单纯的屏蔽中国IP而已23333
server-52-84-221-85.sin3.r.cloudfront.net
访问IP:43.***.158.*** 43.***.158.*** 737***013日本

**Comment by beyondgfw** [comment]
@lrinQVQ 但是似乎还有部分可用的IP啊，比如上面这个72.21.91.127

**Comment by lrinQVQ** [comment]
233好像确实欸

**Comment by lrinQVQ** [comment]
他们官方的IP是ip4:178.249.137.0/22 ip4:145.253.129.216/29 ip4:80.82.202.196/28 ip4:52.17.172.90/32
查出来应该是SOUNDCLOUD-NET 0.0
72.21.91.127查出来是EDGECAST-NETBLK-01丫

**Comment by beyondgfw** [comment]
我估计是他们切了cdn以后旧cdn还留着。。

**Comment by lrinQVQ** [comment]
23333soga 那就加上吧233
