### ISSUE TITLE
上海教育网使用该hosts好像无效？

### ISSUE THREAD

**Issue by ZhangTianrong** [googlehosts/hosts#72]
以前用racaljk的hosts，现在是迁到这里来了吗？但是使用hosts，发现无论是Google还是Facebook什么的都无法连接。（在几个人电脑上试过都是如此）

**Comment by ZhangTianrong** [comment]
好像黄浦区可以用，闵行区不行。

**Comment by beyondgfw** [comment]
咩233确实地区不同影响挺大Facebook Twitter Youtube都已经遭到了CA证书影响具体原因分析中

**Comment by JohnWu17** [comment]
深圳电信一直无效。整个hosts都无效。

**Comment by beyondgfw** [comment]
Duplicate of #64, #69
