### ISSUE TITLE
Tumblr无法正常访问

### ISSUE THREAD

**Issue by userfromchina** [googlehosts/hosts#75]
浏览器访问手机版Tumblr首页时，Dashboard仅能加载出部分内容，很多媒体内容无法访问。
Tumblr安卓APP各页面均无法加载，提示“什么东西出错了”，“连接挂了，请重试”等错误。
请问应该如何查找问题原因？

**Comment by lrinQVQ** [comment]
0.0貌似是因为全部切换雅虎的CDN了现在应该修复了

**Comment by userfromchina** [comment]
我这里今天现象依旧，北方联通，应该不是特殊情况吧……

**Comment by beyondgfw** [comment]
好像是因为78.media.tumblr.com

**Comment by userfromchina** [comment]
近日发现Tumblr的APP又无法正常使用了，提示“什么东西出错了”等，添加api-http2.tumblr.com域名后恢复正常

**Comment by lrinQVQ** [comment]
0.0 thanks 我去加下

**Comment by lrinQVQ** [comment]
加了2333感谢反馈https://github.com/googlehosts/hosts/commit/dde7e2fe8812038e84035ba06e4a2383735739f9

**Comment by userfromchina** [comment]
天啊，秒回啊……感谢添加^_^

**Comment by lrinQVQ** [comment]
2333小意思啦 我基本上成天泡在Github忙东西的
