### ISSUE TITLE
一个复活的ip

### ISSUE THREAD

**Issue by shujunwu** [googlehosts/hosts#77]
61.91.161.217
突然发现复活了，
![2017-09-24 14 29 40](https://user-images.githubusercontent.com/31476931/30780077-0990434a-a135-11e7-9833-b66735d25366.png)

**Comment by huidaoweilai2016** [comment]
不能代理Google

**Comment by shujunwu** [comment]
@huidaoweilai2016 
能支持所有动态类
这个ip的确是gws

**Comment by lrinQVQ** [comment]
非官方IP段 暂时判定为SNI 不使用XD

**Comment by shujunwu** [comment]
@lrinQVQ 
如何判断非官方ip
验证 gws是伪造吗？能否详细讲解一下？

**Comment by lrinQVQ** [comment]
ip whois反查 你就知道了233

**Comment by lrinQVQ** [comment]
inetnum:        61.91.160.0 - 61.91.167.255
netname:        TRUE-Corporate
descr:          Fix ip for coporate customer
country:        TH
admin-c:        TIA6-AP
tech-c:         TIA6-AP
status:         ASSIGNED NON-PORTABLE
changed:        ipadmin@trueinternet.co.th 20070320
mnt-by:         MAINT-AP-TRUEINTERNET
mnt-irt:        IRT-TRUEINTERNET-TH
source:         APNIC

**Comment by xhonker** [comment]
上海，古哥用不了。

**Comment by SerCom-KC** [comment]
@xhonker [确认你的使用姿势正确后](https://github.com/googlehosts/hosts/issues/78#issuecomment-332045435)请到 #64  讨论

**Comment by lrinQVQ** [comment]
楼上+1 IP不会使用close
