### ISSUE TITLE
更改了这个hosts后google还是上不了？

### ISSUE THREAD

**Issue by hjs0512** [googlehosts/hosts#78]
https://www.google.com不行，是哪里操作失误了吗？

**Comment by lrinQVQ** [comment]
https://www.google.com/ncr https://www.google.com.hk/tw

**Comment by pictor** [comment]
@hjs0512 访问不了 Google 是因为项目组出于安全考虑，在 hosts 中只使用 Google 官方的 IP，而 Google 官方 IP 由于国内网络环境的原因可能访问缓慢或者无法访问。

我自己近一段时间都在使用 `202.86.162.172` 这一非 Google 官方的 IP，有访问不了的 Google 域名你可以用这一 IP 替换 hosts 文件中相应域名的 IP ，不保证你所在的地区可用。在问题 https://github.com/googlehosts/hosts/issues/77 中提到的 `61.91.161.217` 你也可以试试，同样是非官方 IP，hosts 项目在上半年用过此 IP 很长一段时间。

另外，明明目前有一个尚未关闭的关于 Google 的问题报告 https://github.com/googlehosts/hosts/issues/64 你又为何非要自己提出一个重复的问题呢？我不是项目维护者，可我都为他们觉得累，既要维护 hosts（他们自己选了较为麻烦的维护方案），又要应对源源不断的问题。彼此换位思考吧，多尝试自己动脑解决问题。

**Comment by SerCom-KC** [comment]
如果你满足以下两点
1. `ping www.google.com` 显示的是 64 开头的 IP
2. 使用的是最新版 Chrome/Chromium 浏览器
那就是墙的问题，请关闭这个 issue 然后到 #64 讨论
否则就是你的问题

**Comment by fuchanghao** [comment]
能问一下66.96.224.143 这个又是什么IP呢？

**Comment by lrinQVQ** [comment]
@fuchanghao 估计SNI之类的==反正我不会用的
inetnum:        66.96.224.0 - 66.96.255.255
netname:        MYREPUBLIC-ID
descr:          PT. Eka Mas Republik
descr:          Internet Service Provider
descr:          Graha FIM
descr:          Jl. Teuku Cik Ditiro No.37
descr:          Jakarta Pusat 10310, Indonesia
admin-c:        MIH5-AP
tech-c:         HG1005-AP
country:        ID
mnt-by:         MNT-APJII-ID
mnt-lower:      MAINT-ID-MYREPUBLIC
mnt-irt:        IRT-MYREPUBLIC-ID
mnt-routes:     MAINT-ID-MYREPUBLIC
status:         ALLOCATED PORTABLE
changed:        hm-changed@apnic.net 20150727
changed:        hostmaster@idnic.net 20160822
source:         APNIC

**Comment by beyondgfw** [comment]
Duplicate of #64
