### ISSUE TITLE
大大们能添加 www.tensorflow.org 的 IP 吗？

### ISSUE THREAD

**Issue by bdmk** [googlehosts/hosts#81]

**Comment by lrinQVQ** [comment]
get 0.0马上看看

**Comment by bdmk** [comment]
@lrinQVQ 谷歌相关的，迟点OK的，谢谢你，谢谢所有的贡献者。

**Comment by AlexDialga** [comment]
@lrinQVQ 
172.217.7.238
有时间可以试试

**Comment by Codersadis** [comment]
tf似乎有.cn域名的镜像站？
我也是听别人安利的。。。
[tf.google.cn](https://tensorflow.google.cn/)
试试看？

**Comment by lrinQVQ** [comment]
cn貌似没用欸23333

**Comment by lrinQVQ** [comment]
tensorflow.google.cn.	205	IN	A	203.208.43.88
tensorflow.google.cn.	205	IN	A	203.208.43.79
tensorflow.google.cn.	205	IN	A	203.208.43.87
tensorflow.google.cn.	205	IN	A	203.208.43.95
几乎没法用2333

**Comment by bdmk** [comment]
tensorflow.google.cn 我这可以，谢谢前面的同学

**Comment by lrinQVQ** [comment]
咩能用就好啦2333
