### ISSUE TITLE
能不能加一些pixiv的域名？

### ISSUE THREAD

**Issue by iamsurfing** [googlehosts/hosts#82]
能不能加一些pixiv的域名？
与现有hosts有重复的
1.http://blog.pixiv.net
2.http://chat.pixiv.net
3.http://comic.pixiv.net
4.http://dev.pixiv.net
5.http://dic.pixiv.net
6.http://en.dic.pixiv.net
7.http://factory.pixiv.net
8.http://festa.pixiv.net
9.http://genepixiv.pr.pixiv.net
10.http://goods.pixiv.net
11.http://help.pixiv.net
12.http://i1.pixiv.net
13.http://inside.pixiv.net
14.http://iracon.pixiv.net
15.http://m.pixiv.net
16.http://matsuri.pixiv.net
17.http://p2.pixiv.net
18.http://pixiv.net
19.http://recruit.pixiv.net
20.http://times.pixiv.net
21.http://touch.pixiv.net
22.http://www.pixiv.net

**Comment by SakuraNeko** [comment]
已经确定从2017年9月18日后Pixiv服务已经被中国大陆封锁

**Comment by iamsurfing** [comment]
还有，我找到了一节mega网盘的hosts
31.216.147.135 eu.api.mega.co.nz
154.53.224.130 eu.static.mega.co.nz
117.18.237.188 g.cdn1.mega.co.nz
154.53.224.118 mega.co.nz
154.53.224.162 mega.nz
31.216.147.161 w.api.mega.co.nz
31.216.147.136 g.api.mega.co.nz
31.216.147.132 lu1.api.mega.nz
31.216.147.133 lu2.api.mega.nz
31.216.147.134 lu3.api.mega.nz
31.216.147.135 lu4.api.mega.nz
31.216.147.136 lu5.api.mega.nz
31.216.147.137 lu6.api.mega.nz
31.216.144.51 gfs270n041.userstorage.mega.co.nz
31.216.144.52 gfs270n042.userstorage.mega.co.nz
31.216.144.64 gfs270n054.userstorage.mega.co.nz
31.216.144.74 gfs270n064.userstorage.mega.co.nz
31.216.145.56 gfs270n103.userstorage.mega.co.nz
31.216.144.79 gfs270n123.userstorage.mega.co.nz
31.216.144.80 gfs270n124.userstorage.mega.co.nz
31.216.144.117 gfs270n177.userstorage.mega.co.nz
31.216.145.10 gfs270n200.userstorage.mega.co.nz
89.44.168.36 gfs270n326.userstorage.mega.co.nz
89.44.168.43 gfs270n333.userstorage.mega.co.nz
89.44.168.52 gfs270n342.userstorage.mega.co.nz
89.44.168.64 gfs270n354.userstorage.mega.co.nz

**Comment by beyondgfw** [comment]
@iamsurfing mega应该没被封吧，而且不要在pixiv的issue下讲mega的事啊。。

**Comment by beyondgfw** [comment]
@SakuraNeko 9月18日，这时间。。
