### ISSUE TITLE
怀疑这个检测系统有问题?

### ISSUE THREAD

**Issue by JohnAndersonCA** [googlehosts/hosts#83]
Hosts 检测时自动的吗? 怀疑这个检测系统可能需要修改吧Google IP 为什么都不能用啊 

在 172.217.25 216.58.203 段
172.217.0.0 216.58.0.0 所有google ip 几乎封光?

可能是这个检测不安全导致GFW 发现?

**Comment by beyondgfw** [comment]
我也很希望它是自动的啊，然而并不是。。
都是手动检测，手动加的。。

**Comment by lrinQVQ** [comment]
0.0 并不会封光丫 而且我的IP是172.217.60段提供核心搜索功能欸 虽然确实经常线路不通0.0

**Comment by birdofprey** [comment]
today update
it's google failue

**Comment by JohnAndersonCA** [comment]
Goagent?

**Comment by JohnAndersonCA** [comment]
大ip都不能用了

**Comment by JohnAndersonCA** [comment]
而且我的IP是172.217.60段提供核心搜索功能欸 What do u mean?

**Comment by JohnAndersonCA** [comment]
Google Cloud 反代吗

**Comment by lrinQVQ** [comment]
不啊 

172.217.0.0 - 172.217.255.255
都是谷歌自家的啊

**Comment by JohnAndersonCA** [comment]
Hong Kong 216.58 172.217 有几个啊实在找不到谁发我一个?

**Comment by lrinQVQ** [comment]
= =嘛 不一定非要hk啊

**Comment by lrinQVQ** [comment]
0.0大概在172.217.0.0 - 172.217.255.255之间可能会有一个是可用的,也不一定是香港的

**Comment by JohnAndersonCA** [comment]
China Telecom Google 慢橙狗

**Comment by lrinQVQ** [comment]
23333电信日常爆炸

**Comment by JohnAndersonCA** [comment]
ping 都是400ms 以上还有那个Amazon AWS

**Comment by JohnAndersonCA** [comment]
GGC 倒是有

**Comment by lrinQVQ** [comment]
嘛2333 GGC我不用的 亚马逊服务器谁都知道

**Comment by Sharkkkk** [comment]
hosts封干净了吗

**Comment by lrinQVQ** [comment]
= =没有啊 凌晨更新

**Comment by lrinQVQ** [comment]
然后到现在－ －处理好了TCP重置的问题 但是路由一直被干扰

**Comment by JohnAndersonCA** [comment]
这里直接ping不通

**Comment by JohnAndersonCA** [comment]
还有你们用的什么carrier UNICOM TELECOM 这里都不行

**Comment by Sharkkkk** [comment]
Google的hosts没有存活的吧，墙应该又升级了，这次直接域名封锁了

**Comment by lrinQVQ** [comment]
咩不好说丫

**Comment by beyondgfw** [comment]
既然不关自动生成的事，也都在讨论Google，拿这里close吧，讨论Google请去#64。
