### ISSUE TITLE
希望添加聊天软件kik的官网地址

### ISSUE THREAD

**Issue by 123ysys** [googlehosts/hosts#84]
Ping www.kik.com [78.16.49.15] 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

78.16.49.15 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)

谢谢。

**Comment by birdofprey** [comment]
建议发起一个基于区块链的GPLV3的全球自由DNS项目。

**Comment by beyondgfw** [comment]
@birdofprey 有什么卵用吗。。

**Comment by lrinQVQ** [comment]
dns污染而已啦2333 自由DNS昂想一想

**Comment by dawangjiaowolaifatie** [comment]
我不得不说一句，我们大王真是金光闪闪、牛逼哄哄、狂拽炫酷屌炸天的一种存在。

**Comment by lrinQVQ** [comment]
2333我很一般的 只能尽力而为

**Comment by lrinQVQ** [comment]
试试最新的commit 应该www.kik.com可用

**Comment by 123ysys** [comment]
@lrinQVQ 谢谢大佬，我试试。

**Comment by 123ysys** [comment]
可以了，谢谢。

**Comment by lrinQVQ** [comment]
小意思啦
