### ISSUE TITLE
你们的IP还能用吗？我的IP都不行了，首次可以pin通，一旦访问google,就pin不通了,应该是证书检测的结果吧

### ISSUE THREAD

**Issue by billy1999** [googlehosts/hosts#85]
非常感谢你能参与本项目地维护，但是：
开新issue前请先阅读注意事项！
开新issue前请先阅读注意事项！
开新issue前请先阅读注意事项！
https://github.com/googlehosts/hosts/blob/master/.github/CONTRIBUTING.md
否则我们可能会不经警告地关闭你的issue，甚至禁言你的账号！
在阅读完后请删除此处的内容并填写你的issue的内容。

**Comment by zhangkuantian** [comment]
遇到了相同的问题

**Comment by lrinQVQ** [comment]
同样的问题2333可能最近我会有大的使用方案改变 如果证实了的话就是一周后

**Comment by beyondgfw** [comment]
> 开新issue前请先阅读注意事项！
> 开新issue前请先阅读注意事项！
> 开新issue前请先阅读注意事项！

我写了三遍了你还看不到啊。。
