### ISSUE TITLE
镜像更新不及时啊

### ISSUE THREAD

**Issue by lizhuangs** [googlehosts/hosts#91]
coding.net镜像更新还是15天前的。
但是github上面已经更新了。连接github真心慢。
无奈我还是切到github上面来吧。

**Comment by SerCom-KC** [comment]
貌似已经修复了

**Comment by SerCom-KC** [comment]
建议 reopen

**Comment by beyondgfw** [comment]
诶到底有没有修复啊xd

**Comment by beyondgfw** [comment]
镜像的问题tag还是用meta？ @beyondgfw 。。自己@自己好诡异啊。。

**Comment by SerCom-KC** [comment]
@beyondgfw 现在应该好了，我去群里说了
