### ISSUE TITLE
用host还是没有翻墙成功

### ISSUE THREAD

**Issue by helxsz** [googlehosts/hosts#92]
因为所用的VPN全部今天挂掉，本人刚刚用host文件来翻墙，曾今用过host文件，操作的方法是  /etc/hosts修改hosts文件，然后  sudo /etc/init.d/networking restart，或者直接重新启动电脑。

但试了一下午还是不管用，连google一直登陆不上去，除了google，还需要登陆dropbox， paper.dropbox.com 。本人现在正在国内出差，在南昌，用的是电信的网，使用的系统是ubuntu 14.04。

很奇怪，有没有人解决

**Comment by beyondgfw** [comment]
Duplicate of #64.
Duplicate of #90.

**Comment by helxsz** [comment]
thanks
