### ISSUE TITLE
Android 端修改 hosts 工具

### ISSUE THREAD

**Issue by mcxinyu** [googlehosts/hosts#94]
你好，我开发了一个 Android 修改 hosts 的工具，你原来项目中的那个 Android 端修改 hosts 的工具在一些系统中已经不能用了，也没人更新。
这个是我自己写的工具，比原来那个增加了一些实用功能，希望可以加入你的 readme 中，方便大家使用。
另外，在 telegram 群中已经有用户参加测试了，效果不错，我也会长期更新，修复 bug。
[后司](https://github.com/mcxinyu/HouSi)

**Comment by lrinQVQ** [comment]
咩2333干脆就列为官方工具好了 我也懒得重写了

**Comment by roc1010kmt** [comment]
安卓必須root才能修改hosts吧？

**Comment by SerCom-KC** [comment]
@roc1010kmt
对，但也可以不用 root 实现类似 hosts 的功能，例如 https://github.com/iTXTech/Daedalus

回到正题，此 issue 已经在
 d6348e6ac0df10e23645a28acb8b88d2bc597816 中解决，建议 close

**Comment by mcxinyu** [comment]
3Q，大家使用中有什么问题可以找我。

**Comment by ivancheng458** [comment]
多谢，虽然我什么都不懂2017年12月14日 上午8:44，YueYue <notifications@github.com>写道：3Q，大家使用中有什么问题可以找我。
