### ISSUE TITLE
建议增加http://opengapps.org/

### ISSUE THREAD

**Issue by WeihuaGu** [googlehosts/hosts#97]
非常感谢你能参与本项目的维护，但是：
开新issue前请先阅读注意事项！
开新issue前请先阅读注意事项！
开新issue前请先阅读注意事项！
https://github.com/googlehosts/hosts/blob/master/.github/CONTRIBUTING.md
否则我们可能会不经警告地关闭你的issue，甚至禁言你的账号！
在阅读完后请删除此处的内容并填写你的issue的内容。

the open gapps project是下载谷歌服务包的网站。它可以帮助没有内置谷歌服务的第三方安卓rom方便的通过卡刷的形式添加谷歌的服务。

**Comment by lrinQVQ** [comment]
咦opemgapps也躺枪了 我准备加下

**Comment by fuchanghao** [comment]
我这边无代理无hosts完全没有访问问题。

**Comment by WeihuaGu** [comment]
@lrinQVQ 感谢。@fuchanghao 我的坐标是陕西。
我又试了下，等了很久，打开成了这样：
![gapps 主页](https://raw.githubusercontent.com/WeihuaGu/asserversource/master/gapps.jpg)

ping 是ping通了……
PING opengapps.org (192.30.252.154) 56(84) bytes of data.
64 bytes from lb-192-30-252-154-iad.github.com (192.30.252.154): icmp_seq=1 ttl=48 time=281 ms
64 bytes from lb-192-30-252-154-iad.github.com (192.30.252.154): icmp_seq=2 ttl=48 time=519 ms

**Comment by SerCom-KC** [comment]
那就是第三方 css/js 崩了
目测是
 https://storage.googleapis.com/code.getmdl.io/1.3.0/material.teal-red.min.css

**Comment by lrinQVQ** [comment]
现在试试捏

**Comment by WeihuaGu** [comment]
@lrinQVQ 访问恢复，可以流畅打开了。感谢。

**Comment by birdofprey** [comment]
回复了吗？google无法使用呀

**Comment by beyondgfw** [comment]
@birdofprey 应该只是`storage.googleapis.com`。。

**Comment by SerCom-KC** [comment]
按理来说 `storage.googleapis.com` 并不在打击范围之内
但是还是有部分地区暴力封掉了……唉……

**Comment by birdofprey** [comment]
穷凶极恶就是只要带Google一律拉黑😏😏😏
